# -*- coding: utf-8 -*-
"""천재 공통영어2 L1 본문 소단원 ①~④."""
import sys; sys.path.insert(0,".")
from _helpers import *

# ===== 본문① 캠핑 중 모기의 습격 (1~8) : 분사구문 =====
r1=["You are on a camping trip with your family or friends.",
"After a long day of hiking, you take a quick shower, sit in your favorite camping chair, pick up a soda, and let out a deep, contented sigh.",
"Right at that moment, you hear that annoying and familiar buzzing sound.",
"Beating its wings as fast as 600 times per second, a mosquito sneaks in and pierces your skin with its straw-like mouthparts.",
"Next, it fills its belly with blood and then escapes quickly, leaving behind an itchy red bump.",
"This is a mild allergic reaction to the mosquito's saliva.",
"The more you scratch the bump, the more it itches.",
"But how do mosquitoes find their victims anyway?"]
ov1=Overview(theme_ko="캠핑의 평화를 깨는 모기의 습격과 흡혈 뒤 남는 가려운 반응",
 key_grammar=KeyGrammar(point="분사구문 (동시동작·연속동작: -ing로 부사절 축약)",
  source_sentence="Beating its wings as fast as 600 times per second, a mosquito sneaks in and pierces your skin with its straw-like mouthparts.",
  explanation=[GN("쉽게 말하면","콤마로 붙은 '-ing ~'는 '접속사+주어'를 지운 [[분사구문]]으로, '~하면서/~한 채'라는 동시상황을 나타내."),
   GN("복원","Beating its wings ~, a mosquito sneaks in = [[As it beats]] its wings ~, a mosquito sneaks in."),
   GN("의미상 주어","분사의 주인은 주절 주어와 [[같아]] — 여기선 a mosquito(날갯짓하는 것도 모기)."),
   GN("문미 분사구문","문장 뒤 'leaving behind ~'(5문장)처럼 '그리고 ~하면서'라는 [[연속·결과]]로도 써."),
   GN("해석 요령","'~하면서/~한 채'로 옮겨 주절에 자연스럽게 이어 붙여.")],
  example="",example_analysis="Beating its wings ~, a mosquito sneaks in = '날갯짓을 하면서 모기가 몰래 들어온다' — 분사구문(동시동작).",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 4문장 'Beating its wings as fast as 600 times per second'의 의미·기능으로 알맞은 것은?",
    options=["'날갯짓을 하면서'라는 동시상황을 나타내는 분사구문","a mosquito를 꾸미는 관계사절","조건을 나타내는 부사절"],answer="'날갯짓을 하면서'라는 동시상황을 나타내는 분사구문"),
   GrammarDrill(kind="객관식",from_passage=False,question="밑줄 친 부분이 '분사구문'인 것은?",
    options=["Smiling brightly, she waved at me.","The girl smiling brightly is my sister.","Her smiling face is lovely."],answer="Smiling brightly, she waved at me."),
   GrammarDrill(kind="객관식",from_passage=False,question="'____ the door, he went out.' 빈칸에 알맞은 것은? (문을 닫으면서)",
    options=["Closing","Closed","To close"],answer="Closing"),
   GrammarDrill(kind="영작",from_passage=False,question="음악을 들으면서, 그녀는 저녁을 요리했다.",answer="Listening to music, she cooked dinner."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 4문장 일부) 날갯짓을 하면서, 모기가 몰래 들어와 당신의 피부를 찌른다.",
    answer="Beating its wings, a mosquito sneaks in and pierces your skin.")]),
 topic="캠핑 중 편히 쉬는 순간 모기가 몰래 다가와 피를 빨고, 가려운 혹을 남긴다는 도입 장면을 그린 글이야.",
 stance="중립적",stance_reason="모기의 습격 장면과 흡혈 반응을 생생한 묘사로 전달하는 도입부야.",
 structure="시간·순서(나열)",structure_reason="캠핑에서 쉬다가(1~2문장) → 소리를 듣고(3문장) → 모기가 찌르고(4문장) → 혹이 남는(5~6문장) 시간 순서로 전개돼.",
 restatement_chains=[RestatementChain(label="모기의 흡혈",
   expressions=["pierces your skin with its straw-like mouthparts","fills its belly with blood","a mild allergic reaction to the mosquito's saliva"],
   variation="'주둥이로 피부를 찌름' → '피로 배를 채움' → '침에 대한 알레르기 반응'으로 이어져."),
  RestatementChain(label="성가신 존재",
   expressions=["that annoying and familiar buzzing sound","an itchy red bump","how do mosquitoes find their victims"],
   variation="'성가신 윙윙 소리' → '가려운 빨간 혹' → '먹잇감을 어떻게 찾나'로 이어져.")],
 flow_blocks=[FlowBlock(stage="도입",sentence_range="1~2",summary="가족·친구와 캠핑 중 긴 하루를 보내고 편안히 쉰다.",easy_example="샤워하고 의자에 앉아 음료 마시며 한숨 돌리는 장면."),
  FlowBlock(stage="습격",sentence_range="3~4",summary="바로 그때 윙윙 소리가 들리고, 모기가 날갯짓하며 몰래 들어와 피부를 찌른다.",easy_example="쉬는 순간 모기가 달려드는 것."),
  FlowBlock(stage="결과",sentence_range="5~7",summary="피를 빨고 달아난 모기는 가려운 혹을 남기는데, 긁을수록 더 가렵다.",easy_example="물린 자리가 부풀고 긁으면 더 간지러운 것."),
  FlowBlock(stage="전환",sentence_range="8",summary="그런데 모기는 대체 어떻게 먹잇감을 찾을까?",easy_example="다음 주제(탐지 원리)로 넘어가는 질문.")])
i1=[S(r1,1,[("be on a trip","'여행 중이다'")],
  [("camping trip","캠핑 여행")],
  [("You are [[on a camping trip]] with your family or friends.","당신은 가족·친구와 [[캠핑 여행 중이다]].")],
  [("이 문장은 모기의 생태를 설명하는 문장이다.","'You are on a camping trip(캠핑 중이다)'로 독자를 상황 속에 놓는 도입 문장이야 — 곧 모기가 등장해.")]),
 S(r1,2,[("병렬 동사","take, sit, pick up, and let out 나열"),("과거분사 contented","'만족한'")],
  [("let out","(소리 등을) 내다"),("contented","만족한"),("sigh","한숨")],
  [("After a long day of hiking,","등산으로 긴 하루를 보낸 뒤,"),
   ("you [[take a quick shower, sit in your favorite camping chair, pick up a soda]],","당신은 [[샤워를 하고, 좋아하는 캠핑 의자에 앉고, 음료를 집어 들고]],"),
   ("and [[let out a deep, contented sigh]].","[[깊고 만족스러운 한숨을 내쉰다]].")],
  [("긴 하루 뒤 불편하게 쉬는 모습이다.","'quick shower, favorite chair, soda, contented sigh(샤워·의자·음료·만족한 한숨)'로 편안히 쉬는 장면이야 — 불편이 아니라 만족이야.")]),
 S(r1,3,[("지시 that","'그 (익숙한)'")],
  [("annoying","성가신"),("buzzing","윙윙거리는")],
  [("Right at that moment, you hear","바로 그때, 당신은 듣는다"),
   ("that [[annoying and familiar buzzing sound]].","그 [[성가시고 익숙한 윙윙거리는 소리]]를.")],
  [("즐거운 음악 소리가 들린다는 내용이다.","'annoying and familiar buzzing sound(성가시고 익숙한 윙윙 소리)'야 — 즐거운 게 아니라 성가신 모기 소리야.")]),
 S(r1,4,[("분사구문 Beating","'날갯짓하면서'(동시동작, ⑤)"),("as fast as","'~만큼 빠르게'")],
  [("beat (wings)","날갯짓하다"),("sneak in","몰래 들어오다"),("pierce","찌르다, 뚫다"),("mouthparts","주둥이")],
  [("[[Beating its wings as fast as 600 times per second]],","[[초당 600번만큼 빠르게 날갯짓을 하면서]],"),
   ("a mosquito sneaks in and pierces your skin with its [[straw-like mouthparts]].","모기가 몰래 들어와 [[빨대처럼 생긴 주둥이]]로 당신의 피부를 찌른다.")],
  [("이 문장은 모기가 조용히 떠나는 장면이다.","'sneaks in and pierces your skin(몰래 들어와 피부를 찌른다)'는, 모기의 습격이 시작되는 핵심 사건이야.")]),
 S(r1,5,[("문미 분사구문 leaving","'~을 남기면서'(연속·결과)"),("병렬 fills and escapes","동사 병렬")],
  [("belly","배"),("escape","달아나다"),("bump","혹, 불룩한 것")],
  [("Next, it fills its belly with blood and then escapes quickly,","다음으로, 그것은 피로 배를 채우고 재빨리 달아난다,"),
   ("[[leaving behind an itchy red bump]].","[[가려운 빨간 혹을 남기면서]].")],
  [("모기는 피를 빨지 않고 그냥 떠난다는 내용이다.","'fills its belly with blood(피로 배를 채운다)'고 했어 — 피를 빨고 혹을 남긴 채 달아나는 거야.")]),
 S(r1,6,[("지시대명사 This","앞 문장 내용을 받음")],
  [("mild","가벼운"),("allergic reaction","알레르기 반응"),("saliva","침, 타액")],
  [("This is a [[mild allergic reaction to the mosquito's saliva]].","이것은 [[모기의 침에 대한 가벼운 알레르기 반응]]이다.")],
  [("(지칭) 'This'는 모기의 주둥이를 가리킨다.","지칭 오인이야. This는 앞의 '가려운 빨간 혹(itchy red bump)'을 가리켜 — 그게 모기 침에 대한 알레르기 반응이라는 뜻이야.")]),
 S(r1,7,[("the 비교급, the 비교급","'~할수록 더 …하다'")],
  [("scratch","긁다"),("itch","가렵다")],
  [("[[The more you scratch the bump]],","[[혹을 긁으면 긁을수록]],"),
   ("[[the more it itches]].","[[그것은 더 가렵다]].")],
  [("(함축) 혹은 긁을수록 덜 가려워 곧 낫는다는 뜻이다.","함축을 놓쳤어. 'The more you scratch, the more it itches(긁을수록 더 가렵다)'는 긁지 말라는 뜻을 담아 — 덜 가려워지는 게 아니야.")]),
 S(r1,8,[("의문문 how","'어떻게 ~하는가'")],
  [("victim","먹잇감, 희생자"),("anyway","대체, 어쨌든")],
  [("But how do mosquitoes [[find their victims]] anyway?","그런데 모기는 대체 [[먹잇감을 어떻게 찾을까]]?")],
  [("이 문장은 모기 습격 장면을 계속 묘사하는 문장이다.","'But how do mosquitoes find their victims?(대체 어떻게 먹잇감을 찾을까?)'로 다음 내용(탐지 원리)으로 넘어가는 전환 질문이야.")])]

# ===== 본문② 모기가 먹잇감을 찾는 단서 (9~13) : 관계사 계속적 용법 =====
r2=["Carbon dioxide, which humans and other animals breathe out, is actually a key signal to mosquitoes that a nice meal is near.",
"They are highly sensitive to CO2 and can detect it from far away.",
"That's not the only cue they use to find their victims.",
"When you sweat, you release certain chemicals that attract them.",
"Moreover, they can easily notice that your body temperature has risen."]
ov2=Overview(theme_ko="이산화탄소·화학물질·체온 등 모기가 먹잇감을 찾는 여러 단서",
 key_grammar=KeyGrammar(point="관계대명사의 계속적 용법 (, which ~,)",
  source_sentence="Carbon dioxide, which humans and other animals breathe out, is actually a key signal to mosquitoes that a nice meal is near.",
  explanation=[GN("쉽게 말하면","콤마로 감싼 ', which ~,'는 앞 명사(선행사)에 [[정보를 덧붙여]] 설명하는 계속적 용법이야."),
   GN("복원",", which humans breathe out, = [[and it]](= carbon dioxide) humans breathe out — '접속사+대명사'로 풀 수 있어."),
   GN("제한적 용법과 차이","콤마 없는 which는 '한정'(어떤 것인지 골라줌), 콤마 있는 which는 [[부연 설명]]이야."),
   GN("that과 구별","계속적 용법에는 [[that]]을 쓸 수 없어 — , that (X)."),
   GN("해석 요령","'~인데, 그것은 …'처럼 앞 명사를 먼저 옮기고 which절을 뒤에 이어 설명해.")],
  example="",example_analysis="Carbon dioxide, which humans ... breathe out, is a key signal = '이산화탄소는 — 인간이 내뿜는 것인데 — 핵심 신호다'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 1문장 ', which humans and other animals breathe out,'의 역할로 알맞은 것은?",
    options=["앞의 Carbon dioxide에 정보를 덧붙이는 계속적 용법","Carbon dioxide가 무엇인지 한정하는 제한적 용법","humans를 꾸미는 관계사"],answer="앞의 Carbon dioxide에 정보를 덧붙이는 계속적 용법"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'My uncle, ____ lives in Busan, is a doctor.'",
    options=["who","that","which"],answer="who"),
   GrammarDrill(kind="객관식",from_passage=False,question="'He passed the exam, which surprised everyone.'에서 which가 가리키는 것은?",
    options=["앞 문장 전체(그가 시험에 합격한 것)","the exam","everyone"],answer="앞 문장 전체(그가 시험에 합격한 것)"),
   GrammarDrill(kind="영작",from_passage=False,question="내 차는, 새것인데, 벌써 고장 났다.",answer="My car, which is new, has already broken down."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 1문장 일부) 이산화탄소는, 인간과 다른 동물들이 내뿜는 것인데, 모기에게 핵심 신호이다.",
    answer="Carbon dioxide, which humans and other animals breathe out, is a key signal to mosquitoes.")]),
 topic="모기가 먹잇감을 찾을 때 쓰는 여러 단서 — 이산화탄소, 땀 속 화학물질, 상승한 체온 — 를 설명하는 글이야.",
 stance="중립적",stance_reason="모기의 먹잇감 탐지 단서를 사실 중심으로 나열·설명하는 정보 전달문이야.",
 structure="예시→일반화(결론)",structure_reason="핵심 단서인 이산화탄소(1~2문장)를 먼저 들고, '유일한 단서가 아니다'(3문장)라며 땀·체온이라는 추가 단서(4~5문장)로 확장해.",
 restatement_chains=[RestatementChain(label="모기의 탐지 단서",
   expressions=["a key signal to mosquitoes","not the only cue","certain chemicals that attract them"],
   variation="'핵심 신호' → '유일한 단서가 아님' → '유인하는 화학물질'로 단서가 늘어나."),
  RestatementChain(label="탐지 능력",
   expressions=["highly sensitive to CO2","detect it from far away","easily notice that your body temperature has risen"],
   variation="'CO2에 매우 민감' → '멀리서도 감지' → '체온 상승을 쉽게 알아챔'으로 이어져.")],
 flow_blocks=[FlowBlock(stage="핵심 단서",sentence_range="1~2",summary="인간이 내뿜는 이산화탄소는 모기에게 먹이가 가깝다는 핵심 신호로, 모기는 멀리서도 감지한다.",easy_example="숨 쉴 때 나오는 CO2가 모기를 부르는 것."),
  FlowBlock(stage="추가 단서",sentence_range="3~5",summary="이것만이 단서는 아니어서, 땀 속 화학물질과 상승한 체온으로도 모기는 먹잇감을 알아챈다.",easy_example="땀 냄새와 따뜻한 체온도 모기를 끄는 것.")])
i2=[S(r2,1,[("관계사 계속적 용법 which",", which humans breathe out, — carbon dioxide 부연(⑤)"),("동격 that","a key signal 뒤 내용 부연")],
  [("carbon dioxide","이산화탄소"),("breathe out","내쉬다, 내뿜다"),("signal","신호")],
  [("Carbon dioxide, [[which humans and other animals breathe out]],","이산화탄소는, [[인간과 다른 동물들이 내뿜는 것인데]],"),
   ("is actually a key signal to mosquitoes [[that a nice meal is near]].","실은 모기에게 [[좋은 먹이가 가깝다는]] 핵심 신호이다.")],
  [("이 문장은 이산화탄소가 모기를 쫓아낸다는 내용이다.","'a key signal to mosquitoes that a nice meal is near(먹이가 가깝다는 핵심 신호)'야 — 쫓아내는 게 아니라 모기를 부르는 신호야.")]),
 S(r2,2,[("병렬 sensitive and can detect","형용사·동사 대등"),("비교 far away","'멀리서'")],
  [("highly","매우"),("sensitive to","~에 민감한"),("detect","감지하다")],
  [("They are [[highly sensitive to CO2]]","그것들은 [[CO2에 매우 민감해서]]"),
   ("and can detect it [[from far away]].","그것을 [[멀리서도]] 감지할 수 있다.")],
  [("(지칭) 'They'는 인간과 다른 동물들을 가리킨다.","지칭 오인이야. They는 앞의 'mosquitoes(모기)'를 가리켜 — 모기가 CO2에 민감하다는 뜻이야.")]),
 S(r2,3,[("목적격 관계대명사 생략","the only cue (that) they use — 관계대명사 생략")],
  [("cue","단서")],
  [("That's [[not the only cue]]","그것이 [[유일한 단서는 아니다]]"),
   ("they use to find their victims.","그들이 먹잇감을 찾는 데 쓰는.")],
  [("이산화탄소가 모기의 유일한 단서라는 내용이다.","'not the only cue(유일한 단서가 아니다)'라고 했어 — 이제 땀·체온 같은 다른 단서로 이어져.")]),
 S(r2,4,[("접속사 when","'~할 때'"),("관계사 that","chemicals 수식")],
  [("sweat","땀을 흘리다"),("release","분비하다, 내보내다"),("attract","유인하다")],
  [("When you sweat, you release","당신이 땀을 흘리면, 당신은 내보낸다"),
   ("[[certain chemicals that attract them]].","[[그것들을 유인하는 특정 화학물질을]].")],
  [("땀을 흘리면 모기를 쫓는 물질이 나온다는 내용이다.","'chemicals that attract them(그것들을 유인하는 화학물질)'이야 — 쫓는 게 아니라 모기를 끌어들이는 물질이야.")]),
 S(r2,5,[("명사절 that","notice의 목적어"),("현재완료 has risen","'상승했다'")],
  [("moreover","게다가"),("body temperature","체온"),("rise","오르다")],
  [("Moreover, they can easily notice","게다가, 그것들은 쉽게 알아챌 수 있다"),
   ("[[that your body temperature has risen]].","[[당신의 체온이 상승했다는 것을]].")],
  [("(함축) 모기는 체온 변화를 전혀 감지하지 못한다는 뜻이다.","함축을 놓쳤어. 'can easily notice that your body temperature has risen(체온 상승을 쉽게 알아챈다)'이야 — 체온까지 단서로 쓴다는, 정교한 탐지 능력을 강조해.")])]

# ===== 본문③ 왜 피를 원하나·흡혈과 산란 (14~20) : 가정법 과거 =====
r3=["Why do they want our blood in the first place?",
"It turns out that only females bite us; they need protein to produce eggs.",
"If our blood did not contain protein, they would not bother us.",
"After the mosquito successfully takes a blood meal of up to three times her own body weight, she quickly lands on the nearest vertical surface.",
"With the aid of gravity, she drains off the water from the blood she took.",
"Using this concentrated blood, she develops her eggs over the next few days.",
"She then lays roughly 200 floating eggs on the surface of a small pool of water."]
ov3=Overview(theme_ko="암컷 모기가 알을 만들기 위해 피를 필요로 하는 이유와 흡혈 뒤 산란 과정",
 key_grammar=KeyGrammar(point="가정법 과거 (If + 과거동사 ~, 주어 + would/could + 동사원형)",
  source_sentence="If our blood did not contain protein, they would not bother us.",
  explanation=[GN("쉽게 말하면","'If + 과거동사 ~, 주어 + would + 동사원형'은 현재 사실의 [[반대]]를 가정해."),
   GN("사실 반대","우리 피에는 실제로 단백질이 [[있으므로]], '없다면 안 괴롭힐 텐데'는 실현되지 않는 가정이야."),
   GN("형태","If절은 [[과거동사]](did not contain), 주절은 [[would + 동사원형]](would not bother)."),
   GN("직설법과 구별","실제로 그럴 수 있으면 If + 현재(직설법), 사실 반대면 If + [[과거]](가정법)."),
   GN("해석 요령","'만약 (지금) ~라면 …할 텐데 (실제론 아님)'로 옮겨.")],
  example="",example_analysis="If our blood did not contain protein, they would not bother us = '피에 단백질이 없다면 안 괴롭힐 텐데'(실제론 있음).",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 3문장 'If our blood did not contain protein, they would not bother us'의 의미로 알맞은 것은?",
    options=["실제로 피에 단백질이 있어서, '없다면 안 괴롭힐 텐데'라는 사실 반대의 가정","피에 단백질이 없어서 모기가 괴롭히지 않는다","앞으로 단백질이 없어질 것이라는 예측"],answer="실제로 피에 단백질이 있어서, '없다면 안 괴롭힐 텐데'라는 사실 반대의 가정"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'If I ____ rich, I would travel the world.'",
    options=["were","am","will be"],answer="were"),
   GrammarDrill(kind="객관식",from_passage=False,question="'If I knew her number, I would call her.'가 의미하는 바는?",
    options=["나는 그녀의 번호를 몰라서 전화를 못 한다","나는 그녀의 번호를 알아서 전화한다","나는 그녀에게 전화할 것이다"],answer="나는 그녀의 번호를 몰라서 전화를 못 한다"),
   GrammarDrill(kind="영작",from_passage=False,question="내가 시간이 있다면, 너를 도울 텐데.",answer="If I had time, I would help you."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 3문장) 우리 피에 단백질이 없다면, 그것들은 우리를 괴롭히지 않을 텐데.",
    answer="If our blood did not contain protein, they would not bother us.")]),
 topic="암컷 모기만 피를 빠는 이유(알에 필요한 단백질)와, 흡혈 후 피를 농축해 산란하는 과정을 설명하는 글이야.",
 stance="중립적",stance_reason="암컷 모기의 흡혈 목적과 산란 과정을 사실·순서 중심으로 설명하는 정보 전달문이야.",
 structure="문제→해결(방안)",structure_reason="'왜 피를 원하나?'라는 질문(1문장)에 '알을 위한 단백질 때문'이라 답하고(2~3문장), 흡혈 후 산란 과정(4~7문장)을 순서대로 설명해.",
 restatement_chains=[RestatementChain(label="피가 필요한 이유",
   expressions=["they need protein to produce eggs","this concentrated blood","she develops her eggs"],
   variation="'알을 만들 단백질이 필요' → '농축된 피' → '알을 발달시킴'으로 이어져."),
  RestatementChain(label="흡혈·산란 과정",
   expressions=["takes a blood meal","drains off the water from the blood","lays roughly 200 floating eggs"],
   variation="'피를 빨아들임' → '피에서 물을 빼냄' → '약 200개의 알을 낳음'으로 순서가 이어져.")],
 flow_blocks=[FlowBlock(stage="질문·답",sentence_range="1~3",summary="왜 피를 원할까? 암컷만 물며, 알에 필요한 단백질 때문이다 — 피에 단백질이 없다면 괴롭히지 않을 것이다.",easy_example="알을 만들 영양분이 피에 있어서 무는 것."),
  FlowBlock(stage="흡혈 후",sentence_range="4~5",summary="제 몸무게의 최대 세 배까지 피를 빤 암컷은 가까운 수직면에 앉아, 중력으로 피에서 물을 빼낸다.",easy_example="배부르게 빤 뒤 물기만 빼 피를 농축하는 것."),
  FlowBlock(stage="산란",sentence_range="6~7",summary="농축된 피로 며칠에 걸쳐 알을 발달시킨 뒤, 작은 물웅덩이에 약 200개의 알을 낳는다.",easy_example="농축한 피로 알을 키워 물 위에 낳는 것.")])
i3=[S(r3,1,[("의문문 why","'왜 ~하는가'"),("in the first place","'애초에, 우선'")],
  [("in the first place","애초에, 우선")],
  [("Why do they want our blood [[in the first place]]?","그것들은 [[애초에]] 왜 우리 피를 원할까?")],
  [("이 문장은 모기가 피를 원하지 않는다는 내용이다.","'Why do they want our blood(왜 피를 원할까)'라는 질문으로, 흡혈의 이유를 여는 도입이야.")]),
 S(r3,2,[("가주어 it ~ that","It turns out that ~"),("부정사 to produce","'~을 만들기 위해'"),("세미콜론 부연","앞 절을 이어 설명")],
  [("turn out","~로 밝혀지다"),("protein","단백질"),("produce","만들어 내다")],
  [("It turns out that [[only females bite us]];","[[오직 암컷만 우리를 문다는]] 것이 밝혀졌다;"),
   ("they need protein to produce eggs.","그들은 알을 만들기 위해 단백질이 필요하다.")],
  [("모든 모기가 우리를 문다는 내용이다.","'only females bite us(오직 암컷만 문다)'고 했어 — 모든 모기가 아니라 암컷만 물어(알을 위한 단백질 때문).")]),
 S(r3,3,[("가정법 과거","If + 과거동사 ~, would + 동사원형(⑤)")],
  [("contain","포함하다"),("bother","괴롭히다")],
  [("[[If our blood did not contain protein]],","[[만약 우리 피에 단백질이 없다면]],"),
   ("[[they would not bother us]].","[[그들은 우리를 괴롭히지 않을 텐데]].")],
  [("실제로 우리 피에 단백질이 없어서 모기가 괴롭히지 않는다는 내용이다.","가정법 과거야 — 실제론 피에 단백질이 '있어서', '없다면 안 괴롭힐 텐데'라는 사실 반대의 가정이야.")]),
 S(r3,4,[("접속사 after","'~한 뒤'"),("비교 up to three times","'최대 세 배까지'")],
  [("blood meal","흡혈, 피 식사"),("vertical surface","수직면")],
  [("After the mosquito successfully takes a blood meal","모기가 피를 성공적으로 빤 뒤,"),
   ("of [[up to three times her own body weight]],","[[제 몸무게의 최대 세 배까지]],"),
   ("she quickly lands on the nearest vertical surface.","그것은 재빨리 가장 가까운 수직면에 앉는다.")],
  [("(지칭) 'her own body weight'의 her는 물린 사람을 가리킨다.","지칭 오인이야. her는 '(암컷) 모기'를 가리켜 — 모기 자기 몸무게의 세 배까지 피를 빤다는 뜻이야.")]),
 S(r3,5,[("목적격 관계대명사 생략","the blood (that) she took — 관계대명사 생략"),("with the aid of","'~의 도움으로'")],
  [("gravity","중력"),("drain off","빼내다, 배출하다")],
  [("With the aid of gravity, she [[drains off the water from the blood]]","중력의 도움으로, 그것은 [[피에서 물을 빼낸다]]"),
   ("she took.","자신이 빤.")],
  [("모기는 빤 피에 물을 더한다는 내용이다.","'drains off the water from the blood(피에서 물을 빼낸다)'야 — 물을 더하는 게 아니라 빼서 피를 농축해.")]),
 S(r3,6,[("분사구문 Using","'~을 이용하여'"),("과거분사 concentrated","'농축된'")],
  [("concentrated","농축된"),("develop","발달시키다")],
  [("[[Using this concentrated blood]], she develops her eggs","[[이 농축된 피를 이용하여]], 그것은 알을 발달시킨다"),
   ("over the next few days.","다음 며칠에 걸쳐.")],
  [("이 문장은 모기가 피를 곧바로 버린다는 내용이다.","'Using this concentrated blood, she develops her eggs(농축된 피로 알을 발달시킨다)'야 — 버리는 게 아니라 알을 위한 영양분으로 써.")]),
 S(r3,7,[("현재분사 floating","'물에 뜨는'(eggs 수식)")],
  [("lay eggs","알을 낳다"),("roughly","대략"),("floating","물에 뜨는")],
  [("She then lays [[roughly 200 floating eggs]]","그런 다음 그것은 [[약 200개의 물에 뜨는 알을]] 낳는다"),
   ("on the surface of a small pool of water.","작은 물웅덩이의 표면에.")],
  [("(함축) 모기는 알을 마른 땅에 하나씩 낳는다는 뜻이다.","함축을 놓쳤어. 'lays roughly 200 floating eggs on the surface of ... water(물 위에 뜨는 알을 약 200개 낳는다)'야 — 마른 땅이 아니라 물 위에, 그것도 한꺼번에 많이 낳아.")])]

# ===== 본문④ 최대 포식자 모기 (21~26) : 비교급으로 최상급 표현 =====
r4=["If you had to choose our greatest predator in nature, which would you pick? Sharks, lions, or bears?",
"According to history professor Timothy Winegard, it is actually the mosquito.",
"Mosquitoes can pass on deadly diseases like malaria and yellow fever.",
"Over a million people worldwide die of these diseases every year.",
"Throughout history, Winegard estimates that mosquitoes have killed more people than any other single cause — about fifty-two billion people, nearly half of all humans who have ever lived.",
"Winegard claims that mosquitoes also played a role in shaping the history of several countries."]
ov4=Overview(theme_ko="상어·사자가 아닌 모기가 인류 최대의 포식자라는 주장과 그 근거",
 key_grammar=KeyGrammar(point="비교급 + than any other + 단수명사 ('다른 어떤 ~보다 더 = 가장')",
  source_sentence="Winegard estimates that mosquitoes have killed more people than any other single cause.",
  explanation=[GN("쉽게 말하면","'비교급 + than any other + 단수명사'는 '다른 어떤 ~보다 더'로, 결국 [[최상급]] 의미야."),
   GN("형태","than any other 뒤에는 반드시 [[단수명사]]가 와 — than any other single cause(다른 어떤 단일 원인보다)."),
   GN("의미","'다른 모든 것보다 더 많이 죽였다' = '[[가장]] 많이 죽였다'(the most)."),
   GN("바꿔 쓰기","= Mosquitoes have killed the [[most]] people (of all causes) — 최상급으로 전환 가능."),
   GN("해석 요령","'다른 어떤 ~보다 더 …하다'로 옮기고, 곧 '가장 …하다'임을 잡아.")],
  example="",example_analysis="killed more people than any other single cause = '다른 어떤 단일 원인보다 더 많은 사람을 죽였다' = 가장 많이.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 5문장 'killed more people than any other single cause'의 의미로 알맞은 것은?",
    options=["다른 어떤 단일 원인보다 더 많이 = 가장 많이 죽였다","특정 한 원인보다 조금 덜 죽였다","다른 원인들과 똑같이 죽였다"],answer="다른 어떤 단일 원인보다 더 많이 = 가장 많이 죽였다"),
   GrammarDrill(kind="객관식",from_passage=False,question="'Time is more precious than any other thing.'과 뜻이 같은 것은?",
    options=["Time is the most precious thing.","Time is as precious as other things.","Nothing is precious like time is not."],answer="Time is the most precious thing."),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'He is taller than any other ____ in his class.'",
    options=["student","students","the student"],answer="student"),
   GrammarDrill(kind="영작",from_passage=False,question="건강이 다른 어떤 것보다 더 중요하다.",answer="Health is more important than any other thing."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 5문장 일부) 모기는 다른 어떤 단일 원인보다 더 많은 사람을 죽였다.",
    answer="Mosquitoes have killed more people than any other single cause.")]),
 topic="상어·사자·곰이 아니라 모기가 인류를 가장 많이 죽인 최대의 포식자이며, 여러 나라 역사에도 영향을 줬다는 글이야.",
 stance="중립적",stance_reason="역사학자 Winegard의 주장·추정을 근거(사망자 수·역사)와 함께 전달하는 정보 전달문이야.",
 structure="통념→반박(반전)",structure_reason="'최대 포식자는 상어·사자?'라는 통념(1문장)을 'it is actually the mosquito(실은 모기)'로 뒤집고(2문장), 사망자 수·역사(3~6문장)로 뒷받침해.",
 restatement_chains=[RestatementChain(label="모기가 최대 포식자",
   expressions=["our greatest predator in nature","it is actually the mosquito","killed more people than any other single cause"],
   variation="'자연 최대의 포식자' → '실은 모기' → '다른 어떤 원인보다 많이 죽임'으로 이어져."),
  RestatementChain(label="치명적 영향",
   expressions=["pass on deadly diseases","Over a million people worldwide die","played a role in shaping the history"],
   variation="'치명적 질병 전파' → '연 100만 명 이상 사망' → '역사를 바꿈'으로 확장돼.")],
 flow_blocks=[FlowBlock(stage="통념·반박",sentence_range="1~2",summary="최대 포식자로 상어·사자를 떠올리지만, 역사학자 Winegard에 따르면 실은 모기다.",easy_example="무서운 맹수보다 작은 모기가 더 위험하다는 반전."),
  FlowBlock(stage="근거-질병",sentence_range="3~4",summary="모기는 말라리아·황열 같은 치명적 질병을 옮겨, 매년 전 세계에서 100만 명 넘게 죽는다.",easy_example="작은 모기가 병을 옮겨 수많은 목숨을 앗는 것."),
  FlowBlock(stage="근거-역사",sentence_range="5~6",summary="역사상 모기는 다른 어떤 원인보다 많은 사람을 죽였고, 여러 나라 역사를 바꾸는 데도 한몫했다.",easy_example="약 520억 명, 인류 절반을 죽였다는 추정.")])
i4=[S(r4,1,[("가정법 과거 If ~ would","'~라면 무엇을 고를까'"),("의문사 which","'어느 것'")],
  [("predator","포식자"),("pick","고르다")],
  [("[[If you had to choose our greatest predator in nature]], which would you pick?","[[자연에서 우리의 최대 포식자를 골라야 한다면]], 어느 것을 고르겠는가?"),
   ("Sharks, lions, or bears?","상어, 사자, 아니면 곰?")],
  [("이 문장은 최대 포식자가 상어·사자·곰이라고 단정하는 문장이다.","'which would you pick?(어느 것을 고르겠는가?)'라는 가정·질문으로 독자의 통념을 떠보는 도입이야 — 단정이 아니야.")]),
 S(r4,2,[("According to","'~에 따르면'")],
  [("history professor","역사학 교수"),("actually","실제로")],
  [("According to history professor Timothy Winegard,","역사학 교수 Timothy Winegard에 따르면,"),
   ("it is actually [[the mosquito]].","그것은 실은 [[모기]]이다.")],
  [("최대 포식자가 결국 상어라는 내용이다.","'it is actually the mosquito(실은 모기)'라며 통념을 뒤집는 반전 문장이야 — 상어가 아니라 모기야.")]),
 S(r4,3,[("병렬 like malaria and yellow fever","예시 명사 병렬")],
  [("pass on","전파하다, 옮기다"),("deadly","치명적인"),("yellow fever","황열")],
  [("Mosquitoes can [[pass on deadly diseases]]","모기는 [[치명적인 질병을 옮길]] 수 있다"),
   ("like malaria and yellow fever.","말라리아와 황열 같은.")],
  [("모기가 질병을 막아 준다는 내용이다.","'pass on deadly diseases(치명적 질병을 옮긴다)'야 — 막는 게 아니라 전파해.")]),
 S(r4,4,[("die of","'~로 죽다'")],
  [("worldwide","전 세계에서"),("million","백만")],
  [("[[Over a million people worldwide]] die of these diseases","[[전 세계에서 백만 명 넘는 사람들이]] 이 질병들로 죽는다"),
   ("every year.","매년.")],
  [("이 질병들로 죽는 사람은 매우 드물다는 내용이다.","'Over a million people ... die ... every year(매년 100만 명 이상 사망)'야 — 드문 게 아니라 엄청난 규모야.")]),
 S(r4,5,[("비교급 more ~ than any other","'다른 어떤 ~보다 더'=최상급(⑤)"),("명사절 that","estimates의 목적어"),("관계사 who","humans 수식")],
  [("estimate","추정하다"),("cause","원인"),("billion","십억")],
  [("Throughout history, Winegard estimates that mosquitoes have [[killed more people than any other single cause]]","역사를 통틀어, Winegard는 모기가 [[다른 어떤 단일 원인보다 더 많은 사람을 죽였다]]고 추정한다"),
   ("— about fifty-two billion people, nearly half of all humans who have ever lived.","— 약 520억 명, 지금껏 살았던 모든 인류의 거의 절반을.")],
  [("모기는 다른 원인들보다 적은 사람을 죽였다는 내용이다.","'more people than any other single cause(다른 어떤 원인보다 더 많은 사람)'야 — 적은 게 아니라 가장 많이 죽였다는 뜻이야.")]),
 S(r4,6,[("명사절 that","claims의 목적어"),("분사 shaping","'형성하는'")],
  [("claim","주장하다"),("play a role","역할을 하다"),("shape","형성하다")],
  [("Winegard claims that mosquitoes also [[played a role in shaping the history]]","Winegard는 모기가 [[역사를 형성하는 데도 한 역할을 했다]]고 주장한다"),
   ("of several countries.","여러 나라의.")],
  [("(함축) 모기는 오직 개인의 건강에만 영향을 줄 뿐이라는 뜻이다.","함축을 놓쳤어. 'played a role in shaping the history of several countries(여러 나라 역사를 형성하는 데 한몫)'라며 영향이 개인을 넘어 '역사'에까지 미쳤음을 예고해.")])]

BON1=[finalize(build("모기의 습격과 흡혈 뒤 남는 가려운 반응","PART 1 · 1 (습격)",r1,ov1,i1)),
 finalize(build("이산화탄소·화학물질·체온으로 먹잇감을 찾는 모기","PART 1 · 2 (탐지 단서)",r2,ov2,i2)),
 finalize(build("암컷 모기가 알을 위해 피를 필요로 하는 이유와 산란 과정","PART 1 · 3 (흡혈·산란)",r3,ov3,i3)),
 finalize(build("상어·사자가 아닌 모기가 인류 최대의 포식자라는 주장","PART 2 · 1 (최대 포식자)",r4,ov4,i4))]
