# -*- coding: utf-8 -*-
"""천재 공통영어2 L1 본문 소단원 ⑤~⑦ + 외 지문(무당벌레·지렁이)."""
import sys; sys.path.insert(0,".")
from _helpers import *
SX="천재(강상구) 공통영어2 · Lesson 1 (본문 외 지문)"

# ===== 본문⑤ 로마 제국과 말라리아 (27~34) : not only A but also B =====
r5=["Take the Roman Empire, for example. The fall of the Western Roman Empire was gradual, spanning over centuries.",
"Here are commonly cited reasons for the fall of the empire: invasions by outside forces, economic troubles, and corruption.",
"Diseases like malaria, however, also contributed.",
"Rome, the capital of the empire, was once surrounded by a huge stretch of wetland.",
"This was an ideal breeding ground for mosquitoes and hence a hot spot for malaria.",
"On the one hand, mosquitoes helped protect the city against the armies coming to attack it.",
"However, they eventually spread the disease not only throughout the city, but also throughout the empire, crushing much of the population.",
"Here is another reason why Winegard considers the mosquito a powerful agent of historical change."]
ov5=Overview(theme_ko="서로마 제국의 쇠퇴에 말라리아를 옮긴 모기가 미친 양면적 영향",
 key_grammar=KeyGrammar(point="상관접속사 not only A but also B ('A뿐 아니라 B도')",
  source_sentence="They eventually spread the disease not only throughout the city, but also throughout the empire, crushing much of the population.",
  explanation=[GN("쉽게 말하면","'not only A but also B'는 'A뿐 아니라 [[B도]]'라며 둘 다임을 강조해(초점은 B)."),
   GN("형태","not only 뒤 A, but also 뒤 B에는 [[대등한 것]]이 와 — throughout the city ↔ throughout the empire."),
   GN("also 생략·변형","but also에서 also는 생략되기도 하고, 'B as well'로도 써 — 뜻은 [[같아]]."),
   GN("도치 주의","Not only가 문두로 가면 뒤가 [[의문문 어순]]으로 도치돼(Not only did he ~)."),
   GN("해석 요령","'A뿐만 아니라 B도'로 옮기고 [[B]]에 무게를 실어.")],
  example="",example_analysis="not only throughout the city, but also throughout the empire = '도시뿐 아니라 제국 전역에도' — 둘 다 퍼짐.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 7문장 'not only throughout the city, but also throughout the empire'의 의미로 알맞은 것은?",
    options=["도시뿐 아니라 제국 전역에도 (퍼졌다)","도시에만 퍼지고 제국에는 안 퍼졌다","도시에도 제국에도 퍼지지 않았다"],answer="도시뿐 아니라 제국 전역에도 (퍼졌다)"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'She is ____ smart ____ kind.' (똑똑할 뿐 아니라 친절하다)",
    options=["not only / but also","either / or","neither / nor"],answer="not only / but also"),
   GrammarDrill(kind="객관식",from_passage=False,question="'He speaks not only English but also French.'의 뜻으로 알맞은 것은?",
    options=["그는 영어뿐 아니라 프랑스어도 한다","그는 영어만 하고 프랑스어는 못 한다","그는 둘 다 못 한다"],answer="그는 영어뿐 아니라 프랑스어도 한다"),
   GrammarDrill(kind="영작",from_passage=False,question="그 책은 재미있을 뿐만 아니라 유익하다.",answer="The book is not only interesting but also useful."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 7문장 일부) 그것들은 도시뿐 아니라 제국 전역에도 그 질병을 퍼뜨렸다.",
    answer="They spread the disease not only throughout the city but also throughout the empire.")]),
 topic="서로마 제국의 쇠퇴에는 침략·경제·부패뿐 아니라 말라리아도 작용했으며, 모기가 방어와 확산 양면으로 역사를 바꿨다는 글이야.",
 stance="중립적",stance_reason="모기가 로마 제국사에 미친 양면적 영향을 사실·인과 중심으로 설명하는 정보 전달문이야.",
 structure="주장→근거·예시",structure_reason="로마를 예로 들어(1~3문장) 말라리아도 쇠퇴에 기여했음을 밝히고, 습지·모기의 방어와 확산이라는 근거(4~8문장)로 뒷받침해.",
 restatement_chains=[RestatementChain(label="말라리아의 기여",
   expressions=["Diseases like malaria, however, also contributed","a hot spot for malaria","spread the disease not only throughout the city, but also throughout the empire"],
   variation="'말라리아도 기여함' → '말라리아 발생지' → '도시·제국 전역에 퍼짐'으로 이어져."),
  RestatementChain(label="모기의 양면성",
   expressions=["helped protect the city against the armies","crushing much of the population"],
   variation="'도시를 지키는 데 도움' → '많은 인구를 무너뜨림'으로 양면적 영향이 대조돼.")],
 flow_blocks=[FlowBlock(stage="예시-로마",sentence_range="1~3",summary="서로마 제국의 쇠퇴는 침략·경제·부패가 흔히 꼽히지만, 말라리아 같은 질병도 기여했다.",easy_example="흔한 원인 외에 '병'도 로마를 무너뜨린 것."),
  FlowBlock(stage="모기의 온상",sentence_range="4~5",summary="수도 로마는 거대한 습지에 둘러싸여, 모기의 이상적 번식지이자 말라리아 발생지였다.",easy_example="습지가 모기를 키우고 말라리아를 퍼뜨린 것."),
  FlowBlock(stage="양면적 영향",sentence_range="6~8",summary="모기는 한편으로 침략군을 막아 도시를 지켰지만, 결국 도시·제국 전역에 병을 퍼뜨려 많은 인구를 무너뜨렸다.",easy_example="적을 막아 주기도, 병으로 무너뜨리기도 한 모기.")])
i5=[S(r5,1,[("명령문 Take ~ for example","'~을 예로 들어 보라'"),("분사구문 spanning","'~에 걸치면서'")],
  [("empire","제국"),("gradual","점진적인"),("span","걸치다, 지속되다")],
  [("Take the Roman Empire, for example.","로마 제국을 예로 들어 보라."),
   ("The fall of the Western Roman Empire was gradual, [[spanning over centuries]].","서로마 제국의 쇠퇴는 점진적이었다, [[수 세기에 걸쳐]].")],
  [("이 문장은 서로마 제국이 갑자기 멸망했다는 내용이다.","'gradual, spanning over centuries(수 세기에 걸쳐 점진적)'라고 했어 — 갑자기가 아니라 서서히 무너졌어.")]),
 S(r5,2,[("콜론(:) 부연","reasons를 나열"),("병렬 명사","invasions, economic troubles, and corruption")],
  [("cited","(자주) 언급되는"),("invasion","침략"),("corruption","부패")],
  [("Here are commonly cited reasons for the fall of the empire:","제국의 쇠퇴에 흔히 언급되는 이유들이 있다:"),
   ("[[invasions by outside forces, economic troubles, and corruption]].","[[외부 세력의 침략, 경제 문제, 그리고 부패]].")],
  [("이 문장은 제국 쇠퇴에 원인이 하나뿐이라는 내용이다.","'invasions ..., economic troubles, and corruption(침략·경제·부패)'처럼 여러 원인을 나열해 — 하나가 아니야.")]),
 S(r5,3,[("however 삽입","'그러나'(대조)")],
  [("contribute","기여하다, 한몫하다")],
  [("Diseases like malaria, however,","그러나 말라리아 같은 질병도,"),
   ("also [[contributed]].","또한 [[기여했다]].")],
  [("(함축) 말라리아는 제국 쇠퇴와 아무 상관이 없다는 뜻이다.","함축을 놓쳤어. 'Diseases like malaria, however, also contributed(말라리아도 기여했다)'며 흔한 원인 외의 숨은 원인으로 질병을 덧붙여.")]),
 S(r5,4,[("동격 the capital","Rome 부연"),("수동태 was surrounded","'둘러싸여 있었다'")],
  [("capital","수도"),("surround","둘러싸다"),("wetland","습지")],
  [("Rome, the capital of the empire, was once [[surrounded by a huge stretch of wetland]].","제국의 수도 로마는 한때 [[거대한 습지로 둘러싸여]] 있었다.")],
  [("(지칭) 'the capital of the empire'는 로마가 아닌 다른 도시를 가리킨다.","지칭 오인이야. the capital of the empire는 바로 앞의 'Rome(로마)'을 부연하는 동격이야 — 로마가 제국의 수도라는 뜻이야.")]),
 S(r5,5,[("지시대명사 This","앞 문장(습지)을 받음"),("hence","'그래서'")],
  [("ideal","이상적인"),("breeding ground","번식지"),("hot spot","다발 지역")],
  [("This was an [[ideal breeding ground for mosquitoes]]","이것은 [[모기에게 이상적인 번식지]]였다"),
   ("and hence a hot spot for malaria.","그래서 말라리아 다발 지역이었다.")],
  [("습지는 모기가 살기 어려운 환경이라는 내용이다.","'an ideal breeding ground for mosquitoes(모기에게 이상적인 번식지)'라고 했어 — 살기 어려운 게 아니라 번식하기 좋은 곳이야.")]),
 S(r5,6,[("On the one hand","'한편으로는'"),("현재분사 coming","armies 수식")],
  [("protect against","~로부터 지키다"),("army","군대")],
  [("On the one hand, mosquitoes [[helped protect the city]]","한편으로, 모기는 [[도시를 지키는 데 도움을 주었다]]"),
   ("against the armies coming to attack it.","공격하러 오는 군대로부터.")],
  [("모기는 언제나 도시에 해롭기만 했다는 내용이다.","'On the one hand ... helped protect the city(한편으로는 도시를 지키는 데 도움)'라며 모기의 '이로운' 면을 먼저 들어 — 뒤에 해로운 면과 대조돼.")]),
 S(r5,7,[("상관접속사 not only A but also B","도시뿐 아니라 제국 전역(⑤)"),("분사구문 crushing","'무너뜨리면서'")],
  [("eventually","결국"),("crush","무너뜨리다, 짓밟다"),("population","인구")],
  [("However, they eventually spread the disease [[not only throughout the city, but also throughout the empire]],","그러나 그것들은 결국 [[도시뿐 아니라 제국 전역에도]] 질병을 퍼뜨렸다,"),
   ("[[crushing much of the population]].","[[많은 인구를 무너뜨리면서]].")],
  [("모기는 병을 도시 안에만 가두어 두었다는 내용이다.","'not only throughout the city, but also throughout the empire(도시뿐 아니라 제국 전역에)'야 — 가둔 게 아니라 제국 전체로 퍼뜨렸어.")]),
 S(r5,8,[("관계부사 why","reason 수식"),("consider A B","'A를 B로 여기다'")],
  [("agent","동인, 행위자"),("historical change","역사적 변화")],
  [("Here is another reason why Winegard considers the mosquito","Winegard가 모기를 ~로 여기는 또 다른 이유가 있다"),
   ("[[a powerful agent of historical change]].","[[역사적 변화의 강력한 동인]]으로.")],
  [("이 문장은 앞의 로마 이야기를 마무리하며 끝내는 문장이다.","'Here is another reason(또 다른 이유가 있다)'으로 다음 사례(스코틀랜드)로 넘어가는 전환 문장이야.")])]

# ===== 본문⑥ 스코틀랜드 다리엔 계획 (35~41) : 가정법 과거완료 =====
r6=["In 1698, five ships set sail from Scotland, carrying twelve hundred settlers and valuable trade goods.",
"They headed for the Darien region of Panama, where Scotland planned to create a trading center.",
"After struggling through years of a food crisis, Scotland had hoped this would help raise its economic prospects.",
"The ambitious plan, however, was brought down by the local diseases: yellow fever and malaria.",
"Virtually no one from Scotland had ever encountered any of these diseases before.",
"After six months, nearly half of them died, and the survivors returned to their ships and fled.",
"If their immune systems had been much stronger, they would not have lost so many lives in such a short time."]
ov6=Overview(theme_ko="풍토병(황열·말라리아)으로 실패한 스코틀랜드의 다리엔 식민 계획",
 key_grammar=KeyGrammar(point="가정법 과거완료 (If + had p.p. ~, 주어 + would have p.p.)",
  source_sentence="If their immune systems had been much stronger, they would not have lost so many lives in such a short time.",
  explanation=[GN("쉽게 말하면","'If + had p.p. ~, 주어 + would have p.p.'는 [[과거 사실의 반대]]를 가정해."),
   GN("사실 반대","실제로 면역계가 강하지 [[않았기]] 때문에 많이 죽은 거야 — '강했더라면 안 죽었을 텐데'는 이미 지난 일."),
   GN("형태","If절은 [[had been]](과거완료), 주절은 [[would have lost]](would have p.p.)."),
   GN("가정법 과거와 구별","'지금'의 반대면 과거형(가정법 과거), '[[과거]]'의 반대면 had p.p.(가정법 과거완료)."),
   GN("해석 요령","'(그때) ~했더라면 …했을 텐데 (실제론 아니었음)'로 옮겨.")],
  example="",example_analysis="If ~ had been stronger, they would not have lost ~ = '면역계가 더 강했더라면 그렇게 많이 잃지 않았을 텐데'(실제론 약해서 잃음).",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 7문장 'If their immune systems had been much stronger, they would not have lost so many lives'의 의미로 알맞은 것은?",
    options=["면역계가 약했던 탓에 많이 죽었다는, 과거 사실 반대의 가정","면역계가 강해서 아무도 죽지 않았다","앞으로 면역계가 강해질 것이라는 예측"],answer="면역계가 약했던 탓에 많이 죽었다는, 과거 사실 반대의 가정"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'If I ____ harder, I would have passed.'",
    options=["had studied","studied","study"],answer="had studied"),
   GrammarDrill(kind="객관식",from_passage=False,question="'If he had left earlier, he would have caught the train.'가 의미하는 바는?",
    options=["그는 늦게 떠나서 기차를 놓쳤다","그는 일찍 떠나서 기차를 탔다","그는 기차를 탈 것이다"],answer="그는 늦게 떠나서 기차를 놓쳤다"),
   GrammarDrill(kind="영작",from_passage=False,question="그가 더 조심했더라면, 그 사고는 일어나지 않았을 텐데.",answer="If he had been more careful, the accident would not have happened."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 7문장) 그들의 면역계가 훨씬 더 강했더라면, 그렇게 짧은 시간에 그렇게 많은 목숨을 잃지 않았을 텐데.",
    answer="If their immune systems had been much stronger, they would not have lost so many lives in such a short time.")]),
 topic="1698년 스코틀랜드의 다리엔 식민·무역 계획이 황열·말라리아 같은 풍토병으로 실패했다는, 모기가 역사를 바꾼 또 다른 사례야.",
 stance="중립적",stance_reason="스코틀랜드 다리엔 계획의 실패 원인을 사실·인과 중심으로 서술하는 정보 전달문이야.",
 structure="시간·순서(나열)",structure_reason="1698년 출항(1~2문장) → 기대(3문장) → 풍토병으로 좌절(4~5문장) → 절반 사망·귀환(6~7문장)의 시간 순서로 전개돼.",
 restatement_chains=[RestatementChain(label="야심 찬 계획",
   expressions=["five ships set sail from Scotland","Scotland planned to create a trading center","The ambitious plan"],
   variation="'다섯 척이 출항' → '무역 거점을 세우려 함' → '야심 찬 계획'으로 이어져."),
  RestatementChain(label="풍토병의 좌절",
   expressions=["brought down by the local diseases","nearly half of them died","would not have lost so many lives"],
   variation="'풍토병에 무너짐' → '절반 가까이 사망' → '그렇게 많은 목숨을 잃지 않았을 텐데'로 이어져.")],
 flow_blocks=[FlowBlock(stage="출항·기대",sentence_range="1~3",summary="1698년 스코틀랜드는 정착민·물자를 싣고 파나마 다리엔에 무역 거점을 세워 경제를 살리려 했다.",easy_example="새 무역 거점으로 나라 경제를 일으키려 한 것."),
  FlowBlock(stage="좌절",sentence_range="4~5",summary="그러나 야심 찬 계획은 황열·말라리아 같은 풍토병에 무너졌고, 스코틀랜드인은 그 병을 겪은 적이 없었다.",easy_example="처음 겪는 풍토병에 속수무책이던 것."),
  FlowBlock(stage="결말",sentence_range="6~7",summary="여섯 달 만에 절반 가까이 죽고 생존자는 도망쳤는데, 면역계가 더 강했더라면 그렇게 많이 잃지 않았을 것이다.",easy_example="면역이 약해 짧은 시간에 많이 죽은 것.")])
i6=[S(r6,1,[("분사구문 carrying","'~을 싣고서'"),("set sail","'출항하다'")],
  [("set sail","출항하다"),("settler","정착민"),("trade goods","무역품")],
  [("In 1698, five ships set sail from Scotland,","1698년, 다섯 척의 배가 스코틀랜드에서 출항했다,"),
   ("[[carrying twelve hundred settlers and valuable trade goods]].","[[1,200명의 정착민과 값진 무역품을 싣고서]].")],
  [("이 문장은 배들이 빈 채로 떠났다는 내용이다.","'carrying twelve hundred settlers and valuable trade goods(정착민과 무역품을 싣고서)'야 — 빈 채가 아니라 사람·물자를 가득 싣고 떠났어.")]),
 S(r6,2,[("관계부사 where","the Darien region 수식"),("head for","'~로 향하다'")],
  [("head for","~로 향하다"),("region","지역"),("trading center","무역 거점")],
  [("They headed for the Darien region of Panama,","그들은 파나마의 다리엔 지역으로 향했다,"),
   ("[[where Scotland planned to create a trading center]].","[[스코틀랜드가 무역 거점을 세우려 계획한]] 곳으로.")],
  [("(지칭) 'They'는 파나마 원주민을 가리킨다.","지칭 오인이야. They는 앞의 '다섯 척의 배(에 탄 정착민들)'를 가리켜 — 그들이 다리엔으로 향했다는 뜻이야.")]),
 S(r6,3,[("과거완료 had hoped","'기대했었다'"),("전치사+동명사 After struggling","'~을 겪은 뒤'")],
  [("struggle through","~을 힘겹게 헤쳐 나가다"),("prospect","전망")],
  [("After struggling through years of a food crisis,","여러 해의 식량난을 힘겹게 겪은 뒤,"),
   ("Scotland had hoped this would [[help raise its economic prospects]].","스코틀랜드는 이것이 [[경제 전망을 높이는 데 도움이 되기를]] 기대했었다.")],
  [("스코틀랜드는 이 계획에 아무 기대가 없었다는 내용이다.","'had hoped this would help raise its economic prospects(경제 전망을 높이길 기대했다)'야 — 기대가 없던 게 아니라 큰 기대를 걸었어.")]),
 S(r6,4,[("수동태 was brought down","'무너졌다'"),("콜론(:) 부연","the local diseases를 나열")],
  [("ambitious","야심 찬"),("bring down","무너뜨리다")],
  [("The ambitious plan, however, was [[brought down by the local diseases]]:","그러나 그 야심 찬 계획은 [[풍토병에 무너졌다]]:"),
   ("yellow fever and malaria.","황열과 말라리아.")],
  [("그 계획은 풍토병에도 끄떡없이 성공했다는 내용이다.","'was brought down by the local diseases(풍토병에 무너졌다)'야 — 성공이 아니라 실패했어.")]),
 S(r6,5,[("현재완료 had ever encountered","'겪은 적이 있었다'"),("부정 virtually no one","'사실상 아무도 ~않다'")],
  [("virtually","사실상"),("encounter","맞닥뜨리다")],
  [("Virtually no one from Scotland","스코틀랜드 출신 중 사실상 아무도"),
   ("had ever [[encountered any of these diseases before]].","이전에 [[이 질병들을 겪어 본 적이 없었다]].")],
  [("스코틀랜드인들은 이 병들에 이미 익숙했다는 내용이다.","'Virtually no one ... had ever encountered ... before(사실상 아무도 겪은 적 없음)'야 — 익숙한 게 아니라 처음 겪는 병이라 더 위험했어.")]),
 S(r6,6,[("병렬 died and returned/fled","동사 병렬")],
  [("survivor","생존자"),("flee","달아나다")],
  [("After six months, nearly half of them died,","여섯 달 만에, 그들 중 절반 가까이가 죽었고,"),
   ("and the survivors [[returned to their ships and fled]].","생존자들은 [[배로 돌아가 달아났다]].")],
  [("여섯 달 뒤 모두가 무사히 정착에 성공했다는 내용이다.","'nearly half of them died ... survivors ... fled(절반이 죽고 생존자는 도망침)'야 — 성공이 아니라 참담한 실패였어.")]),
 S(r6,7,[("가정법 과거완료","If + had p.p. ~, would have p.p.(⑤)"),("such ~ that 뉘앙스 so many","'그렇게 많은'")],
  [("immune system","면역계"),("in such a short time","그렇게 짧은 시간에")],
  [("[[If their immune systems had been much stronger]],","[[그들의 면역계가 훨씬 더 강했더라면]],"),
   ("they [[would not have lost so many lives]] in such a short time.","그렇게 짧은 시간에 [[그렇게 많은 목숨을 잃지 않았을 텐데]].")],
  [("(함축) 그들의 면역계가 실제로 강해서 목숨을 거의 잃지 않았다는 뜻이다.","함축을 놓쳤어. 가정법 과거완료라 '실제로는 면역계가 약해서 많이 죽었다'는 뜻이야 — 강했더라면 안 그랬을 거라는 반대 가정이야.")])]

# ===== 본문⑦ 질병 이해의 역사와 결론 (42~45) : It ~ that 강조구문 =====
r7=["Surprisingly, human beings lived with and died of these diseases for thousands of years without understanding how they were spread.",
"It was not until the end of the nineteenth century that we found out that mosquitoes spread malaria.",
"Before this finding, no one imagined that these tiny annoying insects might be affecting our lives so deeply.",
"Now we all know that human history is not free from the workings of the natural world."]
ov7=Overview(theme_ko="19세기 말에야 밝혀진 모기의 질병 전파와, 자연의 작용에서 자유롭지 않은 인류 역사",
 key_grammar=KeyGrammar(point="It ~ that 강조구문 (It was not until ... that ~)",
  source_sentence="It was not until the end of the nineteenth century that we found out that mosquitoes spread malaria.",
  explanation=[GN("쉽게 말하면","'It is/was + 강조어구 + that ~'은 that 앞의 [[강조어구]]를 콕 집어 강조하는 구문이야."),
   GN("not until 강조","'It was not until A that B'는 'A가 되어서야 (비로소) [[B했다]]'라는 뜻이야."),
   GN("여기선","강조된 건 [[the end of the nineteenth century]](19세기 말) — 그때가 되어서야 알게 됐다는 것."),
   GN("가주어와 구별","It ~ that에서 that절이 [[불완전]]하면 강조구문(강조어구를 빼도 문장 성립), 완전하면 가주어."),
   GN("해석 요령","'…한 것은 바로 ~다' / not until은 '~가 되어서야 비로소'로 옮겨.")],
  example="",example_analysis="It was not until the end of the 19th century that we found out ~ = '19세기 말이 되어서야 비로소 알아냈다'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 2문장 'It was not until the end of the nineteenth century that we found out ~'의 의미로 알맞은 것은?",
    options=["19세기 말이 되어서야 비로소 알아냈다","19세기 말 전에 이미 알아냈다","19세기 말에도 여전히 몰랐다"],answer="19세기 말이 되어서야 비로소 알아냈다"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'It was John ____ broke the window.' (창문을 깬 건 바로 John)",
    options=["that","what","which"],answer="that"),
   GrammarDrill(kind="객관식",from_passage=False,question="'It was not until midnight that she came home.'의 뜻으로 알맞은 것은?",
    options=["자정이 되어서야 그녀가 집에 왔다","자정 전에 그녀가 집에 왔다","그녀는 자정에도 집에 안 왔다"],answer="자정이 되어서야 그녀가 집에 왔다"),
   GrammarDrill(kind="영작",from_passage=False,question="내가 그 소식을 들은 것은 바로 어제였다.",answer="It was yesterday that I heard the news."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 2문장 일부) 우리가 모기가 말라리아를 퍼뜨린다는 것을 알아낸 것은 19세기 말이 되어서였다.",
    answer="It was not until the end of the nineteenth century that we found out that mosquitoes spread malaria.")]),
 topic="인류는 오랫동안 질병의 전파 방식을 모른 채 살다가 19세기 말에야 모기가 원인임을 알아냈고, 역사가 자연의 작용에서 자유롭지 않음을 보여 준다는 결론이야.",
 stance="중립적",stance_reason="질병 이해의 역사와 그 함의를 사실 중심으로 정리하며 결론을 내리는 글이야.",
 structure="예시→일반화(결론)",structure_reason="오랫동안 원인을 몰랐던 사실(1문장)과 19세기 말의 발견(2~3문장)을 든 뒤, '역사는 자연의 작용에서 자유롭지 않다'는 일반화(4문장)로 맺어.",
 restatement_chains=[RestatementChain(label="뒤늦은 이해",
   expressions=["without understanding how they were spread","It was not until the end of the nineteenth century that we found out","Before this finding"],
   variation="'전파 방식을 모른 채' → '19세기 말이 되어서야 알아냄' → '이 발견 이전'으로 이어져."),
  RestatementChain(label="자연의 영향",
   expressions=["might be affecting our lives so deeply","human history is not free from the workings of the natural world"],
   variation="'우리 삶에 깊이 영향' → '역사가 자연의 작용에서 자유롭지 않음'으로 정리돼.")],
 flow_blocks=[FlowBlock(stage="오랜 무지",sentence_range="1",summary="인류는 수천 년간 이 질병들과 함께 살고 죽으면서도 그 전파 방식을 이해하지 못했다.",easy_example="원인도 모른 채 오래 병에 시달린 것."),
  FlowBlock(stage="뒤늦은 발견",sentence_range="2~3",summary="19세기 말이 되어서야 모기가 말라리아를 퍼뜨린다는 것을 알아냈고, 그전엔 아무도 이 작은 곤충의 영향을 상상하지 못했다.",easy_example="한참 뒤에야 범인이 모기임을 안 것."),
  FlowBlock(stage="결론",sentence_range="4",summary="이제 우리는 인류 역사가 자연의 작용에서 자유롭지 않음을 안다.",easy_example="역사도 자연의 힘에서 벗어날 수 없다는 것.")])
i7=[S(r7,1,[("병렬 lived with and died of","동사구 병렬"),("전치사+동명사 without understanding","'~을 이해하지 못한 채'"),("의문사 how","'어떻게 ~하는지'")],
  [("live with","~와 더불어 살다"),("spread","퍼지다, 퍼뜨리다")],
  [("Surprisingly, human beings [[lived with and died of these diseases]] for thousands of years","놀랍게도, 인류는 수천 년간 [[이 질병들과 더불어 살고 그로 죽었다]]"),
   ("without [[understanding how they were spread]].","[[그것들이 어떻게 퍼지는지 이해하지 못한 채]].")],
  [("인류는 오래전부터 질병의 전파 방식을 잘 알고 있었다는 내용이다.","'without understanding how they were spread(어떻게 퍼지는지 이해하지 못한 채)'야 — 잘 안 게 아니라 오랫동안 몰랐어.")]),
 S(r7,2,[("It ~ that 강조구문","not until ~ that ~(⑤)"),("명사절 that","found out의 목적어")],
  [("not until","~가 되어서야"),("find out","알아내다")],
  [("[[It was not until the end of the nineteenth century]]","[[19세기 말이 되어서야 비로소]]"),
   ("[[that we found out that mosquitoes spread malaria]].","[[우리는 모기가 말라리아를 퍼뜨린다는 것을 알아냈다]].")],
  [("이 문장은 19세기 훨씬 전에 이미 원인을 알았다는 내용이다.","'not until the end of the nineteenth century that we found out(19세기 말이 되어서야 알아냈다)'야 — 훨씬 전이 아니라 그때서야 알았어.")]),
 S(r7,3,[("명사절 that","imagined의 목적어"),("부정 no one","'아무도 ~않다'")],
  [("finding","발견"),("imagine","상상하다"),("insect","곤충")],
  [("Before this finding, no one imagined","이 발견 이전에는, 아무도 상상하지 못했다"),
   ("that these tiny annoying insects [[might be affecting our lives so deeply]].","이 작고 성가신 곤충이 [[우리 삶에 그토록 깊이 영향을 미치고 있을지도]] 모른다는 것을.")],
  [("(지칭) 'these tiny annoying insects'는 로마 군대를 가리킨다.","지칭 오인이야. these tiny annoying insects는 글 전체의 주인공인 '모기'를 가리켜 — 모기의 깊은 영향을 아무도 몰랐다는 뜻이야.")]),
 S(r7,4,[("be free from","'~에서 자유롭다·벗어나다'"),("명사절 that","know의 목적어")],
  [("be free from","~에서 자유롭다"),("workings","작용, 작동")],
  [("Now we all know","이제 우리 모두는 안다"),
   ("that human history is [[not free from the workings of the natural world]].","인류 역사가 [[자연의 작용에서 자유롭지 않다는]] 것을.")],
  [("(함축) 인류 역사는 자연의 영향과 완전히 무관하게 흘러왔다는 뜻이다.","함축을 놓쳤어. 'not free from the workings of the natural world(자연의 작용에서 자유롭지 않다)'는 곧 '자연(모기)이 역사를 좌우해 왔다'는, 글 전체의 결론이야.")])]

# ===== 무당벌레 (Ladybugs 1~6) : 주격 관계대명사 that =====
r8=["Ladybugs are probably the most well-known of all the helpful bugs in the garden.",
"First of all, they eat quite a few of the bad bugs that prevent plants from growing.",
"Each ladybug can eat fifty to sixty aphids per day and over five thousand in its lifetime.",
"Their young eat aphids, too.",
"If you grow plants that attract ladybugs, such as cilantro or mint, you may not have to worry about harmful bugs anymore.",
"Even better, ladybugs can defend themselves by giving off a certain smell that their predators do not like."]
ov8=Overview(theme_ko="정원에서 해충을 잡아먹고 스스로를 방어하는 이로운 곤충, 무당벌레",
 key_grammar=KeyGrammar(point="주격 관계대명사 that (선행사 + that + 동사 ~)",
  source_sentence="They eat quite a few of the bad bugs that prevent plants from growing.",
  explanation=[GN("쉽게 말하면","주격 관계대명사 that은 '[[~하는]]'으로 앞의 명사(선행사)를 꾸미고, 바로 뒤에 [[동사]]가 와."),
   GN("판별","that 뒤에 주어가 없고 [[동사]]가 바로 오면 '주격' — the bugs that [[prevent]] ~."),
   GN("who/which와 관계","선행사가 사물·동물이면 that=which, 사람이면 that=who로 바꿔 쓸 수 있어."),
   GN("수일치","that절의 동사는 [[선행사]]의 수에 맞춰 — the bugs that prevent(복수), a smell that [[does]] not(단수 나올 땐 단수)."),
   GN("해석 요령","'~하는 (명사)'로 that절을 앞 명사에 붙여 옮겨.")],
  example="",example_analysis="the bad bugs that prevent plants from growing = '식물이 자라는 것을 막는 나쁜 벌레들' — that가 주격.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 2문장 'the bad bugs that prevent plants from growing'에서 that의 역할은?",
    options=["the bad bugs를 꾸미는 주격 관계대명사","'저것'을 뜻하는 지시대명사","명사절을 이끄는 접속사"],answer="the bad bugs를 꾸미는 주격 관계대명사"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'I have a friend ____ lives in London.'",
    options=["who","whom","whose"],answer="who"),
   GrammarDrill(kind="객관식",from_passage=False,question="'This is the key that opens the door.'에서 that절이 꾸미는 것은?",
    options=["the key","the door","This"],answer="the key"),
   GrammarDrill(kind="영작",from_passage=False,question="나는 하늘을 나는 새들을 좋아한다.",answer="I like birds that fly in the sky."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 2문장 일부) 그것들은 식물이 자라는 것을 막는 나쁜 벌레들을 먹는다.",
    answer="They eat the bad bugs that prevent plants from growing.")]),
 topic="무당벌레가 진딧물 같은 해충을 잡아먹어 정원을 돕고, 냄새로 스스로를 방어하는 이로운 곤충이라는 글이야.",
 stance="긍정적",stance_reason="무당벌레의 이로움을 'most well-known helpful bugs'·'Even better'로 부각하며 그 가치를 인정해.",
 structure="주장→근거·예시",structure_reason="'무당벌레는 가장 잘 알려진 이로운 곤충'이라는 주장(1문장) 뒤, 해충 포식·유충·유인 식물·자기방어라는 근거(2~6문장)로 뒷받침해.",
 restatement_chains=[RestatementChain(label="해충 포식",
   expressions=["eat quite a few of the bad bugs","eat fifty to sixty aphids per day","Their young eat aphids, too"],
   variation="'나쁜 벌레를 잡아먹음' → '하루 50~60마리 진딧물' → '유충도 진딧물을 먹음'으로 이어져."),
  RestatementChain(label="이로움",
   expressions=["the most well-known of all the helpful bugs","you may not have to worry about harmful bugs anymore","defend themselves"],
   variation="'가장 잘 알려진 이로운 곤충' → '해충 걱정이 없어짐' → '스스로 방어함'으로 이어져.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1",summary="무당벌레는 정원의 이로운 곤충 중 아마 가장 잘 알려져 있다.",easy_example="정원 하면 떠오르는 대표적 익충."),
  FlowBlock(stage="해충 포식",sentence_range="2~4",summary="식물 성장을 막는 나쁜 벌레를 잡아먹는데, 한 마리가 하루 50~60마리(평생 5천 마리 넘게) 진딧물을 먹고 유충도 먹는다.",easy_example="진딧물을 엄청나게 먹어 치우는 것."),
  FlowBlock(stage="이로움·방어",sentence_range="5~6",summary="무당벌레를 유인하는 식물을 키우면 해충 걱정이 줄고, 무당벌레는 포식자가 싫어하는 냄새로 스스로를 지킨다.",easy_example="고수·박하로 불러들이면 해충이 줄고, 냄새로 자기 몸을 지키는 것.")])
i8=[S(r8,1,[("최상급 the most well-known","'가장 잘 알려진'"),("of all","'모든 ~ 중에서'")],
  [("well-known","잘 알려진"),("helpful","이로운")],
  [("Ladybugs are probably [[the most well-known]] of all the helpful bugs","무당벌레는 아마 모든 이로운 곤충 중 [[가장 잘 알려져]] 있다"),
   ("in the garden.","정원에서.")],
  [("무당벌레는 정원에서 거의 알려지지 않은 곤충이라는 내용이다.","'the most well-known of all the helpful bugs(가장 잘 알려진 이로운 곤충)'야 — 안 알려진 게 아니라 대표적 익충이야.")]),
 S(r8,2,[("주격 관계대명사 that","the bad bugs that prevent ~(⑤)"),("prevent A from -ing","'A가 ~하지 못하게 막다'")],
  [("first of all","우선"),("quite a few","꽤 많은"),("prevent","막다")],
  [("First of all, they eat [[quite a few of the bad bugs]]","우선, 그것들은 [[꽤 많은 나쁜 벌레들]]을 먹는다"),
   ("[[that prevent plants from growing]].","[[식물이 자라는 것을 막는]].")],
  [("무당벌레는 식물에 해로운 벌레라는 내용이다.","'they eat ... the bad bugs that prevent plants from growing(식물 성장을 막는 나쁜 벌레를 먹는다)'야 — 해로운 게 아니라 해충을 잡아먹는 이로운 곤충이야.")]),
 S(r8,3,[("비교 fifty to sixty / over five thousand","수량 표현"),("병렬 per day and in its lifetime","부사구 대등")],
  [("aphid","진딧물"),("lifetime","일생, 평생")],
  [("Each ladybug can eat [[fifty to sixty aphids per day]]","무당벌레 한 마리는 [[하루에 진딧물 50~60마리]]를 먹을 수 있다"),
   ("and over five thousand in its lifetime.","그리고 평생 5천 마리 넘게.")],
  [("무당벌레는 진딧물을 거의 먹지 않는다는 내용이다.","'fifty to sixty aphids per day ... over five thousand in its lifetime(하루 50~60마리, 평생 5천 마리 넘게)'야 — 엄청나게 많이 먹어.")]),
 S(r8,4,[("too","'~도'")],
  [("young","(동물의) 새끼, 유충")],
  [("Their [[young]] eat aphids, too.","그것들의 [[유충]]도 진딧물을 먹는다.")],
  [("(지칭) 'Their young'의 their는 진딧물을 가리킨다.","지칭 오인이야. their는 'Ladybugs(무당벌레)'를 가리켜 — 무당벌레의 유충도 진딧물을 먹는다는 뜻이야.")]),
 S(r8,5,[("조건 if","'~라면'"),("주격 관계대명사 that","plants that attract ~"),("not have to","'~할 필요가 없다'")],
  [("attract","유인하다"),("cilantro","고수"),("harmful","해로운")],
  [("If you grow [[plants that attract ladybugs]], such as cilantro or mint,","고수나 박하처럼 [[무당벌레를 유인하는 식물]]을 키우면,"),
   ("you may not have to [[worry about harmful bugs anymore]].","더 이상 [[해로운 벌레를 걱정하지 않아도]] 될 것이다.")],
  [("무당벌레를 유인해도 해충은 그대로라는 내용이다.","'you may not have to worry about harmful bugs anymore(더는 해충 걱정을 안 해도 된다)'야 — 그대로가 아니라 해충이 줄어.")]),
 S(r8,6,[("by -ing","'~함으로써'"),("주격 관계대명사 that","a certain smell that ~"),("재귀 themselves","'스스로를'")],
  [("even better","한결 더 나은 것은"),("defend","방어하다"),("give off","(냄새를) 내뿜다")],
  [("Even better, ladybugs can [[defend themselves]]","한결 더 나은 것은, 무당벌레가 [[스스로를 방어할]] 수 있다는 것이다"),
   ("by giving off [[a certain smell that their predators do not like]].","[[포식자가 싫어하는 특정 냄새]]를 내뿜음으로써.")],
  [("(함축) 무당벌레는 포식자에게 아무런 방어 수단이 없다는 뜻이다.","함축을 놓쳤어. 'defend themselves by giving off a certain smell(냄새로 스스로를 방어)'이라며 무당벌레가 자기방어 수단까지 갖췄음을 강조해.")])]

# ===== 지렁이 (Earthworms 1~6) : 전치사 + 동명사 =====
r9=["Earthworms are a great addition to your garden as well.",
"They help keep your soil soft and breathable by digging tunnels that bring air to the roots of plants.",
"They also eat the dead bits of plants that fall to the ground, recycling them back into the soil and helping new plants to grow.",
"Moreover, their waste makes your soil richer, and they are excellent at breaking down organic matter in your garden.",
"However, you should be careful about applying artificial fertilizers to your garden after introducing earthworms.",
"They will find a new home when the soil around them changes."]
ov9=Overview(theme_ko="토양을 부드럽게 하고 유기물을 분해해 정원을 돕는 지렁이와 사용 시 주의점",
 key_grammar=KeyGrammar(point="전치사 + 동명사 (about/at/after + V-ing)",
  source_sentence="You should be careful about applying artificial fertilizers to your garden after introducing earthworms.",
  explanation=[GN("쉽게 말하면","전치사 뒤에는 동사가 그대로 못 오고 반드시 [[동명사(-ing)]]로 바꿔 써."),
   GN("여기선","careful [[about applying]] ~, after [[introducing]] ~ — about·after 뒤가 모두 -ing."),
   GN("빈출 짝","be good/careful at·about, before/after -ing, without -ing 등 '[[전치사+동명사]]'로 굳어진 표현이 많아."),
   GN("to 구별","'to부정사'의 to와 달리, 전치사 to 뒤에는 [[동명사]]가 와(look forward to -ing)."),
   GN("해석 요령","'~하는 것에 대해 / ~한 뒤에'처럼 전치사 뜻에 맞춰 동명사를 명사로 옮겨.")],
  example="",example_analysis="careful about applying ~ after introducing ~ = '~을 들여놓은 뒤 ~을 뿌리는 것에 대해 조심하라'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 5문장 'careful about applying ~ after introducing ~'에서 applying·introducing의 형태가 -ing인 이유는?",
    options=["전치사(about·after) 뒤라서 동명사로 썼다","진행형이라서","분사구문이라서"],answer="전치사(about·after) 뒤라서 동명사로 썼다"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'She is good at ____ pictures.'",
    options=["drawing","draw","to draw"],answer="drawing"),
   GrammarDrill(kind="객관식",from_passage=False,question="어법상 올바른 것은?",
    options=["Thank you for helping me.","Thank you for help me.","Thank you for to help me."],answer="Thank you for helping me."),
   GrammarDrill(kind="영작",from_passage=False,question="그는 아침을 먹지 않고 학교에 갔다.",answer="He went to school without eating breakfast."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 5문장 일부) 당신은 지렁이를 들여놓은 뒤 인공 비료를 뿌리는 것에 대해 조심해야 한다.",
    answer="You should be careful about applying artificial fertilizers after introducing earthworms.")]),
 topic="지렁이가 굴을 파고 죽은 식물을 분해해 토양을 비옥·통기성 있게 만들지만, 들여놓은 뒤 인공 비료는 조심해야 한다는 글이야.",
 stance="긍정적",stance_reason="지렁이를 'a great addition'·'excellent at ~'으로 평가하며 정원에 주는 이로움을 인정해.",
 structure="주장→근거·예시",structure_reason="'지렁이도 정원에 좋다'는 주장(1문장) 뒤, 토양 개선·유기물 분해라는 근거(2~4문장)를 들고 사용상 주의점(5~6문장)을 덧붙여.",
 restatement_chains=[RestatementChain(label="토양을 돕는 지렁이",
   expressions=["a great addition to your garden","keep your soil soft and breathable","their waste makes your soil richer"],
   variation="'정원에 좋은 존재' → '토양을 부드럽고 통기성 있게 유지' → '배설물이 토양을 비옥하게'로 이어져."),
  RestatementChain(label="분해·재순환",
   expressions=["eat the dead bits of plants","recycling them back into the soil","breaking down organic matter"],
   variation="'죽은 식물을 먹음' → '흙으로 재순환' → '유기물 분해'로 이어져.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1",summary="지렁이 또한 정원에 좋은 존재다.",easy_example="정원에 도움이 되는 또 다른 생물."),
  FlowBlock(stage="이로움",sentence_range="2~4",summary="굴을 파 뿌리에 공기를 주고, 죽은 식물을 먹어 흙으로 재순환시키며, 배설물로 토양을 비옥하게 하고 유기물을 잘 분해한다.",easy_example="흙을 부드럽게·비옥하게 만들어 주는 것."),
  FlowBlock(stage="주의점",sentence_range="5~6",summary="다만 지렁이를 들여놓은 뒤 인공 비료는 조심해야 하는데, 주변 토양이 바뀌면 지렁이는 새 서식지를 찾아 떠난다.",easy_example="비료를 함부로 쓰면 지렁이가 떠나 버리는 것.")])
i9=[S(r9,1,[("as well","'~도 또한'")],
  [("addition","보탬, 부가물")],
  [("Earthworms are [[a great addition to your garden]] as well.","지렁이도 [[여러분의 정원에 좋은 보탬]]이다.")],
  [("지렁이는 정원에 해를 끼치는 존재라는 내용이다.","'a great addition to your garden(정원에 좋은 보탬)'이라고 했어 — 해가 아니라 도움이 되는 존재야.")]),
 S(r9,2,[("keep + 목적어 + 형용사","'~을 …한 상태로 유지하다'"),("주격 관계대명사 that","tunnels that bring ~"),("by -ing","'~함으로써'")],
  [("breathable","통기성 있는"),("dig","파다"),("tunnel","굴, 터널")],
  [("They help keep your soil [[soft and breathable]]","그것들은 여러분의 토양을 [[부드럽고 통기성 있게]] 유지하도록 돕는다"),
   ("by digging tunnels [[that bring air to the roots of plants]].","[[식물 뿌리에 공기를 가져다주는]] 굴을 팜으로써.")],
  [("지렁이는 토양을 단단하게 다져 공기를 막는다는 내용이다.","'keep your soil soft and breathable ... bring air to the roots(부드럽고 통기성 있게, 뿌리에 공기를)'야 — 공기를 막는 게 아니라 통하게 해.")]),
 S(r9,3,[("주격 관계대명사 that","the dead bits ... that fall ~"),("분사구문 recycling and helping","'재순환시키고 돕는'(연속·결과)")],
  [("bits","조각들"),("recycle","재순환시키다")],
  [("They also eat the dead bits of plants that fall to the ground,","그것들은 또한 땅에 떨어진 식물의 죽은 조각을 먹는다,"),
   ("[[recycling them back into the soil and helping new plants to grow]].","[[그것들을 흙으로 재순환시키고 새 식물이 자라도록 도우면서]].")],
  [("(지칭) 'recycling them'의 them은 새로운 식물을 가리킨다.","지칭 오인이야. them은 앞의 '죽은 식물 조각(the dead bits of plants)'을 가리켜 — 그 조각을 흙으로 재순환시킨다는 뜻이야.")]),
 S(r9,4,[("make + 목적어 + 비교급","'~을 더 …하게 만들다'"),("전치사+동명사 at breaking down","'분해하는 데'"),("병렬 makes and are","동사 대등")],
  [("waste","배설물"),("break down","분해하다"),("organic matter","유기물")],
  [("Moreover, their waste [[makes your soil richer]],","게다가, 그것들의 배설물은 [[토양을 더 비옥하게 만든다]],"),
   ("and they are excellent [[at breaking down organic matter]] in your garden.","그리고 그것들은 정원의 [[유기물을 분해하는 데]] 탁월하다.")],
  [("지렁이의 배설물은 토양을 척박하게 만든다는 내용이다.","'their waste makes your soil richer(배설물이 토양을 더 비옥하게)'야 — 척박이 아니라 비옥하게 만들어.")]),
 S(r9,5,[("전치사+동명사 about applying / after introducing","'~하는 것에 대해/~한 뒤에'(⑤)"),("however 전환","'그러나'")],
  [("apply","(비료 등을) 뿌리다·주다"),("artificial fertilizer","인공 비료"),("introduce","들여놓다, 도입하다")],
  [("However, you should be careful [[about applying artificial fertilizers]] to your garden","그러나, 여러분은 정원에 [[인공 비료를 뿌리는 것에 대해]] 조심해야 한다"),
   ("[[after introducing earthworms]].","[[지렁이를 들여놓은 뒤에는]].")],
  [("지렁이를 들여놓은 뒤엔 인공 비료를 마음껏 써도 된다는 내용이다.","'should be careful about applying artificial fertilizers(인공 비료 뿌리는 것을 조심해야)'야 — 마음껏이 아니라 조심해야 해.")]),
 S(r9,6,[("접속사 when","'~할 때'")],
  [("find a new home","새 서식지를 찾다")],
  [("They will [[find a new home]]","그것들은 [[새 서식지를 찾을]] 것이다"),
   ("when the soil around them changes.","주변 토양이 바뀌면.")],
  [("(함축) 토양이 바뀌어도 지렁이는 그 자리에 계속 머문다는 뜻이다.","함축을 놓쳤어. 'will find a new home when the soil ... changes(토양이 바뀌면 새 서식지를 찾는다)'는, 비료로 환경을 해치면 지렁이가 '떠난다'는 경고를 담아.")])]

BON2=[finalize(build("서로마 제국 쇠퇴에 말라리아를 옮긴 모기가 미친 양면적 영향","본문5 (모기·로마 제국)",r5,ov5,i5)),
 finalize(build("풍토병으로 실패한 스코틀랜드의 다리엔 식민 계획","본문6 (모기·스코틀랜드)",r6,ov6,i6)),
 finalize(build("19세기 말에야 밝혀진 모기의 질병 전파와 자연에 얽힌 인류 역사","본문7 (모기·역사와 결론)",r7,ov7,i7))]
EXTRA=[finalize(build("해충을 잡아먹고 스스로를 방어하는 이로운 곤충 무당벌레","외 지문1 (무당벌레)",r8,ov8,i8,src=SX)),
 finalize(build("토양을 부드럽게 하고 유기물을 분해해 정원을 돕는 지렁이","외 지문2 (지렁이)",r9,ov9,i9,src=SX))]
