# 고2 2026년 9월 모의고사 산문 20지문 → moui3_prose.json (원문 verbatim)
import json
SC="/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad/moui3"

P = {
"20": ("가까운 이가 아닌 비평적 안목을 가진 독자에게 피드백을 구하라",
"Only when you're happy that you've done the best you can for your story should you show it to someone else. You may well want to show it to your nearest and dearest, and that's fine, but in most cases you shouldn't look to their reading for any great benefit to your work. The most valuable feedback is likely to come from other sources: you should choose readers for their critical insight, not their closeness to you. Fellow writers are ideal, but don't imagine that any writer will do. If you are part of a writers' circle or class, you'll know whose writing you admire, and if you've had feedback in the past you'll know whose opinions have been helpful ― and whose have not."),

"21": ("유연한 시간 문화의 회의는 예측 불가능하게 자라는 상록수 같다",
"A meeting in a flexible-time culture like those found in South America, parts of Europe, Africa, and the Middle East is more like an evergreen tree. An agenda with a meeting start time and a topic will probably be circulated before the meeting. This will serve as the trunk of the tree. But there's no expectation that the meeting will progress in a linear manner. What seemed like a priority last week when the agenda was crafted is not necessarily the priority right now ― so discussion may branch off in a new direction. Other branches may sprout as some members have urgent phone calls that take them in and out of the meeting. Or sub-groups may form within the room to discuss timely subjects linked in some way to the main meeting trunk. In flexible-time cultures, it seems clear that the most productive meetings grow in unpredictable ways, and the effective manager is flexible and professional enough to capitalize on priorities and changing needs as they arise. Interruptions, agenda changes, and frequent shifts in direction are seen as natural and necessary."),

"22": ("먹을 때는 먹기 — '늘 접속' 상태의 멀티태스킹이 부르는 소화불량",
"When we are 'always on' we are constantly ingesting content ― reading alerts and texts, liking, checking emails, downloading, uploading, upgrading, updating, deleting, submitting responses, and posting. If we do it while we are eating, our multi-tasking is overloading us. As our will attempts to digest the virtual content its forces are diverted from the physical content, our food. It's easy to eat a sandwich in a minute while talking on the phone. Some people are skilled at doing both at the same time. Others write a half-hearted, shorthand text while they hurriedly eat their sandwich at the same time. The result can be a misunderstood text with the need for further clarifying texts and the beginnings of nervous indigestion. Eat your sandwich. Taste it. Let it go down. Then text."),

"23": ("긴장과 이완이 만드는 음악의 즐거움",
"Music can bring us into a very comfortable rhythm, and it can be satisfying in and of itself. Most of the time, however, we want something more to happen. There needs to be a process that creates tension and drives the movement towards something in particular. The excitement that arises in this process creates satisfaction and pleasure. This is seen in the measureless prelude as well. But there the tension might be caused by the ambiguity of the rhythm. Therefore, the fluid movement in the prelude usually creates a tension that can be released in the subsequent movement with a set rhythm. This, in turn, creates new and other types of tensions, where the rhythm is unambiguous and predictable, but where unexpected chords and modulations create drama and an experience of development in the piece."),

"24": ("주의력 문해력 — 설계된 산만함을 인식하는 교육",
"Progressive educators and librarians are developing curricula to teach what we might call attention literacy. This means helping students recognize, for example, how the architecture of a social media feed or a news site is deliberately designed to distract or provoke them. Classes in media literacy traditionally cover how to evaluate the credibility of sources ― now they also include recognizing clickbait, understanding the role of algorithms in what content is served up, and observing one's own patterns of distraction. A student might be tasked with tracking how many times they switch tasks or check their phone in an hour of homework, to raise self-awareness about fragmentation. Another lesson might involve unpacking the design of popular apps: Why does an app use infinite scrolling instead of pages? Why do notifications appear with specific colors and sounds? By treating these as deliberate design choices (often rooted in psychology and profit motives), young people become more critical users rather than passive consumers."),

"26": ("미국 조경 건축의 아버지 Frederick Law Olmsted",
"Frederick Law Olmsted, known as the father of American landscape architecture, was born in 1822. When Olmsted was young, he often went on trips to the countryside with his father, who loved scenery. At age 14, he was preparing himself to study at Yale College, but he could not enter due to a severe sumac poisoning that damaged his eyesight. Instead of attending a college, he gained experience working as a clerk, a sailor, and a farmer. In 1858, he worked with Calvert Vaux and won the design competition for New York City's Central Park with the \"Greensward Plan.\" During the Civil War, Olmsted served as General Secretary of the United States Sanitary Commission. Although he passed away in 1903, his sons and successors continued his design philosophy. In 1979, the National Park Service designated his home and office in Brookline, Massachusetts, as a National Historic Site to honor his legacy."),

"29": ("자본주의 — 값싼 자연의 바다 속 현금 교환의 섬들",
"Capitalism is not a system where cash is everywhere but rather one in which islands of cash exchange exist within oceans of cheap―or potentially cheap―natures. Reproducing life within the cash nexus is expensive, and it grows more expensive over time. Workers' wages can be frozen, even rolled back, but in the end inequality leads to crises of the kind we've recently seen bring about populist protests in the United States and the United Kingdom. Workers demand dignity, and their labor becomes expensive. Production processes burn through an island, and energy is no longer cheap. The climate changes, and crops can no longer grow as abundantly as they once did. Frontiers are so important in these processes because they offer places where the new cheap things can be seized―and the cheap work of humans and other natures can be forcefully taken."),

"30": ("도덕적 면허 효과 — 친환경 행동 뒤의 심리",
"Some people are more likely to cheat and steal after purchasing \"eco-friendly\" products, probably because they feel licensed to do so since they morally account the \"eco-friendly\" choice as a \"good\" deed. Moral licensing has also been observed in the context of cooperation for the good of the environment. When people are reminded of deeds they have done that they know were harmful to the environment, they might be left with a feeling of \"eco-guilt.\" People who experience eco-guilt seek pro-environmental actions to compensate for this guilt and restore balance. In their search for such a balance, people are inclined to believe in \"quick-fixes,\" because they want to re-establish the moral balance and escape the guilt as quickly and easily as possible. In the same way that people may change their attitudes to reduce inconsistencies between attitudes and behavior, people may also change their evaluation of past environmentally burdening behaviors and future environmentally friendly behaviors. For instance, people are more likely to sign a petition addressing environmental damage after viewing evidence of human-caused environmental damage."),

"31": ("불분명해지는 인간 지리 — 양자적 인간",
"Human geography is becoming unclear. As people find themselves regularly on the move, we are experiencing a phase shift like when matter transitions from solid to liquid to gas: molecules heat up and loosen from one another, vibrating more rapidly. One might even say that humans are becoming like particles in quantum physics, their velocity and location always in flux. It would be nice to return to some form of stability, but that's not how things work in a quantum world. Instead, the complexity of today's world makes it increasingly difficult to permanently settle anywhere. Highly paid digital nomads and billionaires with multiple passports as well as migratory workers are all part of the diverse and growing global demographic of quantum people."),

"32": ("공유된 의미의 필요 — 불확실성이라는 문제",
"Of the cognitive motivations, the most fundamental one encourages people to understand their environment to predict what is going to happen in case of uncertainties. Most important, people prefer to develop meanings that are shared with other people. For example, if in a given year more people accept offers of admission than a college expects, quite a few students end up living in dorm lounges or campus hotels. It is easy to understand why living in the lounge is problematic (no closet, for one thing). But what is wrong with a room at campus hotels? After all, students in a hotel get private bathrooms, their own TV, and larger rooms. In fact, living in those hotels is problematic because the student residents are not a part of a stable group with people who will be their neighbors for the year; they must wait in uncertainty before finding their social niche. The uncertainty itself is the problem. People lack a shared social understanding, normally developed from membership in a stable group."),

"33": ("상실을 애도하는 일 — 사랑과 삶을 강화하는 슬픔",
"Psychological theories across the field agree on the importance of grieving our losses, from the highly personal through to the broadly collective. Grief is a dynamic emotional process essential to consciousness. At a psychological level, it supports us to both face into our own and others' vulnerability, transience and mortality, and to repair life energy after significant loss. Grief work honours the loss, the sadness and the experience of diminishment or absence, while also setting up the ground for self-transformation and the continuation of life. Psychotherapist Fran Weller describes grief work is \"an act of devotion, rooted in love and compassion\" that requires \"an ongoing practice of deepening, attending and listening.\" When we grieve for what is lost, it clears the way towards a strengthening of love and commitment for what remains. In time this may build a desire to make good from the loss by repairing as many damages as we can and/or compensating for them. Grief can make us both very sad and very motivated to act."),

"34": ("전자레인지의 숨은 장기 영향 — 가족 저녁 식사의 소멸",
"When we focus on the obvious aspects of media, we miss the changes that accumulate over time but are not apparent day to day. Most of us notice the obvious aspects of a new medium or technology while missing the more subtle aspects. Take, for example, the microwave oven. It was introduced in the early 1980s and revolutionized food preparation. Traditionally, one person spent the better part of an afternoon fixing an evening meal for a family. Now, it was possible to prepare foods very quickly, and this shortening of preparation time was liberating for the cooks in the family, most of whom tended to be women. But the short-term, obvious implications of greater convenience made it easy to overlook the long-term implications of no longer having one person fix food for the family to eat together at an evening meal. As time went on, fewer and fewer families sat down together to eat dinner. Meals that took a long time to prepare became a luxury of the past, except perhaps for special occasions. The effects of the microwave oven on family life were not anticipated and would have been difficult to foresee."),

"35": ("디지털 트윈 — 실시간 데이터로 갱신되는 디지털 복제본",
"Digital twins are digital replicas of assets or activities using modeling and sensors to create digital representations. Digital twins are not new; engineering teams in various industries have used 3D renderings of computer-aided design models, asset models, and process simulations for years. However, faster wireless networks and the resulting availability of real-time data enable much more detailed and dynamic digital representations. When sensors collect data from a connected device, the sensor data can be used to continuously update the digital twin. The digital twin becomes a real-time accurate copy of a physical object's properties and states. For instance, digital twins of physical assets such as power-generation turbines, jet engines, and train engines are becoming common when the assets are very valuable and when downtime would be very costly."),

"36": ("미래의 필요를 내다보는 동물의 서식지 선택",
"The ability to select a set of surroundings suitable for foraging, shelter from predators, and the availability of mates is one of the most important determinants of biological success ― measured as survival to reproductive age and the production of offspring. Many studies have shown that not only do animals have a remarkable ability to seek out the best available locations for the necessities of life, but that they are able to anticipate how a setting will serve their future needs. For example, the black-throated green warbler, a small songbird that nests in spruce forests of eastern North America, establishes territories preferentially among the red spruce trees early in the summer months, even though these trees offer less food than the neighboring white spruce trees. Later, though, when nests are built and hungry baby birds need nourishment, it is the red spruce forest that offers the easier pickings. Somehow, the warbler has been guided to settle in locations that will suit its future parenting needs better than its present ones."),

"37": ("언어는 문화의 발현 — 직접적/간접적 소통 양식",
"Language is a manifestation of culture. At different language acquisition stages, children do not learn language per se; rather they learn the various patterns and styles of language interaction that enable them to function as competent communicators in different situational contexts. They develop a culture-specific communication style that is, for example, direct and explicit in individualistic cultures or indirect and implicit in collectivistic cultures. Examples of words linked with the direct style are categorical words like absolutely, certainly, or positively. By contrast, the cultural assumptions of interdependence and harmony require that collectivists limit themselves to implicit and even ambiguous use of words, using terms like maybe, perhaps, or probably. The English language is the only language in the world that spells I with a capital letter. This phenomenon may reflect the fact that the roots of individualism are in England. There is no Japanese equivalent for the English I. Different words are used to refer to the self, depending on the social situation, the speaker's gender, age, and the other social attributes relative to the listener."),

"38": ("밀도와 혼잡 — 기분에 따라 증폭되는 심리적 경험",
"Environmental psychologists make a distinction between the physical measurement of density (how many people are in a particular space) and crowding (the psychological feeling of not having enough space). Usually, high density is needed for the phenomenon of crowding, which makes people experience sensory overload, a lack of control, and rising stress and anxiety. However, some psychologists see crowding as neutral rather than invariably negative, and believe that people's moods and behaviors intensify as density increases. So if an individual is looking forward to a concert, say, the feeling of crowding enhances their enjoyment of the performance. But if they are dreading an event, crowding will make the person's experience of it even worse. Put into a community setting, crowding may accentuate the dominant behavior ― an aggressive group may turn violent as density rises. Conversely, creating positive social spaces such as parks and pedestrian areas in high-density urban environments may help to lift the general mood and defuse tension."),

"39": ("조직 내 배제 — 간과되지만 성과를 좌우하는 문제",
"Exclusion is a state that is ignored by the organization psychologists. Therefore, it is possible that precautions regarding organizational exclusion are not taken. Individuals react to organizational exclusion by trying to strengthen their basic needs, which are threatened. Positive social behaviors develop belonging and self-respect. The likelihood that individuals who try to adapt to positive social behaviors will experience organizational exclusion decreases. However, individuals may be faced with more exclusion when they cannot adapt to a group. When excluded individuals grow away from communication and social activities, their contribution to the organization they are in may decrease. When this situation is not avoided, exclusion increases even more and strongly affects the performance of the employee in a negative way. Precautions need to be taken regarding organizational exclusion, which is very important for business."),

"40": ("선행 그 자체를 위한 마음이 더 큰 선을 부른다",
"Our adult brains retain a preference for perpetuating good, fair behavior. Simply perceiving ourselves as people who do good deeds and behaving accordingly motivates us to do greater good in the future. In one paid study of one hundred college students, subjects who wrote down a list of past good deeds and were then asked to donate money to a charity gave, on average, over half the earnings they'd made from the study — almost twice as much as those who had been instructed to recall previous bad deeds. In addition, subjects who'd taken pains to describe not only how they'd been nice to others but how people responded were likely to donate significantly less than those who focused purely on the actions themselves. In other words, people who seemed concerned about appearances (e.g., the impact of their good deed, as much as the deed itself) were less generous than those who cared more about doing good for its own sake. According to the study, the motivation to do good deeds was more evident in those who recalled their past virtues and those who focused purely on their good deeds than those who recalled their previous bad deeds and those who seemed highly conscious of the appearances of their deeds."),

"41-42": ("알고리즘이라는 선택 설계자 속 인간 주체성 지키기",
"The concept of \"choice architecture,\" popularized in behavioral economics, highlights how the design of the environment in which choices are made can significantly influence the decisions people make. Algorithms are, in essence, sophisticated architects of our digital environments. By curating what we see, what we are recommended, and what options are presented to us, they subtly, and sometimes not so subtly, nudge us towards particular paths. While nudges can be used for beneficial purposes, such as encouraging healthier habits, they also carry the potential for manipulation, particularly when the underlying objectives of the architects are not aligned with the well-being or autonomy of the individual. The question then becomes: how can we cultivate and protect our human agency in an increasingly algorithmic world? It requires a conscious effort to maintain critical engagement with the technologies we use. It means actively seeking out diverse perspectives, challenging algorithmic recommendations, and making deliberate choices that go against the predicted grain. It involves cultivating a healthy skepticism towards the seemingly objective outputs of algorithms and remembering that these systems are designed by humans with specific goals, and that their data is a reflection of past realities, not necessarily a prescription for future flourishing."),

"43-45": ("가사를 붙인 소년과 청각장애 기타리스트 Ridge 이야기",
"Ridge was a high school student who wanted to major in music in college. For weeks, on his balcony, every night he listened to a man playing the guitar in the apartment across the courtyard. Although the songs the man played were all new to Ridge, he somehow managed to attach his own made-up lyrics to them. One night, Ridge slid open the balcony door and stepped outside. He told his mom he was going out to the balcony to do his homework. The man was playing the guitar on his balcony as usual and Ridge started to mindlessly follow the rhythm. While Ridge was singing along to the music, the man suddenly stopped playing. He had never stopped in the middle of a song, so naturally Ridge looked in his direction. The man held up his index finger as if to say, \"Hold on.\" He lifted one sheet of paper, and Ridge narrowed his eyes to get a good look at what was written on it. His phone number and \"Text me\" were written on the sheet. Then he flipped the paper over and wrote, \"I have a question.\" Curious about the man's question, and wondering why he had asked for a text instead of a call, Ridge pulled out his phone and entered the number. He typed, \"What's your question?\" The man texted, \"I want to know how you're singing lyrics to my songs when I haven't even added lyrics to them yet.\" Ridge was greatly surprised. Why hadn't he thought the man could see him sitting out there? He had never thought the man had noticed him singing along to his music. The man sent another message asking, \"Will you send them to me?\" After reading the man's message asking for his lyrics, Ridge hesitated. Ridge loved writing lyrics, but he had never shared anything he'd written with anyone. Eventually, he wrote down one of his favorite lyrics and sent it to him. A few days later, a new message came from the man. He wanted to use Ridge's lyrics for his new album. It turned out he was a deaf guitarist and songwriter in a band called Brennan's Band."),
}

order=["20","21","22","23","24","26","29","30","31","32","33","34","35","36","37","38","39","40","41-42","43-45"]
out=[{"item_no":k,"theme":P[k][0],"text":P[k][1]} for k in order]
json.dump(out, open(SC+"/moui3_prose.json","w"), ensure_ascii=False, indent=1)
print("wrote", len(out), "passages")
for o in out: print(f'  {o["item_no"]:6} ~{len(o["text"].split())}w')
