# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad/batches/공통영어2_능률_민병천_1과")
from _helpers import *

# ==========================================================================
# P5 — Rescue ⑤ 제보자 (제보 · 1 · SNS와 Ben Kuo의 등장)
# ==========================================================================
r5 = [
 "As Compean had already spent one night in difficult conditions, the police worried about his spending a second night.",
 "So they decided to use social media to find out if anyone could find clues in the picture.",
 "They posted the picture and asked if anyone recognized the scenery.",
 "The picture shared by the police was seen by a Californian named Ben Kuo.",
 "One of his hobbies is examining satellite images to track forest fires and informing people of potential dangers.",
 "He also enjoys determining where pictures were taken and where movies were filmed.",
 "When he saw the picture of Compean, he was immediately interested.",
]

ov5 = Overview(
 theme_ko="SNS 제보와 위성 사진 애호가 Ben Kuo의 등장",
 key_grammar=KeyGrammar(
  point="동명사의 의미상 주어 (소유격 + 동명사: his spending)",
  source_sentence="As Compean had already spent one night in difficult conditions, the police worried about his spending a second night.",
  explanation=[
   GN("쉽게 말하면","동명사(-ing) 앞의 [[소유격]]은 '그 동작을 누가 하는지'를 나타내는 [[의미상 주어]]야."),
   GN("복원","his spending a second night = [[he spends]] a second night (그가 둘째 밤을 보내는 것)."),
   GN("주의","격식체에선 목적격(him)보다 [[소유격]](his)을 동명사의 의미상 주어로 쓴다."),
   GN("정리","worried about [[his spending]] = '그가 (둘째 밤을) 보내는 것'을 걱정했다."),
  ],
  example_analysis="his spending a second night에서 소유격 his가 동명사 spending의 의미상 주어.",
  drills=[
   GrammarDrill(kind="객관식",from_passage=True,
    question="지문 'worried about his spending a second night'에서 his의 문법적 역할은?",
    options=["동명사 spending의 의미상 주어","동명사 spending의 목적어","명사 night를 꾸미는 소유격"],
    answer="동명사 spending의 의미상 주어"),
   GrammarDrill(kind="객관식",from_passage=False,
    question="밑줄 친 부분이 '동명사의 의미상 주어'로 쓰인 것은?",
    options=["I don't mind his being late.","This is his new book.","He kept his promise well."],
    answer="I don't mind his being late."),
   GrammarDrill(kind="객관식",from_passage=False,
    question="빈칸: 'She was proud of ____ winning the prize.' (그가 상 탄 것)",
    options=["his","him is","he does"],
    answer="his"),
   GrammarDrill(kind="영작",from_passage=False,
    question="나는 그녀가 일찍 떠나는 것을 걱정했다.",
    answer="I worried about her leaving early."),
   GrammarDrill(kind="영작",from_passage=True,
    question="(지문) 경찰은 그가 둘째 밤을 보내는 것을 걱정했다.",
    answer="The police worried about his spending a second night."),
  ]),
 topic="경찰이 소셜 미디어에 사진을 올리자, 위성 사진 분석이 취미인 Ben Kuo가 사진을 보고 관심을 갖는다.",
 stance="중립적",
 stance_reason="사건 전개를 사실 그대로 전하는 보도.",
 structure="시간·순서(나열)",
 structure_reason="경찰의 SNS 게시 → Kuo가 사진을 봄 → 즉시 흥미를 느낌의 시간 순서.",
 restatement_chains=[
  RestatementChain(label="단서를 찾는 공개 제보",
   expressions=["find clues in the picture","recognized the scenery"],
   variation="'사진 속 단서 찾기' → '풍경을 알아봄'으로 구체화."),
  RestatementChain(label="위치를 알아내는 취미",
   expressions=["examining satellite images","determining where pictures were taken"],
   variation="'위성 사진 분석' → '사진 촬영지 알아내기'로 확장."),
 ],
 flow_blocks=[
  FlowBlock(stage="도입",sentence_range="1",summary="이미 하룻밤을 버틴 Compean의 [[둘째 밤]]을 경찰이 걱정한다."),
  FlowBlock(stage="전개",sentence_range="2~3",summary="경찰이 [[소셜 미디어]]에 사진을 올려 풍경을 아는 사람을 찾는다."),
  FlowBlock(stage="인물 등장",sentence_range="4~5",summary="사진을 본 [[Ben Kuo]]는 위성 사진 분석이 취미인 사람이다."),
  FlowBlock(stage="전환",sentence_range="6~7",summary="촬영지 알아내기를 즐기는 그가 사진을 보고 즉시 [[흥미]]를 느낀다."),
 ])

i5 = [
 S(r5,1,
  [("동명사의 의미상 주어","his spending = 그가 보내는 것 (소유격이 동명사의 주어)"),
   ("이유 접속사 As","'~이므로'라는 원인·이유")],
  [("condition","환경, 상황"),("worry about","~을 걱정하다")],
  [("As Compean had already [[spent one night]]","Compean이 이미 [[하룻밤을 보냈]]기 때문에"),
   ("in [[difficult conditions]],","[[어려운 환경]]에서,"),
   ("the police [[worried]] about","경찰은 ~을 [[걱정했다]]"),
   ("his spending a [[second night]].","그가 [[둘째 밤]]을 보내는 것을.")],
  [("경찰은 Compean이 편안한 곳에서 하룻밤을 보내서 안심했다.","'difficult conditions(어려운 환경)'에서 이미 하룻밤을 보냈기에 경찰은 그가 '둘째 밤(a second night)'까지 버티는 것을 오히려 걱정했다."),
   ("his spending에서 his는 경찰을 가리킨다.","his는 Compean을 가리킨다 — 경찰이 걱정한 것은 'Compean이 둘째 밤을 보내는 것'이다.")]),
 S(r5,2,
  [("to부정사(목적)","to find out = 알아내기 위해"),
   ("간접의문문 if","if = ~인지 아닌지")],
  [("social media","소셜 미디어"),("clue","단서")],
  [("So they [[decided]]","그래서 그들은 [[결정했다]]"),
   ("to use [[social media]]","[[소셜 미디어]]를 사용하기로"),
   ("to [[find out]]","[[알아내려고]]"),
   ("if anyone could [[find clues]]","누군가 [[단서를 찾을]] 수 있는지"),
   ("in [[the picture]].","[[그 사진]]에서.")],
  [("경찰은 전문가에게만 개인적으로 연락해 사진을 분석하게 했다.","'use social media(소셜 미디어 이용)'해 '누구든(anyone)' 단서를 찾을 수 있는지 공개적으로 찾았다 — 전문가 개인 연락이 아니다.")]),
 S(r5,3,
  [("병렬 동사","posted and asked 나열"),
   ("간접의문문 if","if anyone recognized ~ = ~를 알아보는지")],
  [("post","(글·사진을) 올리다"),("scenery","풍경, 경치")],
  [("They [[posted]] the picture","그들은 그 사진을 [[올렸다]]"),
   ("and [[asked]]","그리고 [[물었다]]"),
   ("if anyone [[recognized the scenery]].","누군가 [[그 풍경을 알아보는지]].")],
  [("경찰은 사람들에게 사진 속 인물이 누구인지 물었다.","물어본 것은 '그 풍경(the scenery)'을 알아보는지 — 인물이 아니라 배경 장소를 알아보는 사람을 찾은 것이다.")]),
 S(r5,4,
  [("수동태","was seen by = ~에게 보여졌다"),
   ("과거분사 수식","shared / named가 앞 명사를 꾸밈")],
  [("share","공유하다"),("named","~라는 이름의")],
  [("The picture [[shared by the police]]","[[경찰이 공유한]] 그 사진은"),
   ("was [[seen]] by","~에게 [[보여졌다]]"),
   ("a Californian [[named Ben Kuo]].","[[Ben Kuo라는]] 캘리포니아 사람에게.")],
  [("Ben Kuo는 경찰의 요청으로 공식 수사에 참여한 전문 수사관이다.","그는 경찰이 SNS에 올린 사진을 우연히 본 '캘리포니아의 한 시민(a Californian)'일 뿐, 공식 수사관이 아니다.")]),
 S(r5,5,
  [("동명사 보어 병렬","examining ~ and informing ~ (is의 보어)"),
   ("to부정사(목적)","to track = 추적하기 위해")],
  [("examine","자세히 살펴보다"),("satellite","위성"),("potential","잠재적인")],
  [("One of his [[hobbies]] is","그의 [[취미]] 중 하나는"),
   ("examining [[satellite images]]","[[위성 사진]]을 살펴보는 것이다"),
   ("to track [[forest fires]]","[[산불]]을 추적하려고"),
   ("and [[informing]] people","그리고 사람들에게 [[알리는 것]]"),
   ("of [[potential dangers]].","[[잠재적 위험]]을.")],
  [("his hobbies에서 his는 Compean을 가리킨다.","his는 앞 문장의 Ben Kuo를 가리킨다 — 위성 사진 분석은 Kuo의 취미이다."),
   ("Kuo는 산불을 직접 진화하는 소방관이다.","그는 '위성 사진(satellite images)'으로 산불을 추적하고 위험을 알리는 취미를 가진 사람이지, 소방관이 아니다.")]),
 S(r5,6,
  [("동명사 목적어","enjoys determining = 알아내기를 즐기다"),
   ("간접의문문 where 병렬","where ~ were taken and where ~ were filmed")],
  [("determine","알아내다, 밝히다"),("film","촬영하다")],
  [("He also enjoys [[determining]]","그는 또한 [[알아내는 것]]을 즐긴다"),
   ("where [[pictures were taken]]","[[사진이 어디서 찍혔는지]]"),
   ("and where [[movies were filmed]].","그리고 [[영화가 어디서 촬영됐는지]].")],
  [("Kuo는 사진과 영화를 직접 촬영하는 사진작가이다.","그가 즐기는 것은 사진·영화가 '어디서 찍혔는지(where ~ were taken/filmed)' 장소를 알아내는 것이지, 촬영이 아니다.")]),
 S(r5,7,
  [("감정 형용사","interested = 흥미를 느끼는 (수동 감정)"),
   ("시간 부사절 When","~할 때")],
  [("immediately","즉시"),("interested","흥미를 느끼는")],
  [("When he saw [[the picture of Compean]],","그가 [[Compean의 사진]]을 봤을 때,"),
   ("he was [[immediately interested]].","그는 [[즉시 흥미를 느꼈다]].")],
  [("he was immediately interested는 Kuo가 사진의 낮은 화질에 짜증났다는 뜻이다.","'interested(흥미를 느낀)'는 Kuo가 이 사진을 풀 만한 퍼즐로 보고 돕고 싶어 했다는 함축 — 짜증이 아니다."),
   ("he was interested에서 he는 Compean이다.","he는 Ben Kuo를 가리킨다 — 사진을 보고 흥미를 느낀 사람은 Kuo이다.")]),
]

P5 = build("Rescue ⑤ 제보자","제보 · 1 (SNS와 Ben Kuo의 등장)",r5,ov5,i5)


# ==========================================================================
# P6 — Rescue ⑥ 추론 (추론 · 1 · Kuo의 위치 추론)
# ==========================================================================
r6 = [
 "When Kuo saw the black ash on Compean's legs, it reminded him of a recent forest fire.",
 "This helped him to infer Compean's approximate location.",
 "Kuo was very familiar with the area because he had tracked the fire before and had checked the features of the area in satellite images.",
 "From the plants and trees in Compean's picture, Kuo guessed that it must be the south side of the mountain.",
 "The north side does not have any green valleys like those in the picture.",
]

ov6 = Overview(
 theme_ko="검은 재와 식생으로 위치를 좁힌 Kuo의 추론",
 key_grammar=KeyGrammar(
  point="조동사 must (강한 추측: ~임에 틀림없다)",
  source_sentence="From the plants and trees in Compean's picture, Kuo guessed that it must be the south side of the mountain.",
  explanation=[
   GN("쉽게 말하면","must는 '의무(해야 한다)' 말고, 근거가 있을 때 '[[~임에 틀림없다]]'라는 [[강한 추측]]으로도 쓴다."),
   GN("근거","식물·나무라는 단서 → so it [[must be]] the south side (그러니 남쪽임에 틀림없다)."),
   GN("반대","약한 추측은 may/might([[~일지도 모른다]]), 강한 확신은 must."),
   GN("주의","과거 일에 대한 강한 추측은 [[must have p.p.]] (~였음에 틀림없다)."),
  ],
  example_analysis="it must be the south side에서 must는 근거에 기반한 강한 추측(~임에 틀림없다).",
  drills=[
   GrammarDrill(kind="객관식",from_passage=True,
    question="지문 'it must be the south side'에서 must의 의미는?",
    options=["강한 추측(~임에 틀림없다)","의무(~해야 한다)","금지(~하면 안 된다)"],
    answer="강한 추측(~임에 틀림없다)"),
   GrammarDrill(kind="객관식",from_passage=False,
    question="밑줄 친 must가 '강한 추측'으로 쓰인 것은?",
    options=["He must be tired after the long trip.","You must wear a helmet here.","We must finish it by noon."],
    answer="He must be tired after the long trip."),
   GrammarDrill(kind="객관식",from_passage=False,
    question="빈칸: 'The light is on, so someone ____ be home.' (있음에 틀림없다)",
    options=["must","should","need"],
    answer="must"),
   GrammarDrill(kind="영작",from_passage=False,
    question="그녀가 저렇게 웃는 걸 보니 행복함에 틀림없다.",
    answer="She must be happy to smile like that."),
   GrammarDrill(kind="영작",from_passage=True,
    question="(지문) 그곳은 산의 남쪽 면임에 틀림없다.",
    answer="It must be the south side of the mountain."),
  ]),
 topic="Kuo는 검은 재로 산불을, 식물·나무로 산의 남쪽 면을 추론해 Compean의 대략적 위치를 좁힌다.",
 stance="중립적",
 stance_reason="추론 과정을 사실대로 전달하는 보도.",
 structure="시간·순서(나열)",
 structure_reason="재 관찰 → 산불 연상 → 지역 파악 → 남쪽 면 추론의 순서.",
 restatement_chains=[
  RestatementChain(label="재 → 산불 연상",
   expressions=["it reminded him of a recent forest fire","he had tracked the fire before"],
   variation="'검은 재가 산불을 떠올리게 함' → '전에 그 불을 추적함'으로 연결."),
  RestatementChain(label="식생으로 남쪽 추론",
   expressions=["it must be the south side of the mountain","green valleys like those in the picture"],
   variation="'남쪽임에 틀림없다' ← '사진 속 푸른 계곡'이 근거."),
 ],
 flow_blocks=[
  FlowBlock(stage="관찰",sentence_range="1",summary="다리의 [[검은 재]]가 Kuo에게 최근 산불을 떠올리게 한다."),
  FlowBlock(stage="전개",sentence_range="2~3",summary="그 연상으로 대략적 [[위치]]를 좁히고, 추적 경험으로 지역을 잘 안다."),
  FlowBlock(stage="추론",sentence_range="4",summary="식물과 나무를 근거로 산의 [[남쪽 면]]임에 틀림없다고 추측한다."),
  FlowBlock(stage="근거",sentence_range="5",summary="북쪽엔 사진 같은 [[푸른 계곡]]이 없다는 점이 추론의 근거다."),
 ])

i6 = [
 S(r6,1,
  [("지시대명사 it","it = 검은 재를 본 것 (앞 상황을 가리킴)"),
   ("remind A of B","A에게 B를 떠올리게 하다")],
  [("ash","재"),("remind","떠올리게 하다"),("recent","최근의")],
  [("When Kuo saw [[the black ash]]","Kuo가 [[검은 재]]를 봤을 때"),
   ("on [[Compean's legs]],","[[Compean의 다리]]에 있는,"),
   ("it [[reminded]] him of","그것은 그에게 ~을 [[떠올리게 했다]]"),
   ("a [[recent forest fire]].","[[최근의 산불]]을.")],
  [("it reminded him에서 it이 지칭하는 것은 Compean이다.","it이 가리키는 것은 'Kuo가 본 검은 재(the black ash)'이다 — 그 재가 최근 산불을 떠올리게 했다는 뜻이다."),
   ("검은 재는 Compean이 직접 불을 피운 흔적이다.","검은 재(black ash)는 그 지역의 '최근 산불(recent forest fire)'을 Kuo에게 연상시킨 단서이다 — Compean이 피운 불이 아니다.")]),
 S(r6,2,
  [("지시대명사 This","This = 앞 문장 전체 (재가 산불을 연상시킨 것)"),
   ("help + O + to부정사","This helped him to infer ~")],
  [("infer","추론하다"),("approximate","대략적인"),("location","위치")],
  [("This [[helped]] him","이것은 그를 [[도왔다]]"),
   ("to [[infer]]","[[추론하도록]]"),
   ("[[Compean's approximate location]].","[[Compean의 대략적 위치]]를.")],
  [("This helped him에서 This는 Compean의 다리를 가리킨다.","This는 앞 문장 전체 — '검은 재가 최근 산불을 연상시킨 것'을 가리킨다 — 그 덕분에 위치를 추론했다.")]),
 S(r6,3,
  [("과거완료","had tracked / had checked (앞선 과거)"),
   ("이유 접속사 because","~하기 때문에")],
  [("familiar","익숙한, 잘 아는"),("track","추적하다"),("feature","특징")],
  [("Kuo was very [[familiar]] with the area","Kuo는 그 지역을 매우 [[잘 알고 있었다]]"),
   ("because he had [[tracked the fire]] before","그가 전에 [[그 불을 추적했었]]기 때문에"),
   ("and had [[checked the features]] of the area","그리고 그 지역의 [[특징을 확인했었]]다"),
   ("in [[satellite images]].","[[위성 사진]]에서.")],
  [("Kuo가 그 지역을 잘 안 것은 그곳에서 산 적이 있기 때문이다.","잘 안 이유는 전에 '그 불을 추적(had tracked the fire)'하고 '위성 사진(satellite images)'으로 특징을 확인했기 때문이다 — 거주 경험이 아니다.")]),
 S(r6,4,
  [("조동사 must (강한 추측)","it must be ~ = ~임에 틀림없다"),
   ("that 명사절","guessed that ~ (추측한 내용)")],
  [("guess","추측하다"),("south","남쪽의")],
  [("From the [[plants and trees]]","[[식물과 나무]]로부터"),
   ("in [[Compean's picture]],","[[Compean의 사진]] 속,"),
   ("Kuo [[guessed]] that","Kuo는 ~라고 [[추측했다]]"),
   ("it [[must be the south side]] of the mountain.","그곳은 [[산의 남쪽 면임에 틀림없]]다고.")],
  [("it must be the south side는 남쪽이라는 확실한 증거를 봤다는 뜻이다.","must be는 식물·나무를 근거로 한 '강한 추측(~임에 틀림없다)'이라는 함축이다 — 100% 확정이 아니라 Kuo의 추론이다."),
   ("it must be the south side에서 it은 Compean을 가리킨다.","it은 사진에 찍힌 '그 장소'를 가리킨다 — 그곳이 산의 남쪽 면임에 틀림없다는 추측이다.")]),
 S(r6,5,
  [("지시대명사 those","those = green valleys (앞의 푸른 계곡)"),
   ("부정 does not have any","어떤 ~도 없다")],
  [("valley","계곡"),("green","푸른, 초목이 우거진")],
  [("The [[north side]]","[[북쪽 면]]은"),
   ("does not have any [[green valleys]]","어떤 [[푸른 계곡]]도 없다"),
   ("like those in [[the picture]].","[[사진]] 속 그런 것들 같은.")],
  [("like those in the picture에서 those는 산이나 나무를 가리킨다.","those는 바로 앞의 '푸른 계곡(green valleys)'을 가리킨다 — 사진 속 그런 계곡이 북쪽엔 없으니 남쪽이라 추론한 것이다."),
   ("북쪽에도 사진과 같은 푸른 계곡이 있어 위치를 특정하기 어려웠다.","북쪽 면엔 사진 같은 '푸른 계곡이 없다(does not have)'는 점이 바로 남쪽이라는 추론의 근거였다.")]),
]

P6 = build("Rescue ⑥ 추론","추론 · 1 (Kuo의 위치 추론)",r6,ov6,i6)

PARTS = [P5, P6]
