# -*- coding: utf-8 -*-
"""올림포스 독해 기본1 · Ch03 (Unit09 ANALYSIS/1/2/3 + 서술형/논술형 Practice) 강의컨셉 교재."""
import sys, random
sys.path.insert(0, "/home/user/english_data_making")
from src.lecture_schemas import (Chunk, FlowBlock, GrammarChip, GrammarDrill,
    GrammarNote, KeyGrammar, LecturePassage, LectureSentence, Misread,
    Overview, RestatementChain, SentenceAnalysis, SentenceItem, Vocab)
def mk(r): return [LectureSentence(id=i,text=t) for i,t in enumerate(r,1)]
def S(r,i,g,v,c,m): return SentenceItem(id=i,english=r[i-1],
    grammar=[GrammarChip(tag=a,note=b) for a,b in g],
    vocab=[Vocab(word=w,meaning=k) for w,k in v],
    chunks=[Chunk(en=e,ko=k) for e,k in c],
    misreads=[Misread(statement=s,why=w) for s,w in m])
def GN(c,t): return GrammarNote(chip=c,text=t)
def build(title,src,no,r,ov,items):
    p=LecturePassage(title=title,source=src,item_no=no,sentences=mk(r),
        overview=ov,analysis=SentenceAnalysis(sentences=items)); p.analysis.validate_all(len(r)); return p
def tok(a):
    ws=[w.strip('.,;:!?\"()“”') for w in a.split()]; ws=[w for w in ws if w]
    random.Random(len(a)+sum(map(ord,a[:8]))).shuffle(ws); return ws
_MCQ=[0]
def finalize(p):
    for d in p.overview.key_grammar.drills:
        if d.kind=='영작': d.words=tok(d.answer)
        if d.kind=='객관식' and d.options:
            others=[o for o in d.options if o!=d.answer]
            pos=_MCQ[0]%len(d.options); d.options=others[:]; d.options.insert(pos,d.answer)
        _MCQ[0]+=1
    return p
S9="EBS 올림포스 영어독해 기본1 · Ch03 Unit09"
SP="EBS 올림포스 영어독해 기본1 · Ch03 서술형 Practice"
SN="EBS 올림포스 영어독해 기본1 · Ch03 논술형 Practice"

# ============ Unit09-ANALYSIS : 고성과자 관리자 딜레마 (강조 the very) ============
r1=["If you were a high performer in your work before becoming a manager, you may find the journey into management particularly difficult.",
"Because of their previous success, stars are understandably reluctant to give up the attitudes and practices they think produced their success thus far, and they're unwilling to change themselves.",
"They don't know how to develop or coach people because they never needed much coaching themselves, or so they believe.",
"They don't know how to deal with people who lack their motivation.",
"Because they've never failed, they've had little practice reflecting on and learning from experience.",
"No wonder many former stars turn into mediocre bosses.",
"If you were a star, be aware that the very success that produced your promotion can now work against you."]
ov1=Overview(theme_ko="과거의 성공 방식에 갇혀 관리자로서의 변화에 적응하지 못하는 고성과자의 딜레마",
 key_grammar=KeyGrammar(point="강조 the very + 명사 ('바로 그 ~')",
  source_sentence="If you were a star, be aware that the very success that produced your promotion can now work against you.",
  explanation=[GN("쉽게 말하면","명사 앞의 'the very'는 '[[바로 그]] ~'라며 그 명사를 콕 집어 강조해."),
   GN("형태","the very + 명사 — very가 형용사로 쓰여 '[[다름 아닌 그것]]'이라는 강조야."),
   GN("여기선","the very success = '[[바로 그 성공]]' — 승진을 안겨 준 그 성공 자체를 가리켜."),
   GN("혼동 주의","부사 very(매우)와 달라 — the very success는 '매우 성공'이 아니라 '[[바로 그 성공]]'."),
   GN("해석 요령","'the very + 명사'는 '바로 그/다름 아닌 ~'로 옮겨 앞에서 언급된 대상을 강조해.")],
  example="",example_analysis="the very success that produced your promotion = '당신의 승진을 만든 바로 그 성공' — 그것이 이제 불리하게 작용.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 7문장 'the very success'의 의미로 알맞은 것은?",
    options=["바로 그(다름 아닌) 성공","매우 큰 성공","아주 새로운 성공"],answer="바로 그(다름 아닌) 성공"),
   GrammarDrill(kind="객관식",from_passage=False,question="'This is the very book I wanted.'의 뜻으로 알맞은 것은?",
    options=["이것이 바로 내가 원하던 책이다","이것은 매우 좋은 책이다","이것은 내가 원한 첫 책이다"],answer="이것이 바로 내가 원하던 책이다"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'At that ____ moment, the phone rang.' (바로 그 순간)",
    options=["very","much","so"],answer="very"),
   GrammarDrill(kind="영작",from_passage=False,question="그가 바로 그날 떠났다.",answer="He left on that very day."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 7문장 일부) 당신의 승진을 만든 바로 그 성공이 이제 당신에게 불리하게 작용할 수 있다.",
    answer="The very success that produced your promotion can now work against you.")]),
 topic="관리자가 되기 전 높은 성과를 낸 사람일수록, 과거의 성공 방식을 못 버려 관리자로서의 변화에 적응하기 어렵다는 글이야.",
 stance="중립적",stance_reason="고성과자가 관리직에서 겪는 딜레마를 원인 중심으로 분석하고 조언하는 글이야.",
 structure="주장→근거·예시",structure_reason="'고성과자는 관리직이 특히 어렵다'는 주장(1문장) 뒤, 변화 거부·지도 미숙·성찰 부족이라는 이유(2~5문장)와 결론·조언(6~7문장)으로 이어져.",
 restatement_chains=[RestatementChain(label="과거 성공에 갇힘",
   expressions=["reluctant to give up the attitudes and practices","unwilling to change themselves","the very success that produced your promotion can now work against you"],
   variation="'태도·관행을 못 버림' → '자신을 안 바꾸려 함' → '그 성공이 되레 불리'로 이어져."),
  RestatementChain(label="관리 역량 부족",
   expressions=["don't know how to develop or coach people","little practice reflecting on and learning from experience"],
   variation="'남을 지도할 줄 모름' → '성찰·학습 연습 부족'으로 구체화돼.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1",summary="관리자가 되기 전 고성과자였다면, 관리직 여정이 특히 어렵다고 느낄 수 있다.",easy_example="잘나가던 사람일수록 관리자 역할이 더 힘든 것."),
  FlowBlock(stage="이유1",sentence_range="2",summary="과거 성공 때문에 성공을 만든 태도·관행을 포기하기 꺼리고 자신을 바꾸려 하지 않는다.",easy_example="성공 방식을 못 놓는 것."),
  FlowBlock(stage="이유2",sentence_range="3~5",summary="스스로 지도가 필요 없었기에 남을 지도할 줄 모르고, 실패한 적 없어 성찰·학습 연습도 부족하다.",easy_example="가르치고 되돌아보는 훈련이 안 된 것."),
  FlowBlock(stage="결론·조언",sentence_range="6~7",summary="그래서 과거의 스타가 평범한 상사가 되곤 하니, 승진을 안긴 바로 그 성공이 이제 불리할 수 있음을 알라.",easy_example="성공이 되레 발목 잡을 수 있다는 경고.")])
i1=[S(r1,1,[("조건 if","'~였다면'(과거 사실 조건)"),("전치사+동명사 before becoming","'~가 되기 전에'")],
  [("high performer","고성과자"),("journey","여정"),("particularly","특히")],
  [("If you were a [[high performer]] in your work before becoming a manager,","만약 여러분이 관리자가 되기 전 직무에서 [[높은 성과를 낸 사람]]이었다면,"),
   ("you may find the journey into management","여러분은 관리직으로의 여정이 ~라고 느낄 수 있다"),
   ("[[particularly difficult]].","[[특히 어렵다고]].")],
  [("관리자가 되면 누구나 쉽게 적응한다는 내용이다.","'may find ... particularly difficult(특히 어렵다고 느낄 수 있다)'로 고성과자의 관리직 적응 어려움을 던지는 주제·도입 문장이야.")]),
 S(r1,2,[("목적격 관계대명사 생략","the attitudes and practices (that) they think produced ~ : 관계대명사 생략+they think 삽입"),("병렬","reluctant to give up ~ and unwilling to change ~ 대등")],
  [("reluctant","꺼리는"),("give up","포기하다"),("thus far","지금까지")],
  [("Because of their previous success, stars are understandably [[reluctant to give up the attitudes and practices]]","이전의 성공 때문에, 최고의 직원들은 당연히 [[태도와 관행을 포기하기를 꺼리고]]"),
   ("[[they think produced their success thus far]],","[[자신이 생각하기에 지금까지 성공을 만들어 낸]],"),
   ("and they're unwilling to [[change themselves]].","자신을 [[바꾸려 하지 않는다]].")],
  [("(지칭) 'their success'의 their는 부하 직원들을 가리킨다.","지칭 오인이야. their는 'stars(최고의 직원들)' 자신을 가리켜 — 자기 성공을 만든 태도를 못 버린다는 뜻이야.")]),
 S(r1,3,[("병렬 develop or coach","동사원형 병렬"),("접속사 because","이유"),("삽입 or so they believe","'혹은 그렇게 그들은 믿는다'")],
  [("develop","성장시키다"),("coach","지도하다")],
  [("They don't know [[how to develop or coach people]]","그들은 [[사람들을 어떻게 성장시키고 지도할지]] 모른다"),
   ("because they never needed much [[coaching]] themselves,","그들 자신이 [[지도]]를 많이 필요로 한 적이 없어서,"),
   ("or so they believe.","혹은 그렇게 그들은 믿는다.")],
  [("그들은 스스로 많은 지도가 필요했기에 남을 잘 지도한다는 내용이다.","'never needed much coaching themselves(스스로 지도가 필요 없었다고 믿어서)' 남을 지도할 줄 모른다는 거야 — 정반대야.")]),
 S(r1,4,[("관계사 who","people 수식")],
  [("deal with","다루다"),("lack","부족하다"),("motivation","동기")],
  [("They don't know [[how to deal with people]]","그들은 [[사람들을 어떻게 다뤄야 할지]] 모른다"),
   ("who lack their [[motivation]].","그들의 [[동기]]가 부족한.")],
  [("그들은 동기가 부족한 사람도 능숙하게 다룬다는 내용이다.","'don't know how to deal with(다룰 줄 모른다)'이야 — 능숙이 아니라 서투르다는 뜻이야.")]),
 S(r1,5,[("병렬 reflecting on and learning from","전치사 목적어 동명사 병렬"),("접속사 because","이유")],
  [("reflect on","성찰하다"),("little practice","연습이 거의 없음")],
  [("Because they've [[never failed]],","그들은 [[실패한 적이 한 번도 없어서]],"),
   ("they've had [[little practice reflecting on and learning from experience]].","[[경험을 성찰하고 배우는 연습을 거의 못 했다]].")],
  [("실패 경험이 많아 성찰에 능하다는 내용이다.","'never failed, little practice reflecting(실패한 적 없어 성찰 연습이 부족)'이야 — 능하다가 아니라 부족하다는 뜻이야.")]),
 S(r1,6,[("No wonder","'~은 당연하다/놀랄 일 아니다'"),("turn into","~로 변하다")],
  [("former","이전의"),("mediocre","평범한, 그저 그런")],
  [("No wonder many [[former]] stars","많은 [[이전의]] 스타들이 ~하는 것은 당연하다"),
   ("turn into [[mediocre bosses]].","[[평범한 상사]]로 변하는 것은.")],
  [("(함축) 'No wonder ... mediocre bosses'는 스타가 반드시 훌륭한 상사가 된다는 뜻이다.","함축을 놓쳤어. '평범한 상사가 되는 게 당연(No wonder ... mediocre)'이라며 스타가 좋은 상사가 되리란 보장이 없다는, 앞 이유들을 묶는 결론이야.")]),
 S(r1,7,[("강조 the very","the very success='바로 그 성공'(강조)"),("관계사 that","success 수식"),("조건 if","'~였다면'")],
  [("be aware","인식하다"),("promotion","승진"),("work against","~에 불리하게 작용하다")],
  [("If you were a star, [[be aware]]","만약 여러분이 스타였다면, [[인식하라]]"),
   ("that [[the very success that produced your promotion]]","[[여러분의 승진을 만든 바로 그 성공이]]"),
   ("can now [[work against you]].","이제 여러분에게 [[불리하게 작용할]] 수 있다는 것을.")],
  [("이 문장은 성공이 늘 유리하게 작용한다고 안심시키는 문장이다.","'be aware that the very success ... can now work against you(바로 그 성공이 불리할 수 있음을 알라)'는 경고·조언의 핵심 문장이야.")])]

# ============ Unit09-1 : 시간 희소성·목적 선택 (복합관계사 -ever) ============
r2=["Action takes place by choosing which ends shall be satisfied by the employment of means.",
"Time is scarce for man only because whichever ends he chooses to satisfy, there are others that must remain unsatisfied.",
"When we must use a means so that some ends remain unsatisfied, the necessity for a choice among ends arises.",
"For example, Jones is engaged in watching a baseball game on television.",
"He is faced with the choice of spending the next hour in: (a) continuing to watch the baseball game, (b) playing bridge, or (c) going for a drive.",
"He would like to do all three of these things, but his means (time) is insufficient.",
"As a result, he must choose; one end can be satisfied, but the others must go unfulfilled.",
"Suppose that he decides on course A.",
"This is a clear indication that he has ranked the satisfaction of end A higher than the satisfaction of ends B or C."]
ov2=Overview(theme_ko="시간의 희소성으로 인해 필연적으로 발생하는 목적 간의 선택과 우선순위 결정",
 key_grammar=KeyGrammar(point="복합관계사 -ever (whichever = '어느 것을 ~하든')",
  source_sentence="Time is scarce for man only because whichever ends he chooses to satisfy, there are others that must remain unsatisfied.",
  explanation=[GN("쉽게 말하면","whichever·whatever·whoever는 '[[~든지/어느 것을 ~하든]]'이라는 '양보'의 부사절을 만들어."),
   GN("복원","whichever ends he chooses = no matter [[which]] ends he chooses(어떤 목적을 선택하든)."),
   GN("두 쓰임","복합관계사는 ①명사절('~하는 것은 무엇이든') ②양보 부사절('무엇을 ~하든') — 여기선 [[양보]]."),
   GN("주의","-ever가 붙으면 뒤에 [[불완전한 절]](목적어 자리 빔)이 와 — chooses의 목적어가 whichever ends."),
   GN("해석 요령","'어느 ~을 …하든 (상관없이)'로 옮기고 뒤 주절과 이어 읽어.")],
  example="",example_analysis="whichever ends he chooses to satisfy = '그가 어떤 목적을 충족하려 선택하든' — 양보 부사절.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 2문장 'whichever ends he chooses to satisfy'의 의미로 알맞은 것은?",
    options=["그가 어떤 목적을 선택하든 (상관없이)","그가 선택한 목적만이","그가 목적을 선택할 수 있는지"],answer="그가 어떤 목적을 선택하든 (상관없이)"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? '____ you choose, I'll support you.' (무엇을 선택하든)",
    options=["Whatever","That","Which"],answer="Whatever"),
   GrammarDrill(kind="객관식",from_passage=False,question="'Whoever comes will be welcome.'의 뜻으로 알맞은 것은?",
    options=["오는 사람은 누구든 환영받을 것이다","오는 사람만 환영받는다","누가 오는지 환영한다"],answer="오는 사람은 누구든 환영받을 것이다"),
   GrammarDrill(kind="영작",from_passage=False,question="네가 어느 길을 선택하든, 조심해라.",answer="Whichever road you choose, be careful."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 2문장 일부) 그가 어떤 목적을 선택하든, 충족되지 않은 채 남아야 하는 다른 것이 존재한다.",
    answer="Whichever ends he chooses to satisfy, there are others that must remain unsatisfied.")]),
 topic="시간이라는 수단이 부족하기에, 여러 목적 중 하나를 선택하고 우선순위를 매길 수밖에 없다는 글이야.",
 stance="중립적",stance_reason="시간의 희소성과 선택의 필연성을 예시(Jones)로 설명하는 정보 전달문이야.",
 structure="주장→근거·예시",structure_reason="'시간이 부족해 목적을 선택해야 한다'는 주장(1~3문장) 뒤, Jones의 사례(4~9문장)로 뒷받침해.",
 restatement_chains=[RestatementChain(label="선택의 필연성",
   expressions=["there are others that must remain unsatisfied","the necessity for a choice among ends arises","he must choose"],
   variation="'충족되지 못하는 다른 것이 있음' → '선택의 필요성이 생김' → '그는 선택해야 함'으로 이어져."),
  RestatementChain(label="시간의 희소성",
   expressions=["Time is scarce for man","his means (time) is insufficient"],
   variation="'인간에게 시간이 부족함' → '그의 수단(시간)이 불충분함'으로 반복돼.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1~3",summary="행동은 목적을 선택하는 것이며, 시간이 부족해 어떤 목적을 택하든 다른 것은 남으므로 선택의 필요성이 생긴다.",easy_example="시간이 없어 다 못 하니 골라야 하는 것."),
  FlowBlock(stage="예시-상황",sentence_range="4~6",summary="Jones는 다음 한 시간에 야구 시청·브리지·드라이브 중 하나를 골라야 하는데, 다 하고 싶지만 시간이 부족하다.",easy_example="하고 싶은 세 가지, 시간은 하나뿐."),
  FlowBlock(stage="예시-결론",sentence_range="7~9",summary="결국 그는 선택해야 하고, 경로 A를 정하면 A의 충족을 B·C보다 높게 순위 매긴 것이다.",easy_example="하나를 고르는 건 곧 우선순위를 매기는 것.")])
i2=[S(r2,1,[("관계형용사 which","'어떤 ~을 …할지'(choosing의 목적어절)"),("수동태 shall be satisfied","'충족될'")],
  [("take place","일어나다"),("ends","목적"),("employment","사용, 이용"),("means","수단")],
  [("Action takes place by [[choosing which ends shall be satisfied]]","행동은 [[어떤 목적을 충족시킬지 선택함]]으로써 일어난다"),
   ("by the employment of means.","수단을 사용하여.")],
  [("행동은 목적과 무관하게 저절로 일어난다는 내용이다.","'by choosing which ends ~(어떤 목적을 충족할지 선택함으로써)' 행동이 일어난다는 거야 — 목적 선택이 핵심이야.")]),
 S(r2,2,[("복합관계사 whichever","'어느 목적을 선택하든'(양보)"),("관계사 that","others 수식"),("수동태 remain unsatisfied","'충족되지 않은 채'")],
  [("scarce","부족한, 희소한"),("remain","(여전히) ~인 채로 있다")],
  [("Time is scarce for man only because","인간에게 시간이 부족한 것은 오직 ~이기 때문이다"),
   ("[[whichever ends he chooses to satisfy]],","[[그가 어떤 목적을 충족하려 선택하든]],"),
   ("there are others that must [[remain unsatisfied]].","충족되지 않은 채 [[남아야 하는]] 다른 것이 존재하기 때문에.")],
  [("시간이 부족한 이유는 목적이 하나뿐이기 때문이라는 내용이다.","'whichever ends he chooses(어떤 목적을 택하든) 충족 안 되는 다른 것이 있다'는 거야 — 목적이 많은데 시간이 모자란다는 뜻이야.")]),
 S(r2,3,[("접속사 so that","'~하도록'"),("접속사 when","'~할 때'")],
  [("necessity","필요성"),("arise","생기다, 발생하다")],
  [("When we must use a means so that some ends remain unsatisfied,","어떤 목적이 충족되지 않도록 수단을 써야 할 때,"),
   ("the necessity for a choice among ends [[arises]].","목적 중에서 선택해야 할 필요성이 [[생긴다]].")],
  [("이 문장은 선택이 불필요해지는 조건을 설명한다.","'the necessity for a choice ... arises(선택의 필요성이 생긴다)'는 거야 — 선택이 불필요가 아니라 필연이라는 뜻이야.")]),
 S(r2,4,[("수동태 is engaged in","'~에 몰두하다'")],
  [("be engaged in","~에 몰두하다")],
  [("For example, Jones is [[engaged in watching a baseball game]] on television.","예를 들어, Jones는 텔레비전으로 [[야구 경기 시청에 몰두하고]] 있다.")],
  [("이 문장은 Jones가 여러 활동을 동시에 한다는 내용이다.","'engaged in watching a baseball game(야구 시청에 몰두)'이라는 예시 도입이야 — 이후 그가 세 활동 중 선택하는 상황으로 이어져.")]),
 S(r2,5,[("병렬 (a)continuing (b)playing (c)going","전치사 in의 목적어 동명사 병렬")],
  [("be faced with","~에 직면하다"),("go for a drive","드라이브하러 가다")],
  [("He is faced with the choice of spending the next hour in:","그는 다음 한 시간을 쓰는 선택에 직면한다:"),
   ("(a) [[continuing to watch]] the baseball game, (b) playing bridge, or (c) going for a drive.","(a) 야구를 [[계속 볼지]], (b) 브리지를 할지, (c) 드라이브를 할지.")],
  [("그는 세 가지를 모두 할 수 있는 상황이라는 내용이다.","'the choice of spending the next hour(한 시간을 어디에 쓸지 선택)'에 직면한 거야 — 셋 중 하나만 고를 수 있어.")]),
 S(r2,6,[("would like to","'~하고 싶다'"),("대조 but","'하지만'")],
  [("insufficient","불충분한")],
  [("He would like to do all three of these things,","그는 이 세 가지를 모두 하고 싶지만,"),
   ("but his means (time) is [[insufficient]].","그의 수단(시간)이 [[불충분하다]].")],
  [("그는 시간이 충분해 셋 다 할 수 있다는 내용이다.","'his means (time) is insufficient(수단인 시간이 불충분)'이야 — 그래서 선택이 불가피하다는 거야.")]),
 S(r2,7,[("세미콜론 부연","앞 문장을 이어 설명"),("대동사·생략 the others (must go)","'나머지는 …해야'")],
  [("as a result","결과적으로"),("unfulfilled","충족되지 않은")],
  [("As a result, he must [[choose]];","결과적으로, 그는 [[선택해야]] 한다;"),
   ("one end can be satisfied, but the others must go [[unfulfilled]].","하나의 목적은 충족되지만, 나머지는 [[충족되지 못한 채]] 있어야 한다.")],
  [("모든 목적이 함께 충족될 수 있다는 내용이다.","'one ... satisfied, but the others must go unfulfilled(하나만 충족, 나머지는 미충족)'이야 — 다 되는 게 아니라 하나만 된다는 뜻이야.")]),
 S(r2,8,[("Suppose that","'~라고 가정해 보자'(명령)")],
  [("suppose","가정하다"),("course","경로, 진로")],
  [("Suppose that he [[decides on course A]].","그가 [[경로 A로 결정한다]]고 가정해 보자.")],
  [("이 문장은 그가 A를 포기한다고 가정하는 문장이다.","'decides on course A(경로 A로 결정)'라고 가정하라는 거야 — 포기가 아니라 A를 택한 경우를 보라는 뜻이야.")]),
 S(r2,9,[("동격 that","a clear indication 뒤 내용 부연"),("비교급 higher than","'~보다 더 높게'")],
  [("indication","보여 주는 것, 지표"),("rank","순위를 매기다")],
  [("This is a clear [[indication that he has ranked the satisfaction of end A]]","이것은 그가 목적 A의 충족을 순위 매겼음을 [[분명히 보여 주는 것이다]]"),
   ("[[higher than the satisfaction of ends B or C]].","[[목적 B나 C의 충족보다 더 높게]].")],
  [("(함축) A를 고른 것은 A·B·C를 똑같이 중요하게 여긴다는 뜻이다.","함축을 놓쳤어. 'ranked A higher than B or C(A를 B·C보다 높게 매겼다)'는 곧 '선택=우선순위 매기기'라는, 글의 요지야.")])]

# ============ Unit09-2 : 환경 스트레스·독소 내성 (관계부사 why) ============
r3=["Environmental stresses cause changes in the genetic makeup of a population by favoring certain gene variants more than others.",
"This is, in fact, the normal way that populations can adapt rapidly to changes in their environment without mutations being required to produce new adaptations.",
"It is also the reason why populations with genetic diversity are more likely to survive in the face of change.",
"However, there is another side of this phenomenon related to human impacts on populations.",
"Toxins added to the environment create selection pressure for individuals that are more tolerant of the toxins.",
"One negative impact of this is that it can reduce the genetic diversity of a population.",
"Another problem occurs if the organism is a pest and the toxin is contained in, for example, a pesticide.",
"As a result of the selection pressure, the population seems to develop tolerance to the toxin.",
"The pesticide then becomes less effective."]
ov3=Overview(theme_ko="환경 스트레스로 인한 유전자 구성 변화와, 인위적 독소(살충제)가 초래하는 유전적 다양성 감소·내성 증가",
 key_grammar=KeyGrammar(point="관계부사 why (the reason why ~ : '~하는 이유')",
  source_sentence="It is also the reason why populations with genetic diversity are more likely to survive in the face of change.",
  explanation=[GN("쉽게 말하면","the reason 뒤 why는 '[[~하는 이유]]'라며 앞의 reason을 꾸미는 관계부사야."),
   GN("관계부사 4형제","the reason why(이유)·the place where(장소)·the time when(때)·the way how(방법) — 각 [[선행사]]에 맞춰 써."),
   GN("특징","관계부사 뒤에는 [[완전한 절]]이 와(주어·목적어 안 빠짐) — 관계대명사와의 결정적 차이."),
   GN("생략","the reason (why) / (the reason) why 처럼 선행사나 why를 [[생략]]하기도 해."),
   GN("해석 요령","'~하는 이유(는)'로 선행사 reason에 붙여 옮겨.")],
  example="",example_analysis="the reason why populations ... survive = '개체군이 생존하는 이유' — why가 the reason을 수식.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 3문장 'the reason why populations with genetic diversity are more likely to survive'에서 why의 역할은?",
    options=["the reason을 꾸미는 관계부사(~하는 이유)","'왜'를 뜻하는 의문사","populations를 꾸미는 관계대명사"],answer="the reason을 꾸미는 관계부사(~하는 이유)"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'This is the place ____ we first met.' (우리가 처음 만난 곳)",
    options=["where","which","why"],answer="where"),
   GrammarDrill(kind="객관식",from_passage=False,question="'Tell me the reason why you were late.'의 뜻으로 알맞은 것은?",
    options=["네가 늦은 이유를 말해 줘","네가 늦었는지 말해 줘","네가 늦은 곳을 말해 줘"],answer="네가 늦은 이유를 말해 줘"),
   GrammarDrill(kind="영작",from_passage=False,question="그것이 내가 그를 신뢰하는 이유이다.",answer="That is the reason why I trust him."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 3문장 일부) 그것은 유전적 다양성을 가진 개체군이 생존할 가능성이 더 높은 이유이다.",
    answer="It is the reason why populations with genetic diversity are more likely to survive.")]),
 topic="환경 스트레스는 유전자 구성을 바꿔 적응을 돕지만, 인간이 더한 독소(살충제)는 유전적 다양성을 줄이고 해충의 내성을 키운다는 글이야.",
 stance="중립적",stance_reason="유전적 적응의 원리와 인위적 독소의 부작용을 사실·인과 중심으로 설명하는 정보 전달문이야.",
 structure="통념→반박(반전)",structure_reason="'환경 스트레스가 적응을 돕는 정상적 방식'이라는 긍정 면(1~3문장) 뒤, 'However' 인간이 더한 독소의 부작용(4~9문장)으로 뒤집어.",
 restatement_chains=[RestatementChain(label="유전적 변화·적응",
   expressions=["changes in the genetic makeup of a population","adapt rapidly to changes in their environment","develop tolerance to the toxin"],
   variation="'유전자 구성 변화' → '환경 변화에 빠른 적응' → '독소에 대한 내성 획득'으로 이어져."),
  RestatementChain(label="독소의 부작용",
   expressions=["reduce the genetic diversity of a population","The pesticide then becomes less effective"],
   variation="'유전적 다양성 감소' → '살충제 효과 저하'로 부작용이 구체화돼.")],
 flow_blocks=[FlowBlock(stage="긍정 면",sentence_range="1~3",summary="환경 스트레스는 특정 변이형을 선호해 유전자 구성을 바꾸는데, 이는 개체군이 빠르게 적응·생존하는 정상적 방식이다.",easy_example="스트레스가 유리한 유전자를 골라 적응을 돕는 것."),
  FlowBlock(stage="반전",sentence_range="4~6",summary="그러나 인간이 더한 독소는 내성이 강한 개체를 선택해, 개체군의 유전적 다양성을 줄일 수 있다.",easy_example="독소가 특정 개체만 남겨 다양성을 깎는 것."),
  FlowBlock(stage="사례·결과",sentence_range="7~9",summary="해충에 살충제를 쓰면 선택 압력으로 내성이 생겨, 살충제 효과가 떨어진다.",easy_example="약을 쓸수록 해충이 약에 강해지는 것.")])
i3=[S(r3,1,[("by -ing","'~함으로써'"),("비교 more than","'~보다 더'")],
  [("genetic makeup","유전자 구성"),("favor","선호하다"),("variant","변이형")],
  [("Environmental stresses cause changes in the genetic makeup of a population","환경 스트레스는 개체군의 유전자 구성에 변화를 일으킨다"),
   ("by [[favoring certain gene variants more than others]].","[[특정 유전자 변이형을 다른 것보다 더 선호함]]으로써.")],
  [("환경 스트레스는 모든 유전자 변이형을 똑같이 유지한다는 내용이다.","'favoring certain gene variants more than others(특정 변이형을 더 선호)'로 유전자 구성을 바꾼다는 거야 — 똑같이 유지가 아니야.")]),
 S(r3,2,[("동명사 의미상 주어","without mutations being required : mutations가 being required의 의미상 주어(수동)"),("관계사 that","way 수식")],
  [("adapt","적응하다"),("mutation","돌연변이"),("adaptation","적응 (형태)")],
  [("This is, in fact, the normal way that populations can [[adapt rapidly]] to changes in their environment","이는 사실 개체군이 환경 변화에 [[빠르게 적응할]] 수 있는 정상적 방식이다"),
   ("[[without mutations being required to produce new adaptations]].","[[돌연변이가 새 적응 형태를 만들어 낼 필요 없이]].")],
  [("이 방식은 반드시 돌연변이가 있어야만 가능하다는 내용이다.","'without mutations being required(돌연변이가 필요 없이)'라고 했어 — 돌연변이 없이도 되는 정상적 적응 방식이야.")]),
 S(r3,3,[("관계부사 why","the reason 수식(⑤)"),("비교급 more likely","'~할 가능성이 더 높은'")],
  [("genetic diversity","유전적 다양성"),("in the face of","~에 직면하여")],
  [("It is also [[the reason why populations with genetic diversity]]","그것은 또한 [[유전적 다양성을 가진 개체군이]] ~하는 [[이유]]이기도 하다"),
   ("are more likely to survive in the face of change.","변화에 직면했을 때 생존할 가능성이 더 높은.")],
  [("이 문장은 유전적 다양성이 생존과 무관하다는 내용이다.","'the reason why ... more likely to survive(생존 가능성이 더 높은 이유)'라고 했어 — 다양성이 생존에 유리하다는 뜻이야.")]),
 S(r3,4,[("However 전환","'그러나'(반전)"),("과거분사 related to","'~와 관련된'")],
  [("phenomenon","현상"),("impact","영향")],
  [("However, there is [[another side of this phenomenon]]","그러나 이 현상의 [[또 다른 측면]]이 있다"),
   ("related to human impacts on populations.","개체군에 대한 인간의 영향과 관련된.")],
  [("이 문장은 앞의 긍정적 면을 계속 부연하는 문장이다.","'However ... another side(그러나 또 다른 측면)'로 방향을 트는 반전 문장이야 — 이제 인간이 더한 독소의 부작용으로 넘어가.")]),
 S(r3,5,[("과거분사 added","'더해진'(Toxins 수식)"),("관계사 that","individuals 수식"),("비교급 more tolerant","'더 내성이 강한'")],
  [("toxin","독소"),("selection pressure","선택 압력"),("tolerant","내성이 강한")],
  [("[[Toxins added to the environment]] create selection pressure","[[환경에 더해진 독소]]는 선택 압력을 만든다"),
   ("for individuals that are [[more tolerant of the toxins]].","[[그 독소에 더 내성이 강한]] 개체를 위한.")],
  [("환경에 더해진 독소는 내성이 약한 개체를 선택한다는 내용이다.","'individuals that are more tolerant(더 내성이 강한 개체)'를 선택하는 압력이야 — 약한 개체가 아니라 강한 개체가 살아남아.")]),
 S(r3,6,[("동격/명사절 that","is의 보어")],
  [("negative impact","부정적 영향"),("reduce","줄이다")],
  [("One negative impact of this is","이것의 부정적 영향 한 가지는"),
   ("[[that it can reduce the genetic diversity of a population]].","[[그것이 개체군의 유전적 다양성을 줄일 수 있다는]] 것이다.")],
  [("(지칭) 'this'는 유전적 다양성 증가를 가리킨다.","지칭 오인이야. this는 앞의 '독소가 내성 강한 개체만 선택하는 것'을 가리켜 — 그래서 다양성이 '감소'한다는 부작용이야.")]),
 S(r3,7,[("조건 if","'~인 경우'"),("수동태 is contained","'포함되어 있다'")],
  [("organism","생물체"),("pest","해충"),("pesticide","살충제")],
  [("Another problem occurs if the organism is a pest","또 다른 문제는 생물체가 해충이고 ~인 경우 발생한다"),
   ("and the toxin is contained in, for example, a [[pesticide]].","독소가 예를 들어 [[살충제]]에 포함되어 있는.")],
  [("이 문장은 해충에게는 아무 문제가 없다는 내용이다.","'Another problem occurs if ... a pest ... pesticide(해충이고 독소가 살충제인 경우 또 다른 문제)'라며 새 문제를 여는 거야.")]),
 S(r3,8,[("seem to","'~인 것처럼 보이다'")],
  [("develop tolerance","내성을 갖게 되다")],
  [("As a result of the selection pressure,","선택 압력의 결과로,"),
   ("the population seems to [[develop tolerance to the toxin]].","그 개체군은 [[그 독소에 대한 내성을 갖게 되는]] 것처럼 보인다.")],
  [("선택 압력의 결과로 개체군이 독소에 더 약해진다는 내용이다.","'develop tolerance to the toxin(독소에 대한 내성을 갖게 됨)'이야 — 약해지는 게 아니라 강해진다는 뜻이야.")]),
 S(r3,9,[("비교급 less effective","'덜 효과적인'")],
  [("effective","효과적인")],
  [("The pesticide then becomes [[less effective]].","그러면 그 살충제는 [[효과가 떨어진다]].")],
  [("(함축) 살충제는 시간이 지날수록 더 강력해진다는 뜻이다.","함축을 놓쳤어. 'becomes less effective(효과가 떨어진다)'는 내성 때문에 약이 안 듣게 된다는, 인위적 독소의 역설적 결과야.")])]

# ============ Unit09-3 : 상대적 부·행복 (상관접속사 not A but B) ============
r4=["People's happiness depends not on their absolute wealth, but rather on their wealth relative to those around them.",
"In one experiment, two capuchin monkeys were initially perfectly content with a reward of cucumbers when they successfully performed a task.",
"But when one monkey was later given tastier grapes as a reward, the monkey receiving plain old cucumbers became enraged, angrily throwing the previously satisfactory salad vegetable at its handler.",
"The monkeys' economy had grown, since grapes are better than cucumbers.",
"But the resulting inequality brought only discontent.",
"Humans are the same.",
"When employees at the University of California were given information about the salaries of their peers, those discovering they were paid below the average suddenly became less satisfied and more likely to seek a new job.",
"The attitudes of those earning above the average were happily unaffected."]
ov4=Overview(theme_ko="절대적 부가 아닌, 타인과의 비교를 통한 상대적 부에 좌우되는 행복감",
 key_grammar=KeyGrammar(point="상관접속사 not A but (rather) B ('A가 아니라 (오히려) B')",
  source_sentence="People's happiness depends not on their absolute wealth, but rather on their wealth relative to those around them.",
  explanation=[GN("쉽게 말하면","'not A but B'는 A를 부정하고 B를 택해 — '[[A가 아니라 B]]'로 읽어."),
   GN("형태","not 뒤 A, but 뒤 B에는 [[대등한 것]]이 와 — on their absolute wealth ↔ on their wealth relative to ~."),
   GN("rather 강조","but 뒤에 rather가 붙으면 '[[오히려/차라리]] B'라며 B를 더 강조해."),
   GN("초점","진짜 강조점은 [[B(but 뒤)]] — 행복은 '절대적 부'가 아니라 '상대적 부'에 달렸다."),
   GN("해석 요령","'A가 아니라 (오히려) B'로 옮기고 [[B]]에 무게를 실어.")],
  example="",example_analysis="not on absolute wealth, but rather on their wealth relative to others = '절대적 부가 아니라 오히려 상대적 부에 달려 있다'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 1문장 'not on their absolute wealth, but rather on their wealth relative to those around them'의 의미로 알맞은 것은?",
    options=["행복은 절대적 부가 아니라 남과 비교한 상대적 부에 달려 있다","행복은 상대적 부가 아니라 절대적 부에 달려 있다","행복은 부와 무관하다"],answer="행복은 절대적 부가 아니라 남과 비교한 상대적 부에 달려 있다"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'The problem is ____ money ____ time.' (돈이 아니라 시간)",
    options=["not / but","both / and","either / or"],answer="not / but"),
   GrammarDrill(kind="객관식",from_passage=False,question="'It is not the strongest but the most adaptable that survive.'의 뜻으로 알맞은 것은?",
    options=["가장 강한 것이 아니라 가장 잘 적응하는 것이 살아남는다","가장 잘 적응하는 것이 아니라 가장 강한 것이 살아남는다","강함과 적응력 모두 살아남는다"],answer="가장 강한 것이 아니라 가장 잘 적응하는 것이 살아남는다"),
   GrammarDrill(kind="영작",from_passage=False,question="중요한 것은 양이 아니라 질이다.",answer="What matters is not quantity but quality."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 1문장 일부) 사람들의 행복은 절대적 부가 아니라 상대적 부에 달려 있다.",
    answer="People's happiness depends not on their absolute wealth but on their relative wealth.")]),
 topic="행복은 절대적 부가 아니라 주변과 비교한 상대적 부에 좌우된다는 것을, 원숭이 실험과 대학 직원 사례로 보여 주는 글이야.",
 stance="중립적",stance_reason="상대적 부와 행복의 관계를 실험·사례 중심으로 설명하는 정보 전달문이야.",
 structure="주장→근거·예시",structure_reason="'행복은 상대적 부에 달렸다'는 주장(1문장) 뒤, 카푸친 원숭이 실험(2~5문장)과 대학 직원 사례(6~8문장)로 뒷받침해.",
 restatement_chains=[RestatementChain(label="상대적 비교가 행복 좌우",
   expressions=["their wealth relative to those around them","the resulting inequality brought only discontent","paid below the average suddenly became less satisfied"],
   variation="'주변에 상대적인 부' → '불평등이 불만을 부름' → '평균보다 적게 받자 덜 만족'으로 이어져."),
  RestatementChain(label="비교가 부른 불만",
   expressions=["became enraged","only discontent","became less satisfied"],
   variation="'격분함' → '불만뿐' → '덜 만족'으로 부정적 반응이 반복돼.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1",summary="사람들의 행복은 절대적 부가 아니라 주변과 비교한 상대적 부에 달려 있다.",easy_example="남보다 많으냐 적으냐가 행복을 좌우하는 것."),
  FlowBlock(stage="실험",sentence_range="2~5",summary="오이에 만족하던 원숭이가 다른 원숭이는 포도를 받자 격분했다 — 경제는 커졌어도 불평등이 불만만 낳았다.",easy_example="남이 더 좋은 걸 받으니 화가 나는 것."),
  FlowBlock(stage="사람 사례",sentence_range="6~8",summary="인간도 같아서, 동료보다 적게 받는다는 걸 안 직원은 덜 만족하고 이직을 원한 반면, 더 받는 이들은 영향이 없었다.",easy_example="평균보다 적게 받는다는 사실이 불만을 키우는 것.")])
i4=[S(r4,1,[("상관접속사 not A but B","not on ~ but rather on ~ (⑤)"),("과거분사 relative to","'~에 상대적인'")],
  [("absolute","절대적인"),("wealth","부"),("relative to","~에 상대적인")],
  [("People's happiness depends [[not on their absolute wealth]],","사람들의 행복은 [[그들의 절대적인 부가 아니라]],"),
   ("[[but rather on their wealth relative to those around them]].","[[오히려 주변 사람들에 상대적인 그들의 부에]] 달려 있다.")],
  [("사람들의 행복은 오직 자신이 가진 절대적 부에 달려 있다는 내용이다.","'not on absolute wealth, but rather on ... relative(절대적 부가 아니라 상대적 부에)'라고 했어 — 남과의 비교가 핵심이야.")]),
 S(r4,2,[("접속사 when","'~할 때'"),("수동태 were content","'만족했다'")],
  [("initially","처음에는"),("content","만족한"),("reward","보상")],
  [("In one experiment, two capuchin monkeys were [[initially perfectly content]] with a reward of cucumbers","한 실험에서 두 카푸친 원숭이는 오이 보상에 [[처음에는 완벽히 만족했다]]"),
   ("when they successfully performed a task.","과제를 성공적으로 수행했을 때.")],
  [("원숭이들은 처음부터 오이 보상에 불만이었다는 내용이다.","'initially perfectly content with cucumbers(처음엔 오이에 완벽히 만족)'라고 했어 — 처음엔 불만이 없었다는 뜻이야(비교 전).")]),
 S(r4,3,[("분사구문 throwing","'~하면서'(결과·동시)"),("현재분사 receiving","monkey 수식"),("수동태 was given","'주어지자'")],
  [("enraged","격분한"),("handler","조련사"),("satisfactory","만족스러운")],
  [("But when one monkey was later given [[tastier grapes]] as a reward,","그러나 한 원숭이에게 나중에 [[더 맛있는 포도]]가 보상으로 주어지자,"),
   ("the monkey receiving plain old cucumbers [[became enraged]],","평범한 오이를 받은 원숭이는 [[격분했다]],"),
   ("angrily throwing the previously satisfactory salad vegetable at its handler.","이전엔 만족스럽던 그 채소를 화를 내며 조련사에게 던지면서.")],
  [("한 원숭이가 포도를 받자 오이를 받은 원숭이는 더 기뻐했다는 내용이다.","'became enraged, throwing ... at its handler(격분해 던졌다)'는 거야 — 기뻐한 게 아니라 화를 냈어(상대적 박탈감).")]),
 S(r4,4,[("접속사 since","'~이므로'(이유)"),("비교급 better than","'~보다 더 좋은'")],
  [("economy","경제"),("grow","커지다")],
  [("The monkeys' economy had grown,","원숭이들의 경제는 커졌다,"),
   ("since grapes are [[better than cucumbers]].","포도가 [[오이보다 더 좋으므로]].")],
  [("이 문장은 원숭이들의 상황이 전반적으로 나빠졌다는 내용이다.","'economy had grown ... grapes are better(포도가 더 좋으니 경제는 커졌다)'는 거야 — 전체적으로는 나아졌다는 뜻(그런데도 불만).")]),
 S(r4,5,[("과거분사 resulting","'그 결과 초래된'"),("대조 but","'하지만'")],
  [("inequality","불평등"),("discontent","불만")],
  [("But the resulting inequality brought [[only discontent]].","하지만 그 결과로 초래된 불평등은 [[불만만]] 가져왔다.")],
  [("(함축) 경제가 커졌으니 원숭이들은 더 행복해졌다는 뜻이다.","함축을 놓쳤어. 'inequality brought only discontent(불평등이 불만만 낳았다)'는 절대적 이득보다 '상대적 비교'가 행복을 좌우한다는 요지야.")]),
 S(r4,6,[("the same 보어","'마찬가지다'")],
  [("the same","마찬가지의")],
  [("Humans are [[the same]].","인간도 [[마찬가지이다]].")],
  [("이 문장은 인간은 원숭이와 다르다는 내용이다.","'Humans are the same(인간도 마찬가지)'이라며 원숭이 실험을 사람에게 연결하는 전환 문장이야.")]),
 S(r4,7,[("접속사 when","'~할 때'"),("수동태 were given/were paid","'제공되다/받다'"),("현재분사 discovering","those 수식"),("비교급 less satisfied / more likely","'덜/더 ~한'")],
  [("peer","동료"),("below the average","평균 이하로"),("seek","구하다")],
  [("When employees at the University of California were given information about the salaries of their peers,","캘리포니아 대학교 직원들에게 동료 급여 정보가 제공되었을 때,"),
   ("[[those discovering they were paid below the average]]","[[자신이 평균보다 적게 받는다는 걸 알게 된 이들은]]"),
   ("suddenly became [[less satisfied and more likely to seek a new job]].","갑자기 [[덜 만족하고 새 일자리를 더 구하려 했다]].")],
  [("동료 급여를 알게 된 직원은 모두 더 만족하게 되었다는 내용이다.","'paid below the average ... became less satisfied(평균보다 적게 받는 이는 덜 만족)'이야 — 모두가 아니라 '적게 받는' 쪽만 불만이 커졌어.")]),
 S(r4,8,[("현재분사 earning","those 수식"),("부사 happily","'다행히'")],
  [("earn","(돈을) 벌다"),("unaffected","영향받지 않은")],
  [("The attitudes of those earning above the average","평균보다 더 많이 받는 이들의 태도는"),
   ("were happily [[unaffected]].","다행히 [[영향받지 않았다]].")],
  [("평균 이상을 받는 이들도 크게 불만족스러워졌다는 내용이다.","'those earning above the average were unaffected(평균 이상은 영향 없음)'이야 — 비교에서 유리한 쪽은 불만이 없었다는 대조야.")])]

# ============ Ch03 서술형 Practice : 믿음 vs 지식 (관계대명사 what) ============
r5=["Imagine that a farmer is wondering whether his black-and-white cow, Daisy, is in the field.",
"He believes she is in the field when he goes to look, because he sees something black-and-white in the distance.",
"Later, it turns out that what he saw was a large black-and-white bag, not Daisy.",
"But the cow really was in the field ─ she was just hidden from sight in a dip.",
"The farmer was right that Daisy was there, but wrong in what he saw.",
"So, he didn't have real knowledge ─ it was just a belief that turned out to be true."]
ov5=Overview(theme_ko="우연히 사실로 드러난 믿음(belief)과 정당화된 참된 지식(knowledge)의 철학적 구분",
 key_grammar=KeyGrammar(point="선행사를 포함하는 관계대명사 what ('~하는 것')",
  source_sentence="Later, it turns out that what he saw was a large black-and-white bag, not Daisy.",
  explanation=[GN("쉽게 말하면","관계대명사 what은 선행사(the thing)를 [[자체에 포함]]해 '~하는 것'이라는 명사 덩어리를 만들어."),
   GN("복원","what he saw = the thing [[which]] he saw(그가 본 것) — what = the thing which."),
   GN("자리","what절은 문장에서 [[주어·목적어·보어]] 자리에 와 — 여기선 was의 '주어'."),
   GN("구별","what 뒤 문장이 [[불완전]](saw의 목적어가 빔)하면 관계대명사 what, 완전하면 접속사 that야."),
   GN("해석 요령","'~하는 것은/것을'로 what절을 하나의 명사로 묶어 읽어.")],
  example="",example_analysis="what he saw was a large bag = '그가 본 것은 큰 가방이었다' — what절이 was의 주어.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 3문장 'what he saw'의 문법 설명으로 알맞은 것은?",
    options=["선행사를 포함해 '~하는 것'을 뜻하는 관계대명사 what","the thing을 꾸미는 관계부사","'무엇'을 뜻하는 의문사"],answer="선행사를 포함해 '~하는 것'을 뜻하는 관계대명사 what"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? '____ he needs is a good rest.' (그에게 필요한 것)",
    options=["What","That","Which"],answer="What"),
   GrammarDrill(kind="객관식",from_passage=False,question="'I can't believe what I heard.'의 뜻으로 알맞은 것은?",
    options=["나는 내가 들은 것을 믿을 수 없다","나는 무엇을 들었는지 믿는다","나는 들은 곳을 믿을 수 없다"],answer="나는 내가 들은 것을 믿을 수 없다"),
   GrammarDrill(kind="영작",from_passage=False,question="그가 말한 것은 사실이 아니었다.",answer="What he said was not true."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 3문장 일부) 그가 본 것은 큰 흑백 가방이었다.",
    answer="What he saw was a large black-and-white bag.")]),
 topic="농부가 소가 들판에 있다고 믿었는데 우연히 맞은 이야기로, '사실로 드러난 믿음'과 '정당화된 참된 지식'의 차이를 보여 주는 글이야.",
 stance="중립적",stance_reason="지식과 믿음의 철학적 구분을 하나의 사고 실험(농부·소)으로 설명하는 정보 전달문이야.",
 structure="예시→일반화(결론)",structure_reason="농부와 소 Daisy의 상황(1~5문장)을 제시한 뒤, '그것은 지식이 아니라 우연히 참이 된 믿음'이라는 결론(6문장)으로 일반화해.",
 restatement_chains=[RestatementChain(label="빗나간 근거",
   expressions=["something black-and-white in the distance","what he saw was a large black-and-white bag","wrong in what he saw"],
   variation="'멀리 흑백의 무언가' → '그가 본 것은 큰 가방' → '본 것에 대해 틀림'으로 이어져."),
  RestatementChain(label="우연히 참이 된 믿음",
   expressions=["right that Daisy was there","a belief that turned out to be true"],
   variation="'거기 있다는 점은 옳음' → '사실로 드러난 믿음'으로 정리돼.")],
 flow_blocks=[FlowBlock(stage="상황",sentence_range="1~2",summary="농부는 멀리 흑백의 무언가를 보고 소 Daisy가 들판에 있다고 믿는다.",easy_example="흑백 얼룩을 보고 '소가 있네' 하고 믿는 것."),
  FlowBlock(stage="반전",sentence_range="3~4",summary="그가 본 건 사실 큰 흑백 가방이었지만, 소는 정말로 움푹한 곳에 가려져 들판에 있었다.",easy_example="본 건 가방인데, 소는 우연히 진짜 있었던 것."),
  FlowBlock(stage="결론",sentence_range="5~6",summary="농부는 소가 있다는 점은 옳았지만 본 것은 틀렸으니, 그것은 지식이 아니라 우연히 참이 된 믿음이었다.",easy_example="맞긴 맞았는데 근거가 틀려 '지식'은 아닌 것.")])
i5=[S(r5,1,[("Imagine that","'~라고 상상해 보라'(명령)"),("접속사 whether","'~인지'(wondering의 목적어)")],
  [("wonder","궁금해하다"),("field","들판")],
  [("Imagine that a farmer is [[wondering whether his black-and-white cow, Daisy, is in the field]].","한 농부가 [[자신의 흑백 얼룩소 Daisy가 들판에 있는지 궁금해한다]]고 상상해 보라.")],
  [("농부는 소가 어디 있는지 이미 확실히 안다는 내용이다.","'wondering whether ... is in the field(들판에 있는지 궁금해함)'이야 — 확실히 아는 게 아니라 불확실한 상태에서 시작해.")]),
 S(r5,2,[("접속사 because","이유"),("명사절 생략","believes (that) she is ~ : 접속사 that 생략")],
  [("in the distance","멀리서")],
  [("He believes she is in the field when he goes to look,","확인하러 갔을 때 그는 소가 들판에 있다고 믿는데,"),
   ("because he sees [[something black-and-white in the distance]].","멀리서 [[흑백의 무언가]]를 보기 때문이다.")],
  [("농부는 아무 근거 없이 소가 있다고 믿는다는 내용이다.","'because he sees something black-and-white(흑백의 무언가를 봐서)' 믿는 거야 — 근거가 있긴 한데, 그 근거가 곧 틀린 것으로 드러나.")]),
 S(r5,3,[("관계대명사 what","'~하는 것'(was의 주어, ⑤)"),("가주어 it","it turns out that ~")],
  [("turn out","~로 드러나다")],
  [("Later, it turns out that [[what he saw was a large black-and-white bag]], not Daisy.","나중에, [[그가 본 것은 큰 흑백 가방이었지]], Daisy가 아니었음이 드러난다.")],
  [("나중에 그가 본 것이 정말 소였음이 밝혀진다는 내용이다.","'what he saw was a large ... bag, not Daisy(그가 본 건 소가 아니라 가방)'였음이 드러나 — 근거가 틀렸다는 반전이야.")]),
 S(r5,4,[("대시 부연","앞 내용을 보충"),("수동태 was hidden","'가려져 있었다'")],
  [("hidden","가려진"),("dip","움푹 파인 곳")],
  [("But the cow really was in the field ─","하지만 그 소는 정말로 들판에 있었다 ─"),
   ("she was just [[hidden from sight in a dip]].","단지 움푹한 곳에서 [[시야에서 가려져 있었을]] 뿐이었다.")],
  [("(지칭) 'she'는 농부가 본 가방을 가리킨다.","지칭 오인이야. she는 소 'Daisy'를 가리켜 — 소는 진짜 들판에 있었지만 움푹한 곳에 가려져 안 보였던 거야.")]),
 S(r5,5,[("대조 but","'하지만'"),("관계대명사 what","'~한 것'(in의 목적어)")],
  [("right","옳은"),("wrong","틀린")],
  [("The farmer was right that Daisy was there,","농부는 Daisy가 거기 있다는 점에서는 옳았지만,"),
   ("but [[wrong in what he saw]].","자신이 [[본 것에 대해서는 틀렸다]].")],
  [("농부는 모든 점에서 완전히 옳았다는 내용이다.","'right that Daisy was there, but wrong in what he saw(있다는 건 옳고, 본 것은 틀림)'이야 — 결론은 맞았지만 근거는 틀렸어.")]),
 S(r5,6,[("대시 부연","결론 보충"),("관계사 that","belief 수식")],
  [("knowledge","지식"),("belief","믿음")],
  [("So, he didn't have real knowledge ─","따라서 그는 진정한 지식을 갖지 못했다 ─"),
   ("it was just [[a belief that turned out to be true]].","그것은 단지 [[사실로 드러난 믿음]]일 뿐이었다.")],
  [("(함축) 우연히 맞았으니 농부는 진정한 지식을 가졌다는 뜻이다.","함축을 놓쳤어. 'not real knowledge ─ just a belief that turned out to be true(지식이 아니라 우연히 참이 된 믿음)'라며 지식과 믿음을 가르는 결론이야.")])]

# ============ Ch03 논술형 Practice : 음식 맛·암묵지 (too ~ to) ============
r6=["Nearly everything we eat or drink for pleasure is too complex to fully describe in words.",
"A bottle of wine maybe described as having characteristics you like but still turn out to be not so nice, for reasons that are impossible to express in words.",
"Conversely, it may be described as having characteristics you know you hate but still turn out to be delicious, again for reasons that cannot be explained in words.",
"Even after experiencing the wine, it is impossible to say precisely and completely why you liked it.",
"You might have words to describe some parts of your enjoyment (perhaps it had 'good structure' or 'rich fruit'), but those words will be both imperfect and incomplete descriptions, a pale shadow of what you actually enjoyed about it.",
"What we enjoy in any particular food or drink is a type of tacit knowledge: a complex of interacting characteristics that we know but are unable to say."]
ov6=Overview(theme_ko="언어로 완벽히 묘사할 수 없는 음식의 맛과, 암묵적 지식(tacit knowledge)으로서의 미각 경험",
 key_grammar=KeyGrammar(point="too ~ to 구문 ('너무 ~해서 …할 수 없다')",
  source_sentence="Nearly everything we eat or drink for pleasure is too complex to fully describe in words.",
  explanation=[GN("쉽게 말하면","'too + 형용사/부사 + to부정사'는 '너무 ~해서 [[…할 수 없다]]'라는 부정의 뜻이야."),
   GN("의미","too에 이미 '지나치게'라는 [[부정]] 뉘앙스가 들어 있어 결과가 불가능해져."),
   GN("전환","too complex to describe = [[so]] complex that we can't describe — so~that 부정문으로 바꿔 쓸 수 있어."),
   GN("의미상 주어","'for + 목적격'으로 to부정사의 [[의미상 주어]]를 밝히기도 해(too hard for me to solve)."),
   GN("해석 요령","'너무 ~해서 …할 수 없다'로, to 이하를 [[부정]]으로 옮겨.")],
  example="",example_analysis="too complex to fully describe = '너무 복잡해서 완전히 묘사할 수 없다'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 1문장 'too complex to fully describe in words'의 의미로 알맞은 것은?",
    options=["너무 복잡해서 말로 완전히 묘사할 수 없다","묘사하기에 충분히 복잡하다","말로 묘사할 만큼 단순하다"],answer="너무 복잡해서 말로 완전히 묘사할 수 없다"),
   GrammarDrill(kind="객관식",from_passage=False,question="'The box was too heavy to lift.'의 뜻으로 알맞은 것은?",
    options=["그 상자는 너무 무거워서 들 수 없었다","그 상자는 들 만큼 무거웠다","그 상자는 들기에 가벼웠다"],answer="그 상자는 너무 무거워서 들 수 없었다"),
   GrammarDrill(kind="객관식",from_passage=False,question="'She is too honest to tell a lie.'와 뜻이 같은 것은?",
    options=["so honest that she can't tell a lie","so honest that she tells a lie","honest enough to tell a lie"],answer="so honest that she can't tell a lie"),
   GrammarDrill(kind="영작",from_passage=False,question="그 커피는 너무 뜨거워서 마실 수 없다.",answer="The coffee is too hot to drink."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 1문장 일부) 그것은 너무 복잡해서 말로 완전히 묘사할 수 없다.",
    answer="It is too complex to fully describe in words.")]),
 topic="우리가 즐기는 음식·음료의 맛은 너무 복잡해 말로 다 설명할 수 없는, 일종의 '암묵적 지식'이라는 글이야.",
 stance="중립적",stance_reason="미각 경험이 언어로 온전히 표현되지 않는다는 점을 와인 예시로 설명하는 정보 전달문이야.",
 structure="주장→근거·예시",structure_reason="'즐기는 음식은 말로 다 묘사할 수 없다'는 주장(1문장) 뒤, 와인 예시(2~5문장)로 뒷받침하고 '암묵적 지식'으로 일반화(6문장)해.",
 restatement_chains=[RestatementChain(label="말로 표현 불가",
   expressions=["too complex to fully describe in words","impossible to express in words","cannot be explained in words","imperfect and incomplete descriptions"],
   variation="'너무 복잡해 말로 못 함' → '말로 표현 불가' → '말로 설명 불가' → '불완전한 설명'으로 반복·강조돼."),
  RestatementChain(label="암묵적 지식",
   expressions=["a pale shadow of what you actually enjoyed","a type of tacit knowledge","that we know but are unable to say"],
   variation="'실제 즐긴 것의 희미한 흔적' → '암묵적 지식' → '알지만 말할 수 없는 것'으로 정리돼.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1",summary="우리가 즐기는 거의 모든 음식·음료는 너무 복잡해 말로 완전히 묘사할 수 없다.",easy_example="맛있다는 느낌을 말로 다 못 옮기는 것."),
  FlowBlock(stage="예시",sentence_range="2~4",summary="좋아하는 특징의 와인이 별로거나, 싫어하는 특징의 와인이 맛있기도 한데, 경험 후에도 왜 좋았는지 정확히 말할 수 없다.",easy_example="왜 맛있는지 콕 집어 설명 못 하는 것."),
  FlowBlock(stage="일반화",sentence_range="5~6",summary="몇몇 표현이 있어도 불완전하니, 우리가 즐기는 것은 알지만 말할 수 없는 '암묵적 지식'이다.",easy_example="느낌은 아는데 말로는 못 하는 앎.")])
i6=[S(r6,1,[("too ~ to","'너무 ~해서 …할 수 없다'(⑤)"),("목적격 관계대명사 생략","everything (that) we eat or drink : 관계대명사 생략"),("병렬 eat or drink","동사 병렬")],
  [("nearly","거의"),("complex","복잡한"),("describe","묘사하다")],
  [("[[Nearly everything we eat or drink for pleasure]]","[[우리가 즐거움을 위해 먹거나 마시는 거의 모든 것은]]"),
   ("is [[too complex to fully describe in words]].","[[너무 복잡해서 말로 완전히 묘사할 수 없다]].")],
  [("우리가 즐기는 음식은 대부분 말로 쉽게 설명된다는 내용이다.","'too complex to fully describe(너무 복잡해 완전히 묘사 못 함)'이야 — 쉽게 설명되는 게 아니라 말로 다 못 담는다는 주제야.")]),
 S(r6,2,[("수동태 be described","'묘사되다'"),("관계사 that","reasons 수식"),("목적격 관계대명사 생략","characteristics (that) you like")],
  [("characteristic","특징"),("turn out","~로 판명되다"),("express","표현하다")],
  [("A bottle of wine maybe described as [[having characteristics you like]]","와인 한 병은 [[여러분이 좋아하는 특징을 가진 것]]으로 묘사될 수 있지만"),
   ("but still turn out to be not so nice,","그래도 그리 좋지 않은 것으로 판명될 수 있다,"),
   ("for reasons that are [[impossible to express in words]].","[[말로 표현할 수 없는]] 이유로.")],
  [("좋아하는 특징을 가진 와인은 언제나 맛있다는 내용이다.","'characteristics you like but still ... not so nice(좋아하는 특징인데도 별로)'라며 말로 설명 안 되는 반전을 들어.")]),
 S(r6,3,[("수동태 be described/be explained","'묘사되다/설명되다'"),("부사 Conversely","'반대로'")],
  [("conversely","반대로"),("delicious","맛있는")],
  [("Conversely, it may be described as having characteristics you know you hate","반대로, 그것은 여러분이 싫어한다고 아는 특징을 가진 것으로 묘사될 수 있지만"),
   ("but still turn out to be [[delicious]], again for reasons that [[cannot be explained in words]].","그래도 [[맛있는]] 것으로 판명될 수 있다, 마찬가지로 [[말로 설명할 수 없는]] 이유로.")],
  [("싫어하는 특징의 와인은 반드시 맛없다는 내용이다.","'characteristics you hate but still ... delicious(싫어하는 특징인데도 맛있다)'는 거야 — 말로 설명 안 되는 또 다른 반전이야.")]),
 S(r6,4,[("가주어 it ~ to","it is impossible to say ~"),("관계부사/의문사 why","'왜 ~한지'")],
  [("precisely","정확하게"),("completely","완전하게")],
  [("Even after experiencing the wine,","그 와인을 경험한 후에도,"),
   ("it is [[impossible to say precisely and completely why you liked it]].","여러분이 [[왜 그것을 좋아했는지 정확하고 완전하게 말하기란 불가능하다]].")],
  [("와인을 마셔 보면 왜 좋았는지 정확히 설명할 수 있다는 내용이다.","'impossible to say ... why you liked it(왜 좋았는지 말하기 불가능)'이야 — 경험 후에도 정확히 설명 못 한다는 뜻이야.")]),
 S(r6,5,[("동격 명사구","a pale shadow = descriptions 부연"),("both A and B","'A이자 B'"),("관계대명사 what","'~한 것'(of의 목적어)")],
  [("imperfect","불완전한"),("pale shadow","희미한 흔적")],
  [("You might have words to describe some parts of your enjoyment (perhaps it had 'good structure' or 'rich fruit'),","여러분이 느낀 즐거움의 일부를 설명할 말이 있을 순 있지만 (아마 '훌륭한 짜임새'나 '풍부한 과일 향'이 있었을 것이다),"),
   ("but those words will be [[both imperfect and incomplete descriptions]],","그 말들은 [[불완전하고 불충분한 설명]], "),
   ("a pale shadow of [[what you actually enjoyed about it]].","즉 [[여러분이 실제로 즐긴 것]]의 희미한 흔적일 것이다.")],
  [("몇몇 표현만 있으면 즐거움을 완벽히 전달할 수 있다는 내용이다.","'both imperfect and incomplete ... a pale shadow(불완전·불충분한, 희미한 흔적)'라고 했어 — 말로는 온전히 못 전한다는 뜻이야.")]),
 S(r6,6,[("관계대명사 what","'~하는 것'(is의 주어)"),("콜론 부연","tacit knowledge를 풀어 설명"),("관계사 that","complex 수식")],
  [("tacit knowledge","암묵적 지식"),("interacting","상호 작용하는")],
  [("[[What we enjoy in any particular food or drink]] is a type of tacit knowledge:","[[특정 음식·음료에서 우리가 즐기는 것]]은 일종의 암묵적 지식이다:"),
   ("a complex of interacting characteristics [[that we know but are unable to say]].","[[우리가 알지만 말할 수 없는]] 상호 작용하는 특징들의 복합체.")],
  [("(함축) 암묵적 지식은 노력하면 누구나 말로 정확히 표현할 수 있다.","함축을 놓쳤어. 'tacit knowledge ... we know but are unable to say(알지만 말할 수 없는 암묵적 지식)'라며 언어화 불가능함이 핵심이야.")])]

P_u09a=finalize(build("과거 성공에 갇혀 관리자로서의 변화에 적응 못 하는 고성과자의 딜레마",S9,"Unit09-ANALYSIS",r1,ov1,i1))
P_u091=finalize(build("시간의 희소성으로 필연적으로 발생하는 목적 간의 선택과 우선순위",S9,"Unit09-1",r2,ov2,i2))
P_u092=finalize(build("환경 스트레스의 유전자 변화와 인위적 독소가 부른 다양성 감소·내성 증가",S9,"Unit09-2",r3,ov3,i3))
P_u093=finalize(build("절대적 부가 아닌 타인과의 비교에 좌우되는 상대적 부와 행복",S9,"Unit09-3",r4,ov4,i4))
P_ch03s=finalize(build("우연히 참이 된 믿음과 정당화된 참된 지식의 구분",SP,"서술형 Practice(Ch03)",r5,ov5,i5))
P_ch03n=finalize(build("언어로 완벽히 묘사 못 하는 맛과 암묵적 지식으로서의 미각",SN,"논술형 Practice(Ch03)",r6,ov6,i6))
CH03=[P_u09a,P_u091,P_u092,P_u093,P_ch03s,P_ch03n]
