# -*- coding: utf-8 -*-
"""올림포스 독해 기본1 · Ch04 Unit10 (ANALYSIS/1/2) 강의컨셉 교재. (Unit10-3은 batch00 재사용)"""
import sys, random
sys.path.insert(0, "/home/user/english_data_making")
from src.lecture_schemas import (Chunk, FlowBlock, GrammarChip, GrammarDrill,
    GrammarNote, KeyGrammar, LecturePassage, LectureSentence, Misread,
    Overview, RestatementChain, SentenceAnalysis, SentenceItem, Vocab)
def mk(r): return [LectureSentence(id=i,text=t) for i,t in enumerate(r,1)]
def S(r,i,g,v,c,m): return SentenceItem(id=i,english=r[i-1],
    grammar=[GrammarChip(tag=a,note=b) for a,b in g],
    vocab=[Vocab(word=w,meaning=k) for w,k in v],
    chunks=[Chunk(en=e,ko=k) for e,k in c],
    misreads=[Misread(statement=s,why=w) for s,w in m])
def GN(c,t): return GrammarNote(chip=c,text=t)
def build(title,src,no,r,ov,items):
    p=LecturePassage(title=title,source=src,item_no=no,sentences=mk(r),
        overview=ov,analysis=SentenceAnalysis(sentences=items)); p.analysis.validate_all(len(r)); return p
def tok(a):
    ws=[w.strip('.,;:!?\"()“”') for w in a.split()]; ws=[w for w in ws if w]
    random.Random(len(a)+sum(map(ord,a[:8]))).shuffle(ws); return ws
_MCQ=[1]
def finalize(p):
    for d in p.overview.key_grammar.drills:
        if d.kind=='영작': d.words=tok(d.answer)
        if d.kind=='객관식' and d.options:
            others=[o for o in d.options if o!=d.answer]
            pos=_MCQ[0]%len(d.options); d.options=others[:]; d.options.insert(pos,d.answer)
        _MCQ[0]+=1
    return p
S10="EBS 올림포스 영어독해 기본1 · Ch04 Unit10"

# ============ Unit10-ANALYSIS : 유아 두려움·사회성 발달 (비교급 than절 도치·생략) ============
r1=["Many developmental theorists and researchers, including those studying human as well as nonhuman primate subjects, have recognized the role that fear can play in a primate's social development.",
"When an infant is frightened it always seeks out its mother for protection and safety, and all exploratory and play activity stops until the infant has been sufficiently comforted and reassured by its attachment object.",
"Thus, frequently frightened infants will very likely have less time to explore and fewer opportunities to play than will infants who are not.",
"Such voluntary restraints may serve to slow down the social development of shy or anxious infants if these tendencies are maintained throughout their childhood years."]
ov1=Overview(theme_ko="유아의 잦은 두려움이 탐색 기회 감소를 통해 사회성 발달 지연에 미치는 영향",
 key_grammar=KeyGrammar(point="비교급 than절의 도치·생략 (than will infants ~)",
  source_sentence="Thus, frequently frightened infants will very likely have less time to explore and fewer opportunities to play than will infants who are not.",
  explanation=[GN("쉽게 말하면","비교 대상을 than 뒤에 쓸 때, 균형·강조를 위해 '[[조동사+주어]]'로 도치하고 반복 어구는 [[생략]]하기도 해."),
   GN("복원","than will infants who are not = than infants who are not (frightened) [[will have]] — 도치를 풀고 생략을 복원."),
   GN("도치","than 뒤 'will infants'는 원래 'infants will'인데 [[조동사(will)+주어(infants)]]로 뒤집힌 거야."),
   GN("생략","who are not 뒤엔 [[frequently frightened]]가, will 뒤엔 have ~가 반복이라 생략됐어."),
   GN("해석 요령","'~하지 않은 유아보다 (덜/더) …하다'로 비교 대상을 정확히 맞춰 옮겨.")],
  example="",example_analysis="less time ... than will infants who are not = '그렇지 않은 유아보다 시간이 더 적다' — than+도치·생략.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 3문장 'than will infants who are not'에 대한 설명으로 옳은 것은?",
    options=["than 뒤에 '조동사(will)+주어(infants)'로 도치가 일어났다","than은 전치사이고 infants가 목적어다","infants가 동사, will이 주어로 쓰였다"],answer="than 뒤에 '조동사(will)+주어(infants)'로 도치가 일어났다"),
   GrammarDrill(kind="객관식",from_passage=False,question="'She runs faster than does her brother.'에서 'does her brother'의 어순은?",
    options=["than 뒤 '조동사+주어' 도치","의문문 어순","주어+동사 정상 어순"],answer="than 뒤 '조동사+주어' 도치"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'He earns more money than ____ I.' (나보다)",
    options=["do","does","is"],answer="do"),
   GrammarDrill(kind="영작",from_passage=False,question="그녀는 자기 여동생보다 더 열심히 공부한다. (than 도치)",answer="She studies harder than does her sister."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 3문장 일부) 자주 겁먹는 유아는 그렇지 않은 유아보다 놀 기회가 더 적다.",
    answer="Frequently frightened infants have fewer opportunities to play than infants who are not.")]),
 topic="자주 겁을 먹는 유아는 탐색·놀이 기회가 줄어, 이런 경향이 지속되면 사회성 발달이 늦어질 수 있다는 글이야.",
 stance="중립적",stance_reason="두려움이 영장류의 사회성 발달에 미치는 영향을 인과 중심으로 설명하는 정보 전달문이야.",
 structure="주장→근거·예시",structure_reason="'두려움이 사회성 발달에서 역할을 한다'는 도입(1문장)과 기제(2문장) 뒤, 결과(3문장)와 조건부 결론(4문장)으로 이어져.",
 restatement_chains=[RestatementChain(label="두려움→활동 중단",
   expressions=["all exploratory and play activity stops","less time to explore and fewer opportunities to play","voluntary restraints"],
   variation="'탐색·놀이 활동이 멈춤' → '탐색 시간·놀이 기회가 더 적음' → '자발적 제한'으로 이어져."),
  RestatementChain(label="사회성 발달 지연",
   expressions=["fear can play in a primate's social development","slow down the social development of shy or anxious infants"],
   variation="'두려움이 사회성 발달에서 하는 역할' → '수줍거나 불안한 유아의 발달을 늦춤'으로 구체화돼.")],
 flow_blocks=[FlowBlock(stage="도입",sentence_range="1",summary="많은 연구자가 두려움이 영장류의 사회성 발달에서 하는 역할을 인식해 왔다.",easy_example="무서움이 아이의 성장에 영향을 준다는 것."),
  FlowBlock(stage="기제",sentence_range="2",summary="유아는 겁먹으면 엄마를 찾고, 충분히 안심될 때까지 모든 탐색·놀이 활동을 멈춘다.",easy_example="무서우면 엄마 품에서 놀이를 멈추는 것."),
  FlowBlock(stage="결과",sentence_range="3",summary="그래서 자주 겁먹는 유아는 그렇지 않은 유아보다 탐색·놀이 기회가 더 적을 가능성이 크다.",easy_example="겁이 많을수록 놀 기회가 줄어드는 것."),
  FlowBlock(stage="조건부 결론",sentence_range="4",summary="이런 자발적 제한이 아동기 내내 지속되면 수줍거나 불안한 유아의 사회성 발달을 늦출 수 있다.",easy_example="계속되면 사회성 발달이 뒤처질 수 있는 것.")])
i1=[S(r1,1,[("목적격 관계대명사 that","the role (that) fear can play — role 수식(목적격)"),("현재분사 studying","those 수식"),("as well as","'~뿐 아니라'")],
  [("developmental","발달의"),("primate","영장류"),("recognize","인식하다")],
  [("Many developmental theorists and researchers, including those studying human as well as [[nonhuman primate subjects]],","인간뿐 아니라 [[비인간 영장류]]를 연구하는 이들을 포함한 많은 발달 이론가·연구자는,"),
   ("have recognized [[the role]]","[[역할]]을 인식해 왔다"),
   ("[[that fear can play in a primate's social development]].","[[두려움이 영장류의 사회성 발달에서 할 수 있는]].")],
  [("이 문장은 두려움이 사회성 발달과 무관함을 밝히는 문장이다.","'recognized the role that fear can play in ... social development(두려움이 사회성 발달에서 하는 역할을 인식)'이라는 주제 도입이야.")]),
 S(r1,2,[("접속사 when","'~할 때'"),("완료 수동태 has been comforted","'위로받아 왔다'"),("접속사 until","'~할 때까지'")],
  [("frightened","겁먹은"),("exploratory","탐색의"),("reassure","안심시키다"),("attachment object","애착 대상")],
  [("When an infant is frightened it always [[seeks out its mother for protection and safety]],","유아는 겁먹으면 항상 [[보호와 안전을 위해 엄마를 찾고]],"),
   ("and all exploratory and play activity stops","모든 탐색·놀이 활동이 멈춘다"),
   ("until the infant has been [[sufficiently comforted and reassured by its attachment object]].","유아가 애착 대상에게 [[충분히 위로받고 안심될]] 때까지.")],
  [("(지칭) 'it always seeks out its mother'의 it은 엄마를 가리킨다.","지칭 오인이야. it은 앞의 'an infant(유아)'를 가리켜 — 겁먹은 유아가 엄마를 찾는다는 뜻이야.")]),
 S(r1,3,[("비교급 than절 도치·생략","less/fewer ~ than will infants who are not — than 뒤 도치·생략(⑤)")],
  [("frequently","자주"),("explore","탐색하다"),("opportunity","기회")],
  [("Thus, frequently frightened infants will very likely have [[less time to explore and fewer opportunities to play]]","따라서 자주 겁먹는 유아는 [[탐색할 시간이 더 적고 놀 기회가 더 적을]] 가능성이 크다"),
   ("[[than will infants who are not]].","[[그렇지 않은 유아보다]].")],
  [("자주 겁먹는 유아가 탐색·놀이 기회가 더 많다는 내용이다.","'less time to explore and fewer opportunities to play(탐색 시간·놀이 기회가 더 적다)'는 거야 — 더 많은 게 아니라 더 적어.")]),
 S(r1,4,[("부정사 to slow down","'늦추는'(serve to)"),("수동태 are maintained","'유지되다'"),("조건 if","'~라면'")],
  [("voluntary","자발적인"),("restraint","제한, 억제"),("tendency","경향")],
  [("Such voluntary restraints may serve to [[slow down the social development of shy or anxious infants]]","이러한 자발적 제한은 [[수줍거나 불안한 유아의 사회성 발달을 늦추는]] 역할을 할 수 있다"),
   ("if these tendencies are [[maintained throughout their childhood years]].","이런 경향이 [[아동기 내내 유지되면]].")],
  [("(함축) 잠깐의 두려움도 곧바로 사회성 발달을 늦춘다는 뜻이다.","함축을 놓쳤어. 'may serve to slow down ... if these tendencies are maintained throughout childhood(경향이 아동기 내내 지속되면)'이라는 조건부야 — 잠깐이 아니라 지속될 때 늦춰질 수 있다는 뜻이야.")])]

# ============ Unit10-1 : 유연한 사회적 유대 대상 (as if 가정법) ============
r2=["Our complex brains might have evolved to establish strong social bonds, but defining what should be part of that social group appears to be rather flexible.",
"For instance, some people treat their pets as if they are members of their family, and believe they can relate to the pets' needs, desires, fears and dreams.",
"Others see animals as distinct from humans and wouldn't think of talking to one as if it was a friend.",
"Many people keep the ashes of a deceased loved one nearby, believing those ashes continue to serve as some link to their existence.",
"Even if inanimate objects don't have a distinct personality, many of us still attribute certain human characteristics to non-human objects or beings, such as pets, dolls or even cars and memorabilia."]
ov2=Overview(theme_ko="반려동물이나 무생물까지 포함하는, 인간의 유연한 사회적 유대 대상의 범위",
 key_grammar=KeyGrammar(point="as if + 가정법 과거 ('마치 ~인 것처럼')",
  source_sentence="Others see animals as distinct from humans and wouldn't think of talking to one as if it was a friend.",
  explanation=[GN("쉽게 말하면","'as if + 주어 + 과거동사'는 '마치 [[~인 것처럼]]'이라며 사실과 다른 가정을 나타내(가정법)."),
   GN("사실 반대","as if it was a friend = 실제론 친구가 [[아닌데]] 친구인 것처럼 — 현재 사실의 반대라 과거형(was)."),
   GN("직설 대비","정말 그럴 수도 있다고 보면 as if + [[직설법]](현재)도 써 — as if they are members(2문장)처럼."),
   GN("be동사","가정법에서 was 대신 [[were]]를 쓰기도 해(as if it were a friend)."),
   GN("해석 요령","'마치 ~인 것처럼'으로 옮기되, 과거형이면 '[[실제론 아님]]'을 함께 잡아.")],
  example="",example_analysis="talking to one as if it was a friend = '마치 (동물이) 친구인 것처럼' — 실제론 친구가 아님(가정법 과거).",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 3문장 'as if it was a friend'의 의미로 알맞은 것은?",
    options=["마치 (동물이) 친구인 것처럼(실제론 아님)","동물이 친구인 것이 확실하므로","동물이 친구였는지 물으며"],answer="마치 (동물이) 친구인 것처럼(실제론 아님)"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'He talks as if he ____ everything.' (마치 다 아는 것처럼)",
    options=["knew","knows","know"],answer="knew"),
   GrammarDrill(kind="객관식",from_passage=False,question="'She acts as if she were a queen.'의 뜻으로 알맞은 것은?",
    options=["그녀는 마치 여왕인 것처럼 행동한다","그녀는 (예전에) 여왕이었다","그녀는 여왕이 되고 싶어 한다"],answer="그녀는 마치 여왕인 것처럼 행동한다"),
   GrammarDrill(kind="영작",from_passage=False,question="그는 마치 나를 모르는 것처럼 행동했다.",answer="He acted as if he did not know me."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 3문장 일부) 그들은 마치 그것이 친구인 것처럼 그것에게 말하는 것을 고려하지 않을 것이다.",
    answer="They wouldn't think of talking to one as if it was a friend.")]),
 topic="인간이 사회적 유대를 맺는 대상은 반려동물, 유골, 심지어 무생물까지 포함할 만큼 유연하다는 글이야.",
 stance="중립적",stance_reason="사회적 집단을 정의하는 기준이 유연함을 다양한 사례로 설명하는 정보 전달문이야.",
 structure="주장→근거·예시",structure_reason="'사회적 집단의 정의가 유연하다'는 주장(1문장) 뒤, 반려동물·유골·무생물이라는 사례(2~5문장)로 뒷받침해.",
 restatement_chains=[RestatementChain(label="유연한 유대 대상",
   expressions=["defining what should be part of that social group appears to be rather flexible","attribute certain human characteristics to non-human objects or beings"],
   variation="'사회 집단의 정의가 유연함' → '인간이 아닌 대상에 인간 특성을 부여함'으로 이어져."),
  RestatementChain(label="대상의 확장",
   expressions=["treat their pets as if they are members of their family","the ashes of a deceased loved one","non-human objects or beings, such as pets, dolls or even cars"],
   variation="'반려동물을 가족처럼' → '사망한 이의 유골' → '인형·자동차 같은 무생물'로 대상이 넓어져.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1",summary="두뇌는 강한 사회적 유대를 위해 진화했지만, 무엇을 그 집단에 넣을지는 다소 유연하다.",easy_example="누구·무엇을 '내 사람'으로 볼지가 사람마다 다른 것."),
  FlowBlock(stage="사례-반려동물",sentence_range="2~3",summary="어떤 이는 반려동물을 가족처럼 대하고, 다른 이는 동물을 인간과 별개로 봐 친구처럼 말하지 않는다.",easy_example="반려동물을 가족으로 보느냐 마느냐의 차이."),
  FlowBlock(stage="사례-무생물",sentence_range="4~5",summary="많은 이가 고인의 유골을 곁에 두고, 무생물이어도 인형·자동차 같은 대상에 인간의 특성을 부여한다.",easy_example="물건에도 사람 같은 마음을 붙이는 것.")])
i2=[S(r2,1,[("조동사+완료 might have evolved","'진화했을 수도 있다'"),("관계대명사 what","'~하는 것'(defining의 목적어)"),("대조 but","'하지만'")],
  [("evolve","진화하다"),("social bond","사회적 유대"),("flexible","유연한")],
  [("Our complex brains might have evolved to establish strong social bonds,","우리의 복잡한 두뇌는 강한 사회적 유대를 형성하도록 진화했을 수 있지만,"),
   ("but [[defining what should be part of that social group]]","하지만 [[무엇이 그 사회적 집단의 일부가 되어야 하는지 정의하는 것은]]"),
   ("appears to be rather [[flexible]].","다소 [[유연해]] 보인다.")],
  [("이 문장은 사회적 집단의 정의가 고정적이라는 내용이다.","'defining what should be part of that social group appears to be rather flexible(정의가 다소 유연)'이라는 주제야 — 고정이 아니라 유연해.")]),
 S(r2,2,[("as if 직설","as if they are members — 사실일 수도 있다고 봄"),("병렬 needs, desires, fears and dreams","명사 병렬")],
  [("treat","대하다"),("relate to","~을 이해·공감하다"),("desire","욕구")],
  [("For instance, some people treat their pets [[as if they are members of their family]],","예를 들어, 어떤 사람들은 반려동물을 [[마치 가족 구성원인 것처럼]] 대하고,"),
   ("and believe they can [[relate to the pets' needs, desires, fears and dreams]].","반려동물의 [[필요·욕구·두려움·꿈을 이해할]] 수 있다고 믿는다.")],
  [("어떤 사람들은 반려동물을 가족과 전혀 다르게 대한다는 내용이다.","'treat their pets as if they are members of their family(가족 구성원처럼 대한다)'는 거야 — 다르게가 아니라 가족처럼 대해.")]),
 S(r2,3,[("as if 가정법","as if it was a friend — 마치 ~인 것처럼(사실 반대, ⑤)"),("과거분사 distinct from","'~와 별개인'")],
  [("distinct from","~와 별개의")],
  [("Others see animals as [[distinct from humans]]","다른 이들은 동물을 [[인간과 별개로]] 여기고"),
   ("and wouldn't think of talking to one [[as if it was a friend]].","마치 [[그것이 친구인 것처럼]] 말하는 것을 고려하지 않을 것이다.")],
  [("이 문장은 앞 사람들과 같은 태도를 반복하는 문장이다.","'Others see animals as distinct ... wouldn't ... as if it was a friend(동물을 별개로 봄)'로 앞과 '대조'되는 다른 태도를 제시하는 문장이야.")]),
 S(r2,4,[("분사구문 believing","'~라고 믿으면서'"),("과거분사 deceased","'사망한'")],
  [("ashes","유골, 재"),("deceased","사망한"),("existence","존재")],
  [("Many people keep the [[ashes]] of a deceased loved one nearby,","많은 이들은 사망한 사랑하는 사람의 [[유골]]을 가까이 두는데,"),
   ("[[believing those ashes continue to serve as some link to their existence]].","[[그 유골이 그들의 존재를 잇는 연결고리 역할을 계속한다고 믿으면서]].")],
  [("(지칭) 'their existence'의 their는 유골(ashes)을 가리킨다.","지칭 오인이야. their는 'a deceased loved one(사망한 사랑하는 사람)'을 가리켜 — 유골이 그 사람의 존재를 이어 준다고 믿는 거야.")]),
 S(r2,5,[("양보 even if","'설령 ~일지라도'"),("attribute A to B","'A를 B의 특성으로 돌리다'")],
  [("inanimate","무생물의"),("attribute","(특성을) 부여하다"),("memorabilia","기념품")],
  [("Even if inanimate objects don't have a distinct personality,","설령 무생물이 뚜렷한 개성이 없더라도,"),
   ("many of us still [[attribute certain human characteristics to non-human objects or beings]], such as pets, dolls or even cars and memorabilia.","우리 중 많은 이가 여전히 [[인간이 아닌 사물·존재에 인간의 특성을 부여한다]], 반려동물·인형·심지어 자동차·기념품처럼.")],
  [("(함축) 무생물은 개성이 없으므로 사람들은 인간 특성을 전혀 부여하지 않는다.","함축을 놓쳤어. 'Even if inanimate ... still attribute certain human characteristics(무생물이어도 인간 특성을 부여)'라며 유대 대상이 매우 유연함을 못 박는 마무리야.")])]

# ============ Unit10-2 : 교제·유대 갈망 (병렬구조) ============
r3=["Although the wish to be alone is often strong, its intensity varies from person to person.",
"An equally impelling impulse, though, is to seek the company of others and to spend extended periods of time sharing activities.",
"In these periods we exchange information and feelings in both conversational and non-verbal forms (facial expressions, eye contact, gestures, touching, and so on).",
"We need other people to provide us with love, support, approval, bodily contact, reassurance, physical help and a myriad of other practical, physical and emotional needs.",
"In a very basic sense we need others to confirm that we are there, that we exist and that we have an identity that is unique and separate from anyone else.",
"Thus, we generally cannot exist for too long without seeking companionship."]
ov3=Overview(theme_ko="자신의 존재와 정체성 확인을 위해 타인과의 교제와 유대를 갈망하는 인간의 본성",
 key_grammar=KeyGrammar(point="병렬구조 (and로 연결된 대등한 명사절·부정사)",
  source_sentence="In a very basic sense we need others to confirm that we are there, that we exist and that we have an identity that is unique and separate from anyone else.",
  explanation=[GN("쉽게 말하면","and로 이어진 [[대등한 요소]]는 형태·기능을 맞춰 나열해 — 명사절은 명사절끼리, 부정사는 부정사끼리."),
   GN("여기선","confirm 뒤 세 개의 [[that절]]이 병렬 — that we are there, that we exist, and that we have ~."),
   GN("반복 that","각 절 앞에 that을 [[반복]]해 '무엇을 확인하는지' 세 가지를 분명히 나눴어."),
   GN("찾는 법","and 앞뒤가 '어디부터 어디까지' 한 묶음인지 [[범위]]를 먼저 잡아."),
   GN("해석 요령","'A하고, B하며, C하는 것'처럼 나열해 순서대로 옮겨.")],
  example="",example_analysis="confirm that we are there, that we exist, and that we have an identity = '있고, 존재하며, 정체성을 가짐을 확인' — that절 3개 병렬.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 5문장에서 confirm 뒤 세 개의 that절은 문법적으로 어떤 관계인가?",
    options=["대등하게 나열된 병렬(명사절)","앞 명사를 꾸미는 관계사절","서로 원인과 결과"],answer="대등하게 나열된 병렬(명사절)"),
   GrammarDrill(kind="객관식",from_passage=False,question="병렬이 어법상 올바른 문장은?",
    options=["I like to sing, to dance, and to draw.","I like to sing, dancing, and to draw.","I like singing, to dance, and draws."],answer="I like to sing, to dance, and to draw."),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'She is kind, honest, and ____.'",
    options=["brave","bravely","bravery"],answer="brave"),
   GrammarDrill(kind="영작",from_passage=False,question="우리는 그가 정직하고 성실하며 친절하다는 것을 안다.",answer="We know that he is honest, that he is sincere, and that he is kind."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 5문장 일부) 우리는 우리가 존재하고 고유한 정체성을 가지고 있음을 확인하기 위해 다른 사람들이 필요하다.",
    answer="We need others to confirm that we exist and that we have a unique identity.")]),
 topic="혼자 있고 싶은 마음만큼이나 타인과 교제하려는 충동이 강한데, 이는 우리 존재와 정체성을 확인받기 위한 인간의 본성이라는 글이야.",
 stance="중립적",stance_reason="교제를 향한 인간의 충동과 그 심리적 이유를 설명하는 정보 전달문이야.",
 structure="주장→근거·예시",structure_reason="'혼자 있고픈 마음만큼 교제 충동도 강하다'는 주장(1~2문장) 뒤, 교류의 내용과 이유(3~5문장)를 들고 결론(6문장)을 내려.",
 restatement_chains=[RestatementChain(label="교제를 향한 충동",
   expressions=["to seek the company of others","we exchange information and feelings","without seeking companionship"],
   variation="'타인과 함께하려 함' → '정보·감정을 교환함' → '교제를 추구함'으로 이어져."),
  RestatementChain(label="타인이 필요한 이유",
   expressions=["We need other people to provide us with love","we need others to confirm that we are there, that we exist"],
   variation="'사랑 등을 줄 타인이 필요' → '존재·정체성을 확인해 줄 타인이 필요'로 심화돼.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1~2",summary="혼자 있고 싶은 마음도 강하지만, 똑같이 강한 것이 타인과 함께하려는 충동이다.",easy_example="혼자 있고 싶다가도 사람이 그리운 것."),
  FlowBlock(stage="교류",sentence_range="3",summary="함께하는 시간에 우리는 대화와 비언어적 형태 둘 다로 정보와 감정을 주고받는다.",easy_example="말과 표정·몸짓으로 소통하는 것."),
  FlowBlock(stage="이유",sentence_range="4~5",summary="타인은 사랑·지지 등 여러 필요를 채워 줄 뿐 아니라, 우리가 존재하고 고유한 정체성을 지님을 확인해 준다.",easy_example="남이 있어야 '내가 있다'는 걸 확인받는 것."),
  FlowBlock(stage="결론",sentence_range="6",summary="그래서 우리는 교제를 추구하지 않고는 오래 존재할 수 없다.",easy_example="사람 없이는 오래 못 사는 것.")])
i3=[S(r3,1,[("양보 although","'~이지만'"),("vary from person to person","'사람마다 다르다'")],
  [("intensity","강도"),("vary","다르다")],
  [("Although the [[wish to be alone]] is often strong,","[[혼자 있고 싶은 소망]]은 종종 강하지만,"),
   ("its intensity [[varies from person to person]].","그 강도는 [[사람마다 다르다]].")],
  [("혼자 있고 싶은 소망은 모든 사람에게 똑같이 강하다는 내용이다.","'its intensity varies from person to person(강도는 사람마다 다르다)'이야 — 똑같지 않아. 혼자 있고픈 소망을 소개하는 도입 문장이야.")]),
 S(r3,2,[("병렬 to seek and to spend","보어 부정사 병렬"),("분사구문 sharing","'~하면서'")],
  [("impelling","뿌리칠 수 없는"),("impulse","충동"),("extended","긴, 장기의")],
  [("An equally [[impelling impulse]], though, is","하지만 똑같이 [[뿌리칠 수 없는 충동]]은"),
   ("[[to seek the company of others and to spend extended periods of time sharing activities]].","[[다른 사람과 함께하고, 활동을 공유하며 긴 시간을 보내는 것이다]].")],
  [("이 문장은 혼자 있고 싶은 소망을 계속 설명하는 문장이다.","'An equally impelling impulse ... is to seek the company of others(똑같이 강한, 남과 함께하려는 충동)'로 반대 충동으로 전환하는 문장이야.")]),
 S(r3,3,[("both A and B","'A와 B 둘 다'")],
  [("exchange","교환하다"),("non-verbal","비언어적인"),("gesture","몸짓")],
  [("In these periods we [[exchange information and feelings]]","이 시간 동안 우리는 [[정보와 감정을 교환한다]]"),
   ("in both conversational and [[non-verbal]] forms (facial expressions, eye contact, gestures, touching, and so on).","대화와 [[비언어적]] 형태(표정·눈맞춤·몸짓·접촉 등) 둘 다로.")],
  [("이 시간 동안 우리는 오직 말로만 정보를 교환한다는 내용이다.","'in both conversational and non-verbal forms(대화와 비언어 둘 다로)'라고 했어 — 말로만이 아니라 표정·몸짓으로도 교환해.")]),
 S(r3,4,[("부정사 to provide","'제공할'(other people 수식)"),("병렬 명사 나열","love, support, approval ...")],
  [("approval","인정"),("reassurance","안심"),("a myriad of","무수히 많은")],
  [("We need other people to [[provide us with love, support, approval, bodily contact, reassurance, physical help]]","우리는 [[사랑·지지·인정·신체 접촉·안심·신체적 도움]]을 제공해 줄 다른 사람이 필요하다"),
   ("and [[a myriad of]] other practical, physical and emotional needs.","그리고 [[무수한]] 다른 실질적·신체적·정서적 필요를.")],
  [("(지칭) 'provide us with'의 us는 다른 사람들(other people)을 가리킨다.","지칭 오인이야. us는 '우리(글의 화자·인간)'를 가리켜 — 다른 사람들이 '우리'에게 사랑·지지를 제공한다는 뜻이야.")]),
 S(r3,5,[("병렬구조 that절","confirm that ~, that ~, and that ~ (명사절 병렬, ⑤)"),("관계사 that","identity 수식")],
  [("confirm","확인하다"),("identity","정체성"),("separate from","~와 구별되는")],
  [("In a very basic sense we need others to confirm","아주 기본적으로 우리는 확인해 줄 다른 이가 필요하다"),
   ("[[that we are there, that we exist and that we have an identity]]","[[우리가 있고, 존재하며, 정체성을 가진다는 것을]]"),
   ("that is unique and [[separate from anyone else]].","다른 누구와도 고유하고 [[구별되는]].")],
  [("(함축) 우리는 오직 실용적 도움 때문에만 타인을 필요로 한다.","함축을 놓쳤어. 'confirm that we are there, that we exist and that we have an identity(존재·정체성 확인)'라며 실용적 도움을 넘어 '존재 확인'을 위해 타인이 필요하다는 뜻이야.")]),
 S(r3,6,[("too ~ (부정 뉘앙스) for too long","'너무 오래'"),("전치사+동명사 without seeking","'~을 추구하지 않고서는'")],
  [("companionship","교제, 동반")],
  [("Thus, we generally cannot exist for [[too long]]","따라서 우리는 일반적으로 [[너무 오래]] 살아갈 수 없다"),
   ("without [[seeking companionship]].","[[교제를 추구하지]] 않고서는.")],
  [("이 문장은 우리가 교제 없이도 얼마든지 오래 살 수 있다는 내용이다.","'cannot exist for too long without seeking companionship(교제 없이는 오래 존재 못 함)'이라는 결론이야 — 교제가 필수라는 뜻이야.")])]

P_u10a=finalize(build("유아의 잦은 두려움이 탐색 기회 감소로 사회성 발달을 늦추는 영향",S10,"Unit10-ANALYSIS",r1,ov1,i1))
P_u101=finalize(build("반려동물·무생물까지 포함하는 인간의 유연한 사회적 유대 대상",S10,"Unit10-1",r2,ov2,i2))
P_u102=finalize(build("존재와 정체성 확인을 위해 타인과의 교제를 갈망하는 인간의 본성",S10,"Unit10-2",r3,ov3,i3))
CH04U10=[P_u10a,P_u101,P_u102]
