# -*- coding: utf-8 -*-
"""EBS 올림포스 영어독해 기본1 Ch04 Unit12 (ANALYSIS/1/2/3 + 서술형 Practice) 강의컨셉 교재."""
import sys, random
sys.path.insert(0, "/home/user/english_data_making")
from src.lecture_schemas import (Chunk, FlowBlock, GrammarChip, GrammarDrill,
    GrammarNote, KeyGrammar, LecturePassage, LectureSentence, Misread,
    Overview, RestatementChain, SentenceAnalysis, SentenceItem, Vocab)
from src.lecture_render import render_lecture_pdf
import fitz
BASE="/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad"
SRC="EBS 올림포스 영어독해 기본1 · Ch04 Unit12"
def mk(r): return [LectureSentence(id=i,text=t) for i,t in enumerate(r,1)]
def S(r,i,g,v,c,m): return SentenceItem(id=i,english=r[i-1],
    grammar=[GrammarChip(tag=a,note=b) for a,b in g],
    vocab=[Vocab(word=w,meaning=k) for w,k in v],
    chunks=[Chunk(en=e,ko=k) for e,k in c],
    misreads=[Misread(statement=s,why=w) for s,w in m])
def GN(c,t): return GrammarNote(chip=c,text=t)
def build(title,no,r,ov,items):
    p=LecturePassage(title=title,source=SRC,item_no=no,sentences=mk(r),
        overview=ov,analysis=SentenceAnalysis(sentences=items)); p.analysis.validate_all(len(r)); return p
def tok(a):
    ws=[w.strip('.,;:!?\"()“”') for w in a.split()]; ws=[w for w in ws if w]
    random.Random(len(a)+sum(map(ord,a[:8]))).shuffle(ws); return ws
_MCQ=[1]  # 객관식 정답 위치 분산 카운터
def finalize(p, dedup):
    TRIV=('전치사구','부사구','부사 ','부사(','의문문','명령문','콜론')
    for s in p.analysis.sentences:
        s.grammar=[g for g in s.grammar if not any(t in g.tag for t in TRIV)]
    for d in p.overview.key_grammar.drills:
        if d.kind=='영작': d.words=tok(d.answer)
        if d.kind=='객관식' and d.options:
            others=[o for o in d.options if o!=d.answer]
            pos=_MCQ[0]%len(d.options); d.options=others[:]; d.options.insert(pos,d.answer)
        _MCQ[0]+=1
    return p
def out(p,stem):
    render_lecture_pdf([p],f"{BASE}/{stem}_student.pdf",teacher=False)
    render_lecture_pdf([p],f"{BASE}/{stem}_teacher.pdf",teacher=True)
    d=fitz.open(f"{BASE}/{stem}_student.pdf"); print(stem,d.page_count,'p'); d.close()

# ================= Unit12-ANALYSIS : 전기차·청각 (이중부정) =================
r1=["Vision is our dominant sense, and you want to look both ways before crossing the street — it's the first thing parents drill into their children.",
"But that doesn't mean our sense of hearing isn't a big deal.",
"I don't have to mention the worn-out example of cavemen and hidden saber-toothed tigers.",
"There's something that can sneak up and kill you today: a silent electric car.",
"These pose an unanticipated but serious threat to pedestrians and bicyclists, who depend on engine noise to detect and orient to cars — so much so that the National Highway Traffic Safety Administration now requires slow-moving electric vehicles to generate a warning noise.",
"It's a reminder that even for us in a modern city, having both cues can mean the difference between life and death."]
ov1=Overview(theme_ko="시각이 지배적 감각이지만 조용한 전기차 시대에 생존을 좌우하는 청각 정보의 중요성",
 key_grammar=KeyGrammar(point="이중부정 (부정어 + 부정어 = 강한 긍정)",
  source_sentence="But that doesn't mean our sense of hearing isn't a big deal.",
  explanation=[GN("쉽게 말하면","부정어가 두 번 나오면 서로 상쇄돼 결국 '[[강한 긍정]]'이 돼 — doesn't … isn't = 결국 '중요하다'."),
   GN("구조","doesn't mean (that) our hearing [[isn't]] a big deal — mean 뒤 that절 안에 또 부정(isn't)이 숨어 있어."),
   GN("의미","'청각이 중요하지 않다는 뜻이 아니다' = 결국 '청각도 [[중요하다]]'는 강조야."),
   GN("함정","부정 하나만 보고 '청각은 중요하지 않다'로 읽으면 [[정반대]]로 오역해 — 두 부정을 함께 봐야 해."),
   GN("해석 요령","부정+부정이 보이면 '[[결국 ~다]]'라는 긍정으로 정리해.")],
  example="",example_analysis="doesn't mean … isn't a big deal = '중요하지 않다는 뜻이 아니다' → '청각도 매우 중요하다'는 강한 긍정.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 2문장 'that doesn't mean our sense of hearing isn't a big deal'의 의미로 알맞은 것은?",
    options=["우리의 청각도 (그에 못지않게) 중요하다는 뜻이다","우리의 청각은 중요하지 않다는 뜻이다","시각과 청각 모두 중요하지 않다는 뜻이다"],
    answer="우리의 청각도 (그에 못지않게) 중요하다는 뜻이다"),
   GrammarDrill(kind="객관식",from_passage=False,question="'It is not true that he cannot swim.'의 뜻으로 알맞은 것은?",
    options=["그는 수영을 할 수 있다","그는 수영을 전혀 못한다","그가 수영한다는 것은 사실이 아니다"],answer="그는 수영을 할 수 있다"),
   GrammarDrill(kind="객관식",from_passage=False,question="'You can't say she isn't talented.'가 의미하는 바로 알맞은 것은?",
    options=["그녀는 재능이 있다","그녀는 재능이 없다","그녀의 재능은 알 수 없다"],answer="그녀는 재능이 있다"),
   GrammarDrill(kind="영작",from_passage=False,question="그것이 그가 관심 없다는 뜻은 아니다.",
    answer="That doesn't mean he isn't interested."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 2문장) 그러나 그것이 우리의 청각이 중요하지 않다는 뜻은 아니다.",
    answer="But that doesn't mean our sense of hearing isn't a big deal.")]),
 topic="시각이 지배적 감각이지만, 조용한 전기차가 등장한 오늘날 청각 정보 역시 생존에 필수적이라는 글이야.",
 stance="긍정적",stance_reason="청각 정보의 가치를 'big deal'·'life and death'로 강조하며 그 필요성을 적극적으로 인정해.",
 structure="통념→반박(반전)",structure_reason="'시각이 지배적 감각'이라는 통념(1문장) 뒤 'But 청각도 중요하다'로 반박(2문장)하고, 조용한 전기차 사례로 뒷받침해.",
 restatement_chains=[RestatementChain(label="청각의 중요성",
   expressions=["our sense of hearing isn't a big deal","depend on engine noise","having both cues"],
   variation="'청각이 중요하다' → '엔진 소리에 의존' → '두 신호를 다 받음'으로 구체화돼."),
  RestatementChain(label="조용한 위협",
   expressions=["a silent electric car","These","slow-moving electric vehicles"],
   variation="'조용한 전기차' → 'These(이것들)' → '저속 전기차'로 이어져.")],
 flow_blocks=[FlowBlock(stage="통념",sentence_range="1",summary="시각은 우리의 지배적 감각이고, 부모가 아이에게 가장 먼저 '양쪽을 보라'고 가르친다.",easy_example="길 건널 때 좌우를 보라며 시각을 강조하는 것."),
  FlowBlock(stage="반박",sentence_range="2~3",summary="그렇다고 청각이 중요하지 않은 건 아니며, 진부한 원시시대 예를 들 필요도 없다.",easy_example="시각만이 아니라 소리도 생존에 중요하다는 반전."),
  FlowBlock(stage="사례",sentence_range="4~5",summary="오늘날엔 조용한 전기차가 몰래 다가와 위협하는데, 엔진 소리에 의존하는 보행자에게 위험해 당국은 경고음을 의무화했다.",easy_example="소리가 없으니 위험 → 일부러 경고음을 내게 함."),
  FlowBlock(stage="결론",sentence_range="6",summary="현대 도시에서도 시각·청각 두 신호를 다 받는 것이 삶과 죽음을 가를 수 있다.",easy_example="보는 것과 듣는 것 둘 다 있어야 안전한 것.")])
i1=[S(r1,1,[("관계사 생략(목적격)","the first thing (that) parents drill — that 생략")],
  [("dominant","지배적인"),("drill (A into B)","(반복해) 주입하다·훈련시키다")],
  [("Vision is our [[dominant]] sense,","시각은 우리의 [[지배적인]] 감각이고,"),
   ("and you want to [[look both ways]] before crossing the street","길을 건너기 전에 [[양쪽을 다 보려]] 하는데,"),
   ("— [[it's the first thing parents drill into their children]].","— [[그것은 부모가 아이들에게 처음으로 주입하는 것이다]].")],
  [("시각은 우리 감각 중 그다지 중요하지 않은 감각이라는 내용이다.","'dominant sense(지배적 감각)'라고 했어 — 시각이 가장 중요하게 여겨진다는 거야(그 위에서 청각도 중요하다고 이어져).")]),
 S(r1,2,[("명사절 that","mean의 목적어절(that 생략)")],
  [("a big deal","중요한 것, 큰일")],
  [("But that doesn't mean","그러나 그것이 (~라는) 뜻은 아니다"),
   ("[[our sense of hearing isn't a big deal]].","[[우리의 청각이 중요하지 않다는]].")],
  [("이 문장은 시각이 청각보다 중요하다는 앞 내용을 한 번 더 강조하는 문장이다.","'But(그러나)'으로 방향을 틀어 '청각도 중요하다'는 이 글의 주제를 꺼내는 전환·주장 문장이야.")]),
 S(r1,3,[("don't have to","~할 필요가 없다")],
  [("worn-out","진부한, 낡은"),("caveman","원시인"),("saber-toothed","검치(칼 같은 송곳니)의")],
  [("I [[don't have to mention]]","나는 [[언급할 필요가 없다]]"),
   ("the [[worn-out]] example of cavemen and hidden saber-toothed tigers.","원시인과 숨어 있는 검치호랑이라는 [[진부한]] 예를.")],
  [("(함축) 필자는 원시인·검치호랑이 예가 청각의 중요성을 잘 보여줘서 자세히 설명하려 한다.","함축을 놓쳤어. 'don't have to mention the worn-out example(진부한 예는 언급할 필요도 없다)'은 그 예를 생략하고 더 현대적인 예로 넘어가겠다는 뜻이야.")]),
 S(r1,4,[("관계사 that","something 수식")],
  [("sneak up","몰래 다가오다")],
  [("[[There's something that can sneak up and kill you today]]:","[[오늘날 몰래 다가와 여러분을 죽일 수 있는 무언가가 있다]]:"),
   ("a [[silent]] electric car.","바로 [[조용한]] 전기차다.")],
  [("이 문장은 앞의 원시시대 예를 계속 부연하는 문장이다.","'today(오늘날)'의 '조용한 전기차'라는 현대적 위협 사례로 넘어가는 전환 문장이야 — 콜론 뒤에서 그 정체를 밝혀.")]),
 S(r1,5,[("계속적 용법 who","pedestrians and bicyclists 부연"),("so much so that","'그 정도가 심해서 (결과)'")],
  [("unanticipated","예상치 못한"),("pedestrian","보행자"),("orient to","~로 방향을 잡다")],
  [("These pose an [[unanticipated]] but serious threat to pedestrians and bicyclists,","이것들은 보행자와 자전거 이용자에게 [[예상치 못한]], 그러나 심각한 위협을 제기하는데,"),
   ("[[who depend on engine noise to detect and orient to cars]]","[[그들은 차를 감지하고 방향을 잡기 위해 엔진 소리에 의존한다]]"),
   ("— so much so that the [[National Highway Traffic Safety Administration]]","— 그 정도가 심해서 미국 [[고속도로교통안전국]]이"),
   ("now requires slow-moving electric vehicles to generate a [[warning noise]].","이제 저속 전기차가 [[경고음]]을 내도록 요구할 정도다.")],
  [("(지칭) 'These'는 앞 문장의 보행자와 자전거 이용자를 가리킨다.","지칭 오인이야. These는 앞의 '조용한 전기차(a silent electric car)'를 가리켜 — 전기차가 보행자·자전거 이용자에게 위협이라는 거야.")]),
 S(r1,6,[("동격 that","a reminder 뒤 내용 부연"),("동명사 주어","having both cues")],
  [("cue","신호, 단서"),("reminder","상기시키는 것")],
  [("It's a [[reminder]] that even for us in a modern city,","그것은 현대 도시의 우리에게도 [[상기시켜]] 주는 것이다,"),
   ("[[having both cues can mean the difference between life and death]].","[[두 신호를 다 갖는 것이 삶과 죽음의 차이를 의미할 수 있다는 것을]].")],
  [("이 문장은 새로운 위험 사례를 하나 더 추가하는 문장이다.","'It's a reminder that …(~을 상기시킨다)'로 글 전체를 마무리하는 결론 문장이야 — 시각·청각 두 신호가 생사를 가른다는 요지.")])]

# ================= Unit12-1 : 음식 조리법 변화 (병렬구조) =================
r2=["Sometimes traditions may change or appear to end because of convenience or changes in taste.",
"For example, to make a pumpkin pie, a cook used to have to first find a pumpkin of suitable size, cut it, peel it, cook it, and mash it, all before combining it with other ingredients and pouring the mixture into a crust.",
"Now, cooks may choose to use canned pumpkin from the supermarket and cut out a great deal of labor and time.",
"Another changing food tradition is that many families no longer make refried beans by cooking them in lard and choose instead to use vegetable shortening.",
"Perhaps this change came about because the family has come to prefer the taste of beans without lard, because concepts of healthy cooking have changed, or because someone in the family has heart disease or high cholesterol."]
ov2=Overview(theme_ko="편의성·건강·취향의 변화로 인해 달라지거나 사라지는 것처럼 보이는 음식 조리법과 전통",
 key_grammar=KeyGrammar(point="병렬구조 (등위접속사 and/or로 연결된 대등한 요소)",
  source_sentence="a cook used to have to first find a pumpkin of suitable size, cut it, peel it, cook it, and mash it",
  explanation=[GN("쉽게 말하면","and/or는 문법적으로 [[대등한 것]]끼리 연결해 — 동사원형은 동사원형끼리, 명사는 명사끼리."),
   GN("찾는 법","and 앞뒤를 보고 '무엇과 무엇을 묶었나'를 확인해 — find … cut … peel … cook … and [[mash]] 는 모두 동사원형."),
   GN("공통 요소","앞의 조동사·전치사가 뒤 항목에도 [[똑같이]] 적용돼 — (used to have to) find/cut/peel/cook/mash."),
   GN("주의","연결된 항목의 [[형태·시제]]가 어긋나면 병렬이 깨진 오류야(cut → cutting X)."),
   GN("해석 요령","and를 만나면 '어디부터 어디까지'가 한 묶음인지 [[범위]]를 먼저 잡고 순서대로 옮겨.")],
  example="",example_analysis="find … cut it, peel it, cook it, and mash it = '(used to have to)'가 다섯 동사원형에 공통으로 걸린 병렬.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 2문장 'cut it, peel it, cook it, and mash it'에서 and로 연결된 요소들의 공통점은?",
    options=["모두 (used to have to에 걸리는) 동사원형이다","모두 명사이다","모두 형용사이다"],
    answer="모두 (used to have to에 걸리는) 동사원형이다"),
   GrammarDrill(kind="객관식",from_passage=False,question="병렬이 어법상 올바른 문장은?",
    options=["She likes to read, write, and draw.","She likes to read, writing, and draw.","She likes reading, to write, and draws."],
    answer="She likes to read, write, and draw."),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'He washed, dried, and ____ the dishes.'",
    options=["stacked","stacking","to stack"],answer="stacked"),
   GrammarDrill(kind="영작",from_passage=False,question="그는 채소를 씻고 자르고 요리했다.",
    answer="He washed, cut, and cooked the vegetables."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 3문장) 이제 요리사들은 슈퍼마켓의 통조림 호박을 사용해 많은 노동과 시간을 줄일 수 있다.",
    answer="Now, cooks may choose to use canned pumpkin from the supermarket and cut out a great deal of labor and time.")]),
 topic="전통이 편의성·건강·취향의 변화 때문에 달라지거나 사라지는 것처럼 보이는 현상을, 호박파이와 콩 요리로 보여 주는 글이야.",
 stance="중립적",stance_reason="음식 전통이 왜 변하는지를 사실·예시 중심으로 설명하는 정보 전달문이야.",
 structure="주장→근거·예시",structure_reason="'전통은 편의·취향으로 변한다'는 일반 진술(1문장) 뒤, 호박파이(2~3문장)와 콩 요리(4~5문장) 두 예시로 뒷받침해.",
 restatement_chains=[RestatementChain(label="변화의 이유",
   expressions=["convenience or changes in taste","cut out a great deal of labor and time","concepts of healthy cooking have changed"],
   variation="'편의성·취향' → '노동·시간 절약' → '건강 요리 개념 변화'로 이유가 구체화돼."),
  RestatementChain(label="달라진 조리법",
   expressions=["appear to end","use canned pumpkin","use vegetable shortening"],
   variation="'끝난 것처럼 보임' → '통조림 호박 사용' → '식물성 쇼트닝 사용'으로 변화가 이어져.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1",summary="때로 전통은 편의성이나 취향 변화 때문에 바뀌거나 끝난 것처럼 보인다.",easy_example="번거롭거나 입맛이 바뀌면 전통 방식이 슬쩍 달라지는 것."),
  FlowBlock(stage="예시1-과거",sentence_range="2",summary="예전엔 호박파이를 만들려면 호박을 찾아 자르고 껍질 벗기고 익히고 으깨는 모든 과정을 거쳐야 했다.",easy_example="처음부터 생호박을 손질하던 옛 방식."),
  FlowBlock(stage="예시1-현재",sentence_range="3",summary="이제는 통조림 호박을 써서 많은 노동과 시간을 줄일 수 있다.",easy_example="통조림 하나로 손질 과정을 건너뛰는 것."),
  FlowBlock(stage="예시2",sentence_range="4",summary="또 다른 변화로, 많은 가정이 돼지기름 대신 식물성 쇼트닝으로 콩 요리를 만든다.",easy_example="라드 대신 식물성 기름을 쓰는 것."),
  FlowBlock(stage="이유",sentence_range="5",summary="이 변화는 라드 없는 맛 선호, 건강 요리 개념 변화, 가족의 건강 문제 때문일 수 있다.",easy_example="맛·건강·질병 등 여러 이유로 방식이 바뀐 것.")])
i2=[S(r2,1,[("조동사 may","'~일 수도 있다'(추측)")],
  [("tradition","전통"),("convenience","편의성"),("appear to","~인 것처럼 보이다")],
  [("Sometimes traditions may change or [[appear to end]]","때로 전통은 바뀌거나 [[끝난 것처럼 보일]] 수 있다"),
   ("because of [[convenience]] or changes in taste.","[[편의성]]이나 취향의 변화 때문에.")],
  [("(함축) 전통이 'appear to end'라는 것은 그 전통이 실제로 완전히 사라졌다는 뜻이다.","함축을 놓쳤어. 'appear to end(끝난 것처럼 보인다)'는 실제 소멸이 아니라 '변형됐을 뿐'일 수 있음을 암시해 — 뒤 예시들이 '방식만 달라졌음'을 보여줘.")]),
 S(r2,2,[("used to","(과거엔) ~하곤 했다"),("부정사 to make","'~하기 위해'")],
  [("suitable","적당한, 알맞은"),("peel","껍질을 벗기다"),("mash","으깨다"),("ingredient","재료"),("crust","(파이) 껍질")],
  [("For example, to make a pumpkin pie, a cook used to have to first","예를 들어, 호박 파이를 만들려면, 요리사는 먼저 ~해야만 했다"),
   ("[[find a pumpkin of suitable size, cut it, peel it, cook it, and mash it]],","[[적당한 크기의 호박을 찾아 자르고, 껍질을 벗기고, 익히고, 으깨는 것을]],"),
   ("all before combining it with other ingredients and pouring the mixture into a [[crust]].","다른 재료와 섞어 혼합물을 [[파이 껍질]]에 붓기 전에 그 모든 것을.")],
  [("예전 호박파이 조리는 통조림 호박만 있으면 간단히 끝났다는 내용이다.","'find … cut … peel … cook … and mash(찾아 자르고 벗기고 익히고 으깨기)'라는 긴 과정을 다 거쳐야 했다는 거야 — 과거의 번거로움을 강조해.")]),
 S(r2,3,[("조동사 may","'~할 수도 있다'(선택 가능)")],
  [("canned","통조림으로 된"),("cut out","없애다, 줄이다"),("a great deal of","많은")],
  [("Now, cooks may choose to use [[canned]] pumpkin from the supermarket","이제 요리사들은 슈퍼마켓의 [[통조림]] 호박을 쓰기로 선택해"),
   ("and [[cut out a great deal of labor and time]].","[[많은 노동과 시간을 줄일]] 수 있다.")],
  [("이 문장은 앞의 과거 조리법을 다시 설명하는 문장이다.","'Now(이제)'로 시작해 과거(2문장)와 대비되는 '현재'의 간편한 방식으로 넘어가는 대조·전환 문장이야.")]),
 S(r2,4,[("명사절 that","is의 보어"),("no longer","더 이상 ~ 않다"),("instead","대신에")],
  [("refried beans","(다시 튀긴) 콩 요리"),("lard","돼지기름, 라드"),("shortening","쇼트닝(제과용 유지)")],
  [("Another changing food tradition is","변화하고 있는 또 다른 음식 전통은"),
   ("[[that many families no longer make refried beans by cooking them in lard]]","[[많은 가정이 더 이상 콩을 돼지기름에 조리해 만들지 않고]]"),
   ("and choose instead to use vegetable [[shortening]].","대신 식물성 [[쇼트닝]]을 쓰기로 한다는 것이다.")],
  [("(지칭) 'them'은 여러 가정(families)을 가리킨다.","지칭 오인이야. cooking them in lard의 them은 앞의 'refried beans(콩)'를 가리켜 — 콩을 라드에 조리한다는 뜻이야.")]),
 S(r2,5,[("이유 because(병렬)","because A, because B, or because C"),("came about","생겨나다")],
  [("come to prefer","~을 선호하게 되다"),("cholesterol","콜레스테롤"),("heart disease","심장병")],
  [("Perhaps this change came about because the family has come to [[prefer]] the taste of beans without lard,","아마 이 변화는 가족이 라드 없는 콩의 맛을 [[선호하게]] 되었거나,"),
   ("because concepts of [[healthy cooking]] have changed,","[[건강한 요리]]에 대한 개념이 바뀌었거나,"),
   ("or because someone in the family has heart disease or high [[cholesterol]].","가족 중 누군가가 심장병이나 높은 [[콜레스테롤]]이 있기 때문일 수 있다.")],
  [("변화의 원인은 오직 맛의 선호 하나뿐이라는 내용이다.","'because A, because B, or because C'로 맛·건강 개념·질병이라는 여러 이유를 나란히 제시해 — 원인이 하나가 아니야.")])]

# ================= Unit12-2 : 시장 기능과 자원 (분사구문) =================
r3=["Forecasters who predict resource depletion often ignore or underestimate the power of markets.",
"For example, some forecasters use a current reserve index to estimate how long a resource would last.",
"The current reserve index divides the current known reserve of a resource by the amount currently used each period.",
"So, if we know of 445 billion barrels of oil, and we are currently using 15 billion barrels per year, the index indicates that we will run out of oil in about 30 years.",
"Some studies, like the Limits to Growth, further assume that demand will increase each year, thus depleting resources even faster.",
"But what they fail to see is that if markets are allowed to do their usual duty, that is, prices rise as depletion occurs, resources will last much longer."]
ov3=Overview(theme_ko="자원 고갈 예측이 간과하는, 가격 상승으로 소비를 억제하고 보존을 유도하는 시장 기능의 힘",
 key_grammar=KeyGrammar(point="선행사를 포함하는 관계대명사 what ('~하는 것')",
  source_sentence="But what they fail to see is that if markets are allowed to do their usual duty, that is, prices rise as depletion occurs, resources will last much longer.",
  explanation=[GN("쉽게 말하면","관계대명사 what은 선행사(the thing)를 [[자체에 포함]]해 '~하는 것'이라는 명사 덩어리를 만들어."),
   GN("복원","what they fail to see = the thing [[which]] they fail to see(그들이 보지 못하는 것) — what = the thing which."),
   GN("자리","what절은 문장에서 [[주어·목적어·보어]] 자리에 와 — 여기선 is의 '주어'(문두)."),
   GN("구별","what 뒤 문장이 [[불완전]](see의 목적어가 빔)하면 관계대명사 what, 완전하면 접속사 that·관계부사야."),
   GN("해석 요령","'~하는 것은/것을'로 what절을 하나의 명사로 묶어 읽어.")],
  example="",example_analysis="what they fail to see is that … = '그들이 보지 못하는 것은 …라는 점이다' — what절이 is의 주어.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 6문장 'what they fail to see'의 문법 설명으로 알맞은 것은?",
    options=["선행사를 포함해 '~하는 것'을 뜻하는 관계대명사 what(is의 주어)","the fact를 꾸미는 관계부사","'무엇'을 뜻하는 의문사"],
    answer="선행사를 포함해 '~하는 것'을 뜻하는 관계대명사 what(is의 주어)"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? '____ he said surprised everyone.' (그가 말한 것)",
    options=["What","That","Which"],answer="What"),
   GrammarDrill(kind="객관식",from_passage=False,question="'What matters is your effort.'의 뜻으로 알맞은 것은?",
    options=["중요한 것은 너의 노력이다","네 노력이 무엇인지 중요하다","무엇이 중요한지 노력한다"],answer="중요한 것은 너의 노력이다"),
   GrammarDrill(kind="영작",from_passage=False,question="내가 원하는 것은 약간의 휴식이다.",
    answer="What I want is some rest."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 6문장 일부) 그러나 그들이 보지 못하는 것은 자원이 훨씬 더 오래갈 것이라는 점이다.",
    answer="But what they fail to see is that resources will last much longer.")]),
 topic="자원 고갈을 예측하는 사람들이 간과하는 것, 즉 고갈 시 가격 상승으로 소비를 억제하고 자원을 오래 지속시키는 시장의 힘에 관한 글이야.",
 stance="부정적·비판적",stance_reason="예측자들이 시장의 힘을 'ignore or underestimate(무시·과소평가)'하고 'fail to see(보지 못한다)'라며 그들의 한계를 비판적으로 지적해.",
 structure="통념→반박(반전)",structure_reason="예측자들이 매장량 지수로 자원 고갈을 계산하는 통념(1~5문장) 뒤, 'But 시장의 가격 기능을 간과했다'는 반박(6문장)으로 뒤집어.",
 restatement_chains=[RestatementChain(label="고갈 예측 방식",
   expressions=["predict resource depletion","a current reserve index","run out of oil in about 30 years"],
   variation="'자원 고갈 예측' → '현재 매장량 지수' → '30년 내 석유 고갈'로 구체화돼."),
  RestatementChain(label="시장의 힘",
   expressions=["the power of markets","markets are allowed to do their usual duty","resources will last much longer"],
   variation="'시장의 힘' → '시장이 통상 기능을 함' → '자원이 훨씬 오래감'으로 이어져.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1",summary="자원 고갈을 예측하는 사람들은 흔히 시장의 힘을 무시하거나 과소평가한다.",easy_example="'자원이 곧 바닥난다'며 시장의 조절력을 빼먹는 것."),
  FlowBlock(stage="통념-방법",sentence_range="2~3",summary="그들은 현재 매장량 지수(매장량 ÷ 기간별 사용량)로 자원이 얼마나 갈지 추정한다.",easy_example="남은 양을 지금 쓰는 속도로 나눠 '몇 년 남았다'를 계산."),
  FlowBlock(stage="통념-예",sentence_range="4~5",summary="석유 4,450억 배럴을 연 150억 배럴씩 쓰면 약 30년 뒤 고갈이라 보고, 일부 연구는 수요 증가로 더 빨리 고갈된다고 본다.",easy_example="단순 계산으로 '30년, 혹은 더 빨리 끝'이라 단정하는 것."),
  FlowBlock(stage="반박",sentence_range="6",summary="그러나 그들이 못 보는 것은, 시장이 제 기능을 해 고갈이 진행되며 가격이 오르면 자원이 훨씬 더 오래간다는 점이다.",easy_example="비싸지면 덜 쓰고 대체하니 자원이 더 오래 버티는 것.")])
i3=[S(r3,1,[("관계사 who","Forecasters 수식")],
  [("forecaster","예측자, 예보자"),("depletion","고갈"),("underestimate","과소평가하다")],
  [("Forecasters who predict resource depletion","자원 고갈을 예측하는 사람들은"),
   ("often ignore or [[underestimate the power of markets]].","흔히 [[시장의 힘을 무시하거나 과소평가한다]].")],
  [("이 문장은 시장의 힘을 예측자들이 정확히 계산한다는 내용이다.","'ignore or underestimate(무시하거나 과소평가한다)'라는 비판을 던지는 주제·주장 문장이야 — 뒤에서 그 근거를 펼쳐.")]),
 S(r3,2,[("부정사 to estimate","'추정하기 위해'"),("의문사 how long","'얼마나 오래'")],
  [("reserve","매장량, 비축량"),("index","지수"),("estimate","추정하다")],
  [("For example, some forecasters use a current [[reserve index]]","예를 들어, 일부 예측자는 현재의 [[매장량 지수]]를 사용한다"),
   ("to estimate how long a resource would last.","자원이 얼마나 오래 지속될지 추정하기 위해.")],
  [("일부 예측자들은 아무 근거 없이 자원 고갈 시점을 말한다는 내용이다.","'a current reserve index(현재 매장량 지수)'라는 도구로 추정한다고 했어 — 나름의 계산 방법을 소개하는 예시야.")]),
 S(r3,3,[("divide A by B","A를 B로 나누다")],
  [("known reserve","알려진 매장량"),("amount","양"),("period","기간")],
  [("The current reserve index [[divides the current known reserve of a resource]]","현재 매장량 지수는 [[자원의 현재 알려진 매장량을 나눈다]]"),
   ("by the amount currently used each [[period]].","각 [[기간]]에 현재 사용되는 양으로.")],
  [("매장량 지수는 사용량에 매장량을 곱해 구한다는 내용이다.","'divides … by …(매장량을 사용량으로 나눈다)'가 계산법이야 — 곱하는 게 아니라 나눠서 '몇 기간 갈지'를 구해.")]),
 S(r3,4,[("조건 if","'~라면'"),("명사절 that","indicates의 목적어")],
  [("barrel","배럴"),("run out of","~을 다 써 버리다"),("indicate","나타내다")],
  [("So, if we know of 445 billion barrels of oil, and we are currently using 15 billion barrels per year,","따라서, 우리가 4,450억 배럴의 석유를 알고, 현재 연 150억 배럴을 쓰고 있다면,"),
   ("the index indicates [[that we will run out of oil in about 30 years]].","그 지수는 [[우리가 약 30년 뒤 석유를 다 써 버릴 것임을]] 나타낸다.")],
  [("(지칭) 'we'는 석유를 채굴하는 특정 기업을 가리킨다.","지칭 오인이야. 여기서 we는 지수를 계산하는 '우리(일반)'를 가리켜 — 특정 기업이 아니라 예시 계산의 주체야.")]),
 S(r3,5,[("명사절 that","assume의 목적어"),("비교급 강조 even","'훨씬 더'")],
  [("assume","가정하다"),("demand","수요"),("deplete","고갈시키다")],
  [("Some studies, like the Limits to Growth, further assume","'성장의 한계' 같은 일부 연구는 더 나아가 가정한다"),
   ("[[that demand will increase each year]],","[[수요가 매년 증가할 것이라고]],"),
   ("thus depleting resources even [[faster]].","그리하여 자원을 훨씬 더 [[빨리]] 고갈시키면서.")],
  [("(함축) 이 문장은 자원이 실제로 30년보다 더 빨리 고갈된다는 필자의 결론이다.","함축을 놓쳤어. 이건 '일부 연구(예측자들)의 가정'을 소개한 것일 뿐, 필자의 결론이 아니야 — 바로 다음 문장에서 이 비관적 계산을 반박해.")]),
 S(r3,6,[("관계사 what","'~하는 것'(주어절)"),("조건 if","'~라면'"),("that is","'즉'(부연)")],
  [("fail to","~하지 못하다"),("usual duty","통상적인 기능·의무"),("last","지속되다")],
  [("But [[what they fail to see]] is","그러나 [[그들이 보지 못하는 것은]] ~이다"),
   ("that if markets are allowed to do their [[usual duty]],","시장이 [[통상적인 기능]]을 하도록 허용되면,"),
   ("that is, prices rise as depletion occurs, resources will [[last much longer]].","즉, 고갈이 진행되며 가격이 오르면, 자원이 [[훨씬 더 오래갈]] 것이라는 점이다.")],
  [("이 문장은 예측자들의 계산이 대체로 옳다고 인정하는 문장이다.","'But what they fail to see(그러나 그들이 못 보는 것)'로 시작해 예측을 뒤집는 반박·핵심 문장이야 — 가격이 오르면 소비가 줄어 자원이 더 오래간다는 거야.")])]

# ================= Unit12-3 : 프로젝트 팀 의견차이 (양보 although) =================
r4=["Project leaders should not be surprised when disagreements emerge within the team.",
"In fact, they should expect them.",
"If they remain hidden, the leader may even want to seek them out for at least two reasons.",
"First, different views can bring with them good ideas about the project and how it might be run.",
"Although snap decisions about project changes should be avoided, leaders should be open to new and better ways to run the project.",
"Second, when conflicting viewpoints are found, they are more easily resolved earlier rather than later in the project.",
"Although team members may disagree about one or another aspect of the project, most simply want their ideas considered and resolved.",
"The team tends to look to the project leader to play the lead role in resolving differences, and members will generally defer to the leader if they believe their views have been given due consideration."]
ov4=Overview(theme_ko="프로젝트 팀 내 의견 차이의 긍정적 가치와, 이를 조기에 찾아 해결해야 하는 리더의 역할",
 key_grammar=KeyGrammar(point="양보의 접속사 although ('비록 ~일지라도')",
  source_sentence="Although snap decisions about project changes should be avoided, leaders should be open to new and better ways to run the project.",
  explanation=[GN("쉽게 말하면","although는 '비록 ~이지만'으로, 뒤 주절과 [[반대·대조]]되는 내용을 앞세워."),
   GN("구조","Although + [주어+동사]~, [주절] — although절은 '양보', 진짜 하고 싶은 말은 [[주절]]에 있어."),
   GN("핵심 잡기","although절은 한 발 물러서는 조건이고, 필자의 [[주장]]은 콤마 뒤 주절이야 — 주절을 놓치지 마."),
   GN("though/even though","although = though = even though — 다 '[[비록 ~지만]]'이야(but과 함께 쓰지 않음)."),
   GN("해석 요령","'비록 ~일지라도, (그래도) …'로 옮기고 [[주절]]의 주장을 중심으로 정리해.")],
  example="",example_analysis="Although snap decisions … should be avoided(양보), leaders should be open …(주절) = '성급한 결정은 피해야 하지만, 그래도 열려 있어야 한다'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 5문장에서 'Although snap decisions about project changes should be avoided'가 하는 역할은?",
    options=["주절과 대조되는 '양보'로, 진짜 주장은 콤마 뒤 주절에 있다","글 전체의 결론을 내리는 주절이다","앞 명사를 꾸미는 관계사절이다"],
    answer="주절과 대조되는 '양보'로, 진짜 주장은 콤마 뒤 주절에 있다"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? '____ it was raining, we went out.' (비가 왔지만 나갔다)",
    options=["Although","Because","So"],answer="Although"),
   GrammarDrill(kind="객관식",from_passage=False,question="어법상 올바른 문장은?",
    options=["Although he was tired, he kept working.","Although he was tired, but he kept working.","Because he was tired, he kept working hard."],
    answer="Although he was tired, he kept working."),
   GrammarDrill(kind="영작",from_passage=False,question="비록 그 일이 어려웠지만, 그녀는 포기하지 않았다.",
    answer="Although the task was difficult, she did not give up."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 7문장 일부) 비록 팀원들이 프로젝트의 한 측면에 대해 동의하지 않을 수 있지만, 대부분은 단지 자기 아이디어가 고려되고 해결되기를 원한다.",
    answer="Although team members may disagree about one aspect of the project, most simply want their ideas considered and resolved.")]),
 topic="프로젝트 팀 내 의견 차이가 왜 긍정적이며, 리더가 왜 그것을 조기에 찾아 해결해야 하는지에 관한 글이야.",
 stance="긍정적",stance_reason="의견 차이를 'good ideas'를 가져오는 것으로 보고, 리더가 이를 예상·환영·해결해야 한다고 그 가치를 적극 인정해.",
 structure="주장→근거·예시",structure_reason="'리더는 이견을 예상·환영해야 한다'는 주장(1~3문장) 뒤, 두 가지 이유(4·6문장)와 팀 역학·리더 역할(7~8문장)로 뒷받침해.",
 restatement_chains=[RestatementChain(label="의견 차이",
   expressions=["disagreements","different views","conflicting viewpoints"],
   variation="'이견' → '다양한 견해' → '상충하는 관점'으로 표현이 바뀌며 이어져."),
  RestatementChain(label="리더의 대응",
   expressions=["seek them out","be open to new and better ways","play the lead role in resolving differences"],
   variation="'이견을 찾아냄' → '새 방법에 열려 있음' → '해결에 주도적 역할'로 구체화돼.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1~2",summary="리더는 팀 내 이견에 놀라지 말고 오히려 예상해야 한다.",easy_example="갈등이 생겨도 당연한 일로 받아들이는 태도."),
  FlowBlock(stage="전개예고",sentence_range="3",summary="이견이 숨어 있다면 리더는 적어도 두 가지 이유로 그것을 찾아내려 할 수 있다.",easy_example="드러나지 않은 불만도 일부러 끄집어내려는 것."),
  FlowBlock(stage="이유1",sentence_range="4~5",summary="첫째, 다양한 견해는 좋은 아이디어를 주므로, 성급한 결정은 피하되 리더는 더 나은 방법에 열려 있어야 한다.",easy_example="다른 의견에서 더 좋은 운영법이 나올 수 있는 것."),
  FlowBlock(stage="이유2",sentence_range="6",summary="둘째, 상충하는 관점은 프로젝트 나중보다 이른 시기에 더 쉽게 해결된다.",easy_example="문제는 초반에 잡아야 풀기 쉬운 것."),
  FlowBlock(stage="결론",sentence_range="7~8",summary="팀원은 대개 자기 의견이 고려·해결되길 원하며, 자기 의견이 충분히 고려됐다고 믿으면 리더의 주도적 해결을 따른다.",easy_example="내 말이 존중받았다고 느끼면 리더 결정을 받아들이는 것.")])
i4=[S(r4,1,[("접속사 when","'~할 때'"),("감정 형용사 surprised","should not be surprised: 조동사+원형, surprised는 감정 형용사")],
  [("disagreement","의견 차이, 이견"),("emerge","나타나다, 부상하다")],
  [("Project leaders should [[not be surprised]]","프로젝트 리더는 [[놀라지 말아야]] 한다"),
   ("when disagreements emerge within the team.","팀 내에서 이견이 나타날 때.")],
  [("이 문장은 리더가 이견을 억눌러야 한다고 조언하는 문장이다.","'should not be surprised(놀라지 말라)'로 이견을 자연스러운 것으로 받아들이라는, 글의 주제·주장 문장이야.")]),
 S(r4,2,[("대명사 them","= disagreements(이견)")],
  [("in fact","사실은"),("expect","예상하다")],
  [("In fact, they should [[expect them]].","사실, 그들은 [[그것들을 예상해야]] 한다.")],
  [("(지칭) 'them'은 프로젝트 리더들을 가리킨다.","지칭 오인이야. expect them의 them은 앞 문장의 'disagreements(이견)'를 가리켜 — 리더가 이견을 예상해야 한다는 뜻이야.")]),
 S(r4,3,[("조건 if","'~라면'"),("seek out","찾아내다")],
  [("remain","(여전히) ~인 상태다"),("hidden","숨겨진"),("at least","적어도")],
  [("If they remain [[hidden]], the leader may even want to","그것들이 [[숨겨져]] 있다면, 리더는 심지어 ~하고 싶어 할 수도 있다"),
   ("[[seek them out for at least two reasons]].","[[적어도 두 가지 이유로 그것들을 찾아내려]].")],
  [("숨은 이견은 그대로 두는 것이 최선이라는 내용이다.","'seek them out(그것들을 찾아낸다)'며 오히려 적극적으로 끄집어내려 한다는 거야 — 그 이유가 뒤에 둘 나와.")]),
 S(r4,4,[("bring with them","'~을 함께 가져오다'"),("의문사 how","'어떻게 ~하는지'")],
  [("view","견해, 관점"),("run (a project)","(프로젝트를) 운영하다")],
  [("First, different views can bring with them","첫째, 다양한 견해는 그것들과 함께 가져올 수 있다"),
   ("[[good ideas about the project and how it might be run]].","[[프로젝트와 그것을 어떻게 운영할지에 대한 좋은 아이디어를]].")],
  [("이 문장은 리더가 두 이유를 찾는 첫 번째 이유를 제시하는 문장이다.","'First(첫째)'로 시작해 이유①을 여는 전개 문장이야 — 다양한 견해가 '좋은 아이디어'를 가져온다는 거야.")]),
 S(r4,5,[("수동 should be avoided","'피해져야 한다'"),("be open to","~에 열려 있다")],
  [("snap decision","성급한 결정"),("avoid","피하다")],
  [("Although snap decisions about project changes [[should be avoided]],","프로젝트 변경에 대한 성급한 결정은 [[피해야 하지만]],"),
   ("leaders should be [[open to new and better ways to run the project]].","리더는 [[프로젝트를 운영할 새롭고 더 나은 방법에 열려 있어야]] 한다.")],
  [("성급한 결정을 피해야 하므로 리더는 새 방법을 받아들이면 안 된다는 내용이다.","'Although ~ avoided(피해야 하지만)'는 양보일 뿐, 주절은 'should be open(열려 있어야 한다)'이야 — 성급함은 경계하되 더 나은 방법엔 열려 있으라는 거야.")]),
 S(r4,6,[("접속사 when","'~할 때'"),("수동 are found/resolved","'발견·해결되다'"),("A rather than B","'B보다 A'")],
  [("conflicting","상충하는"),("viewpoint","관점"),("resolve","해결하다")],
  [("Second, when conflicting viewpoints are found,","둘째, 상충하는 관점이 발견되면,"),
   ("they are more easily resolved [[earlier rather than later]] in the project.","그것들은 프로젝트에서 [[나중보다 더 이른 시기에]] 더 쉽게 해결된다.")],
  [("상충하는 관점은 프로젝트 후반에 다룰수록 해결하기 쉽다는 내용이다.","'earlier rather than later(나중보다 이른 시기에)' 더 쉽게 해결된다는 거야 — 초기에 다뤄야 한다는 이유②야.")]),
 S(r4,7,[("접속사 although(양보)","주절과 대조"),("분사 considered/resolved","'고려·해결되는'")],
  [("aspect","측면"),("consider","고려하다")],
  [("Although team members may disagree about one or another [[aspect]] of the project,","팀원들은 프로젝트의 이런저런 [[측면]]에 대해 동의하지 않을 수 있지만,"),
   ("most simply want their [[ideas considered and resolved]].","대부분은 단지 자기 [[아이디어가 고려되고 해결되기를]] 원한다.")],
  [("(함축) 팀원들은 자기 의견이 반드시 그대로 채택되기를 요구한다.","함축을 놓쳤어. 'want their ideas considered and resolved(고려되고 해결되기를 원한다)'는 관철이 아니라 '진지하게 다뤄지는 것' 자체를 바란다는 뜻이야.")]),
 S(r4,8,[("look to A to B","'A가 B하기를 기대하다'"),("조건 if","'~라면'"),("수동 have been given","'주어져 왔다'")],
  [("tend to","~하는 경향이 있다"),("defer to","~에 따르다·양보하다"),("due consideration","합당한 고려")],
  [("The team tends to look to the project leader to [[play the lead role in resolving differences]],","팀은 프로젝트 리더가 [[의견 차이를 해결하는 주도적 역할을 하기를]] 기대하는 경향이 있고,"),
   ("and members will generally defer to the leader","팀원들은 대체로 리더에게 따를 것이다"),
   ("if they believe their views have been given [[due consideration]].","자기 견해가 [[합당한 고려]]를 받았다고 믿으면.")],
  [("팀원들은 어떤 경우에도 리더의 결정을 따르지 않는다는 내용이다.","'defer to the leader if they believe … due consideration(합당히 고려됐다고 믿으면 리더에게 따른다)'는 거야 — 의견이 존중됐다고 느끼면 리더를 따른다는 결론이야.")])]

# ================= 서술형 Practice : 음악 훈련과 뇌 (동명사 주어 수일치) =================
r5=["There is no question that learning to sing or play a musical instrument changes the structure of your brain.",
"If you enjoy music but have no special training, then your brain processes it mostly through its right hemisphere, the side of the brain that deals with emotion.",
"In the face of music, you are 'right-lateralised'.",
"Many studies show that musical training shifts the brain's processing of music to its left hemisphere; musicians are left-brained.",
"There are several guesses about why this happens.",
"One explanation is that they have learned to hear music more like language, discerning a level of structural complexity beyond the grasp of ordinary listeners.",
"When trained musicians hear music, it activates the part of the brain associated with language comprehension."]
ov5=Overview(theme_ko="음악 훈련이 뇌의 음악 처리 영역을 우반구(감정)에서 좌반구(언어)로 이동시키는 신경학적 변화",
 key_grammar=KeyGrammar(point="동명사(구) 주어의 수일치 (동명사 주어 = 단수 취급)",
  source_sentence="learning to sing or play a musical instrument changes the structure of your brain",
  explanation=[GN("쉽게 말하면","동명사(-ing)가 주어면 '~하는 것'이라는 [[하나의 개념]]이라 언제나 [[단수]] 취급이야."),
   GN("수일치","learning … or play … 처럼 or로 이어져도 주어는 '한 덩어리' → 동사는 [[changes]](단수)."),
   GN("함정","바로 앞 명사(instrument)에 이끌려 change로 쓰면 [[오류]] — 진짜 주어는 'learning …'이야."),
   GN("자리 찾기","동사(changes) 앞의 '~ing … 덩어리' 전체가 [[주어]]임을 먼저 묶어."),
   GN("해석 요령","'~하는 것은/~하기는'으로 주어를 묶고 단수 동사로 받아 옮겨.")],
  example="",example_analysis="learning to sing or play … changes … = '노래하거나 악기를 연주하는 법을 배우는 것은'이 단수 주어라 changes.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 1문장에서 주어 'learning to sing or play a musical instrument'에 대한 동사로 changes(단수)를 쓴 이유는?",
    options=["동명사구 'learning …'이 단수 주어라서","instrument가 단수라서","musical이 형용사라서"],
    answer="동명사구 'learning …'이 단수 주어라서"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'Reading books ____ your vocabulary.'",
    options=["improves","improve","are improving"],answer="improves"),
   GrammarDrill(kind="객관식",from_passage=False,question="어법상 올바른 문장은?",
    options=["Learning new languages takes time.","Learning new languages take time.","Learning new languages are taking time."],
    answer="Learning new languages takes time."),
   GrammarDrill(kind="영작",from_passage=False,question="매일 운동하는 것은 건강을 향상시킨다.",
    answer="Exercising every day improves your health."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 1문장 일부) 노래하거나 악기를 연주하는 법을 배우는 것은 뇌의 구조를 바꾼다.",
    answer="Learning to sing or play a musical instrument changes the structure of your brain.")]),
 topic="음악 훈련이 뇌의 음악 처리 부위를, 감정을 다루는 우반구에서 언어를 다루는 좌반구로 옮긴다는 신경학적 변화에 관한 글이야.",
 stance="중립적",stance_reason="연구 결과를 사실 중심으로 설명하는 정보 전달문으로, 우반구·좌반구 처리 변화를 관찰·서술해.",
 structure="비교·대조",structure_reason="훈련 없는 사람의 우반구(감정) 처리와 훈련된 음악가의 좌반구(언어) 처리를 대조하며, 그 이유를 설명해.",
 restatement_chains=[RestatementChain(label="비훈련 = 우반구·감정",
   expressions=["its right hemisphere","the side of the brain that deals with emotion","right-lateralised"],
   variation="'우반구' → '감정을 다루는 뇌' → '우측 지배'로 같은 상태가 반복돼."),
  RestatementChain(label="훈련 = 좌반구·언어",
   expressions=["its left hemisphere","musicians are left-brained","the part of the brain associated with language comprehension"],
   variation="'좌반구' → '좌뇌형' → '언어 이해와 관련된 뇌 부위'로 구체화돼.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1",summary="노래나 악기 연주를 배우는 것이 뇌 구조를 바꾼다는 데는 의심의 여지가 없다.",easy_example="음악을 배우면 실제로 뇌가 달라진다는 것."),
  FlowBlock(stage="대조-비훈련",sentence_range="2~3",summary="훈련이 없으면 뇌는 주로 감정을 다루는 우반구로 음악을 처리해 '우측 지배'가 된다.",easy_example="그냥 음악을 즐기는 사람은 감정 위주로 듣는 것."),
  FlowBlock(stage="대조-훈련",sentence_range="4",summary="많은 연구에 따르면 음악 훈련은 음악 처리를 좌반구로 옮겨, 음악가는 좌뇌형이 된다.",easy_example="훈련하면 음악을 '언어처럼' 분석해 듣게 되는 것."),
  FlowBlock(stage="이유",sentence_range="5~7",summary="왜 그런지에 대한 여러 추측이 있는데, 훈련된 음악가는 음악을 언어처럼 들으며 언어 이해 뇌 부위를 활성화하기 때문이다.",easy_example="음악의 구조적 복잡성을 언어처럼 해석하는 능력이 생긴 것.")])
i5=[S(r5,1,[("동격 that","no question 뒤 내용 부연"),("부정사 to sing","learning의 목적어")],
  [("no question","의심의 여지가 없음"),("instrument","악기"),("structure","구조")],
  [("There is no question that","~라는 데는 의심의 여지가 없다"),
   ("[[learning to sing or play a musical instrument]]","[[노래하거나 악기를 연주하는 법을 배우는 것이]]"),
   ("[[changes the structure of your brain]].","[[뇌의 구조를 바꾼다는]].")],
  [("이 문장은 음악 학습이 뇌에 미치는 영향이 불확실하다는 내용이다.","'There is no question that(의심의 여지가 없다)'로 음악 학습이 뇌 구조를 바꾼다고 단언하는 주제 문장이야.")]),
 S(r5,2,[("조건 if","'~라면'"),("관계사 that","the side 수식"),("동격","the side … = right hemisphere")],
  [("process","처리하다"),("hemisphere","(뇌) 반구"),("deal with","다루다")],
  [("If you enjoy music but have no special training,","여러분이 음악을 즐기지만 특별한 훈련이 없다면,"),
   ("then your brain [[processes it mostly through its right hemisphere]],","여러분의 뇌는 [[주로 우반구를 통해 그것을 처리한다]],"),
   ("the side of the brain [[that deals with emotion]].","[[감정을 다루는]] 뇌의 그 부분인.")],
  [("훈련이 없어도 뇌는 음악을 좌반구로 처리한다는 내용이다.","'through its right hemisphere(우반구를 통해)' 처리한다고 했어 — 훈련이 없으면 '감정'을 다루는 우반구로 듣는다는 거야(좌반구는 훈련 이후).")]),
 S(r5,3,[("전치사구 in the face of","'~을 접하여/마주하여'")],
  [("in the face of","~을 마주하여, 접하여"),("right-lateralised","우측 지배의(우반구 우세)")],
  [("In the face of music,","음악을 접하면,"),
   ("you are [['right-lateralised']].","여러분은 [['우측 지배를 받게']] 된다.")],
  [("(함축) 'right-lateralised'는 여러분이 음악을 논리적으로 분석해 듣는다는 뜻이다.","함축을 놓쳤어. 'right-lateralised(우측 지배)'는 앞의 '감정을 다루는 우반구'로 음악을 처리한다는 뜻 — 논리·언어(좌반구)가 아니라 감정 중심으로 듣는다는 거야.")]),
 S(r5,4,[("명사절 that","show의 목적어"),("세미콜론(;)","앞 내용을 요약·부연")],
  [("shift","옮기다, 이동시키다"),("left-brained","좌뇌형의")],
  [("Many studies show","많은 연구는 보여 준다"),
   ("[[that musical training shifts the brain's processing of music to its left hemisphere]];","[[음악 훈련이 뇌의 음악 처리를 좌반구로 옮긴다는 것을]];"),
   ("musicians are [[left-brained]].","즉, 음악가는 [[좌뇌형]]이다.")],
  [("이 문장은 훈련이 뇌의 음악 처리를 우반구로 더 굳힌다는 내용이다.","'shifts … to its left hemisphere(좌반구로 옮긴다)'가 핵심 — 훈련이 처리 부위를 우반구에서 '좌반구'로 이동시킨다는, 앞과 대조되는 발견 문장이야.")]),
 S(r5,5,[("의문사 why","'왜 ~하는지'(전치사 about의 목적어절)")],
  [("guess","추측"),("happen","일어나다")],
  [("There are several guesses","여러 추측이 있다"),
   ("about [[why this happens]].","[[왜 이것이 일어나는지]]에 관한.")],
  [("(지칭) 'this'는 음악이 감정을 자극하는 현상을 가리킨다.","지칭 오인이야. this는 앞 문장의 '음악 처리가 좌반구로 옮겨 가는(좌뇌화) 현상'을 가리켜 — 그 이유를 이제 설명해.")]),
 S(r5,6,[("명사절 that","is의 보어"),("분사구문 discerning","'분간하면서'"),("A more like B","'B에 더 가깝게'")],
  [("explanation","설명"),("discern","분간하다, 식별하다"),("complexity","복잡성"),("grasp","이해(력)")],
  [("One explanation is [[that they have learned to hear music more like language]],","한 가지 설명은 [[그들이 음악을 언어에 더 가깝게 듣는 법을 배웠다는]] 것이다,"),
   ("discerning a level of structural complexity","구조적 복잡성의 수준을 분간하면서"),
   ("beyond the grasp of [[ordinary listeners]].","[[평범한 청취자]]의 이해를 넘어선.")],
  [("이 문장은 음악가가 음악을 감정으로만 느낀다는 이유를 드는 문장이다.","'hear music more like language(음악을 언어처럼 듣는다)'가 이유야 — 언어처럼 구조를 분석해 듣기에 좌반구가 관여한다는 설명이야.")]),
 S(r5,7,[("접속사 when","'~할 때'"),("분사 associated with","'~와 관련된'")],
  [("activate","활성화하다"),("associated with","~와 관련된"),("comprehension","이해")],
  [("When trained musicians hear music,","훈련된 음악가가 음악을 들을 때,"),
   ("it activates the part of the brain [[associated with language comprehension]].","그것은 [[언어 이해와 관련된]] 뇌 부위를 활성화한다.")],
  [("훈련된 음악가가 음악을 들으면 감정 관련 뇌 부위만 켜진다는 내용이다.","'the part of the brain associated with language comprehension(언어 이해와 관련된 뇌 부위)'를 활성화한다는 거야 — 감정이 아니라 '언어' 부위가 켜진다는, 좌뇌화를 뒷받침하는 마무리야.")])]

DED={'an':['이중부정','부정어'],'u1':['병렬','등위'],'u2':['분사구문'],
     'u3':['양보','although','Although'],'pr':['동명사 주어','동명사(구) 주어']}
P_an=finalize(build("조용한 전기차 시대에 생존을 좌우하는 청각 정보의 중요성","Unit12-ANALYSIS",r1,ov1,i1),DED['an'])
P_u1=finalize(build("편의성·건강·취향 변화로 달라지거나 사라지는 것처럼 보이는 음식 조리법과 전통","Unit12-1",r2,ov2,i2),DED['u1'])
P_u2=finalize(build("가격 상승으로 소비를 억제하고 자원 보존을 유도하는, 예측이 간과한 시장 기능의 힘","Unit12-2",r3,ov3,i3),DED['u2'])
P_u3=finalize(build("프로젝트 팀 내 의견 차이의 긍정적 가치와 이를 조기에 해결해야 하는 리더의 역할","Unit12-3",r4,ov4,i4),DED['u3'])
P_pr=finalize(build("음악 훈련이 뇌의 음악 처리를 우반구(감정)에서 좌반구(언어)로 이동시키는 변화","서술형 Practice",r5,ov5,i5),DED['pr'])
U12_ALL=[P_an,P_u1,P_u2,P_u3,P_pr]
FOOT="© 2026. 김은아영어연구소. All rights reserved."
if __name__=="__main__":
    for p,st in zip(U12_ALL,["u12_an","u12_1","u12_2","u12_3","u12_pr"]): out(p,st)
    render_lecture_pdf(U12_ALL,f"{BASE}/hapbon_u12_student.pdf",teacher=False,footer_note=FOOT)
    render_lecture_pdf(U12_ALL,f"{BASE}/hapbon_u12_teacher.pdf",teacher=True,footer_note=FOOT)
    ds=fitz.open(f"{BASE}/hapbon_u12_student.pdf"); dt=fitz.open(f"{BASE}/hapbon_u12_teacher.pdf")
    print("합본 student",ds.page_count,"p / teacher",dt.page_count,"p"); ds.close(); dt.close()
    print("U12 DONE")
