# -*- coding: utf-8 -*-
"""EBS 올림포스 영어독해 기본1 Ch04 (Unit10-3, Unit11-ANALYSIS/1/2/3) 강의컨셉 교재 생성."""
import sys, random
sys.path.insert(0, "/home/user/english_data_making")
from src.lecture_schemas import (Chunk, FlowBlock, GrammarChip, GrammarDrill,
    GrammarNote, KeyGrammar, LecturePassage, LectureSentence, Misread,
    Overview, RestatementChain, SentenceAnalysis, SentenceItem, Vocab)
from src.lecture_render import render_lecture_pdf
import fitz
BASE="/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad"
SRC="EBS 올림포스 영어독해 기본1 · Ch04"
def mk(r): return [LectureSentence(id=i,text=t) for i,t in enumerate(r,1)]
def S(r,i,g,v,c,m): return SentenceItem(id=i,english=r[i-1],
    grammar=[GrammarChip(tag=a,note=b) for a,b in g],
    vocab=[Vocab(word=w,meaning=k) for w,k in v],
    chunks=[Chunk(en=e,ko=k) for e,k in c],
    misreads=[Misread(statement=s,why=w) for s,w in m])
def GN(c,t): return GrammarNote(chip=c,text=t)
def build(title,no,r,ov,items):
    p=LecturePassage(title=title,source=SRC,item_no=no,sentences=mk(r),
        overview=ov,analysis=SentenceAnalysis(sentences=items)); p.analysis.validate_all(len(r)); return p
def tok(a):
    ws=[w.strip('.,;:!?\"()“”') for w in a.split()]; ws=[w for w in ws if w]
    random.Random(len(a)+sum(map(ord,a[:8]))).shuffle(ws); return ws
_MCQ=[0]  # 객관식 정답 위치 분산 카운터
def finalize(p, dedup):
    TRIV=('전치사구','부사구','부사 ','부사(','의문문','명령문','콜론')
    TRIV_EXACT={'gradually','One of these'}
    for s in p.analysis.sentences:
        s.grammar=[g for g in s.grammar if not(any(t in g.tag for t in TRIV) or g.tag in TRIV_EXACT)]
    for d in p.overview.key_grammar.drills:
        if d.kind=='영작': d.words=tok(d.answer)
        if d.kind=='객관식' and d.options:
            others=[o for o in d.options if o!=d.answer]
            pos=_MCQ[0]%len(d.options); d.options=others[:]; d.options.insert(pos,d.answer)
        _MCQ[0]+=1
    return p
def out(p,stem):
    render_lecture_pdf([p],f"{BASE}/{stem}_student.pdf",teacher=False)
    render_lecture_pdf([p],f"{BASE}/{stem}_teacher.pdf",teacher=True)
    d=fitz.open(f"{BASE}/{stem}_student.pdf"); print(stem,d.page_count,'p'); d.close()

# ========== Unit10-3 : 단일재배와 원치 않는 종 (도치) ==========
r1=["At one end of the spectrum of transformations was the forest gardening as practiced by the peoples of New Guinea and Amazonia that mimicked natural growth and left minimal traces on the land.",
"At the other end was monoculture: cultivating only one species of plant or raising only one species of animal.",
"The beginnings of monoculture can be seen in the wheat fields of the Middle East, the rice paddies of China, and the herds of sheep and goats on the Eurasian steppe.",
"Biologically speaking, these species suddenly became very successful, measured by their rates of survival and reproduction.",
"So did other, unwanted species.",
"Crops that ripened or were stored after harvesting attracted rats, mice, sparrows, and roaches.",
"Water pools provided habitats for mosquitoes.",
"Garbage and human or animal waste attracted flies.",
"Thanks to humans, weeds and pests were also biological winners."]
ov1=Overview(theme_ko="단일 재배 농업이 잡초·해충 같은 원치 않는 종의 번식을 도운 생태적 결과",
 key_grammar=KeyGrammar(point="긍정 동의의 도치 (So + 동사 + 주어 = '~도 그랬다')",
  source_sentence="So did other, unwanted species.",
  explanation=[GN("쉽게 말하면","'So + 동사 + 주어'는 앞 문장을 받아 '[[~도 그랬다/그렇다]]'라고 덧붙이는 도치야."),
   GN("어순","보통 '주어+동사'인데 So 뒤에서는 '[[동사+주어]]'로 뒤집혀 — So did other species(다른 종들도 그랬다)."),
   GN("동사 맞추기","앞 문장 동사에 맞춰 [[do/did/does]]·be·조동사를 골라 써 — became(과거)라서 did."),
   GN("복원","So did other, unwanted species = other unwanted species [[also became successful]]."),
   GN("해석 요령","So 뒤 '동사+주어'가 보이면 앞 내용을 받아 '그 주어도 마찬가지'로 옮겨.")],
  example="",example_analysis="앞 문장 became successful을 받아 'So did other species' = '다른 원치 않는 종들도 (그렇게) 성공했다'로 did+주어 도치.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 5문장 'So did other, unwanted species.'의 의미로 알맞은 것은?",
    options=["원치 않는 다른 종들도 (마찬가지로) 매우 성공적이 되었다","원치 않는 종들은 성공하지 못했다","원치 않는 종들이 재배종을 성공하게 만들었다"],
    answer="원치 않는 다른 종들도 (마찬가지로) 매우 성공적이 되었다"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'My sister loves dogs, and ____ I.' (나도 그렇다)",
    options=["so do","so am","do so"],answer="so do"),
   GrammarDrill(kind="객관식",from_passage=False,question="'Prices went up, and so did complaints.'의 뜻으로 알맞은 것은?",
    options=["불평도 (마찬가지로) 늘었다","불평은 줄었다","불평이 가격을 올렸다"],answer="불평도 (마찬가지로) 늘었다"),
   GrammarDrill(kind="영작",from_passage=False,question="농작물이 번성했고, 해충도 그랬다. (So 도치 사용)",
    words=["the crops","thrived",",","and","so","did","the pests"],answer="The crops thrived, and so did the pests."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 5문장) 원치 않는 다른 종들도 그랬다.",
    words=["so","did","other",",","unwanted","species"],answer="So did other, unwanted species.")]),
 topic="단일 재배 농업이 재배종뿐 아니라 잡초·해충 같은 원치 않는 종까지 번성시킨 생태적 결과에 관한 글이야.",
 stance="중립적",stance_reason="현상을 사실 중심으로 설명하는 정보 전달문으로, 단일 재배의 결과를 관찰·서술해.",
 structure="비교·대조",structure_reason="스펙트럼의 한 끝(산림 정원)과 다른 끝(단일 재배)을 대조한 뒤, 단일 재배가 부른 결과를 사례로 든다.",
 restatement_chains=[RestatementChain(label="성공한 종",
   expressions=["these species suddenly became very successful","biological winners"],
   variation="'갑자기 매우 성공적이 됨' → '생물학적 승자'로 표현이 압축돼."),
  RestatementChain(label="원치 않는 종",
   expressions=["other, unwanted species","rats, mice, sparrows, and roaches","weeds and pests"],
   variation="'원치 않는 다른 종' → '쥐·참새·바퀴' → '잡초와 해충'으로 구체화돼.")],
 flow_blocks=[FlowBlock(stage="도입",sentence_range="1~2",summary="변화의 한 끝엔 흔적을 적게 남기는 산림 정원, 다른 끝엔 한 종만 기르는 단일 재배가 있다.",easy_example="자연 그대로 가꾸기 vs 한 작물만 왕창 심기."),
  FlowBlock(stage="전개",sentence_range="3",summary="단일 재배의 시작은 중동 밀밭·중국 논·유라시아 목축에서 볼 수 있다.",easy_example="옛날부터 밀·쌀·양 떼처럼 한 종을 대량으로 키운 것."),
  FlowBlock(stage="핵심",sentence_range="4~5",summary="이 재배종들은 갑자기 크게 번성했는데, 원치 않는 다른 종들도 그랬다.",easy_example="농사가 잘되니 덩달아 쥐·벌레도 늘어난 셈."),
  FlowBlock(stage="사례",sentence_range="6~8",summary="농작물은 쥐·참새·바퀴를, 물웅덩이는 모기를, 쓰레기는 파리를 끌어들였다.",easy_example="사람이 만든 환경이 해충의 서식지가 된 것."),
  FlowBlock(stage="결론",sentence_range="9",summary="인간 덕분에 잡초와 해충도 생물학적 승자가 되었다.",easy_example="사람이 판을 깔아 준 덕에 해충까지 번성한 결말.")])
i1=[S(r1,1,[("도치(부사구+동사+주어)","At one end 앞으로, was가 주어 앞에"),("관계사 that","forest gardening 수식")],
  [("spectrum","범위, 스펙트럼"),("mimic","모방하다"),("trace","흔적")],
  [("At one end of the spectrum of transformations","변화의 스펙트럼 한쪽 끝에는"),
   ("was the forest gardening as practiced by the peoples of New Guinea and Amazonia","뉴기니·아마존 사람들이 하던 산림 정원이 있었다"),
   ("[[that mimicked natural growth and left minimal traces on the land]].","[[자연적 성장을 모방하고 땅에 최소한의 흔적만 남기는]].")],
  [("산림 정원은 땅에 큰 흔적을 남기는 방식이라는 내용이다.","'minimal traces(최소한의 흔적)'라고 했어 — 자연을 모방해 흔적을 거의 안 남기는 방식이야(단일 재배와 대조).")]),
 S(r1,2,[("도치(부사구+동사+주어)","At the other end 앞으로"),("콜론(:) 부연","monoculture를 풀어 설명")],
  [("monoculture","단일 재배"),("cultivate","경작하다")],
  [("At the other end was [[monoculture]]:","다른 쪽 끝에는 [[단일 재배]]가 있었다:"),
   ("cultivating only one species of plant","한 종의 식물만 재배하거나"),("or raising only one species of animal.","한 종의 동물만 기르는 것.")],
  [("단일 재배는 여러 종을 동시에 기르는 방식이라는 내용이다.","'only one species(한 종만)'가 핵심 — 오직 한 종만 기르는 게 단일 재배야.")]),
 S(r1,3,[("병렬 명사구","밀밭/논/양·염소 무리")],
  [("wheat","밀"),("paddy","논"),("steppe","(유라시아) 스텝, 초원")],
  [("The beginnings of monoculture can be seen","단일 재배의 시작은 볼 수 있다"),
   ("in the wheat fields of the Middle East, the rice paddies of China,","중동의 밀밭, 중국의 논,"),
   ("and [[the herds of sheep and goats on the Eurasian steppe]].","[[유라시아 스텝의 양·염소 무리]]에서.")],
  [("단일 재배는 최근에야 생긴 방식이라는 내용이다.","중동 밀·중국 논 등 아주 오래된 예를 들어 — 단일 재배의 '기원'이 오래됐음을 보여줘.")]),
 S(r1,4,[("분사 measured","'~로 측정될 때'"),("Biologically speaking","'생물학적으로 말하면'")],
  [("survival","생존"),("reproduction","번식")],
  [("Biologically speaking, these species suddenly became [[very successful]],","생물학적으로 말하면, 이 종들은 갑자기 [[매우 성공적이 되었다]],"),
   ("[[measured by their rates of survival and reproduction]].","[[생존율과 번식률로 측정할 때]].")],
  [("(지칭) 'these species'는 잡초와 해충을 가리킨다.","지칭 오인이야. these species는 앞의 '단일 재배 대상(밀·쌀·양 등 재배종)'을 가리켜 — 잡초·해충은 다음 문장부터야.")]),
 S(r1,5,[("도치(So+동사+주어)","앞 문장을 받아 '~도 그랬다'")],
  [("unwanted","원치 않는")],
  [("[[So did other, unwanted species]].","[[원치 않는 다른 종들도 그랬다]].")],
  [("원치 않는 종들은 단일 재배로 오히려 사라졌다는 내용이다.","'So did(~도 그랬다)'로 앞의 '성공'을 받아 — 원치 않는 종들'도' 번성했다는, 글의 전환점이야.")]),
 S(r1,6,[("관계사 that","Crops 수식"),("수동 were stored","'저장된'")],
  [("ripen","익다"),("harvest","수확하다"),("attract","끌어들이다")],
  [("[[Crops that ripened or were stored after harvesting]]","[[익거나 수확 후 저장된 농작물은]]"),
   ("attracted rats, mice, sparrows, and roaches.","쥐·생쥐·참새·바퀴를 끌어들였다.")],
  [("농작물은 해로운 동물을 전혀 끌어들이지 않았다는 내용이다.","익거나 저장된 농작물이 쥐·참새·바퀴를 '끌어들였다(attracted)'는, 원치 않는 종 번성의 사례야.")]),
 S(r1,7,[("provide A for B","B에게 A를 제공하다")],
  [("habitat","서식지"),("mosquito","모기")],
  [("Water pools [[provided habitats for mosquitoes]].","물웅덩이는 [[모기에게 서식지를 제공했다]].")],
  [("물웅덩이는 모기의 번식을 막았다는 내용이다.","물웅덩이가 모기에게 '서식지를 제공했다'는 거야 — 인간 환경이 해충을 늘린 또 다른 예.")]),
 S(r1,8,[("병렬 주어","Garbage and ... waste")],
  [("garbage","쓰레기"),("waste","배설물, 폐기물")],
  [("Garbage and human or animal waste [[attracted flies]].","쓰레기와 사람·동물의 배설물은 [[파리를 끌어들였다]].")],
  [("쓰레기와 배설물은 파리와 무관하다는 내용이다.","'attracted flies(파리를 끌어들였다)'는 거야 — 사람이 만든 쓰레기가 해충을 부른 사례.")]),
 S(r1,9,[("Thanks to","'~덕분에'")],
  [("weed","잡초"),("pest","해충"),("winner","승자")],
  [("Thanks to humans,","인간 덕분에,"),("weeds and pests were [[also biological winners]].","잡초와 해충도 [[생물학적 승자였다]].")],
  [("(함축) 'winners(승자)'라는 표현은 잡초·해충이 인간에게 이롭다는 칭찬이다.","함축을 놓쳤어. 'biological winners'는 '번식에 성공했다'는 뜻이지 이롭다는 칭찬이 아니야 — 인간이 원치 않는 종까지 번성시켰다는 반어적 마무리야.")])]

# ========== Unit11-ANALYSIS : 십대 소셜미디어 (would rather A than B) ==========
r2=["Observation studies of teenagers using social media have discovered one peculiar behaviour in particular that sets them apart — teenagers will post or share something on social media, but then they'll monitor the post to gauge the volume of reactions.",
"After a set amount of time, if the number of resulting 'Likes' and 'Shares' is too low, they'll delete the content.",
"Sometimes within the first ten minutes!",
"Their aim of posting is to earn recognition for what they're sharing as a way to self-enhance.",
"If the recognition is insufficient, they'd rather delete the content than suffer perceived judgement from others against their failed efforts to self-enhance.",
"Not getting a reaction has a negative effect on their self-esteem."]
ov2=Overview(theme_ko="자신을 고양하려는 욕구로 소셜미디어 반응을 확인하고 게시물을 삭제하는 십대들의 행동",
 key_grammar=KeyGrammar(point="would rather A than B ('B하느니 차라리 A하겠다')",
  source_sentence="If the recognition is insufficient, they'd rather delete the content than suffer perceived judgement from others against their failed efforts to self-enhance.",
  explanation=[GN("쉽게 말하면","'would rather A than B'는 'B할 바에야 차라리 [[A하겠다]]'라는 '선택·선호'야."),
   GN("형태","rather 뒤 A, than 뒤 B에는 둘 다 [[동사원형]]이 와 — rather delete ... than suffer ..."),
   GN("의미","단순 비교가 아니라 'B는 싫어서 A를 택한다'는 [[선호]]를 나타내."),
   GN("주의","'d는 [[would]]의 축약이야(had 아님) — they'd rather = they would rather."),
   GN("해석 요령","'than B할 바에 (차라리) A한다'로, A를 택하는 이유(B 회피)를 함께 잡아.")],
  example="",example_analysis="rather delete the content(A) than suffer judgement(B) — 비판을 겪느니 차라리 삭제하겠다는 선택.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 5문장 'they'd rather delete the content than suffer perceived judgement'의 의미로 알맞은 것은?",
    options=["타인의 비판을 겪느니 차라리 콘텐츠를 삭제하겠다","콘텐츠를 삭제하기보다 비판을 견디겠다","콘텐츠도 삭제하고 비판도 견디겠다"],
    answer="타인의 비판을 겪느니 차라리 콘텐츠를 삭제하겠다"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'I would ____ walk ____ take a crowded bus.' (붐비는 버스를 타느니 걷겠다)",
    options=["rather / than","rather / then","better / than"],answer="rather / than"),
   GrammarDrill(kind="객관식",from_passage=False,question="'She'd rather stay home than go to the party.'의 뜻으로 알맞은 것은?",
    options=["파티에 가느니 차라리 집에 있겠다","집에 있기보다 파티에 가겠다","집에도 있고 파티에도 가겠다"],answer="파티에 가느니 차라리 집에 있겠다"),
   GrammarDrill(kind="영작",from_passage=False,question="그들은 비판을 받느니 차라리 침묵을 지키겠다.",
    words=["they","would","rather","keep","silent","than","face","criticism"],answer="They would rather keep silent than face criticism."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 5문장 일부) 그들은 타인의 비판을 겪느니 차라리 콘텐츠를 삭제하겠다.",
    words=["they'd","rather","delete","the content","than","suffer","judgement","from others"],
    answer="They'd rather delete the content than suffer judgement from others.")]),
 topic="십대가 소셜미디어에서 반응(인정)을 확인하고, 반응이 적으면 게시물을 지우는 행동과 그 심리에 관한 글이야.",
 stance="중립적",stance_reason="관찰 연구 결과를 사실 중심으로 설명하며, 십대 행동을 평가보다 분석적으로 서술해.",
 structure="주장→근거·예시",structure_reason="관찰된 독특한 행동(1~3문장)을 제시하고, 그 목적·이유(4~6문장)로 설명해.",
 restatement_chains=[RestatementChain(label="인정 욕구",
   expressions=["earn recognition","self-enhance","self-esteem"],
   variation="'인정을 얻다' → '자기 고양' → '자존감'으로 심리 동기가 이어져."),
  RestatementChain(label="삭제 행동",
   expressions=["they'll delete the content","they'd rather delete the content than suffer"],
   variation="'콘텐츠를 삭제한다'는 행동 → '비판을 겪느니 차라리 삭제한다'는 이유가 붙어 구체화돼.")],
 flow_blocks=[FlowBlock(stage="도입",sentence_range="1",summary="십대는 소셜미디어에 올린 뒤 반응의 양을 관찰하는 독특한 행동을 보인다.",easy_example="글 올리고 좋아요가 얼마나 붙나 계속 확인하는 모습."),
  FlowBlock(stage="전개",sentence_range="2~3",summary="일정 시간 뒤 '좋아요·공유'가 너무 적으면 게시물을 지우는데, 때론 10분 안에도 지운다.",easy_example="반응 없으면 금방 슬쩍 지워 버리는 것."),
  FlowBlock(stage="이유",sentence_range="4",summary="게시의 목표는 공유한 것으로 '인정'을 받아 자신을 고양하는 것이다.",easy_example="칭찬·인정을 받으려고 올리는 것."),
  FlowBlock(stage="핵심",sentence_range="5",summary="인정이 부족하면 타인의 비판을 겪느니 차라리 콘텐츠를 삭제한다.",easy_example="반응이 시원찮으면 창피 당하기 전에 지워 버리는 것."),
  FlowBlock(stage="결론",sentence_range="6",summary="반응을 얻지 못하는 것은 그들의 자존감에 부정적 영향을 준다.",easy_example="무반응이 마음에 상처가 되는 것.")])
i2=[S(r2,1,[("관계사 that","behaviour 수식"),("대시 부연","독특한 행동을 풀어 설명")],
  [("peculiar","독특한, 특이한"),("set apart","구별 짓다"),("gauge","측정하다, 가늠하다")],
  [("Observation studies of teenagers using social media have discovered one peculiar behaviour in particular","소셜미디어를 사용하는 십대에 대한 관찰 연구는 특히 하나의 독특한 행동을 발견했다"),
   ("[[that sets them apart]]","[[그들을 (남들과) 구별 짓는]]"),
   ("— teenagers will post or share something on social media,","— 십대는 소셜미디어에 무언가를 올리거나 공유하는데,"),
   ("but then they'll [[monitor the post to gauge the volume of reactions]].","그런 다음 [[반응의 양을 가늠하려고 그 게시물을 관찰한다]].")],
  [("십대는 게시물을 올린 뒤 신경 쓰지 않는다는 내용이다.","올린 뒤 '반응의 양을 재려고 관찰한다(monitor to gauge)'는 게 이 글이 주목한 독특한 행동이야.")]),
 S(r2,2,[("조건 if","'~라면'")],
  [("a set amount","일정한 양"),("resulting","결과로 생긴")],
  [("After a set amount of time, [[if the number of resulting 'Likes' and 'Shares' is too low]],","일정 시간 뒤, [[그 결과로 생긴 '좋아요'와 '공유' 수가 너무 적으면]],"),
   ("they'll [[delete the content]].","그들은 [[콘텐츠를 삭제한다]].")],
  [("반응이 적어도 게시물을 그대로 둔다는 내용이다.","'if ... too low, they'll delete(적으면 삭제한다)'는 조건부 행동 — 반응이 적으면 지운다는 거야.")]),
 S(r2,3,[("생략·강조","(they delete it) within ten minutes")],
  [("within","~ 이내에")],
  [("Sometimes [[within the first ten minutes]]!","때로는 [[첫 10분 이내에도]]!")],
  [("삭제는 항상 오랜 시간이 지난 뒤에만 일어난다는 내용이다.","'within the first ten minutes(10분 안에도)'라며 삭제가 매우 빠를 수 있음을 강조해 — 앞 문장을 이어받은 거야.")]),
 S(r2,4,[("관계사 what","for의 목적어 '~하는 것'"),("as a way to","'~하는 방법으로서'")],
  [("recognition","인정"),("self-enhance","자기를 고양하다")],
  [("Their aim of posting is to earn recognition","그들의 게시 목표는 인정을 얻는 것이다"),
   ("for [[what they're sharing]]","[[자신이 공유하는 것에 대해]]"),("as a way to [[self-enhance]].","[[자신을 고양하는]] 방법으로서.")],
  [("게시의 목표는 정보를 알리는 것이라는 내용이다.","목표는 '인정을 얻어 자신을 고양(self-enhance)'하는 것 — 정보 전달이 아니라 인정 욕구가 핵심이야.")]),
 S(r2,5,[("would rather A than B","'B하느니 A하겠다'"),("조건 if","'~라면'")],
  [("insufficient","불충분한"),("perceived","인지된"),("judgement","비판, 판단")],
  [("If the recognition is insufficient,","인정이 불충분하면,"),
   ("they'd [[rather delete the content than suffer perceived judgement]]","그들은 [[비판을 겪느니 차라리 콘텐츠를 삭제한다]]"),
   ("from others against their failed efforts to self-enhance.","자기 고양 실패에 대한 타인의.")],
  [("십대는 비판을 견디며 게시물을 끝까지 남겨 둔다는 내용이다.","'rather delete ... than suffer judgement(비판을 겪느니 삭제)'가 핵심 — 비판을 피하려고 지운다는 선택이야.")]),
 S(r2,6,[("동명사 주어","Not getting a reaction")],
  [("self-esteem","자존감"),("reaction","반응")],
  [("[[Not getting a reaction]]","[[반응을 얻지 못하는 것은]]"),("has a negative effect on their [[self-esteem]].","그들의 [[자존감]]에 부정적 영향을 준다.")],
  [("(함축) 반응이 없어도 십대의 자존감은 아무 영향을 받지 않는다는 내용이다.","함축을 놓쳤어. 'negative effect on self-esteem'은 무반응이 자존감을 '해친다'는 뜻 — 삭제 행동의 심리적 뿌리를 밝히는 마무리야.")])]

# ========== Unit11-1 : 비관론자 (명사절 that) ==========
r3=["The reason pessimists often sound smart is that they can avoid being 'wrong' by moving the goalposts.",
"When a doomer predicts that the world will end in five years, and it doesn't, they just shift the date.",
"The American biologist Paul R. Ehrlich — author of the 1968 book The Population Bomb — has been doing this for decades.",
"In 1970 he said that 'sometime in the next 15 years, the end will come. And by \"the end\" I mean an utter breakdown of the capacity of the planet to support humanity.'",
"Of course, that was terribly wrong.",
"He had another go: he said that 'England will not exist in the year 2000.'",
"Wrong again.",
"Ehrlich will keep pushing this deadline back.",
"A pessimistic stance is a safe one."]
ov3=Overview(theme_ko="예측 실패 시 시점을 바꿔 오류를 회피하고 안전을 도모하는 비관론자들의 전략",
 key_grammar=KeyGrammar(point="명사절을 이끄는 접속사 that ('~라는 것/~라고')",
  source_sentence="The reason pessimists often sound smart is that they can avoid being 'wrong' by moving the goalposts.",
  explanation=[GN("쉽게 말하면","접속사 that은 '주어+동사'를 묶어 '[[~라는 것/~라고]]'라는 하나의 명사 덩어리(명사절)로 만들어."),
   GN("자리","이 that절은 문장에서 [[주어·목적어·보어]] 자리에 와 — 1문장은 is 뒤 '보어', 2·4문장은 동사(predict/said) 뒤 '목적어'."),
   GN("관계사와 구별","that 뒤 문장이 '완전'하면 명사절(접속사), 뒤에 [[빠진 자리]]가 있으면 관계사야."),
   GN("생략","목적어 자리 that은 자주 [[생략]]돼 — say (that) ~."),
   GN("해석 요령","that 뒤를 '~라는 것/~라고'로 묶어 앞 동사·be에 붙여 읽어.")],
  example="",example_analysis="is that they can avoid ~ : that절이 is의 '보어' 역할로, 'they가 ~할 수 있다는 것'이라는 명사 덩어리.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 1문장 'The reason pessimists often sound smart is that they can avoid being wrong'에서 that의 역할은?",
    options=["is의 '보어'가 되는 명사절을 이끄는 접속사","the reason을 꾸미는 관계대명사","'그것'을 뜻하는 지시대명사"],
    answer="is의 '보어'가 되는 명사절을 이끄는 접속사"),
   GrammarDrill(kind="객관식",from_passage=False,question="밑줄 친 that이 '명사절 접속사'인 것은?",
    options=["The problem is that we have no time.","The car that he bought is red.","I met a man that knows you."],
    answer="The problem is that we have no time."),
   GrammarDrill(kind="객관식",from_passage=False,question="'He said that he was tired.'에서 that절의 역할은?",
    options=["said의 목적어","said를 꾸미는 부사","he를 꾸미는 관계사"],answer="said의 목적어"),
   GrammarDrill(kind="영작",from_passage=False,question="문제는 그들이 결코 자신의 실수를 인정하지 않는다는 것이다.",
    words=["the problem","is","that","they","never","admit","their mistakes"],answer="The problem is that they never admit their mistakes."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 1문장) 비관론자들이 흔히 똑똑하게 들리는 이유는 골대를 옮김으로써 '틀림'을 피할 수 있기 때문이다.",
    words=["the reason","pessimists","often","sound smart","is","that","they can avoid","being wrong","by moving the goalposts"],
    answer="The reason pessimists often sound smart is that they can avoid being wrong by moving the goalposts.")]),
 topic="비관론자가 예측이 틀릴 때마다 시점을 바꿔 '틀림'을 피하는 전략과 그 안전성에 관한 글이야.",
 stance="부정적·비판적",stance_reason="avoid being wrong·moving the goalposts·keep pushing back 같은 표현으로, 비관론자의 회피 전략을 비판적으로 꼬집어.",
 structure="주장→근거·예시",structure_reason="'비관론자는 골대를 옮겨 틀림을 피한다'는 주장(1~2문장) 뒤, Ehrlich의 반복된 예측 실패(3~8문장)로 뒷받침해.",
 restatement_chains=[RestatementChain(label="예측 회피",
   expressions=["avoid being 'wrong' by moving the goalposts","they just shift the date","keep pushing this deadline back"],
   variation="'골대를 옮겨 틀림을 피함' → '날짜를 바꿈' → '시한을 계속 미룸'으로 같은 전략이 반복돼."),
  RestatementChain(label="비관 = 안전",
   expressions=["sound smart","a safe one"],
   variation="'똑똑하게 들림' → '안전한 자세'로 비관 태도의 이점이 정리돼.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1~2",summary="비관론자가 똑똑해 보이는 이유는 골대를 옮겨 '틀림'을 피하기 때문이다.",easy_example="예측이 빗나가면 날짜만 슬쩍 바꾸는 것."),
  FlowBlock(stage="사례도입",sentence_range="3",summary="생물학자 Ehrlich는 수십 년째 이렇게 해 왔다.",easy_example="유명 학자도 예측을 계속 미뤄 온 것."),
  FlowBlock(stage="사례1",sentence_range="4~5",summary="1970년 '15년 내 종말'을 예측했지만 완전히 틀렸다.",easy_example="종말 예언이 빗나간 것."),
  FlowBlock(stage="사례2",sentence_range="6~7",summary="'2000년에 영국이 사라진다'고 또 예측했지만 또 틀렸다.",easy_example="다시 한 예측도 빗나간 것."),
  FlowBlock(stage="결론",sentence_range="8~9",summary="Ehrlich는 시한을 계속 미룰 것이고, 비관적 자세는 안전한 자세다.",easy_example="틀려도 미루면 되니 비관은 손해 볼 게 없다는 마무리.")])
i3=[S(r3,1,[("명사절 that","is의 보어"),("by -ing","'~함으로써'")],
  [("pessimist","비관론자"),("avoid","피하다"),("move the goalposts","(유리하게) 기준을 바꾸다")],
  [("The reason pessimists often sound smart","비관론자가 흔히 똑똑하게 들리는 이유는"),
   ("is [[that they can avoid being 'wrong']]","[['틀림'을 피할 수 있기]] 때문이다"),
   ("by [[moving the goalposts]].","[[골대를 옮김으로써]].")],
  [("비관론자가 똑똑한 이유는 예측이 늘 맞기 때문이라는 내용이다.","예측이 맞아서가 아니라 '골대를 옮겨 틀림을 피하기(avoid being wrong)' 때문이라는, 글의 주제야.")]),
 S(r3,2,[("명사절 that","predicts의 목적어"),("대동사 doesn't","end 대신")],
  [("doomer","운명론자, 비관론자"),("predict","예측하다"),("shift","바꾸다"),],
  [("When a doomer [[predicts that the world will end in five years]],","운명론자가 [[5년 내 세상이 끝난다고 예측했는데]],"),
   ("and it doesn't,","그렇지 않으면,"),("they just [[shift the date]].","그들은 그냥 [[날짜를 바꾼다]].")],
  [("예측이 빗나가면 비관론자는 예측을 철회한다는 내용이다.","예측을 철회하는 게 아니라 '날짜를 바꾼다(shift the date)'는 거야 — 틀림을 인정하지 않고 시점만 미루는 전략.")]),
 S(r3,3,[("대시 동격","저서 정보 부연"),("현재완료진행","계속 해 오고 있다")],
  [("biologist","생물학자"),("author","저자"),("decade","10년")],
  [("The American biologist Paul R. Ehrlich","미국 생물학자 폴 R. 에얼릭은"),
   ("— author of the 1968 book The Population Bomb —","— 1968년 책 『인구 폭탄』의 저자 —"),
   ("[[has been doing this for decades]].","[[수십 년째 이렇게 해 오고 있다]].")],
  [("(지칭) 'this'는 인구 문제를 해결하는 일을 가리킨다.","지칭 오인이야. this는 앞의 '예측이 틀리면 날짜를 미루는 회피 전략'을 가리켜 — 문제 해결이 아니야.")]),
 S(r3,4,[("명사절 that","said의 목적어"),("동격 the end","'종말'의 뜻 부연")],
  [("utter","완전한"),("breakdown","붕괴"),("capacity","능력, 수용력")],
  [("In 1970 he said [[that 'sometime in the next 15 years, the end will come]].","1970년 그는 [['앞으로 15년 안에 언젠가 종말이 온다]]고 말했다."),
   ("And by \"the end\" I mean","그리고 '종말'이란 내 말은"),("an utter breakdown of the capacity of the planet to support humanity.'","인류를 지탱할 지구 능력의 완전한 붕괴다.'")],
  [("에얼릭은 종말의 시점을 애매하게 두지 않고 정확히 못박았다는 내용이다.","'sometime in the next 15 years(15년 안 언젠가)'처럼 시점을 넓게 잡았어 — 나중에 미루기 쉽게.")]),
 S(r3,5,[("지시 that","앞 예측을 받음")],
  [("terribly","몹시"),("wrong","틀린")],
  [("Of course, [[that was terribly wrong]].","물론, [[그것은 완전히 틀렸다]].")],
  [("에얼릭의 1970년 예측은 대체로 들어맞았다는 내용이다.","'terribly wrong(완전히 틀렸다)'이라고 못박아 — 예측이 빗나갔음을 보여줘.")]),
 S(r3,6,[("명사절 that","said의 목적어"),("have another go","'다시 한 번 하다'")],
  [("another go","또 한 번의 시도"),("exist","존재하다")],
  [("He had another go:","그는 다시 한 번 했다:"),("he said [[that 'England will not exist in the year 2000]].'","[['2000년에 영국이 존재하지 않을 것']]이라고 말했다.")],
  [("에얼릭은 한 번 틀린 뒤 예측을 그만두었다는 내용이다.","'had another go(또 한 번 했다)'며 다시 예측했어 — 틀려도 계속 새 예측을 내놓는다는 거야.")]),
 S(r3,7,[("생략","(He was) wrong again")],
  [("again","또, 다시")],
  [("[[Wrong again]].","[[또 틀렸다]].")],
  [("이번 예측은 맞았다는 내용이다.","'Wrong again(또 틀렸다)' — 두 번째 예측도 빗나갔다는 짧은 확인이야.")]),
 S(r3,8,[("will keep -ing","'계속 ~할 것이다'"),("push back","미루다")],
  [("deadline","기한, 시한"),("push back","뒤로 미루다")],
  [("Ehrlich will [[keep pushing this deadline back]].","에얼릭은 [[이 시한을 계속 뒤로 미룰 것이다]].")],
  [("에얼릭은 이제 예측을 멈출 것이라는 내용이다.","'keep pushing this deadline back(계속 미룬다)'는 거야 — 틀릴 때마다 시한만 미루는 전략을 이어간다는 뜻.")]),
 S(r3,9,[("보어 명사","a safe one = a safe stance")],
  [("stance","입장, 자세"),("safe","안전한")],
  [("[[A pessimistic stance is a safe one]].","[[비관적 자세는 안전한 자세다]].")],
  [("(함축) 비관적 자세가 안전하다는 것은 필자가 비관론을 권장한다는 뜻이다.","함축을 놓쳤어. '안전하다(safe)'는 '틀려도 책임을 피할 수 있어 손해가 없다'는 반어적 비판 — 비관론을 칭찬하는 게 아니야.")])]

# ========== Unit11-2 : 기억/script (전치사+관계대명사 to which) ==========
r4=["We all understand differently — this much is obvious.",
"The reason we understand differently is that our memories are different.",
"Our experiences simply are not yours.",
"In order to understand anything, we must find the closest item in memory to which it relates.",
"Schank and Abelson claimed that understanding required one to find the correct knowledge structure, and to use that structure to create expectations for what events were likely to take place, so that new events could be understood in terms of what was normal.",
"Thus, when a story about a cocktail party was being told, an understander brought out his cocktail party script which told him about what ordinarily happens at cocktail parties, and he used that script to guide his understanding of the story he was about to hear."]
ov4=Overview(theme_ko="개인의 기억과 경험적 대본(script)을 바탕으로 이루어지는 주관적인 이해 과정",
 key_grammar=KeyGrammar(point="전치사 + 관계대명사 (to which)",
  source_sentence="In order to understand anything, we must find the closest item in memory to which it relates.",
  explanation=[GN("쉽게 말하면","'전치사 + which'는 관계사절 안의 전치사가 which 앞으로 [[당겨진]] 형태야."),
   GN("복원","to which it relates = which it relates [[to]] — 원래 'it relates to the item(그것이 그 항목과 관련된다)'."),
   GN("찾는 법","which가 받는 명사(the closest item)에, 관계사절 동사(relates) 뒤 [[전치사(to)]]를 붙여 뜻을 맞춰."),
   GN("주의","전치사+which는 that으로 바꿀 수 [[없어]] — to that (X)."),
   GN("해석 요령","'그것과 관련되는 (가장 가까운) 항목'처럼, 전치사 뜻을 살려 명사에 붙여 옮겨.")],
  example="",example_analysis="the closest item ... to which it relates = 'it relates to the item'에서 to which가 앞으로 나온 것 — '그것과 관련되는 항목'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 4문장 'the closest item in memory to which it relates'의 의미로 알맞은 것은?",
    options=["그것(이해 대상)과 관련되는, 기억 속 가장 가까운 항목","기억을 관련짓지 않는 항목","가장 먼 기억 항목"],
    answer="그것(이해 대상)과 관련되는, 기억 속 가장 가까운 항목"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'This is the house ____ ____ I was born.' (내가 태어난 집)",
    options=["in which","in that","which in"],answer="in which"),
   GrammarDrill(kind="객관식",from_passage=False,question="'the tool with which he fixed it'의 뜻으로 알맞은 것은?",
    options=["그가 그것을 고친 (그) 도구","그가 고치지 않은 도구","그를 고친 도구"],answer="그가 그것을 고친 (그) 도구"),
   GrammarDrill(kind="영작",from_passage=False,question="그것은 우리가 의지할 수 있는 유일한 규칙이다.",
    words=["it","is","the only rule","on","which","we","can","rely"],answer="It is the only rule on which we can rely."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 4문장) 무언가를 이해하려면, 우리는 그것과 관련되는 기억 속 가장 가까운 항목을 찾아야 한다.",
    words=["in order to","understand anything",",","we","must","find","the closest item","in memory","to","which","it","relates"],
    answer="In order to understand anything, we must find the closest item in memory to which it relates.")]),
 topic="사람마다 이해가 다른 이유와, 기억·경험적 대본(script)을 통해 이해가 이루어지는 과정에 관한 글이야.",
 stance="중립적",stance_reason="인지 이론(Schank·Abelson)을 사실 중심으로 설명하는 정보 전달문이야.",
 structure="주장→근거·예시",structure_reason="'이해는 기억·대본에 기반한다'는 주장(1~4문장) 뒤, 칵테일파티 대본이라는 예시(5~6문장)로 뒷받침해.",
 restatement_chains=[RestatementChain(label="이해는 주관적",
   expressions=["We all understand differently","Our experiences simply are not yours"],
   variation="'모두 다르게 이해' → '우리의 경험은 네 것이 아님'으로 주관성이 강조돼."),
  RestatementChain(label="기억·대본 기반 이해",
   expressions=["the closest item in memory","the correct knowledge structure","his cocktail party script"],
   variation="'기억 속 가까운 항목' → '올바른 지식 구조' → '칵테일파티 대본'으로 구체화돼.")],
 flow_blocks=[FlowBlock(stage="도입",sentence_range="1~3",summary="우리는 모두 다르게 이해하는데, 그 이유는 기억과 경험이 서로 다르기 때문이다.",easy_example="같은 말을 들어도 각자 경험에 따라 다르게 받아들이는 것."),
  FlowBlock(stage="원리",sentence_range="4",summary="무언가를 이해하려면 기억에서 그것과 관련된 가장 가까운 항목을 찾아야 한다.",easy_example="새 정보를 이미 아는 비슷한 것에 연결해 이해하는 것."),
  FlowBlock(stage="이론",sentence_range="5",summary="Schank·Abelson은 올바른 지식 구조를 찾아 사건을 예측하며 이해한다고 주장했다.",easy_example="상황에 맞는 '틀'을 꺼내 앞일을 예상하며 이해하는 것."),
  FlowBlock(stage="예시",sentence_range="6",summary="칵테일파티 이야기를 들으면 '칵테일파티 대본'을 꺼내 이해를 안내한다.",easy_example="파티 얘기가 나오면 머릿속 '파티 각본'으로 내용을 짐작하는 것.")])
i4=[S(r4,1,[("대시 부연","this much is obvious 덧붙임")],
  [("differently","다르게"),("obvious","명백한")],
  [("We all understand differently","우리는 모두 다르게 이해한다"),("— this much is [[obvious]].","— 이 점만큼은 [[명백하다]].")],
  [("사람들은 대체로 똑같이 이해한다는 내용이다.","'understand differently(다르게 이해한다)'가 명백하다고 했어 — 이해의 '차이'가 이 글의 출발점이야.")]),
 S(r4,2,[("명사절 that","is의 보어")],
  [("reason","이유"),("memory","기억")],
  [("The reason we understand differently","우리가 다르게 이해하는 이유는"),("is [[that our memories are different]].","[[우리의 기억이 다르기]] 때문이다.")],
  [("이해가 다른 이유는 언어가 다르기 때문이라는 내용이다.","이유는 '기억이 다르기(memories are different)' 때문이라고 못박았어 — 언어가 아니라 기억·경험의 차이야.")]),
 S(r4,3,[("be동사 강조","simply are not")],
  [("experience","경험"),("simply","단순히, 결코")],
  [("Our experiences [[simply are not yours]].","우리의 경험은 [[결코 여러분의 것이 아니다]].")],
  [("경험은 사람들 사이에 대체로 공유된다는 내용이다.","'are not yours(네 것이 아니다)'로 경험의 개별성을 강조 — 경험이 사람마다 다르다는 뜻이야.")]),
 S(r4,4,[("전치사+관계대명사 to which","item을 수식"),("In order to","'~하기 위해'")],
  [("relate to","~와 관련되다"),("item","항목")],
  [("In order to understand anything, we must find","무언가를 이해하려면, 우리는 찾아야 한다"),
   ("[[the closest item in memory]]","[[기억 속 가장 가까운 항목을]]"),
   ("[[to which it relates]].","[[그것과 관련되는]].")],
  [("이해하려면 기억을 완전히 비워야 한다는 내용이다.","기억에서 '그것과 관련되는 가장 가까운 항목'을 찾아야 한다는 거야 — 기억을 비우는 게 아니라 연결하는 거야.")]),
 S(r4,5,[("명사절 that","claimed의 목적어"),("so that","'~하도록/그 결과'"),("관계사 what","'~하는 것'")],
  [("claim","주장하다"),("knowledge structure","지식 구조"),("expectation","예상, 기대")],
  [("Schank and Abelson claimed [[that understanding required one to find the correct knowledge structure]],","섄크와 에이벌슨은 [[이해가 올바른 지식 구조를 찾을 것을 요구한다]]고 주장했다,"),
   ("and to use that structure to create expectations for what events were likely to take place,","그리고 그 구조로 어떤 사건이 일어날지 예상을 만들도록,"),
   ("[[so that new events could be understood in terms of what was normal]].","[[새 사건을 '보통 무엇인가'의 관점에서 이해할 수 있도록]].")],
  [("이해는 지식 구조 없이 즉흥적으로 이뤄진다는 내용이다.","'올바른 지식 구조(knowledge structure)를 찾아' 예측하며 이해한다는 주장이야 — 즉흥이 아니라 틀 기반이야.")]),
 S(r4,6,[("관계사 which","script 부연"),("관계사 what","'~하는 것'")],
  [("understander","이해하는 사람"),("script","대본, 각본"),("ordinarily","보통, 대개")],
  [("Thus, when a story about a cocktail party was being told,","그래서 칵테일파티 이야기를 들을 때,"),
   ("an understander brought out his cocktail party script","이해자는 자신의 칵테일파티 대본을 꺼냈다"),
   ("[[which told him about what ordinarily happens at cocktail parties]],","[[칵테일파티에서 보통 무슨 일이 일어나는지 그에게 알려 주는]],"),
   ("and he used that script to guide his understanding of the story he was about to hear.","그리고 그는 그 대본으로 자신이 곧 들을 이야기의 이해를 이끌었다.")],
  [("(지칭) 'that script'는 이야기를 실제로 녹음한 대본을 가리킨다.","지칭 오인이야. that script는 실제 녹음이 아니라 머릿속 '칵테일파티에서 보통 일어나는 일에 대한 지식 틀(대본)'을 가리켜.")])]

# ========== Unit11-3 : 붉은색 (비교 A rather than B) ==========
r5=["Of all the colours of the rainbow the one that makes the greatest impact on the eye is red.",
"There is something instantly arresting about the colour of fire and danger.",
"It is charged with alarm and urgency.",
"We have red fire engines, red warning lights and the Red Cross.",
"If we want something to be seen from a distance, such as a post box or (formerly) a telephone kiosk, we paint it red.",
"Perhaps it is because red is so obvious that few wild animals are truly red: even the so-called Red Squirrel and the Red Deer are really shades of reddish-brown that conceal rather than advertise.",
"Relatively few butterflies are red either.",
"In Britain, and indeed, in all mainland Europe, only one species has a pattern of full-on bright red, like a splash of blood: the Red Admiral."]
ov5=Overview(theme_ko="시각적 충격과 위험을 알리는 붉은색의 특성과 야생 동물이 위장을 위해 이를 기피하는 현상",
 key_grammar=KeyGrammar(point="A rather than B ('B라기보다 (차라리) A')",
  source_sentence="even the so-called Red Squirrel and the Red Deer are really shades of reddish-brown that conceal rather than advertise.",
  explanation=[GN("쉽게 말하면","'A rather than B'는 'B가 아니라(B라기보다) [[A]]'라며 둘 중 A를 택해 대조해."),
   GN("형태","rather than 앞뒤에는 문법적으로 [[대등한 것]](동사원형↔동사원형, 명사↔명사)이 와 — conceal ↔ advertise."),
   GN("의미","단순 비교가 아니라 'B는 아니고 A다'라는 [[선택·부정]]의 뉘앙스야."),
   GN("해석 요령","'B하기보다 (오히려) A하다'로 옮기고, B(광고)를 부정하고 A(숨김)를 택했음을 잡아.")],
  example="",example_analysis="conceal rather than advertise = '드러내기(광고)보다 숨긴다' — 붉은색 대신 적갈색으로 위장한다는 의미.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 6문장 'shades of reddish-brown that conceal rather than advertise'의 의미로 알맞은 것은?",
    options=["(눈에 띄게) 드러내기보다 오히려 숨기는 적갈색","드러내기 위해 붉게 빛나는 색","광고와 은폐를 모두 하는 색"],
    answer="(눈에 띄게) 드러내기보다 오히려 숨기는 적갈색"),
   GrammarDrill(kind="객관식",from_passage=False,question="'She chose to walk rather than drive.'의 뜻으로 알맞은 것은?",
    options=["운전하기보다 걷기를 택했다","걷기보다 운전을 택했다","걷지도 운전하지도 않았다"],answer="운전하기보다 걷기를 택했다"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'He is a teacher ____ ____ a writer.' (작가라기보다 교사)",
    options=["rather than","other than","more than"],answer="rather than"),
   GrammarDrill(kind="영작",from_passage=False,question="그 동물들은 눈에 띄기보다 배경에 섞인다.",
    words=["the animals","blend in","with the background","rather than","stand out"],answer="The animals blend in with the background rather than stand out."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 6문장 일부) 그것들은 드러내기보다 숨기는 적갈색의 색조이다.",
    words=["they","are","shades of reddish-brown","that","conceal","rather than","advertise"],
    answer="They are shades of reddish-brown that conceal rather than advertise.")]),
 topic="붉은색이 왜 눈에 가장 잘 띄고 위험을 알리는지, 그래서 야생 동물은 왜 붉은색을 피하는지에 관한 글이야.",
 stance="중립적",stance_reason="색의 특성과 동물의 위장을 사실·예시 중심으로 설명하는 정보 전달문이야.",
 structure="주장→근거·예시",structure_reason="'붉은색은 눈에 가장 띈다'는 주장(1~3문장)과 사례(4~5문장) 뒤, 그래서 야생 동물엔 드물다(6~8문장)로 이어져.",
 restatement_chains=[RestatementChain(label="붉은색 = 눈에 띔·경고",
   expressions=["makes the greatest impact on the eye","instantly arresting","charged with alarm and urgency","red is so obvious"],
   variation="'눈에 가장 큰 영향' → '즉각 시선을 사로잡음' → '경고·긴급으로 가득' → '너무 눈에 띔'으로 강조돼."),
  RestatementChain(label="야생동물은 붉은색을 피함",
   expressions=["few wild animals are truly red","conceal rather than advertise","Relatively few butterflies are red"],
   variation="'진짜 붉은 야생동물은 드묾' → '드러내기보다 숨김' → '붉은 나비도 드묾'으로 이어져.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1~3",summary="무지개 색 중 눈에 가장 큰 영향을 주는 색은 붉은색으로, 경고·긴급의 느낌을 준다.",easy_example="빨강을 보면 바로 위험·주의가 떠오르는 것."),
  FlowBlock(stage="사례",sentence_range="4~5",summary="소방차·경고등·적십자처럼, 멀리서 보이게 하려면 우리는 그것을 붉게 칠한다.",easy_example="우체통·소방차를 빨갛게 칠하는 이유."),
  FlowBlock(stage="반전",sentence_range="6",summary="붉은색은 너무 눈에 띄어서, 진짜 붉은 야생동물은 드물고 오히려 드러내기보다 숨긴다.",easy_example="눈에 띄면 잡아먹히니 적갈색으로 숨는 것."),
  FlowBlock(stage="부연",sentence_range="7~8",summary="붉은 나비도 드물고, 유럽에서 완전한 밝은 빨강은 붉은제독나비 하나뿐이다.",easy_example="자연에서 진짜 새빨간 색은 거의 예외인 것.")])
i5=[S(r5,1,[("관계사 that","the one 수식"),("최상급 the greatest","가장 큰 영향")],
  [("impact","영향, 충격")],
  [("Of all the colours of the rainbow","무지개의 모든 색 중에서"),
   ("[[the one that makes the greatest impact on the eye]]","[[눈에 가장 큰 영향을 주는 색은]]"),("is red.","붉은색이다.")],
  [("무지개 색 중 붉은색이 눈에 가장 영향을 적게 준다는 내용이다.","'the greatest impact(가장 큰 영향)'라고 했어 — 붉은색이 눈에 가장 강하게 작용한다는 주제 문장이야.")]),
 S(r5,2,[("There is something ... about","'~에는 ~한 무언가가 있다'"),("현재분사 arresting","형용사적")],
  [("instantly","즉각"),("arresting","시선을 사로잡는")],
  [("There is [[something instantly arresting]]","[[즉각 시선을 사로잡는 무언가가]] 있다"),("about the colour of fire and danger.","불과 위험의 색에는.")],
  [("불과 위험의 색은 사람의 시선을 거의 끌지 못한다는 내용이다.","'instantly arresting(즉각 시선을 사로잡는)'이라고 했어 — 붉은색이 바로 눈길을 끈다는 뜻이야.")]),
 S(r5,3,[("수동 be charged with","'~로 가득 차다'")],
  [("charged with","~로 가득 찬"),("alarm","경고"),("urgency","긴급함")],
  [("It is [[charged with alarm and urgency]].","그것은 [[경고와 긴급함으로 가득 차 있다]].")],
  [("(지칭) 'It'은 불과 위험을 겪은 사람을 가리킨다.","지칭 오인이야. It은 앞의 '붉은색(the colour)'을 가리켜 — 붉은색이 경고·긴급의 느낌을 준다는 거야.")]),
 S(r5,4,[("병렬 명사","fire engines/warning lights/Red Cross")],
  [("fire engine","소방차"),("warning light","경고등")],
  [("We have [[red fire engines, red warning lights and the Red Cross]].","우리에겐 [[붉은 소방차·경고등·적십자]]가 있다.")],
  [("붉은색은 경고·구조와 무관하게 쓰인다는 내용이다.","소방차·경고등·적십자를 예로 들어 — 붉은색이 '경고·위험' 신호로 쓰인다는 사례야.")]),
 S(r5,5,[("조건 if","'~라면'"),("수동 to be seen","'보이도록'")],
  [("from a distance","멀리서"),("kiosk","(공중전화) 부스"),("paint","칠하다")],
  [("[[If we want something to be seen from a distance]],","[[무언가를 멀리서 보이게 하려면]],"),
   ("such as a post box or (formerly) a telephone kiosk,","우체통이나 (예전엔) 공중전화 부스처럼,"),("we paint it red.","우리는 그것을 붉게 칠한다.")],
  [("멀리서 잘 안 보이게 하려고 붉게 칠한다는 내용이다.","'to be seen from a distance(멀리서 보이도록)'가 목적이야 — 눈에 띄게 하려고 빨갛게 칠하는 거야.")]),
 S(r5,6,[("so ... that","'너무 ~해서 …하다'"),("A rather than B","'B라기보다 A'"),("관계사 that","reddish-brown 수식")],
  [("obvious","눈에 띄는"),("conceal","숨기다"),("advertise","드러내다, 광고하다")],
  [("Perhaps it is because red is [[so obvious that few wild animals are truly red]]:","아마 붉은색이 [[너무 눈에 띄어서 진짜 붉은 야생동물이 드문]] 것이다:"),
   ("even the so-called Red Squirrel and the Red Deer","이른바 북방청서와 붉은사슴조차"),
   ("are really shades of reddish-brown [[that conceal rather than advertise]].","실은 [[드러내기보다 숨기는]] 적갈색 색조다.")],
  [("붉은색 이름의 동물들은 실제로도 새빨간 색이라는 내용이다.","이름만 'Red'일 뿐 실제론 '적갈색(reddish-brown)'이라 '드러내기보다 숨긴다(conceal rather than advertise)'는 거야.")]),
 S(r5,7,[("either","'~도 (아니다)'")],
  [("relatively","비교적"),("butterfly","나비")],
  [("Relatively few butterflies are red [[either]].","붉은 나비도 [[마찬가지로]] 비교적 드물다.")],
  [("붉은 나비는 자연에 매우 흔하다는 내용이다.","'few ... either(~도 드물다)'라고 했어 — 붉은 동물처럼 붉은 나비도 드물다는 부연이야.")]),
 S(r5,8,[("only one","'단 하나의'"),("비유 like","'~처럼'"),("콜론(:) 부연","the Red Admiral")],
  [("mainland","본토의"),("full-on","완전한"),("splash","(튄) 자국")],
  [("In Britain, and indeed, in all mainland Europe,","영국, 그리고 실은 유럽 본토 전체에서,"),
   ("[[only one species has a pattern of full-on bright red]], like a splash of blood:","[[단 한 종만 완전한 밝은 빨강 무늬를 지닌다]], 핏방울처럼:"),
   ("the Red Admiral.","바로 붉은제독나비다.")],
  [("(함축) 유럽엔 완전한 밝은 빨강을 지닌 종이 매우 많다는 내용이다.","함축을 놓쳤어. 'only one species(단 한 종)'가 예외라는 뜻 — 완전한 빨강이 자연에 그만큼 드물다는, 앞 주장을 못 박는 마무리야.")])]

DED={'u103':['도치','So did','So+동사'],'u11a':['rather','than'],'u111':['명사절 that','명사절'],
     'u112':['which','전치사+관계'],'u113':['rather than','rather']}
P_u103=finalize(build("단일 재배 농업이 원치 않는 종의 번식을 도운 생태적 결과","Unit10-3",r1,ov1,i1),DED['u103'])
P_u11a=finalize(build("자신을 고양하려는 욕구로 소셜미디어 반응을 확인·삭제하는 십대들의 행동","Unit11-ANALYSIS",r2,ov2,i2),DED['u11a'])
P_u111=finalize(build("예측 실패 시 시점을 바꿔 오류를 회피하는 비관론자들의 전략","Unit11-1",r3,ov3,i3),DED['u111'])
P_u112=finalize(build("개인의 기억과 경험적 대본(script)을 바탕으로 이루어지는 주관적 이해 과정","Unit11-2",r4,ov4,i4),DED['u112'])
P_u113=finalize(build("위험을 알리는 붉은색의 특성과 야생 동물이 이를 기피하는 현상","Unit11-3",r5,ov5,i5),DED['u113'])
OL_ALL=[P_u103,P_u11a,P_u111,P_u112,P_u113]
if __name__=="__main__":
    for p,st in zip(OL_ALL,["ol_u103","ol_u11a","ol_u111","ol_u112","ol_u113"]): out(p,st)
    print("OL DONE")
