# -*- coding: utf-8 -*-
"""EBS 올림포스 영어독해 기본1 Ch05 (Unit13 ANALYSIS/1/2/3 + Unit14 ANALYSIS) 강의컨셉 교재."""
import sys, random
sys.path.insert(0, "/home/user/english_data_making")
from src.lecture_schemas import (Chunk, FlowBlock, GrammarChip, GrammarDrill,
    GrammarNote, KeyGrammar, LecturePassage, LectureSentence, Misread,
    Overview, RestatementChain, SentenceAnalysis, SentenceItem, Vocab)
from src.lecture_render import render_lecture_pdf
import fitz
BASE="/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad"
def mk(r): return [LectureSentence(id=i,text=t) for i,t in enumerate(r,1)]
def S(r,i,g,v,c,m): return SentenceItem(id=i,english=r[i-1],
    grammar=[GrammarChip(tag=a,note=b) for a,b in g],
    vocab=[Vocab(word=w,meaning=k) for w,k in v],
    chunks=[Chunk(en=e,ko=k) for e,k in c],
    misreads=[Misread(statement=s,why=w) for s,w in m])
def GN(c,t): return GrammarNote(chip=c,text=t)
def build(title,src,no,r,ov,items):
    p=LecturePassage(title=title,source=src,item_no=no,sentences=mk(r),
        overview=ov,analysis=SentenceAnalysis(sentences=items)); p.analysis.validate_all(len(r)); return p
def tok(a):
    ws=[w.strip('.,;:!?\"()“”') for w in a.split()]; ws=[w for w in ws if w]
    random.Random(len(a)+sum(map(ord,a[:8]))).shuffle(ws); return ws
_MCQ=[2]  # 객관식 정답 위치 분산 카운터
def finalize(p, dedup):
    TRIV=('전치사구','부사구','부사 ','부사(','의문문','명령문','콜론','there is/are')
    for s in p.analysis.sentences:
        s.grammar=[g for g in s.grammar if not any(t in g.tag for t in TRIV)]
    for d in p.overview.key_grammar.drills:
        if d.kind=='영작': d.words=tok(d.answer)
        if d.kind=='객관식' and d.options:
            others=[o for o in d.options if o!=d.answer]
            pos=_MCQ[0]%len(d.options); d.options=others[:]; d.options.insert(pos,d.answer)
        _MCQ[0]+=1
    return p
def out(p,stem):
    render_lecture_pdf([p],f"{BASE}/{stem}_student.pdf",teacher=False)
    render_lecture_pdf([p],f"{BASE}/{stem}_teacher.pdf",teacher=True)
    d=fitz.open(f"{BASE}/{stem}_student.pdf"); print(stem,d.page_count,'p'); d.close()
S13="EBS 올림포스 영어독해 기본1 · Ch05 Unit13"
S14="EBS 올림포스 영어독해 기본1 · Ch05 Unit14"

# ============ Unit13-ANALYSIS : 연설=의사소통 (not A but B) ============
r1=["One of the biggest reasons people are concerned about making a mistake in a speech is that they view speechmaking as a performance rather than an act of communication.",
"They feel the audience is judging them against a scale of absolute perfection in which every misstated word or awkward gesture will count against them.",
"But speech audiences are not like judges in a violin recital or an ice-skating contest.",
"They are not looking for a virtuoso performance, but for a well-thought-out address that communicates the speaker's ideas clearly and directly.",
"Sometimes an error or two can actually enhance a speaker's appeal by making her or him seem more human."]
ov1=Overview(theme_ko="연설을 공연이 아닌 의사소통으로 인식해야 할 필요성과 실수가 주는 인간적인 매력",
 key_grammar=KeyGrammar(point="상관접속사 not A but B ('A가 아니라 B')",
  source_sentence="They are not looking for a virtuoso performance, but for a well-thought-out address that communicates the speaker's ideas clearly and directly.",
  explanation=[GN("쉽게 말하면","'not A but B'는 A를 부정하고 B를 택해 — '[[A가 아니라 B]]'로 읽어."),
   GN("형태","not 뒤 A, but 뒤 B에는 문법적으로 [[대등한 것]]이 와 — for a performance ↔ for an address."),
   GN("초점","진짜 강조점은 [[B(but 뒤)]]에 있어 — 청중이 원하는 건 '공연'이 아니라 '잘 짜인 연설'."),
   GN("변형","B, not A / not A but (rather) B 등 순서·형태가 바뀌어도 뜻은 [[같아]]."),
   GN("해석 요령","'A가 아니라 (오히려) B'로 옮기고 [[B]]에 무게를 실어.")],
  example="",example_analysis="not looking for a virtuoso performance, but for a well-thought-out address = '고난도 공연이 아니라 잘 짜인 연설을 원한다'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 4문장 'not looking for a virtuoso performance, but for a well-thought-out address'의 의미로 알맞은 것은?",
    options=["청중은 화려한 공연이 아니라 생각을 명확히 전하는 잘 짜인 연설을 원한다","청중은 잘 짜인 연설보다 화려한 공연을 원한다","청중은 공연도 연설도 원하지 않는다"],
    answer="청중은 화려한 공연이 아니라 생각을 명확히 전하는 잘 짜인 연설을 원한다"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'He is ____ a fool ____ a genius.' (바보가 아니라 천재)",
    options=["not / but","both / and","either / or"],answer="not / but"),
   GrammarDrill(kind="객관식",from_passage=False,question="'Success comes not from luck but from effort.'의 뜻으로 알맞은 것은?",
    options=["성공은 운이 아니라 노력에서 온다","성공은 노력이 아니라 운에서 온다","성공은 운과 노력 모두에서 온다"],answer="성공은 운이 아니라 노력에서 온다"),
   GrammarDrill(kind="영작",from_passage=False,question="그것은 벌이 아니라 기회다.",
    answer="It is not a punishment but an opportunity."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 4문장 일부) 그들은 화려한 공연이 아니라 잘 짜인 연설을 원한다.",
    answer="They are not looking for a virtuoso performance but for a well-thought-out address.")]),
 topic="사람들이 연설 실수를 두려워하는 이유는 연설을 '공연'으로 여기기 때문이지만, 청중은 심사위원이 아니며 오히려 실수가 인간미를 더한다는 글이야.",
 stance="긍정적",stance_reason="실수를 두려워 말라며 'enhance appeal'·'seem more human'으로 실수의 긍정적 면을 부각해.",
 structure="통념→반박(반전)",structure_reason="사람들이 연설을 완벽해야 할 '공연'으로 보는 통념(1~2문장) 뒤, 'But 청중은 심사위원이 아니다'로 반박(3~5문장)해.",
 restatement_chains=[RestatementChain(label="완벽주의 압박",
   expressions=["a performance","a scale of absolute perfection","judges in a violin recital or an ice-skating contest"],
   variation="'공연' → '절대적 완벽의 잣대' → '연주회·스케이팅 심사위원'으로 압박이 구체화돼."),
  RestatementChain(label="의사소통 본질",
   expressions=["an act of communication","a well-thought-out address that communicates","seem more human"],
   variation="'의사소통 행위' → '생각을 전하는 잘 짜인 연설' → '더 인간적으로 보임'으로 이어져.")],
 flow_blocks=[FlowBlock(stage="통념",sentence_range="1~2",summary="사람들이 연설 실수를 걱정하는 큰 이유는 연설을 의사소통이 아닌 '공연'으로 보고, 완벽의 잣대로 평가받는다 느끼기 때문이다.",easy_example="단어 하나 틀려도 감점당하는 무대처럼 여기는 것."),
  FlowBlock(stage="반박",sentence_range="3~4",summary="하지만 청중은 연주회·스케이팅 심사위원과 달라, 화려한 공연이 아니라 생각을 명확히 전하는 잘 짜인 연설을 원한다.",easy_example="청중은 점수 매기는 심사위원이 아니라 내용을 들으려는 사람."),
  FlowBlock(stage="결론",sentence_range="5",summary="때로는 한두 실수가 오히려 발표자를 더 인간적으로 보이게 해 매력을 높인다.",easy_example="살짝 실수하면 오히려 친근해 보이는 것.")])
i1=[S(r1,1,[("명사절 that","is의 보어(is that ~)"),("A rather than B","'B라기보다 A'")],
  [("be concerned about","~을 걱정하다"),("speechmaking","연설(하기)"),("act of communication","의사소통 행위")],
  [("One of the biggest reasons people are [[concerned about making a mistake]] in a speech","사람들이 연설에서 [[실수하는 것을 걱정하는]] 가장 큰 이유 중 하나는"),
   ("is that they [[view speechmaking]]","그들이 [[연설을 여긴다는]] 것이다"),
   ("[[as a performance rather than an act of communication]].","[[의사소통 행위라기보다 공연으로]].")],
  [("이 문장은 연설 실수를 줄이는 구체적 방법을 알려주는 문장이다.","'가장 큰 이유 중 하나는 ~ 때문이다(is that ~)'로 실수를 두려워하는 '이유'를 짚는 주제·도입 문장이야 — 방법 제시가 아니야.")]),
 S(r1,2,[("관계사 in which","perfection 수식"),("명사절 생략","feel (that) ~")],
  [("audience","청중"),("misstated","잘못 말한"),("awkward","어색한"),("count against","~에게 불리하게 작용하다")],
  [("They feel the audience is [[judging]] them","그들은 청중이 자신을 [[평가한다고]] 느낀다"),
   ("against a scale of [[absolute perfection]]","[[절대적 완벽]]이라는 잣대로"),
   ("[[in which every misstated word or awkward gesture will count against them]].","[[잘못 말한 단어나 어색한 제스처 하나하나가 자신에게 불리하게 작용하는]].")],
  [("그들은 청중이 사소한 실수를 너그럽게 봐줄 거라 느낀다는 내용이다.","'against a scale of absolute perfection(절대적 완벽의 잣대로)' 평가받는다고 '느낀다'는 거야 — 너그러움이 아니라 냉혹한 완벽주의 압박을 느낀다는 뜻.")]),
 S(r1,3,[("비교 not like","'~와 같지 않다'")],
  [("recital","연주회"),("contest","대회, 시합")],
  [("But speech audiences are [[not like]]","하지만 연설의 청중은 [[~와 같지 않다]]"),
   ("judges in a violin recital or an ice-skating contest.","바이올린 연주회나 아이스 스케이팅 대회의 [[심사위원]]과.")],
  [("이 문장은 연설 청중이 심사위원처럼 엄격하다는 앞 내용을 뒷받침한다.","'But(하지만)'으로 방향을 틀어 '청중은 심사위원과 다르다'고 반박하는 전환 문장이야 — 앞 완벽주의 통념을 뒤집어.")]),
 S(r1,4,[("관계사 that","address 수식")],
  [("virtuoso","(고도의) 기교의, 거장의"),("well-thought-out","잘 숙고된"),("address","연설")],
  [("They are not looking for a [[virtuoso performance]],","그들은 [[고도의 기교를 보여 주는 공연]]을 원하는 게 아니라,"),
   ("[[but for a well-thought-out address]]","[[오히려 잘 짜인 연설을 (원한다)]]"),
   ("that communicates the speaker's ideas [[clearly and directly]].","연설자의 생각을 [[명확하고 직접적으로]] 전달하는.")],
  [("(지칭) 'They'는 연주회·스케이팅 대회의 심사위원을 가리킨다.","지칭 오인이야. They는 앞의 'speech audiences(연설 청중)'를 가리켜 — 청중이 원하는 건 공연이 아니라 잘 짜인 연설이라는 거야.")]),
 S(r1,5,[("by -ing","'~함으로써'"),("make + 목적어 + 원형","'~을 …하게 하다'")],
  [("enhance","높이다, 향상시키다"),("appeal","매력"),("seem","~처럼 보이다")],
  [("Sometimes an error or two can actually [[enhance a speaker's appeal]]","때로는 한두 실수가 실제로 [[발표자의 매력을 높일]] 수 있다"),
   ("[[by making her or him seem more human]].","[[그 사람을 더 인간적으로 보이게 함으로써]].")],
  [("(함축) 실수는 발표자의 신뢰를 떨어뜨려 청중을 실망시킨다는 내용이다.","함축을 놓쳤어. 'enhance a speaker's appeal … seem more human(매력을 높이고 더 인간적으로 보이게)'이라며 실수의 '긍정적' 효과를 말해 — 실망이 아니라 친근함이야.")])]

# ============ Unit13-1 : 인간 건설 생태계 (분사구문) ============
r2=["Some ecosystems, over a wide range of sites and purposes, are constructed by humans.",
"For example, we may construct shallow ponds or a series of canals known as bioswales that collect runoff of surface water.",
"Marsh plants, such as cattails, when planted in ponds or canals, use and remove nutrients in water that's delivered to them as a waste or pollutant, helping clean the water.",
"Specially designed wetland ecosystems have been constructed where bacteria and plants process mine wastewater and help remove toxins from water.",
"Other large-scale ecosystems are constructed to partially treat urban wastewater.",
"Human-constructed ecosystems are part of what is known as biological engineering."]
ov2=Overview(theme_ko="수질 정화와 폐기물 처리를 위해 생물 공학적으로 설계·건설되는 인간 건설 생태계의 기능",
 key_grammar=KeyGrammar(point="분사구문 (부사절을 -ing/-ed로 줄인 것)",
  source_sentence="Marsh plants, such as cattails, when planted in ponds or canals, use and remove nutrients …, helping clean the water.",
  explanation=[GN("쉽게 말하면","분사구문은 '접속사+주어'를 지우고 동사를 [[-ing/-ed]]로 바꿔 부사절을 간결히 줄인 거야."),
   GN("두 형태","when planted = when they [[are planted]](수동, 접속사 남김), helping = and [[it helps]](능동, 결과)."),
   GN("의미상 주어","분사의 주인은 주절 주어와 [[같아]] — 여기선 Marsh plants."),
   GN("접속사 남김","뜻을 분명히 하려고 when·while 등 접속사를 [[남겨]] 두기도 해(when planted)."),
   GN("해석 요령","'~할 때 / ~하면서(그 결과)'로 앞뒤 절에 자연스럽게 이어 붙여.")],
  example="",example_analysis="when planted in ponds …, (marsh plants) use and remove nutrients …, helping clean the water = '심어지면 영양분을 사용·제거하고, (그 결과) 물을 정화하면서'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 3문장 'when planted in ponds or canals'의 의미로 알맞은 것은?",
    options=["(습지 식물이) 연못이나 수로에 심어지면","연못이나 수로를 심으면","심는 것을 좋아하면"],
    answer="(습지 식물이) 연못이나 수로에 심어지면"),
   GrammarDrill(kind="객관식",from_passage=False,question="밑줄 친 부분이 '분사구문'인 것은?",
    options=["Feeling tired, she went to bed.","The girl feeling tired is my sister.","This is a feeling of joy."],
    answer="Feeling tired, she went to bed."),
   GrammarDrill(kind="객관식",from_passage=False,question="'The plants absorb water, ____ the soil dry.' 빈칸에 알맞은 것은?",
    options=["leaving","left","to leave"],answer="leaving"),
   GrammarDrill(kind="영작",from_passage=False,question="연못에 심어지면, 그 식물들은 물을 정화한다.",
    answer="When planted in ponds, the plants clean the water."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 3문장 일부) 습지 식물은 물속의 영양분을 사용·제거하여 물을 정화하는 데 도움이 된다.",
    answer="Marsh plants use and remove nutrients in water, helping clean the water.")]),
 topic="인간이 수질 정화·폐기물 처리 같은 목적으로 다양한 생태계를 설계·건설한다는, 생물 공학의 예에 관한 글이야.",
 stance="중립적",stance_reason="인간이 건설한 생태계의 기능을 사례 중심으로 설명하는 정보 전달문이야.",
 structure="주장→근거·예시",structure_reason="'일부 생태계는 인간이 건설한다'는 진술(1문장) 뒤, 식생수로·습지·대규모 생태계 사례(2~5문장)를 들고 '생물 공학'으로 일반화(6문장)해.",
 restatement_chains=[RestatementChain(label="인간이 건설한 생태계",
   expressions=["constructed by humans","Specially designed wetland ecosystems","Human-constructed ecosystems"],
   variation="'인간이 건설' → '특별히 설계된 습지 생태계' → '인간이 건설한 생태계'로 반복·강조돼."),
  RestatementChain(label="물 정화 기능",
   expressions=["collect runoff of surface water","helping clean the water","remove toxins from water","treat urban wastewater"],
   variation="'지표수 모으기' → '물 정화' → '독소 제거' → '도시 폐수 처리'로 기능이 나열돼.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1",summary="매우 다양한 장소·목적으로 일부 생태계는 인간이 건설한다.",easy_example="사람이 일부러 만든 '인공 생태계'가 있다는 것."),
  FlowBlock(stage="예시1",sentence_range="2~3",summary="예를 들어 지표수를 모으는 식생수로를 만들고, 부들 같은 습지 식물이 오염물질 영양분을 흡수·제거해 물을 정화한다.",easy_example="습지 식물을 심어 물을 깨끗이 하는 것."),
  FlowBlock(stage="예시2",sentence_range="4~5",summary="박테리아·식물이 광산 폐수를 처리하는 습지, 도시 폐수를 처리하는 대규모 생태계도 건설된다.",easy_example="폐수를 자연의 힘으로 처리하도록 설계한 것."),
  FlowBlock(stage="결론",sentence_range="6",summary="이런 인간이 건설한 생태계는 '생물 공학'으로 불리는 것의 일부다.",easy_example="이 모두가 '생물 공학'이라는 분야에 속하는 것.")])
i2=[S(r2,1,[("수동태 are constructed","'건설된다'")],
  [("ecosystem","생태계"),("a wide range of","광범위한"),("construct","건설하다")],
  [("Some ecosystems, over a [[wide range of sites and purposes]],","매우 [[다양한 장소와 목적]]에 걸쳐, 일부 생태계는"),
   ("are constructed by [[humans]].","[[인간]]에 의해 건설된다.")],
  [("이 문장은 자연 생태계가 스스로 형성되는 과정을 설명하는 문장이다.","'are constructed by humans(인간에 의해 건설된다)'가 핵심 — 일부 생태계는 인간이 '만든다'는 이 글의 주제·도입 문장이야.")]),
 S(r2,2,[("관계사 that","canals 수식"),("분사 known as","'~로 알려진'")],
  [("shallow","얕은"),("canal","운하, 수로"),("runoff","흘러가는 물, 유출수")],
  [("For example, we may construct shallow ponds or a series of canals [[known as bioswales]]","예를 들어, 우리는 얕은 연못이나 [[식생수로라 알려진]] 일련의 수로를 건설할 수 있다"),
   ("[[that collect runoff of surface water]].","[[지표수의 흐르는 물을 모으는]].")],
  [("이 문장은 식생수로가 물을 오염시킨다는 문제를 지적한다.","'For example(예를 들어)'로 시작해 인공 생태계의 첫 사례(지표수를 모으는 식생수로)를 드는 전개 문장이야 — 오염이 아니라 물 관리 목적이야.")]),
 S(r2,3,[("관계사 that","water 수식")],
  [("marsh","습지"),("cattail","부들"),("nutrient","영양분"),("pollutant","오염 물질")],
  [("[[Marsh plants, such as cattails, when planted in ponds or canals]],","[[부들 같은 습지 식물은, 연못이나 수로에 심어지면]],"),
   ("use and remove [[nutrients]] in water that's delivered to them as a waste or pollutant,","폐기물이나 오염물질로 그것들에게 전달되는 물속 [[영양분]]을 사용·제거하여,"),
   ("helping [[clean the water]].","물을 [[정화하는]] 데 도움이 된다.")],
  [("(지칭) 'them'은 오염 물질(pollutant)을 가리킨다.","지칭 오인이야. delivered to them의 them은 앞의 'Marsh plants(습지 식물)'를 가리켜 — 오염물질이 식물에게 전달된다는 뜻이야.")]),
 S(r2,4,[("수동태 have been constructed","'건설되어 왔다'"),("관계부사 where","ecosystems 부연")],
  [("wetland","습지"),("wastewater","폐수"),("toxin","독소")],
  [("[[Specially designed]] wetland ecosystems have been constructed","[[특별히 설계된]] 습지 생태계가 건설되어 왔다"),
   ("[[where bacteria and plants process mine wastewater and help remove toxins from water]].","[[박테리아와 식물이 광산 폐수를 처리하고 물에서 독소를 제거하는]].")],
  [("특별히 설계된 습지 생태계는 광산 폐수를 더 오염시킨다는 내용이다.","'process mine wastewater and help remove toxins(폐수를 처리하고 독소를 제거한다)'는 거야 — 오염이 아니라 정화 기능이야.")]),
 S(r2,5,[("부정사 to treat","'처리하기 위해'")],
  [("large-scale","대규모의"),("partially","부분적으로"),("urban","도시의")],
  [("Other [[large-scale]] ecosystems are constructed","다른 [[대규모]] 생태계가 건설된다"),
   ("[[to partially treat urban wastewater]].","[[도시 폐수를 부분적으로 처리하기 위해]].")],
  [("대규모 생태계는 도시 폐수를 완전히 정화한다는 내용이다.","'partially treat(부분적으로 처리한다)'라고 했어 — 완전 정화가 아니라 일부를 처리한다는 거야.")]),
 S(r2,6,[("관계사 what","'~라고 알려진 것'")],
  [("biological engineering","생물 공학")],
  [("[[Human-constructed]] ecosystems are part of","[[인간이 건설한]] 생태계는 ~의 일부다"),
   ("[[what is known as biological engineering]].","[['생물 공학'이라 알려진 것]]의.")],
  [("(함축) 이 문장은 인간이 만든 생태계가 자연 생태계와 무관하다는 뜻이다.","함축을 놓쳤어. 'part of what is known as biological engineering(생물 공학의 일부)'이라며 앞 사례들을 하나의 학문 분야로 묶는 일반화·결론이야.")])]

# ============ Unit13-2 : 비음성 모바일 소통 (so...that) ============
r3=["Mobile communications have changed the way we interact with our computers and, as more time is spent on mobile devices, emoticon use has followed.",
"Cellular phones, smartphones, tablets, and similar technologies have penetrated the world at an enormous rate and non-voice communications have become the norm rather than the rule.",
"In 2013, the number of mobile subscriptions almost equaled the estimated number of individuals that made up the global population in the same year.",
"Users of these technologies have posted, pinned, tweeted, sent and/or received billions of electronic messages through public or private (text messages, emails, etc.) means.",
"These communications media have become so prolific, researchers have worried that face-to-face communications could become extinct."]
ov3=Overview(theme_ko="비음성 모바일 소통의 급격한 확산에 따른 대면 소통 소멸에 대한 우려",
 key_grammar=KeyGrammar(point="so + 형용사/부사 + (that) 절 (강조·결과: '너무 ~해서 …하다')",
  source_sentence="These communications media have become so prolific, (that) researchers have worried that face-to-face communications could become extinct.",
  explanation=[GN("쉽게 말하면","so + 형용사/부사 뒤에 '(that) 주어+동사'가 오면 '너무 ~해서 [[…하다]]'라는 정도·결과야."),
   GN("that 생략","회화·글에서 결과절의 [[that]]이 자주 생략돼 — so prolific, (that) researchers worried."),
   GN("정도↔결과","'so prolific(너무 많음)'이 원인, 뒤 절이 그로 인한 [[결과]]야."),
   GN("such와 구별","'so + 형용사'는 뒤에 절, 뒤에 [[명사]]가 오면 'such + (a) 명사 + that'을 써."),
   GN("해석 요령","'너무/매우 ~해서, (그 결과) [[…하다]]'로 앞뒤를 인과로 이어.")],
  example="",example_analysis="have become so prolific, (that) researchers have worried … = '너무 많아져서, (그 결과) 연구자들이 … 걱정하게 되었다'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 5문장 'have become so prolific, researchers have worried'의 의미·구조로 알맞은 것은?",
    options=["통신 매체가 너무 많아져서, (그 결과) 연구자들이 대면 소통 소멸을 걱정하게 되었다","연구자들이 걱정해서 통신 매체가 많아졌다","통신 매체와 걱정은 서로 무관하다"],
    answer="통신 매체가 너무 많아져서, (그 결과) 연구자들이 대면 소통 소멸을 걱정하게 되었다"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'He was ____ tired ____ he fell asleep at once.'",
    options=["so / that","such / that","too / to"],answer="so / that"),
   GrammarDrill(kind="객관식",from_passage=False,question="어법상 올바른 문장은?",
    options=["It was so hot that we stayed inside.","It was such hot that we stayed inside.","It was so a hot day that we stayed inside."],
    answer="It was so hot that we stayed inside."),
   GrammarDrill(kind="영작",from_passage=False,question="그 책은 너무 어려워서 나는 그것을 이해할 수 없었다.",
    answer="The book was so difficult that I couldn't understand it."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 5문장 일부) 이러한 통신 매체가 너무 많아져서 연구자들은 대면 소통이 소멸할 수 있다고 우려해 왔다.",
    answer="These communications media have become so prolific that researchers have worried that face-to-face communications could become extinct.")]),
 topic="모바일 기기·비음성 소통이 급격히 확산하면서, 대면 소통이 사라질 수 있다는 우려에 관한 글이야.",
 stance="중립적",stance_reason="비음성 소통의 확산을 통계·사실 중심으로 서술하고, 끝에 연구자들의 우려를 전달해.",
 structure="주장→근거·예시",structure_reason="'모바일이 소통 방식을 바꿨다'는 주장(1~2문장) 뒤, 2013년 통계·메시지 이용(3~4문장)을 근거로 들고 '대면 소통 소멸 우려'로 마무리(5문장)해.",
 restatement_chains=[RestatementChain(label="비음성 소통 확산",
   expressions=["emoticon use has followed","non-voice communications have become the norm","billions of electronic messages","so prolific"],
   variation="'이모티콘 사용' → '비음성 소통이 표준' → '수십억 전자 메시지' → '너무 많아짐'으로 확산이 강조돼."),
  RestatementChain(label="확산의 규모",
   expressions=["penetrated the world at an enormous rate","almost equaled the estimated number of individuals"],
   variation="'엄청난 속도로 전 세계에 침투' → '전 세계 인구수와 거의 맞먹음'으로 규모가 구체화돼.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1~2",summary="모바일 통신이 소통 방식을 바꿔 이모티콘 같은 비음성 소통이 규칙이 아닌 표준이 되었다.",easy_example="전화 대신 문자·이모티콘으로 소통하는 게 당연해진 것."),
  FlowBlock(stage="근거",sentence_range="3~4",summary="2013년 모바일 가입 수가 전 세계 인구와 맞먹었고, 이용자들은 수십억 개의 전자 메시지를 주고받았다.",easy_example="거의 모든 사람이 폰으로 메시지를 쏟아낸 것."),
  FlowBlock(stage="결론",sentence_range="5",summary="이런 통신 매체가 너무 많아져서, 연구자들은 대면 소통이 소멸할 수 있다고 우려해 왔다.",easy_example="온라인 소통이 넘쳐 얼굴 보고 하는 대화가 사라질까 걱정하는 것.")])
i3=[S(r3,1,[("관계부사 the way","'~하는 방식'"),("수동 is spent","'소비되다'")],
  [("interact with","~와 상호 작용하다"),("emoticon","이모티콘"),("follow","뒤따르다")],
  [("Mobile communications have [[changed the way we interact]] with our computers","모바일 통신은 우리가 컴퓨터와 [[상호작용하는 방식을 바꿨다]]"),
   ("and, as more time is spent on [[mobile devices]],","그리고, 더 많은 시간이 [[모바일 기기]]에 쓰이면서,"),
   ("[[emoticon use]] has followed.","[[이모티콘 사용]]이 뒤따랐다.")],
  [("이 문장은 모바일 통신이 컴퓨터 사용을 줄였다는 문제를 지적한다.","'have changed the way we interact(상호작용 방식을 바꿨다)'며 이모티콘 사용으로 이어졌다는, 글의 주제·도입 문장이야 — 사용 감소가 아니라 방식 변화야.")]),
 S(r3,2,[("A rather than B","'B가 아니라 A'"),("현재완료 have penetrated","'침투해 왔다'")],
  [("penetrate","침투하다"),("enormous","엄청난"),("norm","표준, 기준")],
  [("Cellular phones, smartphones, tablets, and similar technologies have penetrated the world at an [[enormous rate]]","휴대폰·스마트폰·태블릿 등 유사 기술이 [[엄청난 속도]]로 전 세계에 침투했고"),
   ("[[and non-voice communications have become the norm rather than the rule]].","[[비음성 소통이 규칙이 아닌 표준이 되었다]].")],
  [("(함축) 'the norm rather than the rule'은 비음성 소통이 여전히 예외적이라는 뜻이다.","함축을 놓쳤어. 'the norm(표준)이 되었다'는 건 비음성 소통이 이제 예외가 아니라 '일반적 관행'이 됐다는 뜻이야.")]),
 S(r3,3,[("관계사 that","individuals 수식")],
  [("subscription","가입(건)"),("estimated","추정된"),("make up","구성하다")],
  [("In 2013, the number of mobile subscriptions [[almost equaled]]","2013년, 모바일 가입 건수는 [[거의 맞먹었다]]"),
   ("[[the estimated number of individuals that made up the global population in the same year]].","[[같은 해 전 세계 인구를 구성한 추정 인구수]]와.")],
  [("2013년 모바일 가입 건수는 세계 인구보다 훨씬 적었다는 내용이다.","'almost equaled the estimated number of individuals(추정 인구수와 거의 같았다)'는 거야 — 훨씬 적은 게 아니라 인구수에 맞먹었다는 뜻.")]),
 S(r3,4,[("병렬 동사","posted·pinned·tweeted·sent·received")],
  [("post","게시하다"),("means","수단"),("billions of","수십억의")],
  [("Users of these technologies have [[posted, pinned, tweeted, sent and/or received]]","이 기술 이용자들은 [[게시하고, 고정하고, 트윗하고, 송·수신했다]]"),
   ("[[billions of]] electronic messages through public or private (text messages, emails, etc.) means.","공개·사적 (문자·이메일 등) 수단으로 [[수십억 개]]의 전자 메시지를.")],
  [("(지칭) 'these technologies'는 공개·사적 메시지를 가리킨다.","지칭 오인이야. these technologies는 앞의 '휴대폰·스마트폰·태블릿 등'을 가리켜 — 그 이용자들이 수십억 메시지를 주고받았다는 거야.")]),
 S(r3,5,[("명사절 that","worried의 목적어")],
  [("prolific","(수가) 많은, 왕성한"),("extinct","소멸한, 멸종한"),("face-to-face","대면의")],
  [("These communications media have become [[so prolific]],","이러한 통신 매체가 [[너무 많아져서]],"),
   ("[[researchers have worried that face-to-face communications could become extinct]].","[[연구자들은 대면 소통이 소멸할 수 있다고 우려해 왔다]].")],
  [("이 문장은 대면 소통이 늘어나고 있다는 새로운 사실을 소개한다.","'so prolific … could become extinct(너무 많아져서 대면 소통이 소멸할 수 있다)'며 연구자들의 우려로 글을 맺는 결론 문장이야 — 대면 소통 증가가 아니라 소멸 우려야.")])]

# ============ Unit13-3 : 아이 짜증 진정 (부정사 목적) ============
r4=["When a region of the emotional brain is overexcited due to frustration, sadness or any other intense emotion, the child is not able to contain their mood.",
"This is when the tantrums occur — situations in which the child closes in on themself and is not able to do what they are told — or comments are made which the parents find hard to deal with.",
"Literally, the child is outside themselves, outside their rational part.",
"To help them calm down, and to see reason, the best strategy is a hug and an empathic reflection of the situation to defuse the intensity of the emotion.",
"A spoken word will form a bridge between the two worlds, allowing the child's rational brain to help soothe their emotions, or at least give them the ability to listen to what their parents are saying."]
ov4=Overview(theme_ko="감정적으로 흥분한 아이의 짜증을 진정시키기 위한 포옹과 공감적 반응의 중요성",
 key_grammar=KeyGrammar(point="부정사의 부사적 용법 · 목적 ('~하기 위해')",
  source_sentence="To help them calm down, and to see reason, the best strategy is a hug and an empathic reflection of the situation to defuse the intensity of the emotion.",
  explanation=[GN("쉽게 말하면","to + 동사원형이 '[[~하기 위해]]'라는 '목적'을 나타내며 문장을 꾸며."),
   GN("위치","문장 맨 앞의 'To help …,'처럼 [[콤마]]로 주절과 나뉘어 목적을 먼저 밝히기도 해."),
   GN("여러 개","여기선 To help … / to see … / to defuse …처럼 목적 부정사가 [[여러 개]] 쓰였어."),
   GN("강조형","'in order to'·'so as to'로 바꿔 써도 뜻은 [[같아]] — 목적을 분명히 할 때 써."),
   GN("해석 요령","'~하기 위해 / ~하려고'로 옮기고, 그 목적을 이루는 [[수단]](주절)과 연결해.")],
  example="",example_analysis="To help them calm down …, the best strategy is a hug … to defuse the intensity = '진정시키기 위해 최선의 전략은 포옹이며, (그것은) 감정 강도를 누그러뜨리기 위한 것'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 4문장 'To help them calm down'의 의미·기능으로 알맞은 것은?",
    options=["'그들을 진정시키기 위해'라는 목적을 나타낸다","'그들을 돕는 것'이라는 주어다","'도움받은'이라는 수동의 뜻이다"],
    answer="'그들을 진정시키기 위해'라는 목적을 나타낸다"),
   GrammarDrill(kind="객관식",from_passage=False,question="밑줄 친 부분이 '목적'의 부정사인 것은?",
    options=["She got up early to catch the train.","She wants to catch the train.","To catch the train is hard."],
    answer="She got up early to catch the train."),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'He studied hard ____ the exam.' (시험에 합격하기 위해)",
    options=["in order to pass","for passing","that he passes"],answer="in order to pass"),
   GrammarDrill(kind="영작",from_passage=False,question="그를 진정시키기 위해, 그녀는 그를 안아 주었다.",
    answer="To calm him down, she gave him a hug."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 4문장 일부) 그들을 진정시키기 위한 최선의 전략은 포옹과 공감적 반영이다.",
    answer="To help them calm down, the best strategy is a hug and an empathic reflection.")]),
 topic="감정적으로 흥분해 짜증(tantrum)을 부리는 아이를 진정시키는 데, 포옹과 공감적 반응(그리고 한마디 말)이 가장 효과적이라는 글이야.",
 stance="긍정적",stance_reason="포옹·공감적 반영을 'the best strategy'로 제시하고, 말이 '다리'가 된다며 그 효과를 적극 권해.",
 structure="문제→해결(방안)",structure_reason="감정 흥분으로 아이가 짜증을 부리는 '문제'(1~3문장) 뒤, 포옹·공감·말이라는 '해결책'(4~5문장)을 제시해.",
 restatement_chains=[RestatementChain(label="아이의 감정 폭발",
   expressions=["overexcited","not able to contain their mood","the tantrums","outside their rational part"],
   variation="'과도하게 흥분' → '기분을 억누르지 못함' → '짜증' → '이성 밖에 있음'으로 상태가 심화돼."),
  RestatementChain(label="진정시키는 해결책",
   expressions=["a hug and an empathic reflection","defuse the intensity of the emotion","form a bridge between the two worlds","soothe their emotions"],
   variation="'포옹과 공감적 반영' → '감정 강도 누그러뜨림' → '두 세계의 다리' → '감정 진정'으로 이어져.")],
 flow_blocks=[FlowBlock(stage="문제-원인",sentence_range="1",summary="좌절·슬픔 등 강렬한 감정으로 정서적 뇌가 과도하게 흥분하면, 아이는 기분을 억누르지 못한다.",easy_example="감정이 폭발하면 스스로 못 다스리는 것."),
  FlowBlock(stage="문제-양상",sentence_range="2~3",summary="이때 짜증이 터지는데, 아이는 자신을 가두고 들은 말을 못 하며, 말 그대로 이성 밖에 있다.",easy_example="떼쓰는 순간엔 말이 안 통하는 상태."),
  FlowBlock(stage="해결",sentence_range="4",summary="진정시키고 사리를 분별하게 하려면, 포옹과 공감적 반영으로 감정 강도를 누그러뜨리는 것이 최선이다.",easy_example="혼내기보다 안아 주고 마음을 읽어 주는 것."),
  FlowBlock(stage="해결-보충",sentence_range="5",summary="한마디 말이 두 세계에 다리를 놓아 아이의 이성적 뇌가 감정을 달래거나, 적어도 부모 말을 들을 수 있게 한다.",easy_example="따뜻한 말 한마디가 아이를 다시 대화로 이끄는 것.")])
i4=[S(r4,1,[("접속사 when","'~할 때'"),("수동 is overexcited","'과도하게 흥분되다'")],
  [("overexcited","과도하게 흥분한"),("frustration","좌절(감)"),("contain","억누르다, 담다")],
  [("[[When a region of the emotional brain is overexcited due to frustration, sadness or any other intense emotion]],","[[좌절, 슬픔 또는 다른 강렬한 감정으로 정서적 뇌의 한 부위가 과도하게 흥분하면]],"),
   ("the child is not able to [[contain their mood]].","아이는 자신의 [[기분을 억누를]] 수 없게 된다.")],
  [("(지칭) 'their mood'는 부모의 기분을 가리킨다.","지칭 오인이야. contain their mood의 their는 앞의 'the child(아이)'를 가리켜 — 아이가 자기 기분을 억누르지 못한다는 뜻이야.")]),
 S(r4,2,[("전치사+관계 in which","situations 수식"),("관계사 which","comments 수식"),("관계사 what","'~하는 것'")],
  [("tantrum","짜증, 떼쓰기"),("close in on","~을 옥죄다, 가두다"),("deal with","다루다, 감당하다")],
  [("This is when the tantrums occur — [[situations in which the child closes in on themself]]","이때가 짜증이 발생하는 때다 — [[아이가 자신을 가두는 상황]],"),
   ("and is not able to do [[what they are told]] —","그리고 [[들은 말]]을 할 수 없는 —"),
   ("or comments are made which the parents [[find hard to deal with]].","혹은 부모가 [[감당하기 힘든]] 말이 나오는.")],
  [("이 문장은 아이가 스스로 마음을 열고 부모 말을 잘 따르는 상황을 묘사한다.","'closes in on themself and is not able to do what they are told(자신을 가두고 들은 말을 못 한다)'는 거야 — 마음을 여는 게 아니라 닫히고 통제 불능이 되는 짜증 상황이야.")]),
 S(r4,3,[("재귀대명사 themselves","주어=목적어")],
  [("literally","말 그대로"),("rational","이성적인")],
  [("[[Literally]], the child is outside themselves,","[[말 그대로]], 아이는 자신 밖에 있다,"),
   ("[[outside their rational part]].","[[자신의 이성적인 부분 밖에 (있다)]].")],
  [("(함축) 'outside their rational part'는 아이가 논리적으로 침착하게 사고한다는 뜻이다.","함축을 놓쳤어. '이성적 부분 밖에 있다'는 건 아이가 지금 이성적으로 사고하지 '못하는' 상태라는 뜻 — 그래서 논리적 설득이 안 통해.")]),
 S(r4,4,[("명사 보어","the best strategy is a hug")],
  [("empathic","공감적인"),("reflection","반영, 비추기"),("defuse","(긴장을) 누그러뜨리다"),("intensity","강도")],
  [("[[To help them calm down, and to see reason]],","[[그들을 진정시키고 사리를 분별하도록 돕기 위해]],"),
   ("the best strategy is a hug and an [[empathic reflection]] of the situation","최선의 전략은 포옹과 상황에 대한 [[공감적 반영]]이다"),
   ("to [[defuse the intensity]] of the emotion.","감정의 [[강도를 누그러뜨리기]] 위한.")],
  [("이 문장은 아이의 짜증이 왜 위험한지 그 원인을 설명한다.","'the best strategy is a hug and an empathic reflection(최선의 전략은 포옹과 공감적 반영)'으로 넘어가는, 문제에서 '해결책'으로의 전환 문장이야.")]),
 S(r4,5,[("분사구문 allowing","'~하게 하면서'"),("관계사 what","'~하는 것'")],
  [("form a bridge","다리를 놓다"),("soothe","달래다"),("at least","적어도")],
  [("A spoken word will [[form a bridge]] between the two worlds,","한마디 말은 두 세계 사이에 [[다리를 놓을]] 것이다,"),
   ("[[allowing the child's rational brain to help soothe their emotions]],","[[아이의 이성적 뇌가 감정을 달래도록 도우면서]],"),
   ("or at least give them the ability to listen to [[what their parents are saying]].","혹은 적어도 부모가 하는 말을 [[들을 능력]]을 아이에게 줄.")],
  [("이 문장은 아이에게 말을 거는 것이 오히려 감정을 악화시킨다는 내용이다.","'form a bridge … help soothe their emotions(다리를 놓아 감정을 달래도록 돕는다)'는 거야 — 말이 악화가 아니라 진정과 소통의 다리가 된다는 결론이야.")])]

# ============ Unit14-ANALYSIS : 방관자 효과 (the 비교급, the 비교급) ============
r5=["Social psychology tells us that bystanders in emergency situations are acting normally when they fail to respond.",
"We would fail to respond as well.",
"That social psychological insight makes us uncomfortable.",
"We like to feel we would behave differently, better.",
"The problem with bystanders, however, does not stem from defects in their character that prevent them from helping.",
"Rather, the situation that bystanders find themselves in constrains their behavior more than we realize.",
"For example, the more bystanders there are, the less likely any one of them will intervene.",
"A single bystander at the scene of an emergency would usually respond, just as we hope we would.",
"But when a number of bystanders witness an emergency, responsibility apparently diffuses among them, getting weaker.",
"No one bystander feels enough personal responsibility to respond."]
ov5=Overview(theme_ko="위급 상황에서 타인의 존재로 인해 책임감이 분산되어 발생하는 방관자 효과",
 key_grammar=KeyGrammar(point="the 비교급 ~, the 비교급 ~ ('~하면 할수록 더 …하다')",
  source_sentence="For example, the more bystanders there are, the less likely any one of them will intervene.",
  explanation=[GN("쉽게 말하면","'the 비교급 A, the 비교급 B'는 'A할수록 (그만큼) 더 [[B하다]]'라는 비례 관계야."),
   GN("두 짝","앞 the절은 [[조건·원인]], 뒤 the절은 그에 따른 [[결과]] — 둘은 함께 움직여."),
   GN("어순","각 the 뒤에 비교급을 먼저 내세우고 '주어+동사'가 이어져 — the more bystanders there are …."),
   GN("의미","여기선 '방관자가 많을수록, 개입 가능성은 더 [[낮아진다]]'는 반비례야."),
   GN("해석 요령","'~하면 할수록 (그만큼) 더 …하다'로 두 the절을 하나로 묶어 옮겨.")],
  example="",example_analysis="the more bystanders there are, the less likely any one … will intervene = '방관자가 많을수록, 누구든 개입할 가능성은 더 낮아진다'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 7문장 'the more bystanders there are, the less likely any one of them will intervene'의 의미로 알맞은 것은?",
    options=["방관자가 많을수록 누구든 개입할 가능성이 더 낮아진다","방관자가 많을수록 더 빨리 개입한다","방관자 수는 개입과 관련이 없다"],
    answer="방관자가 많을수록 누구든 개입할 가능성이 더 낮아진다"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'The higher you climb, ____ colder it gets.'",
    options=["the","more","so"],answer="the"),
   GrammarDrill(kind="객관식",from_passage=False,question="'The more we have, the more we want.'의 뜻으로 알맞은 것은?",
    options=["많이 가질수록 더 많이 원한다","많이 원할수록 더 많이 가진다","많이 가져도 원하지 않는다"],answer="많이 가질수록 더 많이 원한다"),
   GrammarDrill(kind="영작",from_passage=False,question="우리가 더 많이 연습할수록, 우리는 더 나아진다.",
    answer="The more we practice, the better we become."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 7문장) 방관자가 많을수록, 그들 중 누구든 개입할 가능성이 더 낮아진다.",
    answer="The more bystanders there are, the less likely any one of them will intervene.")]),
 topic="위급 상황에서 방관자가 반응하지 않는 것은 성격 결함이 아니라, 타인의 존재로 책임감이 분산되기 때문이라는 '방관자 효과'에 관한 글이야.",
 stance="중립적",stance_reason="사회 심리학의 방관자 효과를 사실·원리 중심으로 설명하며, 방관자를 도덕적으로 비난하기보다 상황 요인으로 분석해.",
 structure="통념→반박(반전)",structure_reason="'우리라면 다르게 행동할 것'이라는 통념(1~4문장) 뒤, '문제는 성격이 아니라 상황(책임 분산)'이라는 반박(5~10문장)으로 뒤집어.",
 restatement_chains=[RestatementChain(label="방관자의 무반응",
   expressions=["fail to respond","the less likely any one of them will intervene","No one bystander feels enough personal responsibility"],
   variation="'반응하지 못함' → '개입 가능성 낮음' → '아무도 충분한 책임을 못 느낌'으로 이어져."),
  RestatementChain(label="원인은 상황·책임 분산",
   expressions=["the situation that bystanders find themselves in constrains their behavior","responsibility apparently diffuses among them"],
   variation="'상황이 행동을 제약' → '책임감이 그들 사이에서 분산됨'으로 원인이 구체화돼.")],
 flow_blocks=[FlowBlock(stage="통념",sentence_range="1~2",summary="사회 심리학에 따르면 위급 상황의 방관자가 반응하지 못하는 건 정상이며, 우리도 그럴 것이다.",easy_example="누구라도 선뜻 못 나서는 게 보통이라는 것."),
  FlowBlock(stage="반응(불편)",sentence_range="3~4",summary="그 통찰은 우리를 불편하게 하고, 우리는 자신은 다르게·더 잘 행동할 거라 믿고 싶어 한다.",easy_example=""),
  FlowBlock(stage="반박",sentence_range="5~6",summary="하지만 방관자 문제는 성격 결함이 아니라, 그들이 처한 '상황'이 생각보다 더 행동을 제약하기 때문이다.",easy_example="사람 탓이 아니라 상황 탓이라는 반전."),
  FlowBlock(stage="원리·예시",sentence_range="7~8",summary="방관자가 많을수록 누구도 개입하지 않으며, 혼자라면 대개 우리가 바라는 대로 도왔을 것이다.",easy_example=""),
  FlowBlock(stage="결론",sentence_range="9~10",summary="다수가 목격하면 책임감이 분산·약화되어, 아무도 나설 만큼의 개인적 책임을 느끼지 못한다.",easy_example="'누군가 하겠지' 하며 아무도 안 나서는 것.")])
i5=[S(r5,1,[("명사절 that","tells us의 목적어"),("접속사 when","'~할 때'")],
  [("bystander","방관자, 구경꾼"),("emergency","비상, 위급"),("respond","반응하다, 대응하다")],
  [("Social psychology tells us that bystanders in emergency situations are [[acting normally]]","사회 심리학은 위급 상황의 방관자가 [[정상적으로 행동하는]] 것이라고 말한다"),
   ("[[when they fail to respond]].","[[그들이 대응하지 못할 때]].")],
  [("이 문장은 위급 상황에서 방관자가 반드시 도와야 한다는 규범을 제시한다.","'bystanders … are acting normally when they fail to respond(반응 못 하는 게 정상이다)'라는, 방관자 효과를 소개하는 주제·도입 문장이야 — 규범 제시가 아니야.")]),
 S(r5,2,[("조동사 would","'(그런 상황이면) ~할 것이다'")],
  [("as well","~도, 또한"),("fail to","~하지 못하다")],
  [("[[We would fail to respond as well]].","[[우리도 또한 대응하지 못할 것이다]].")],
  [("우리는 방관자와 달리 반드시 반응할 것이라는 내용이다.","'We would fail to respond as well(우리도 마찬가지로 반응 못 할 것이다)'이라고 했어 — 우리도 예외가 아니라는 뜻이야.")]),
 S(r5,3,[("지시 That","앞 통찰을 받음"),("make + 목적어 + 형용사","'~을 …하게 만들다'")],
  [("insight","통찰"),("uncomfortable","불편한")],
  [("That social psychological [[insight]]","그 사회 심리학적 [[통찰]]은"),
   ("makes us [[uncomfortable]].","우리를 [[불편하게]] 만든다.")],
  [("그 사회 심리학적 통찰이 우리를 편안하게 만든다는 내용이다.","'makes us uncomfortable(우리를 불편하게 만든다)'이야 — 편안이 아니라 인정하기 불편한 진실이라는 뜻.")]),
 S(r5,4,[("명사절 생략","feel (that) ~")],
  [("behave","행동하다"),("differently","다르게")],
  [("[[We like to feel we would behave differently, better]].","[[우리는 다르게, 더 잘 행동할 것으로 생각하고 싶어 한다]].")],
  [("우리는 실제로 남들과 똑같이 행동할 것이라고 인정한다는 내용이다.","'like to feel we would behave differently, better(다르게, 더 잘 행동할 거라 믿고 싶어 한다)'는 거야 — 인정이 아니라 그렇게 '믿고 싶어' 한다는 뜻.")]),
 S(r5,5,[("관계사 that","defects 수식"),("prevent A from -ing","'A가 ~하지 못하게 하다'")],
  [("stem from","~에서 비롯되다"),("defect","결함"),("character","성격")],
  [("[[The problem with bystanders, however, does not stem from defects in their character]]","[[그러나 방관자 문제는 그들의 성격 결함에서 비롯되지 않는다]]"),
   ("that prevent them from [[helping]].","그들이 [[돕지 못하게]] 막는.")],
  [("이 문장은 방관자 문제가 성격 결함에서 비롯된다는 것을 확인한다.","'does not stem from defects in their character(성격 결함에서 비롯되지 않는다)'로 통념을 뒤집는 반박 문장이야 — 성격 탓이 아니라는 거야.")]),
 S(r5,6,[("관계사 that","the situation 수식"),("비교 more than","'~보다 더'")],
  [("constrain","제약하다"),("realize","깨닫다"),("situation","상황")],
  [("Rather, the situation that bystanders [[find themselves in]]","오히려, 방관자가 [[처한 상황]]이"),
   ("[[constrains their behavior more than we realize]].","[[우리가 인식하는 것보다 더 그들의 행동을 제약한다]].")],
  [("이 문장은 방관자의 성격이 행동을 결정한다는 앞 내용을 보충한다.","'Rather, the situation … constrains their behavior(오히려 상황이 행동을 제약한다)'로 진짜 원인을 밝히는 핵심 주장이야 — 성격이 아니라 '상황'이야.")]),
 S(r5,7,[("형용사 likely + 절","the less likely (that) ~ : '~할 것 같은/가능성이 있는'")],
  [("intervene","개입하다"),("likely","~할 것 같은")],
  [("For example, [[the more bystanders there are]],","예를 들어, [[방관자가 많을수록]],"),
   ("the less likely any one of them will [[intervene]].","그들 중 누구든 [[개입할]] 가능성은 더 낮아진다.")],
  [("방관자가 많을수록 누군가는 더 빨리 나서서 돕는다는 내용이다.","'the more bystanders …, the less likely any one … will intervene(많을수록 개입 가능성은 낮아진다)'는 반비례야 — 더 빨리 돕는 게 아니라 오히려 아무도 안 나서.")]),
 S(r5,8,[("가정법 would","'(혼자라면) ~할 것이다'"),("just as","'꼭 ~처럼'")],
  [("single","단 하나의"),("scene","현장"),("hope","바라다")],
  [("A [[single]] bystander at the scene of an emergency would usually respond,","위급 현장의 [[단 한 명]]의 방관자는 대개 반응할 것이다,"),
   ("[[just as we hope we would]].","[[꼭 우리가 그러길 바라는 대로]].")],
  [("(함축) 혼자 있는 방관자도 위급 상황에서 대개 돕지 않는다는 내용이다.","함축을 놓쳤어. 'A single bystander would usually respond, just as we hope we would(혼자면 대개 우리가 바라는 대로 돕는다)'는 거야 — 문제는 개인이 아니라 '수(여럿)'라는 걸 암시해.")]),
 S(r5,9,[("접속사 when","'~할 때'"),("분사구문 getting","'~해지면서'")],
  [("witness","목격하다"),("diffuse","분산되다, 퍼지다"),("apparently","명백히, 보아하니")],
  [("But when a [[number of bystanders]] witness an emergency,","그러나 [[다수의 방관자]]가 위급 상황을 목격할 때,"),
   ("[[responsibility apparently diffuses among them, getting weaker]].","[[책임감이 명백히 그들 사이로 분산되어, 점점 약해진다]].")],
  [("(지칭) 'them'은 위급 상황(emergency)들을 가리킨다.","지칭 오인이야. diffuses among them의 them은 앞의 'a number of bystanders(다수의 방관자)'를 가리켜 — 책임감이 방관자들 사이로 분산된다는 뜻이야.")]),
 S(r5,10,[("enough ... to","'~할 만큼 충분히'")],
  [("personal responsibility","개인적 책임")],
  [("[[No one bystander feels enough personal responsibility to respond]].","[[어떤 한 명의 방관자도 대응할 만큼 충분한 개인적 책임을 느끼지 못한다]].")],
  [("각 방관자는 강한 개인적 책임감을 느껴 결국 나선다는 내용이다.","'No one bystander feels enough personal responsibility(아무도 충분한 개인적 책임을 못 느낀다)'는 거야 — 강한 책임감이 아니라 책임 분산으로 아무도 안 나선다는 결론이야.")])]

DED={'a':['not A but','상관접속사'],'1':['분사구문'],'2':['so ... that','so +','강조·결과'],
     '3':['부정사의 부사적','목적의 부정사','부사적 용법'],'4':['the 비교급','비례']}
P_a=finalize(build("연설을 공연이 아닌 의사소통으로 인식할 필요성과 실수가 주는 인간적 매력",S13,"Unit13-ANALYSIS",r1,ov1,i1),DED['a'])
P_1=finalize(build("수질 정화·폐기물 처리를 위해 생물 공학적으로 설계·건설되는 인간 건설 생태계",S13,"Unit13-1",r2,ov2,i2),DED['1'])
P_2=finalize(build("비음성 모바일 소통의 급격한 확산에 따른 대면 소통 소멸에 대한 우려",S13,"Unit13-2",r3,ov3,i3),DED['2'])
P_3=finalize(build("감정적으로 흥분한 아이의 짜증을 진정시키기 위한 포옹과 공감적 반응의 중요성",S13,"Unit13-3",r4,ov4,i4),DED['3'])
P_4=finalize(build("위급 상황에서 타인의 존재로 책임감이 분산되어 발생하는 방관자 효과",S14,"Unit14-ANALYSIS",r5,ov5,i5),DED['4'])
ALL=[P_a,P_1,P_2,P_3,P_4]
FOOT="© 2026. 김은아영어연구소. All rights reserved."
if __name__=="__main__":
    for p,st in zip(ALL,["u13_a","u13_1","u13_2","u13_3","u14_a"]): out(p,st)
    render_lecture_pdf(ALL,f"{BASE}/hapbon_ch05_student.pdf",teacher=False,footer_note=FOOT)
    render_lecture_pdf(ALL,f"{BASE}/hapbon_ch05_teacher.pdf",teacher=True,footer_note=FOOT)
    ds=fitz.open(f"{BASE}/hapbon_ch05_student.pdf"); dt=fitz.open(f"{BASE}/hapbon_ch05_teacher.pdf")
    print("합본 student",ds.page_count,"p / teacher",dt.page_count,"p"); ds.close(); dt.close()
    print("CH05 DONE")
