# -*- coding: utf-8 -*-
"""
1과(Lesson 1) 전체 콘텐츠 — '중등 기초 브릿지' 한 달 과정 중 1~2주차.
지문 출처: 2022 개정 천재(강상구) 공통영어2 · Lesson 1
대상: 읽기만으로는 안 외워지는 고1 학생. → 쓰기 학습 + 누적 반복으로 암기.

하루 숙제 구성(쓰기 강화판):
  1) 누적 단어 복습  — 이전 날 단어를 매일 다시 (반복 암기 엔진)
  2) 오늘의 단어 10개 · 3번 쓰기
  3) 뜻 보고 영어 쓰기(영작) — 첫 글자만 힌트
  4) 문장 통째로 쓰기 — 지문 실제 문장 손으로 쓰기(근육 기억)
  5) 문장 속 빈칸
  6) 오늘의 문법 한 입
  * 정답은 '별지'로 분리 (학생용엔 정답 없음)
"""

SOURCE = "2022 개정 천재(강상구) 공통영어2 · Lesson 1 · 고1 2학기 내신 대비"
COPYRIGHT = "ⓒ2026.김은아영어연구소.All rights reserved"

# day, week, weekday, title_en, title_ko, part, goal_title, goal_desc,
# words[(en,ko)x10], copy[문장], cloze[(문장,답,힌트)], grammar_q[(문제,답)], gnote
DAYS = [
    dict(day=1, week=1, weekday="월", title_en="The Nuisance ①", title_ko="모기가 문다",
        part="PART 1 · 문장 1–9",
        goal_title="be동사(am·are·is) + 일반동사 3인칭 -s",
        goal_desc="주어가 '하나(he/she/it)'면 동사에 -s! 오늘은 이것만 잡으면 성공.",
        words=[("mosquito","모기"),("skin","피부"),("blood","피, 혈액"),("itchy","가려운"),
               ("escape","달아나다, 탈출하다"),("annoying","짜증나는, 성가신"),("victim","먹잇감, 희생자"),
               ("signal","신호"),("pierce","뚫다, 찌르다"),("near","가까운")],
        copy=["A mosquito sneaks in and pierces your skin.",
              "The more you scratch, the more it itches."],
        cloze=[("Right at that moment, you hear that ______ buzzing sound.","annoying","성가신"),
               ("A mosquito sneaks in and ______s your skin.","pierce","뚫다"),
               ("It fills its belly with ______ and then escapes.","blood","피")],
        grammar_q=[("You ( am / are / is ) on a camping trip.","are"),
                   ("A mosquito ( sneak / sneaks ) in.","sneaks"),
                   ("It ( fill / fills ) its belly with blood.","fills"),
                   ("How ( do / does ) mosquitoes find their victims?","do")],
        gnote="주어가 하나(a mosquito, it)면 동사에 -s. You/여럿(mosquitoes)이면 do·동사원형."),

    dict(day=2, week=1, weekday="화", title_en="The Nuisance ②", title_ko="모기는 어떻게 찾을까",
        part="PART 1 · 문장 10–15",
        goal_title="관계대명사 that / which — 명사를 뒤에서 꾸미기",
        goal_desc="명사 + [that/which ~] = '~하는 (명사)'. 이 덩어리를 묶어 읽으면 쉬워요.",
        words=[("detect","감지하다, 알아차리다"),("sensitive","민감한"),("release","내보내다, 분비하다"),
               ("attract","끌어당기다, 유인하다"),("notice","알아채다"),("cue","단서, 신호"),
               ("protein","단백질"),("female","암컷, 여성"),("bite","물다, 깨물다"),("produce","생산하다, 만들어 내다")],
        copy=["When you sweat, you release certain chemicals that attract them.",
              "Only females bite us; they need protein to produce eggs."],
        cloze=[("When you sweat, you ______ certain chemicals.","release","분비하다"),
               ("Those chemicals ______ mosquitoes to you.","attract","유인하다"),
               ("They are highly ______ to CO2.","sensitive","민감한")],
        grammar_q=[("certain chemicals ( that / who ) attract them","that"),
                   ("chemicals that attract them = 그들을 ( 유인하는 / 유인당하는 ) 화학 물질","유인하는"),
                   ("the only cue ( they use / use they ) → 그들이 이용하는 단서","they use")],
        gnote="사물·동물을 꾸미면 that/which. '명사 + 주어 + 동사'면 관계대명사가 생략된 것."),

    dict(day=3, week=1, weekday="수", title_en="The Nuisance ③", title_ko="알을 낳기까지",
        part="PART 1 · 문장 16–20",
        goal_title="가정법 과거 : If + 과거, 주어 would + 동사원형",
        goal_desc="'만약 (지금) ~라면 ~할 텐데' — 사실은 반대! 동사는 과거지만 뜻은 현재.",
        words=[("contain","포함하다, 담고 있다"),("bother","귀찮게 하다"),("surface","표면, 겉면"),
               ("gravity","중력"),("land","내려앉다, 착륙하다"),("develop","발달·성숙시키다"),
               ("lay","(알을) 낳다"),("vertical","수직의"),("roughly","대략, 약"),("concentrated","농축된, 진해진")],
        copy=["If our blood did not contain protein, they would not bother us.",
              "She lays roughly 200 eggs on the surface of the water."],
        cloze=[("If our blood did not ______ protein, they would not bite us.","contain","포함하다"),
               ("She quickly ______s on the nearest vertical surface.","land","내려앉다"),
               ("With the aid of ______, she drains off the water.","gravity","중력")],
        grammar_q=[("If our blood ( did not / does not ) contain protein,","did not"),
                   ("they ( will / would ) not bother us.","would"),
                   ("이 문장은 실제로 피에 단백질이 ( 있다 / 없다 ) 는 뜻.","있다")],
        gnote="가정법 과거 = 사실의 반대. If+과거동사, 주어 would+동사원형. (실제론 단백질이 있어서 문다.)"),

    dict(day=4, week=1, weekday="목", title_en="The Predator ①", title_ko="가장 위험한 동물",
        part="PART 2 · 문장 21–28",
        goal_title="현재완료 : have / has + 과거분사(p.p.)",
        goal_desc="'지금까지 ~해 왔다 / ~한 적이 있다' — 과거가 지금까지 이어지는 느낌.",
        words=[("predator","포식자, 천적"),("disease","질병, 병"),("deadly","치명적인"),
               ("estimate","추정하다"),("empire","제국"),("fall","몰락, 붕괴"),("claim","주장하다"),
               ("invasion","침략, 침입"),("corruption","부패, 타락"),("nearly","거의")],
        copy=["Mosquitoes can pass on deadly diseases like malaria.",
              "Mosquitoes have killed more people than any other single cause."],
        cloze=[("Mosquitoes can pass on ______ diseases like malaria.","deadly","치명적인"),
               ("The real ______ in nature is the mosquito.","predator","포식자"),
               ("Winegard ______s that mosquitoes have killed billions.","estimate","추정하다")],
        grammar_q=[("Mosquitoes ( have / has ) killed many people.","have"),
                   ("all humans who ( have / has ) ever lived","have"),
                   ("'have killed' 의 뜻: 지금까지 ( 죽여 왔다 / 죽일 것이다 )","죽여 왔다")],
        gnote="have/has + p.p. = 지금까지 이어진 일. 주어가 여럿(mosquitoes, humans)이면 have."),

    dict(day=5, week=1, weekday="금", title_en="The Predator ②", title_ko="로마 제국과 모기",
        part="PART 2 · 문장 29–34",
        goal_title="수동태 : be동사 + 과거분사(p.p.)",
        goal_desc="'~되다 / ~당하다' — 주어가 직접 하는 게 아니라 당하는 쪽. by ~ (~에 의해).",
        words=[("capital","수도; 자본"),("surround","둘러싸다"),("wetland","습지"),("ideal","이상적인"),
               ("eventually","결국, 마침내"),("spread","퍼뜨리다, 퍼지다"),("population","인구, 개체 수"),
               ("contribute","기여하다, 한몫하다"),("powerful","강력한"),("attack","공격하다")],
        copy=["Rome was once surrounded by a huge stretch of wetland.",
              "They eventually spread the disease throughout the empire."],
        cloze=[("Rome, the ______ of the empire, had a huge wetland.","capital","수도"),
               ("Rome was once ______ed by a huge wetland.","surround","둘러싸다"),
               ("The wetland was an ______ breeding ground for mosquitoes.","ideal","이상적인")],
        grammar_q=[("Rome ( surrounded / was surrounded ) by a huge wetland.","was surrounded"),
                   ("주어 Rome은 습지를 ( 둘러쌌다 / 둘러싸였다 )","둘러싸였다"),
                   ("수동태의 형태는 be동사 + ( 동사원형 / 과거분사 )","과거분사")],
        gnote="수동태 = be(am/are/is/was/were) + p.p. = '~되다/당하다'. 로마가 당한 쪽."),

    # ===== 2주차 =====
    dict(day=6, week=2, weekday="월", title_en="The Predator ③", title_ko="스코틀랜드의 실패",
        part="PART 2 · 문장 35–40",
        goal_title="과거완료 : had + 과거분사(p.p.)",
        goal_desc="'(과거 그때보다) 더 이전에 ~했었다' — 과거보다 한 발 앞선 과거.",
        words=[("settler","정착민"),("valuable","값진, 귀중한"),("region","지역, 지방"),
               ("ambitious","야심 찬, 원대한"),("encounter","맞닥뜨리다, 접하다"),("survivor","생존자"),
               ("flee","달아나다, 도망치다"),("virtually","사실상, 거의"),("raise","높이다, 끌어올리다"),
               ("create","만들다, 창조하다")],
        copy=["In 1698, five ships set sail from Scotland.",
              "Nearly half of them died, and the survivors fled."],
        cloze=[("Five ships set sail, carrying twelve hundred ______s.","settler","정착민"),
               ("They headed for the Darien ______ of Panama.","region","지역"),
               ("No one had ever ______ed these diseases before.","encounter","접하다")],
        grammar_q=[("No one ( has / had ) ever encountered these diseases before.","had"),
                   ("'had + p.p.' 는 과거보다 ( 더 이전 / 더 나중 )의 일.","더 이전"),
                   ("The plan ( was / were ) brought down by diseases.","was")],
        gnote="과거완료 had + p.p. = 과거보다 앞선 과거. 주어와 상관없이 had."),

    dict(day=7, week=2, weekday="화", title_en="The Predator ④", title_ko="뒤늦게 밝혀진 진실",
        part="PART 2 · 문장 41–45",
        goal_title="가정법 과거완료 : If + had p.p., 주어 would have p.p.",
        goal_desc="'(과거에) ~했더라면 ~했을 텐데' — 지나간 일에 대한 후회. 사실은 반대!",
        words=[("immune system","면역 체계"),("lose","잃다"),("surprisingly","놀랍게도"),
               ("find out","알아내다, 알게 되다"),("imagine","상상하다"),("tiny","아주 작은"),
               ("insect","곤충, 벌레"),("affect","영향을 주다"),("deeply","깊이, 깊게"),("finding","발견, 밝혀진 사실")],
        copy=["No one had ever encountered these diseases before.",
              "Human history is not free from the natural world."],
        cloze=[("If their ______ had been stronger, they would not have died.","immune system","면역 체계"),
               ("It was not until the 19th century that we ______ the truth.","find out","알아내다"),
               ("No one ______d these tiny insects could affect us so deeply.","imagine","상상하다")],
        grammar_q=[("If their immune systems ( had been / were ) stronger,","had been"),
                   ("they ( would not have lost / would not lose ) so many lives.","would not have lost"),
                   ("이 문장은 실제로 면역계가 ( 강했다 / 약했다 ) 는 뜻.","약했다")],
        gnote="가정법 과거완료: If+had p.p., 주어 would have p.p. (실제론 약해서 많이 죽었다.)"),

    dict(day=8, week=2, weekday="수", title_en="Ladybugs", title_ko="무당벌레 (본문 외)",
        part="본문 외 · 무당벌레 문장 1–6",
        goal_title="최상급 : the + 최상급(-est / most ~) = '가장 ~한'",
        goal_desc="여럿 중 '가장'. 짧은 단어는 -est, 긴 단어는 앞에 most. 앞에 the.",
        words=[("ladybug","무당벌레"),("helpful","도움이 되는, 유익한"),("garden","정원, 텃밭"),
               ("grow","자라다, 기르다"),("lifetime","일생, 평생"),("harmful","해로운"),
               ("defend","방어하다, 지키다"),("give off","내뿜다, 발산하다"),("smell","냄새"),("predator","포식자, 천적")],
        copy=["Ladybugs are the most well-known of all the helpful bugs.",
              "They defend themselves by giving off a certain smell."],
        cloze=[("Ladybugs are the most ______ of all the helpful bugs.","well-known","잘 알려진"),
               ("Bad bugs ______ plants from growing.","prevent","막다"),
               ("Ladybugs ______ themselves by giving off a smell.","defend","방어하다")],
        grammar_q=[("Ladybugs are the ( more / most ) well-known bugs.","most"),
                   ("'the most well-known' 의 뜻: 가장 ( 잘 알려진 / 덜 알려진 )","잘 알려진"),
                   ("don't have to = ~할 ( 필요 없다 / 하면 안 된다 )","필요 없다")],
        gnote="긴 단어의 최상급은 most + 원급. don't have to = '~할 필요 없다'(시험 함정!)."),

    dict(day=9, week=2, weekday="목", title_en="Earthworms", title_ko="지렁이 (본문 외)",
        part="본문 외 · 지렁이 문장 7–12",
        goal_title="동명사 : 동사+ing = '~하는 것 / ~함' (명사 역할)",
        goal_desc="전치사(by·at·about·after) 뒤에는 반드시 ~ing! '~함으로써 / ~하는 것에'.",
        words=[("earthworm","지렁이"),("soil","흙, 토양"),("dig","파다"),("root","뿌리"),
               ("recycle","재순환·재활용하다"),("waste","배설물, 노폐물"),("break down","분해하다"),
               ("apply","(비료를) 사용하다"),("introduce","들여놓다, 도입하다"),("around","~ 주위에")],
        copy=["Earthworms are a great addition to your garden.",
              "Their waste makes your soil richer."],
        cloze=[("They keep your ______ soft by digging tunnels.","soil","흙"),
               ("They are excellent at ______ down organic matter.","break","분해하다"),
               ("Be careful about ______ing fertilizers to your garden.","apply","사용하다")],
        grammar_q=[("They help keep your soil soft by ( dig / digging ) tunnels.","digging"),
                   ("They are excellent at ( break / breaking ) down matter.","breaking"),
                   ("Be careful about ( apply / applying ) fertilizers.","applying")],
        gnote="전치사(by/at/about/after) 뒤에는 반드시 동사+ing! (동명사)"),
]

# 문법 총정리(10일차 복습용)
GRAMMAR_SUMMARY = [
    ("1일차", "be동사 + 3인칭 -s", "주어가 하나면 동사에 -s (a mosquito sneaks)"),
    ("2일차", "관계대명사 that/which", "명사 뒤에서 꾸밈 (chemicals that attract them)"),
    ("3일차", "가정법 과거", "If+과거, would+원형 (현재 사실의 반대)"),
    ("4일차", "현재완료 have/has+p.p.", "지금까지 ~해 왔다/한 적 있다"),
    ("5일차", "수동태 be+p.p.", "~되다/당하다 (Rome was surrounded)"),
    ("6일차", "과거완료 had+p.p.", "과거보다 앞선 과거"),
    ("7일차", "가정법 과거완료", "If+had p.p., would have p.p. (과거 사실의 반대)"),
    ("8일차", "최상급 the+most/-est", "가장 ~한"),
    ("9일차", "동명사 동사+ing", "전치사 뒤에는 ~ing"),
]
