# -*- coding: utf-8 -*-
"""
1과(Lesson 1) 콘텐츠 — '중등 기초 브릿지' (은아쌤 손글씨판).
지문 출처: 2022 개정 천재(강상구) 공통영어2 · Lesson 1
대상: 읽기만으로는 안 외워지는 고1 학생.

이 파일의 말투/구성 원칙 (은아쌤 지침):
  · AI 티 나는 설명 금지. 쌤이 옆에서 말해주듯 쉽고 따뜻하게.
  · 단어는 같은 10개를 여러 유형으로 반복 노출.
  · 문법은 예문을 보며 학생이 스스로 규칙을 '발견'하게.
  · 문장은 '생각하며' 외우게(빈칸 사다리). 그냥 베껴 쓰기 금지.
  · 지문이 무슨 내용인지 + 지칭(it·they·this…)이 뭘 가리키는지 꼭 짚기.
"""

SOURCE = "2022 개정 천재(강상구) 공통영어2 · Lesson 1 · 고1 2학기 내신 대비"
COPYRIGHT = "ⓒ2026.김은아영어연구소.All rights reserved"
TEACHER = "은아쌤"

DAYS = [
    dict(day=1, week=1, weekday="월", title_en="The Nuisance ①", title_ko="모기가 문다",
        part="PART 1 · 문장 1–9",
        goal_title="be동사(am·are·is) + 일반동사 3인칭 -s",
        open="자, 오늘부터 모기 이야기 시작이야. 하나도 안 어려워. 쌤이랑 천천히 가보자!",
        summary=("여름 캠핑 중에 모기가 슬그머니 다가와 우리 피부를 콕 찌르고 피를 빨아. "
                 "그러면 가렵고 빨간 자국이 남지. 오늘 지문은 <b>‘모기가 어떻게 우리를 무는가’</b>를 "
                 "설명하는 이야기야."),
        words=[("mosquito","모기"),("skin","피부"),("blood","피, 혈액"),("itchy","가려운"),
               ("escape","달아나다, 탈출하다"),("annoying","짜증나는, 성가신"),("victim","먹잇감, 희생자"),
               ("signal","신호"),("pierce","뚫다, 찌르다"),("near","가까운")],
        discovery=dict(
            examples=["You **are** on a camping trip.  (주어 You)",
                      "A mosquito **sneaks** in.  (주어 a mosquito = 하나)",
                      "It **fills** its belly with blood.  (주어 it = 하나)"],
            ask="주어가 하나(a mosquito, it)일 때, 동사 꽁무니에 붙은 글자가 뭐야?",
            answer="-s (sneak→sneaks, fill→fills)",
            rule="주어가 ‘하나(he·she·it)’면 동사 뒤에 <b>-s</b>를 딱 붙여! You·We·They(여럿)엔 안 붙여. 이게 시험 단골 함정이야."),
        practice=[("A mosquito ( sneak / sneaks ) in.","sneaks"),
                  ("You ( am / are / is ) on a camping trip.","are"),
                  ("How ( do / does ) mosquitoes find us?","do")],
        refs=[("It fills its belly with blood.","그것은 배를 피로 채운다.","It","모기 (a mosquito)"),
              ("This is a mild allergic reaction.","이것은 가벼운 알레르기 반응이다.","This","모기에 물려 가렵고 빨갛게 부어오른 것")],
        memorize=[("A mosquito sneaks in and pierces your skin.",
                   "A mosquito sneaks in / and pierces your skin.",
                   "모기가 몰래 들어와 / 네 피부를 찌른다."),
                  ("The more you scratch, the more it itches.",
                   "The more you scratch, / the more it itches.",
                   "긁으면 긁을수록, / 더 가렵다.")],
        close="첫날 잘했어! 단어 10개랑 문장 2개만 입에 붙으면 오늘은 대성공이야. 👍",
        gnote="주어가 하나면 동사에 -s. You/여럿이면 do·동사원형."),

    dict(day=2, week=1, weekday="화", title_en="The Nuisance ②", title_ko="모기는 어떻게 찾을까",
        part="PART 1 · 문장 10–15",
        goal_title="관계대명사 that / which — 명사를 뒤에서 꾸미기",
        open="어제 배운 모기, 오늘은 걔가 우리를 ‘어떻게 찾아내는지’ 알아볼 거야. 신기해!",
        summary=("모기는 우리가 내쉬는 이산화탄소(CO2)를 멀리서도 감지해. 게다가 땀 속 화학물질 냄새, "
                 "올라간 체온까지 알아채고 찾아오지. 그리고 우리를 무는 건 오직 <b>‘암컷’</b> 모기야 — "
                 "알을 낳으려면 단백질(피)이 필요하거든."),
        words=[("detect","감지하다, 알아차리다"),("sensitive","민감한"),("release","내보내다, 분비하다"),
               ("attract","끌어당기다, 유인하다"),("notice","알아채다"),("cue","단서, 신호"),
               ("protein","단백질"),("female","암컷, 여성"),("bite","물다, 깨물다"),("produce","생산하다, 만들어 내다")],
        discovery=dict(
            examples=["certain chemicals **that attract them**  (화학물질 ← 유인하는)",
                      "the only cue **[that] they use**  (단서 ← 그들이 이용하는)"],
            ask="that 바로 앞의 명사(chemicals, cue)를, that 뒤 내용이 설명해 주고 있지?",
            answer="응. that 뒤는 앞 명사를 꾸며주는 설명!",
            rule="명사 뒤에 <b>that/which</b>가 오면, 그 뒤는 앞 명사를 꾸미는 설명이야. ‘<b>~하는 (명사)</b>’로 통째로 묶어서 읽자."),
        practice=[("certain chemicals ( that / who ) attract them","that"),
                  ("chemicals that attract them = 그들을 ( 유인하는 / 유인당하는 ) 화학물질","유인하는"),
                  ("the only cue ( they use / use they )","they use")],
        refs=[("They are highly sensitive to CO2 and can detect it.","그들은 CO2에 민감해서 그것을 감지한다.","They / it","They=모기들, it=이산화탄소(CO2)"),
              ("you release certain chemicals that attract them","그들을 유인하는 화학물질을 내보낸다","them","모기들 (mosquitoes)")],
        memorize=[("When you sweat, you release certain chemicals that attract them.",
                   "When you sweat, / you release certain chemicals / that attract them.",
                   "네가 땀을 흘리면, / 특정 화학물질을 내보낸다 / 그들을 유인하는."),
                  ("Only females bite us; they need protein to produce eggs.",
                   "Only females bite us; / they need protein / to produce eggs.",
                   "암컷만 우리를 문다; / 그들은 단백질이 필요하다 / 알을 낳기 위해.")],
        close="관계대명사 that, 별거 아니지? ‘~하는 명사’로 묶으면 끝! 내일 또 보자.",
        gnote="사물·동물을 꾸미면 that/which. ‘명사+주어+동사’면 that이 생략된 것."),

    dict(day=3, week=1, weekday="수", title_en="The Nuisance ③", title_ko="알을 낳기까지",
        part="PART 1 · 문장 16–20",
        goal_title="가정법 과거 : If + 과거, 주어 would + 동사원형",
        open="오늘은 조금 어려운 문법이 나와. 근데 걱정 마, 쌤이 진짜 쉽게 풀어줄게.",
        summary=("피를 배불리 빤 암컷 모기는 가까운 벽 같은 곳에 앉아, 중력으로 피의 수분을 빼내며 피를 진하게 농축시켜. "
                 "그 진한 피로 며칠에 걸쳐 알을 키우고, 물웅덩이 위에 <b>약 200개의 알</b>을 낳아."),
        words=[("contain","포함하다, 담고 있다"),("bother","귀찮게 하다"),("surface","표면, 겉면"),
               ("gravity","중력"),("land","내려앉다, 착륙하다"),("develop","발달·성숙시키다"),
               ("lay","(알을) 낳다"),("vertical","수직의"),("roughly","대략, 약"),("concentrated","농축된, 진해진")],
        discovery=dict(
            examples=["If our blood **did not contain** protein, they **would not** bother us.",
                      "→ did / would 는 과거형인데, 지금 이야기일까 옛날 이야기일까?"],
            ask="실제로 우리 피에 단백질이 있을까, 없을까? (문장은 ‘없다면’이라고 상상 중)",
            answer="실제론 ‘있어’! 그래서 모기가 무는 거야. (상상은 사실의 반대)",
            rule="<b>If + 과거동사, 주어 would + 동사원형</b> = ‘만약 (지금) ~라면 ~할 텐데’. 동사는 과거지만 뜻은 <b>현재</b>! 그리고 사실은 그 반대라는 뜻이야."),
        practice=[("If our blood ( did not / does not ) contain protein,","did not"),
                  ("they ( will / would ) not bother us.","would"),
                  ("실제로 피에 단백질이 ( 있다 / 없다 )","있다")],
        refs=[("She quickly lands on the nearest vertical surface.","가장 가까운 수직면에 재빨리 앉는다.","She","암컷 모기 (the female mosquito)"),
              ("Using this concentrated blood, she develops her eggs.","이 농축된 피로 알을 키운다.","this concentrated blood","수분을 빼내 진해진 피")],
        memorize=[("If our blood did not contain protein, they would not bother us.",
                   "If our blood did not contain protein, / they would not bother us.",
                   "만약 우리 피에 단백질이 없다면, / 그들은 우리를 안 괴롭힐 텐데."),
                  ("She lays roughly 200 eggs on the water.",
                   "She lays / roughly 200 eggs / on the water.",
                   "그녀는 낳는다 / 약 200개의 알을 / 물 위에.")],
        close="가정법, 생각보다 할 만하지? ‘사실은 반대!’ 이 한마디만 기억하자.",
        gnote="가정법 과거 = 사실의 반대. If+과거, 주어 would+원형. (실제론 단백질이 있어서 문다.)"),

    dict(day=4, week=1, weekday="목", title_en="The Predator ①", title_ko="가장 위험한 동물",
        part="PART 2 · 문장 21–28",
        goal_title="현재완료 : have / has + 과거분사(p.p.)",
        open="퀴즈! 자연에서 가장 위험한 동물이 뭘까? 상어? 사자? …정답은 오늘 지문에 있어.",
        summary=("자연에서 가장 위험한 동물은 놀랍게도 <b>‘모기’</b>야. 모기는 말라리아·황열 같은 치명적인 병을 옮겨서, "
                 "역사상 어떤 원인보다 많은 사람(약 520억 명!)을 죽여 왔어. 심지어 여러 나라의 역사까지 바꿨대."),
        words=[("predator","포식자, 천적"),("disease","질병, 병"),("deadly","치명적인"),
               ("estimate","추정하다"),("empire","제국"),("fall","몰락, 붕괴"),("claim","주장하다"),
               ("invasion","침략, 침입"),("corruption","부패, 타락"),("nearly","거의")],
        discovery=dict(
            examples=["Mosquitoes **have killed** more people ...  (지금까지 죽여 왔다)",
                      "all humans who **have** ever lived  (지금까지 살아 본)"],
            ask="have + killed(죽인)는 옛날에 한 번 하고 끝난 일일까, 지금까지 쭉 이어진 일일까?",
            answer="지금까지 쭉 이어져 온 일!",
            rule="<b>have/has + p.p.(과거분사)</b> = ‘지금까지 ~해 왔다 / ~한 적 있다’. 과거가 현재까지 연결된 느낌이야. 주어가 여럿이면 have."),
        practice=[("Mosquitoes ( have / has ) killed many people.","have"),
                  ("all humans who ( have / has ) ever lived","have"),
                  ("‘have killed’ = 지금까지 ( 죽여 왔다 / 죽일 것이다 )","죽여 왔다")],
        refs=[("It is actually the mosquito.","그것은 사실 모기다.","It","가장 위험한 포식자 (our greatest predator)"),
              ("Mosquitoes also played a role in shaping the history.","역사를 형성하는 데 역할을 했다.","a role","역사를 바꾼 역할·영향")],
        memorize=[("Mosquitoes can pass on deadly diseases like malaria.",
                   "Mosquitoes can pass on / deadly diseases / like malaria.",
                   "모기는 옮길 수 있다 / 치명적인 병을 / 말라리아 같은."),
                  ("Mosquitoes have killed more people than any other single cause.",
                   "Mosquitoes have killed more people / than any other single cause.",
                   "모기는 더 많은 사람을 죽여 왔다 / 다른 어떤 원인보다도.")],
        close="모기가 이렇게 무서운 동물이었다니! 오늘 단어들 시험에 진짜 잘 나와. 꼭 써보자.",
        gnote="have/has + p.p. = 지금까지 이어진 일. 주어가 여럿이면 have."),

    dict(day=5, week=1, weekday="금", title_en="The Predator ②", title_ko="로마 제국과 모기",
        part="PART 2 · 문장 29–34",
        goal_title="수동태 : be동사 + 과거분사(p.p.)",
        open="한 주 마지막 날! 오늘은 모기가 로마 제국을 어떻게 흔들었는지 보자. 금요일 파이팅!",
        summary=("제국의 수도 로마는 한때 거대한 습지에 둘러싸여 있었어. 습지는 모기의 완벽한 번식지 = 말라리아 창궐지였지. "
                 "처음엔 모기가 쳐들어온 적군을 병으로 막아주기도 했지만, 결국 병을 도시와 제국 전체에 퍼뜨려 수많은 사람을 죽였어."),
        words=[("capital","수도; 자본"),("surround","둘러싸다"),("wetland","습지"),("ideal","이상적인"),
               ("eventually","결국, 마침내"),("spread","퍼뜨리다, 퍼지다"),("population","인구, 개체 수"),
               ("contribute","기여하다, 한몫하다"),("powerful","강력한"),("attack","공격하다")],
        discovery=dict(
            examples=["Rome **was surrounded** by a huge wetland.",
                      "→ 로마가 습지를 둘러쌌을까? 아니면 습지에 ‘둘러싸인’ 걸까?"],
            ask="was + surrounded 형태를 보면, 로마는 하는 쪽이야 당하는 쪽이야?",
            answer="당하는 쪽! (둘러싸였다)",
            rule="<b>be동사 + p.p.</b> = ‘~되다 / ~당하다’(수동태). 주어가 직접 하는 게 아니라 당하는 쪽이야. ‘by ~’는 ‘~에 의해’."),
        practice=[("Rome ( surrounded / was surrounded ) by a huge wetland.","was surrounded"),
                  ("주어 Rome은 습지를 ( 둘러쌌다 / 둘러싸였다 )","둘러싸였다"),
                  ("수동태 = be동사 + ( 동사원형 / 과거분사 )","과거분사")],
        refs=[("This was an ideal breeding ground for mosquitoes.","이곳은 모기의 이상적 번식지였다.","This","로마를 둘러싼 거대한 습지 (the wetland)"),
              ("Mosquitoes helped protect the city against the armies coming to attack it.","도시를 공격하러 오는 군대로부터 도시를 지켰다.","it","그 도시 (the city) = 로마")],
        memorize=[("Rome was once surrounded by a huge wetland.",
                   "Rome was once surrounded / by a huge wetland.",
                   "로마는 한때 둘러싸여 있었다 / 거대한 습지로."),
                  ("They eventually spread the disease throughout the empire.",
                   "They eventually spread the disease / throughout the empire.",
                   "그들은 결국 병을 퍼뜨렸다 / 제국 전체에.")],
        close="한 주 동안 정말 수고 많았어! 주말에 단어 테스트로 가볍게 확인해보자. 😊",
        gnote="수동태 = be(am/are/is/was/were) + p.p. = ‘~되다/당하다’. 로마가 당한 쪽."),

    # ===== 2주차 =====
    dict(day=6, week=2, weekday="월", title_en="The Predator ③", title_ko="스코틀랜드의 실패",
        part="PART 2 · 문장 35–40",
        goal_title="과거완료 : had + 과거분사(p.p.)",
        open="새 한 주 시작! 오늘은 모기 때문에 나라 하나가 휘청한 실화를 볼 거야. 흥미진진해.",
        summary=("1698년, 스코틀랜드는 배 다섯 척에 1,200명과 물자를 싣고 파나마 다리엔으로 떠났어. 식량난에 시달리던 나라의 "
                 "경제를 살릴 <b>야심 찬 계획</b>이었지. 하지만 아무도 겪어본 적 없던 현지 병(황열·말라리아)에 무너져, 6개월 만에 "
                 "절반이 죽고 생존자들은 도망쳤어."),
        words=[("settler","정착민"),("valuable","값진, 귀중한"),("region","지역, 지방"),
               ("ambitious","야심 찬, 원대한"),("encounter","맞닥뜨리다, 접하다"),("survivor","생존자"),
               ("flee","달아나다, 도망치다"),("virtually","사실상, 거의"),("raise","높이다, 끌어올리다"),
               ("create","만들다, 창조하다")],
        discovery=dict(
            examples=["nearly half of them **died** (과거)",
                      "No one **had ever encountered** these diseases **before**. (그보다 더 전)"],
            ask="‘병을 만난 적 없던 것’은 ‘죽은 것(과거)’보다 더 이전 일이야, 더 나중 일이야?",
            answer="더 이전! (과거보다 앞선 과거)",
            rule="<b>had + p.p.</b> = (과거 그때보다) 더 이전에 ~했었다. 과거보다 한 발 앞선 과거야. 주어 상관없이 항상 had!"),
        practice=[("No one ( has / had ) ever encountered these diseases before.","had"),
                  ("‘had + p.p.’ 는 과거보다 ( 더 이전 / 더 나중 )의 일","더 이전"),
                  ("The plan ( was / were ) brought down by diseases.","was")],
        refs=[("They headed for the Darien region of Panama.","그들은 파나마 다리엔 지역으로 향했다.","They","스코틀랜드에서 출항한 배·사람들"),
              ("Scotland had hoped this would help its economy.","이것이 경제를 살리길 바랐다.","this","다리엔에 교역 거점을 만드는 계획")],
        memorize=[("In 1698, five ships set sail from Scotland.",
                   "In 1698, / five ships set sail / from Scotland.",
                   "1698년에, / 배 다섯 척이 출항했다 / 스코틀랜드에서."),
                  ("Nearly half of them died, and the survivors fled.",
                   "Nearly half of them died, / and the survivors fled.",
                   "그들 중 거의 절반이 죽고, / 생존자들은 달아났다.")],
        close="과거완료도 ‘과거보다 더 과거’ 이거 하나면 끝! 잘 따라오고 있어.",
        gnote="과거완료 had+p.p. = 과거보다 앞선 과거. 주어 상관없이 had."),

    dict(day=7, week=2, weekday="화", title_en="The Predator ④", title_ko="뒤늦게 밝혀진 진실",
        part="PART 2 · 문장 41–45",
        goal_title="가정법 과거완료 : If + had p.p., 주어 would have p.p.",
        open="어제 가정법(현재), 오늘은 그 형이야: 가정법 ‘과거완료’. 이름만 길지 원리는 똑같아!",
        summary=("면역력이 강했더라면 그렇게 많이 죽진 않았을 거야. 놀랍게도 인류는 수천 년간 이 병으로 죽으면서도 "
                 "‘어떻게 퍼지는지’ 몰랐어. <b>19세기 말</b>이 되어서야 모기가 말라리아를 옮긴다는 걸 알아냈지. "
                 "결국 인간의 역사도 자연의 작용에서 자유롭지 못하다는 이야기야."),
        words=[("immune system","면역 체계"),("lose","잃다"),("surprisingly","놀랍게도"),
               ("find out","알아내다, 알게 되다"),("imagine","상상하다"),("tiny","아주 작은"),
               ("insect","곤충, 벌레"),("affect","영향을 주다"),("deeply","깊이, 깊게"),("finding","발견, 밝혀진 사실")],
        discovery=dict(
            examples=["If their immune systems **had been** stronger,",
                      "they **would not have lost** so many lives."],
            ask="이미 지나간 과거 얘기야. ‘더 강했더라면’ — 실제로 면역력은 강했을까 약했을까?",
            answer="실제론 약했어! 그래서 많이 죽은 거지. (역시 사실의 반대)",
            rule="<b>If + had p.p., 주어 would have p.p.</b> = ‘(과거에) ~했더라면 ~했을 텐데’. 지나간 일에 대한 후회·아쉬움. 어제 배운 가정법의 ‘과거 버전’이야."),
        practice=[("If their immune systems ( had been / were ) stronger,","had been"),
                  ("they ( would not have lost / would not lose ) so many lives.","would not have lost"),
                  ("실제로 면역계가 ( 강했다 / 약했다 )","약했다")],
        refs=[("...without understanding how they were spread.","그것들이 어떻게 퍼지는지 모른 채.","they","질병들 (these diseases)"),
              ("No one imagined that these tiny insects might be affecting our lives.","이 작은 곤충들이 영향을 줄 거라 아무도 상상 못 했다.","these tiny insects","모기 (mosquitoes)")],
        memorize=[("No one had ever encountered these diseases before.",
                   "No one had ever encountered / these diseases / before.",
                   "아무도 접해본 적 없었다 / 이런 병들을 / 이전에."),
                  ("Human history is not free from the natural world.",
                   "Human history is not free / from the natural world.",
                   "인간 역사는 자유롭지 못하다 / 자연 세계로부터.")],
        close="드디어 모기 이야기 끝! 어려운 문법 다 해냈어. 스스로 칭찬해줘. 🙌",
        gnote="가정법 과거완료: If+had p.p., would have p.p. (실제론 약해서 많이 죽었다.)"),

    dict(day=8, week=2, weekday="수", title_en="Ladybugs", title_ko="무당벌레 (본문 외)",
        part="본문 외 · 무당벌레 문장 1–6",
        goal_title="최상급 : the + 최상급(-est / most ~) = ‘가장 ~한’",
        open="이번엔 착한 벌레 이야기! 무당벌레가 왜 정원의 인기스타인지 보자. 귀엽지 않아?",
        summary=("무당벌레는 정원의 이로운 벌레 중 <b>‘가장’ 유명해</b>. 식물을 해치는 진딧물을 하루 50~60마리, 평생 5천 마리 넘게 "
                 "먹어치우거든. 무당벌레를 부르는 고수·박하를 심으면 해충 걱정이 줄고, 무당벌레는 천적이 싫어하는 냄새를 뿜어 "
                 "스스로를 지키기도 해."),
        words=[("ladybug","무당벌레"),("helpful","도움이 되는, 유익한"),("garden","정원, 텃밭"),
               ("grow","자라다, 기르다"),("lifetime","일생, 평생"),("harmful","해로운"),
               ("defend","방어하다, 지키다"),("give off","내뿜다, 발산하다"),("smell","냄새"),("predator","포식자, 천적")],
        discovery=dict(
            examples=["Ladybugs are the **most well-known** of all the helpful bugs.",
                      "→ well-known은 긴 단어. 앞에 뭐가 붙어 ‘가장’이 됐지?"],
            ask="긴 단어를 ‘가장 ~한’으로 만들 때, 단어 앞에 무엇을 붙여?",
            answer="most (그리고 앞에 the!)",
            rule="가장 ~한 = <b>the + 최상급</b>. 짧은 단어는 -est(tallest), 긴 단어는 앞에 most(most famous). ‘of/in ~’로 범위를 나타내."),
        practice=[("Ladybugs are the ( more / most ) well-known bugs.","most"),
                  ("‘the most well-known’ = 가장 ( 잘 알려진 / 덜 알려진 )","잘 알려진"),
                  ("don’t have to = ~할 ( 필요 없다 / 하면 안 된다 )","필요 없다")],
        refs=[("They eat the bad bugs that prevent plants from growing.","식물이 자라는 걸 막는 나쁜 벌레를 먹는다.","They","무당벌레들 (ladybugs)"),
              ("Ladybugs can defend themselves by giving off a smell.","냄새를 뿜어 스스로를 방어한다.","themselves","무당벌레 자신 (ladybugs)")],
        memorize=[("Ladybugs are the most well-known of all the helpful bugs.",
                   "Ladybugs are the most well-known / of all the helpful bugs.",
                   "무당벌레는 가장 유명하다 / 모든 이로운 벌레 중에서."),
                  ("They defend themselves by giving off a certain smell.",
                   "They defend themselves / by giving off a certain smell.",
                   "그들은 스스로를 지킨다 / 특정한 냄새를 뿜어서.")],
        close="최상급 the most, 완전 쉽지? 무당벌레 단어들은 일상에서도 자주 써. 챙겨두자!",
        gnote="긴 단어의 최상급은 most+원급. don’t have to = ‘~할 필요 없다’(함정!)."),

    dict(day=9, week=2, weekday="목", title_en="Earthworms", title_ko="지렁이 (본문 외)",
        part="본문 외 · 지렁이 문장 7–12",
        goal_title="동명사 : 동사+ing = ‘~하는 것 / ~함’",
        open="마지막 지문은 지렁이야! 징그럽다고? 알고 보면 흙의 영웅이야. 오늘도 힘내자!",
        summary=("지렁이도 정원에 큰 도움이 돼. 굴을 파서 흙을 부드럽고 숨 쉬게 하고, 죽은 식물 조각을 먹어 흙으로 되돌리며 "
                 "새 식물을 돕지. 배설물은 흙을 더 비옥하게 만들어. 단, 지렁이를 들인 뒤엔 <b>인공 비료를 조심</b>해야 해 — "
                 "흙이 확 바뀌면 지렁이가 떠나버리거든."),
        words=[("earthworm","지렁이"),("soil","흙, 토양"),("dig","파다"),("root","뿌리"),
               ("recycle","재순환·재활용하다"),("waste","배설물, 노폐물"),("break down","분해하다"),
               ("apply","(비료를) 사용하다"),("introduce","들여놓다, 도입하다"),("around","~ 주위에")],
        discovery=dict(
            examples=["by **digging** tunnels  (~을 팜으로써)",
                      "excellent at **breaking** down  (분해하는 것에 뛰어난)",
                      "careful about **applying** ... after **introducing**"],
            ask="by, at, about, after 뒤에 온 단어들의 공통된 꼬리가 뭐야?",
            answer="-ing (전치사 뒤라서!)",
            rule="전치사(by·at·about·after…) 뒤에는 동사를 꼭 <b>-ing</b>로! 이걸 동명사라고 해. ‘by ~ing = ~함으로써’."),
        practice=[("They keep the soil soft by ( dig / digging ) tunnels.","digging"),
                  ("They are excellent at ( break / breaking ) down matter.","breaking"),
                  ("Be careful about ( apply / applying ) fertilizers.","applying")],
        refs=[("They help keep your soil soft by digging tunnels.","굴을 파서 흙을 부드럽게 유지하도록 돕는다.","They","지렁이들 (earthworms)"),
              ("They will find a new home when the soil around them changes.","주변 흙이 바뀌면 새 서식지를 찾는다.","them","지렁이들 (earthworms)")],
        memorize=[("Earthworms are a great addition to your garden.",
                   "Earthworms are a great addition / to your garden.",
                   "지렁이는 훌륭한 보탬이다 / 네 정원에."),
                  ("Their waste makes your soil richer.",
                   "Their waste makes / your soil richer.",
                   "그들의 배설물은 만든다 / 네 흙을 더 비옥하게.")],
        close="1과 완주 축하해! 🎉 이제 한 주 동안 배운 걸 총복습으로 확실히 굳혀보자.",
        gnote="전치사(by/at/about/after) 뒤에는 반드시 동사+ing! (동명사)"),
]

# 문법 총정리(10일차 복습용)
GRAMMAR_SUMMARY = [
    ("1일차", "be동사 + 3인칭 -s", "주어가 하나면 동사에 -s (a mosquito sneaks)"),
    ("2일차", "관계대명사 that/which", "명사 뒤에서 꾸밈 (chemicals that attract them)"),
    ("3일차", "가정법 과거", "If+과거, would+원형 (현재 사실의 반대)"),
    ("4일차", "현재완료 have/has+p.p.", "지금까지 ~해 왔다/한 적 있다"),
    ("5일차", "수동태 be+p.p.", "~되다/당하다 (Rome was surrounded)"),
    ("6일차", "과거완료 had+p.p.", "과거보다 앞선 과거"),
    ("7일차", "가정법 과거완료", "If+had p.p., would have p.p. (과거 사실의 반대)"),
    ("8일차", "최상급 the+most/-est", "가장 ~한"),
    ("9일차", "동명사 동사+ing", "전치사 뒤에는 ~ing"),
]
