# -*- coding: utf-8 -*-
"""YBM(박준언) 공통영어2 L1 · gen3 소단원: 가짜 뉴스가 확산되는 이유 ①②."""
import sys; sys.path.insert(0, "/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad/batches/공통영어2_YBM_박준언_1과")
from _helpers import *

# ===== 확산이유 ① 빠른 전파와 새로움 선호 (1~5) : 배수 비교 구문 =====
r5=["Fake news on social media spreads significantly farther and faster than true stories.",
"A study by the Massachusetts Institute of Technology in the US has shown that fake news spreads online 6 times faster than real news on average.",
"One explanation for this phenomenon is that people like new and provocative things.",
"When information is astonishing, people not only feel that it is surprising, but they also want to share the stimulating news with others.",
"By passing it to others on social media, they can gain attention because they are the first to post previously unknown, but possibly false, information."]
ov5=Overview(theme_ko="가짜 뉴스가 진짜보다 빠르게 퍼지는 이유 ① — 새로움·자극 선호",
 key_grammar=KeyGrammar(point="배수 비교 구문 ('몇 배 + 비교급 + than')",
  source_sentence="A study by the Massachusetts Institute of Technology in the US has shown that fake news spreads online 6 times faster than real news on average.",
  explanation=[GN("쉽게 말하면","'6 times faster than'은 '~보다 [[6배]] 더 빠른'이라는 배수 비교야."),
   GN("어순","'배수사(6 times) + 비교급(faster) + [[than]]' 순서로 써."),
   GN("원급도 가능","'몇 배'는 'X times [[as ~ as]]' 형태(as fast as)로도 표현해."),
   GN("주의","far→farther, fast→faster처럼 -er을 붙이거나 more를 붙여 [[비교급]]을 만들어.")],
  example="",example_analysis="6 times faster than real news = 배수사+비교급+than(진짜 뉴스보다 6배 빠른).",
  drills=[GrammarDrill(kind="객관식",from_passage=True,
    question="지문 2문장 'fake news spreads online 6 times faster than real news'가 뜻하는 것은?",
    options=["가짜 뉴스가 진짜 뉴스보다 6배 더 빠르게 퍼진다","가짜 뉴스가 진짜 뉴스와 같은 속도로 퍼진다","가짜 뉴스가 진짜 뉴스보다 6배 느리게 퍼진다"],
    answer="가짜 뉴스가 진짜 뉴스보다 6배 더 빠르게 퍼진다"),
   GrammarDrill(kind="객관식",from_passage=False,question="'그 강은 이 강보다 세 배 더 길다'를 바르게 옮긴 것은?",
    options=["The river is three times longer than this one.","The river is longer three times than this one.","The river is three times as longer as this one."],
    answer="The river is three times longer than this one."),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? 'This box is twice ____ heavy as that one.' (두 배 무거운)",
    options=["as","more","than"],answer="as"),
   GrammarDrill(kind="영작",from_passage=False,question="이 도로는 저 도로보다 두 배 더 넓다.",
    answer="This road is twice as wide as that one."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 2문장 일부) 가짜 뉴스는 진짜 뉴스보다 6배 더 빠르게 퍼진다.",
    answer="Fake news spreads 6 times faster than real news.")]),
 topic="소셜 미디어에서 가짜 뉴스가 진짜보다 훨씬 빠르게 퍼지는 현상을 MIT 연구로 제시하고, 그 원인을 '새롭고 자극적인 것을 좋아하는 성향'으로 설명하는 글이야.",
 stance="중립적",stance_reason="연구 결과를 근거로 확산 현상과 그 원인을 객관적으로 분석·설명하는 글이야.",
 structure="주장→근거·예시",structure_reason="가짜 뉴스가 더 빨리 퍼진다는 주장(1~2문장)을 내세운 뒤, '사람들이 새로움·자극을 선호한다'는 원인으로 뒷받침해(3~5문장).",
 restatement_chains=[RestatementChain(label="가짜 뉴스의 빠른 확산",
   expressions=["spreads significantly farther and faster than true stories","spreads online 6 times faster than real news"],
   variation="'진짜보다 훨씬 멀리·빠르게' → 'MIT 연구: 6배 더 빠르게'로 구체화돼."),
  RestatementChain(label="새로움·자극 선호",
   expressions=["people like new and provocative things","share the stimulating news with others"],
   variation="'새롭고 자극적인 것을 좋아함' → '자극적인 뉴스를 남들과 공유하고 싶어함'으로 이어져.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1~2",summary="가짜 뉴스는 진짜보다 훨씬 [[빠르게]] 퍼지며, MIT 연구는 6배 빠르다고 밝혔다.",easy_example="같은 소문이라도 거짓이 더 빨리 도는 것."),
  FlowBlock(stage="근거",sentence_range="3",summary="한 가지 설명은 사람들이 [[새롭고 자극적인]] 것을 좋아한다는 점이다.",easy_example="흔한 얘기보다 놀라운 얘기에 더 끌리는 것."),
  FlowBlock(stage="부연",sentence_range="4~5",summary="놀라운 정보를 [[공유하고]] 싶어 하고, 먼저 올려 관심을 얻으려 한다.",easy_example="아무도 모르는 소식을 제일 먼저 올려 주목받으려는 것.")])
i5=[S(r5,1,[("비교급 farther and faster ~ than","'~보다 더 멀리·더 빠르게'")],
  [("spread","퍼지다, 확산되다"),("significantly","훨씬, 상당히"),("farther","더 멀리")],
  [("[[Fake news]] on social media","소셜 미디어의 [[가짜 뉴스는]]"),
   ("spreads [[significantly farther and faster]]","[[훨씬 더 멀리, 더 빠르게 퍼진다]]"),
   ("than [[true stories]].","[[진짜 이야기]]보다.")],
  [("가짜 뉴스와 진짜 이야기가 비슷한 속도로 퍼진다는 뜻이다.","'spreads significantly farther and faster than true stories(진짜보다 훨씬 멀리·빠르게 퍼진다)'라서 비슷한 게 아니라 가짜가 더 빠르다는 뜻이야.")]),
 S(r5,2,[("배수 비교","'6 times faster than' 배수사+비교급+than (⑤)"),("명사절 that","has shown that ~ '~을 보여 주었다'")],
  [("Institute of Technology","공과대학"),("on average","평균적으로"),("real news","진짜 뉴스")],
  [("[[A study]] by the Massachusetts Institute of Technology in the US","미국 매사추세츠 공과대학의 [[한 연구는]]"),
   ("has [[shown]] that","~을 [[보여 주었다]]"),
   ("fake news spreads online [[6 times faster]]","가짜 뉴스가 온라인에서 [[6배 더 빠르게]] 퍼진다는 것을"),
   ("than real news [[on average]].","[[평균적으로]] 진짜 뉴스보다.")],
  [("이 연구는 가짜 뉴스가 진짜 뉴스만큼 빠르다고 밝혔다.","'6 times faster than real news(진짜 뉴스보다 6배 빠르다)'라고 했으니 같은 속도가 아니라 6배나 더 빠르다는 뜻이야.")]),
 S(r5,3,[("지시형용사 this","'이 (현상)'"),("보어 명사절 that","is that ~ '~라는 것이다'")],
  [("explanation","설명"),("phenomenon","현상"),("provocative","자극적인, 도발적인")],
  [("One [[explanation]] for this phenomenon","이 현상에 대한 한 가지 [[설명]]은"),
   ("is that","~라는 것이다"),
   ("people like [[new and provocative things]].","사람들이 [[새롭고 자극적인 것을]] 좋아한다는.")],
  [("'this phenomenon'은 앞에 나온 매사추세츠 공과대학을 가리킨다.","'this phenomenon(이 현상)'은 가짜 뉴스가 진짜보다 더 빠르고 멀리 퍼지는 현상을 가리켜 — 대학을 가리키는 게 아니야.")]),
 S(r5,4,[("상관접속사 not only A but also B","'A뿐만 아니라 B도'"),("명사절 that","feel that it is surprising")],
  [("astonishing","놀라운"),("stimulating","자극적인"),("share","공유하다")],
  [("When information is [[astonishing]],","정보가 [[놀라울]] 때,"),
   ("people not only feel that it is [[surprising]],","사람들은 그것이 [[놀랍다고]] 느낄 뿐만 아니라,"),
   ("but they also want to [[share]]","하지만 그들은 또한 [[공유하고]] 싶어 한다"),
   ("the [[stimulating news]] with others.","[[자극적인 뉴스를]] 다른 사람들과.")],
  [("'it is surprising'의 it은 사람들(people)을 가리킨다.","여기서 it은 앞의 information(그 정보)을 가리켜 — 정보가 놀랍다는 뜻이야, 사람이 놀랍다는 게 아니야.")]),
 S(r5,5,[("전치사 By + 동명사","'~함으로써' (passing)"),("to부정사 형용사적","the first to post '가장 먼저 올리는'")],
  [("pass","전달하다, 넘기다"),("gain attention","관심을 얻다"),("previously unknown","이전에 알려지지 않은")],
  [("By [[passing it to others]] on social media,","소셜 미디어에서 [[그것을 다른 사람들에게 전달함]]으로써,"),
   ("they can gain [[attention]]","그들은 [[관심]]을 얻을 수 있다"),
   ("because they are the first to [[post]]","그들이 가장 먼저 [[올리는]] 사람이기 때문에"),
   ("[[previously unknown, but possibly false]], information.","[[이전에 알려지지 않았지만 어쩌면 거짓일 수도 있는]] 정보를.")],
  [("'By passing it'의 it은 다른 사람들(others)을 가리킨다.","it은 앞의 그 자극적인 뉴스(정보)를 가리켜 — 그 뉴스를 남에게 전달한다는 뜻이야, 사람을 전달하는 게 아니야."),
   ("사람들이 사실 확인을 마친 정보만 신중히 올린다는 뜻이다.","'previously unknown, but possibly false(어쩌면 거짓일 수도 있는)' 정보를 먼저 올려 attention(관심)을 얻으려 한다는 속뜻이야 — 검증보다 주목이 목적이야.")])]
P5=build("Reasons for the Viral Spread ①","확산이유 · 1 (빠른 전파와 새로움 선호)",r5,ov5,i5)

# ===== 확산이유 ② 단순 사고·확증 편향 (1~6) : 가주어-진주어 =====
r6=["Also, fake news goes viral because people in their daily lives tend to think simply and effortlessly.",
"It is more likely for them to believe new information without any proof, instead of critically examining it.",
"Moreover, people are inclined to believe information that fits their prejudices or experiences even when not true.",
'In this process, people easily fall into the trap of "confirmation bias."',
"That is, they selectively accept news in a way that only confirms their beliefs and ignore news that doesn't support them.",
"During election season, for example, people tend to blindly believe any news describing their favored candidates in a positive way, while unconsciously believing news that reports something negative about other candidates."]
ov6=Overview(theme_ko="가짜 뉴스가 퍼지는 이유 ② — 단순한 사고와 확증 편향",
 key_grammar=KeyGrammar(point="가주어 It - 진주어 to부정사 (It ~ for ... to-V)",
  source_sentence="It is more likely for them to believe new information without any proof, instead of critically examining it.",
  explanation=[GN("쉽게 말하면","맨 앞 It은 뜻 없는 [[가주어]]이고, 진짜 주어는 뒤의 to-V(to believe ~)야."),
   GN("의미상 주어","to-V의 행위 주체는 'for + 목적격'으로 나타내 — 여기선 [[for them]]."),
   GN("복원","It is ~ for them to believe = [[To believe]] ~ is more likely (진주어를 앞으로)."),
   GN("주의","이때 It을 '그것'으로 해석하지 [[말고]] 뒤의 to-V를 주어처럼 옮겨.")],
  example="",example_analysis="It(가주어) ~ for them(의미상 주어) to believe(진주어) — '그들이 믿을 가능성이 더 크다'.",
  drills=[GrammarDrill(kind="객관식",from_passage=True,question="지문 2문장의 맨 앞 It의 역할로 알맞은 것은?",
    options=["뒤의 to believe ~를 대신하는 가주어","앞 문장의 fake news를 가리키는 대명사","'~한 것은 …이다'의 강조구문 It"],
    answer="뒤의 to believe ~를 대신하는 가주어"),
   GrammarDrill(kind="객관식",from_passage=False,question="빈칸에 알맞은 것은? '____ is important for us to tell fact from fake.'",
    options=["It","That","There"],answer="It"),
   GrammarDrill(kind="객관식",from_passage=False,question="가주어-진주어 구문으로 바르게 쓴 것은?",
    options=["It is hard for me to trust the news.","Is it hard for me trust the news.","That is hard for me to trust the news."],
    answer="It is hard for me to trust the news."),
   GrammarDrill(kind="영작",from_passage=False,question="우리가 가짜 뉴스를 알아차리기는 어렵다.",
    answer="It is hard for us to notice fake news."),
   GrammarDrill(kind="영작",from_passage=True,question="(지문 2문장 일부) 그들이 증거 없이 새로운 정보를 믿을 가능성이 더 크다.",
    answer="It is more likely for them to believe new information without any proof.")]),
 topic="사람들이 일상에서 단순하고 힘 안 들이는 방식으로 생각하기 때문에 증거 없이 새 정보를 믿고, 자기 편견에 맞는 뉴스만 받아들이는 '확증 편향'에 빠져 가짜 뉴스가 퍼진다는 글이야.",
 stance="부정적·비판적",stance_reason="'trap(함정)', 'blindly believe(맹목적으로 믿다)', 'confirmation bias(확증 편향)' 같은 표현으로 무비판적 수용의 문제를 비판적으로 지적해.",
 structure="주장→근거·예시",structure_reason="'단순한 사고 때문에 가짜 뉴스가 퍼진다'는 주장(1~2문장)을 편견 선호·확증 편향으로 뒷받침하고(3~5문장), 선거철 사례로 마무리해(6문장).",
 restatement_chains=[RestatementChain(label="단순·무비판적 사고",
   expressions=["think simply and effortlessly","believe new information without any proof"],
   variation="'단순하고 힘 안 들이는 사고' → '증거 없이 새 정보를 믿음'으로 구체화돼."),
  RestatementChain(label="확증 편향",
   expressions=["confirmation bias","only confirms their beliefs","favored candidates in a positive way"],
   variation="'확증 편향' → '믿음에 맞는 것만 수용' → '선거철 지지 후보 긍정 뉴스 맹신'으로 이어져.")],
 flow_blocks=[FlowBlock(stage="주장",sentence_range="1",summary="가짜 뉴스가 퍼지는 이유는 사람들이 [[단순하고]] 힘 안 들이게 생각하기 때문이다.",easy_example="깊이 따지지 않고 대충 믿어 버리는 것."),
  FlowBlock(stage="전개",sentence_range="2~3",summary="증거 없이 믿고, 자기 [[편견]]에 맞는 정보를 사실이 아니어도 믿는 경향이 있다.",easy_example="자기 생각과 같은 얘기만 골라 믿는 것."),
  FlowBlock(stage="개념",sentence_range="4~5",summary="이 과정이 바로 '[[확증 편향]]' — 믿음에 맞는 뉴스만 받고 나머지는 무시한다.",easy_example="응원하는 팀에 유리한 소식만 챙겨 보는 것."),
  FlowBlock(stage="사례",sentence_range="6",summary="선거철에 지지 후보의 [[긍정적]] 뉴스는 맹신하고 상대 후보의 부정 뉴스를 믿는다.",easy_example="내가 지지하는 후보 칭찬 기사만 믿는 것.")])
i6=[S(r6,1,[("tend to+V","'~하는 경향이 있다'"),("이유 부사절 because","'~하기 때문에'")],
  [("go viral","급속히 퍼지다, 입소문 나다"),("daily lives","일상생활"),("effortlessly","힘 안 들이고, 손쉽게")],
  [("Also, fake news [[goes viral]]","또한, 가짜 뉴스는 [[급속히 퍼진다]]"),
   ("because people in their [[daily lives]]","사람들이 [[일상생활]]에서"),
   ("tend to think [[simply and effortlessly]].","[[단순하고 별 노력 없이]] 생각하는 경향이 있기 때문에.")],
  [("가짜 뉴스는 사람들이 깊이 고민하기 때문에 퍼진다는 뜻이다.","'think simply and effortlessly(단순하고 힘 안 들이고 생각한다)'가 이유야 — 깊이 고민해서가 아니라 대충 생각하기 때문에 퍼져.")]),
 S(r6,2,[("가주어 It - 진주어 to부정사","It ~ for them to believe (⑤)"),("비교급 more likely","'~할 가능성이 더 크다'")],
  [("proof","증거"),("critically","비판적으로"),("examine","검토하다, 살펴보다")],
  [("It is more [[likely]] for them to believe","그들이 믿을 [[가능성이 더 크다]]"),
   ("new information without any [[proof]],","아무 [[증거]] 없이 새로운 정보를,"),
   ("instead of critically [[examining]] it.","그것을 [[비판적으로 검토]]하기보다는.")],
  [("'critically examining it'의 it은 사람들(them)을 가리킨다.","it은 앞의 new information(그 새 정보)을 가리켜 — 새 정보를 비판적으로 검토하지 않는다는 뜻이야.")]),
 S(r6,3,[("관계대명사 that","information that fits ~ '~에 들어맞는 정보'"),("부사절 생략","even when (it is) not true")],
  [("be inclined to","~하는 경향이 있다"),("prejudice","편견"),("experience","경험")],
  [("Moreover, people are [[inclined to believe]] information","게다가, 사람들은 정보를 [[믿는 경향이 있다]]"),
   ("that fits their [[prejudices or experiences]]","자신의 [[편견이나 경험]]에 들어맞는"),
   ("even when [[not true]].","설령 [[사실이 아닐]] 때에도.")],
  [("사람들이 자신의 편견을 버리고 정보를 판단한다는 뜻이다.","'believe information that fits their prejudices(편견에 들어맞는 정보를 믿는다)'니까 편견을 버리는 게 아니라 오히려 편견에 맞는 것만 믿는다는 뜻이야.")]),
 S(r6,4,[("지시형용사 this","'이 (과정)' = 앞의 편향된 수용 과정"),("fall into the trap of","'~의 함정에 빠지다'")],
  [("process","과정"),("trap","함정"),("confirmation bias","확증 편향")],
  [("In this [[process]],","이 [[과정]]에서,"),
   ("people easily [[fall into the trap]]","사람들은 쉽게 [[함정에 빠진다]]"),
   ('of "[[confirmation bias]]."',"'[[확증 편향]]'이라는.")],
  [("'In this process'의 this process는 뒤에 나오는 선거 과정을 가리킨다.","this process는 앞서 말한 '편견에 맞는 정보만 믿는 과정'을 가리켜 — 선거 과정을 가리키는 게 아니야.")]),
 S(r6,5,[("병렬 accept ~ and ignore ~","동사 병렬"),("관계대명사 that","a way that ~ / news that ~")],
  [("selectively","선택적으로"),("confirm","확인해 주다, 뒷받침하다"),("ignore","무시하다")],
  [("That is, they [[selectively accept]] news","즉, 그들은 뉴스를 [[선택적으로 받아들이고]]"),
   ("in a way that only [[confirms their beliefs]]","자신의 [[믿음을 확인해 주는]] 방식으로만"),
   ("and ignore news that doesn't [[support them]].","자신을 [[뒷받침하지 않는]] 뉴스는 무시한다.")],
  [("'doesn't support them'의 them은 뉴스(news)를 가리킨다.","them은 사람들(그들 자신)을 가리켜 — 자기 생각을 뒷받침하지 않는 뉴스를 무시한다는 뜻이야."),
   ("이들은 반대되는 뉴스도 공정하게 받아들인다는 뜻이다.","'only confirms their beliefs ~ ignore news that doesn't support(믿음에 맞는 것만 받고 안 맞는 건 무시)'라서 공정한 게 아니라 편향된 태도라는 속뜻이야.")]),
 S(r6,6,[("현재분사 describing","news를 뒤에서 수식 '~을 묘사하는'"),("접속사 while","'반면에' (대조)")],
  [("election season","선거철"),("blindly","맹목적으로"),("favored candidate","지지하는 후보"),("unconsciously","무의식적으로")],
  [("During [[election season]], for example,","예를 들어, [[선거철]]에는,"),
   ("people tend to [[blindly believe]] any news","사람들은 어떤 뉴스든 [[맹목적으로 믿는]] 경향이 있다"),
   ("describing their [[favored candidates]] in a positive way,","자신이 [[지지하는 후보]]를 긍정적으로 묘사하는,"),
   ("while [[unconsciously believing]] news","반면 뉴스를 [[무의식적으로 믿는다]]"),
   ("that reports [[something negative]] about other candidates.","다른 후보에 대해 [[부정적인 것을]] 보도하는.")],
  [("사람들이 지지 후보의 나쁜 뉴스도 똑같이 잘 믿는다는 뜻이다.","'blindly believe ~ favored candidates in a positive way, while ~ negative about other candidates(지지 후보엔 긍정 뉴스를 맹신, 상대 후보엔 부정 뉴스를 믿음)'라서 편향된 수용을 보여 줘.")])]
P6=build("Reasons for the Viral Spread ②","확산이유 · 2 (단순 사고·확증 편향)",r6,ov6,i6)

PARTS=[P5,P6]
