# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad/batches/공통영어2_YBM_박준언_1과")
from _helpers import *

r7 = [
 "With so much information on the Internet, how can you make sure that fake news does not mislead you?",
 "First, read beyond the provocative headlines.",
 "They can be so stimulating to get more clicks that you may click on them accidentally.",
 "So don't just read the headlines, but read the text carefully.",
 "Second, don't read the news at face value.",
 "Exercise critical thinking skills to judge the news.",
 "You should question, analyze, and evaluate what you read.",
]

ov7 = Overview(
 theme_ko="가짜뉴스를 가려내는 첫 두 방법: 표제 넘어읽기와 액면 부정",
 key_grammar=KeyGrammar(
  point="관계대명사 what (~하는 것; 선행사 포함)",
  source_sentence="You should question, analyze, and evaluate what you read.",
  explanation=[
   GN("쉽게 말하면","관계대명사 [[what]]은 선행사를 스스로 [[포함]]해 '~하는 것'으로 해석한다."),
   GN("복원","what you read = [[the thing]] that you read, 즉 '네가 [[읽는 것]]'."),
   GN("역할","what절은 문장에서 [[명사]] 역할(주어·목적어·보어)을 하며, 여기선 evaluate의 [[목적어]]."),
   GN("주의","앞에 선행사(the thing 등)가 이미 있으면 what을 못 쓰고 [[that/which]]를 쓴다."),
  ],
  example_analysis="evaluate what you read = 관계대명사 what절(선행사 포함)이 동사 evaluate의 목적어 역할.",
  drills=[
   GrammarDrill(kind="객관식",from_passage=True,
    question="지문 'evaluate what you read'의 what을 바르게 풀어 쓴 것은?",
    options=["the thing that you read","which you read","that you read","the news that"],answer="the thing that you read"),
   GrammarDrill(kind="객관식",from_passage=False,
    question="빈칸에 알맞은 것: 'I couldn't believe ____ he said.'",
    options=["what","that","which","who"],answer="what"),
   GrammarDrill(kind="객관식",from_passage=False,
    question="관계대명사 what이 어법상 옳게 쓰인 문장은?",
    options=["What matters is your effort.","The book what I read was fun.","This is the house what I live in.","Tell me the reason what you left."],
    answer="What matters is your effort."),
   GrammarDrill(kind="영작",from_passage=True,
    question="(지문) 너는 네가 읽는 것을 질문하고, 분석하고, 평가해야 한다.",
    answer="You should question, analyze, and evaluate what you read."),
   GrammarDrill(kind="영작",from_passage=False,
    question="이것이 바로 내가 원하는 것이다.",
    answer="This is what I want."),
  ]),
 topic="넘치는 인터넷 정보 속에서 가짜뉴스에 속지 않는 첫 두 가지 방법.",
 stance="부정적·비판적",
 stance_reason="가짜뉴스에 속지 말라고 경계하며 대응법을 권하는 비판적 태도.",
 structure="문제→해결(방안)",
 structure_reason="정보 홍수 속 가짜뉴스 문제를 던진 뒤(1), 표제 넘어읽기·액면 부정이라는 해결책을 제시(2~7).",
 restatement_chains=[
  RestatementChain(label="표제 너머로 읽기",
   expressions=["read beyond the provocative headlines","read the text carefully"],
   variation="'표제를 넘어 읽어라' → '본문을 주의 깊게 읽어라'로 구체화."),
  RestatementChain(label="곧이곧대로 믿지 않기",
   expressions=["don't read the news at face value","question, analyze, and evaluate"],
   variation="'액면 그대로 읽지 마라' → '질문·분석·평가하라'로 실천 방법 제시."),
 ],
 flow_blocks=[
  FlowBlock(stage="도입(문제)",sentence_range="1",
   summary="넘치는 정보 속 [[가짜뉴스]]에 속지 않을 방법을 묻는다."),
  FlowBlock(stage="해결1",sentence_range="2~4",
   summary="첫째, 자극적 [[표제]]를 넘어 본문까지 꼼꼼히 읽어라."),
  FlowBlock(stage="해결2",sentence_range="5~7",
   summary="둘째, [[액면 그대로]] 믿지 말고 비판적으로 판단하라."),
 ])

i7 = [
 S(r7,1,
  [("make sure that+절","'~을 확실히 하다/확신하다' + 명사절 목적어"),("수사의문문","how로 시작해 답을 유도하는 물음")],
  [("mislead","오도하다, 잘못 이끌다"),("make sure","확실히 하다")],
  [("With [[so much information]] on the Internet,","인터넷에 [[그토록 많은 정보]]가 있는 상황에서,"),
   ("how can you [[make sure]]","어떻게 [[확신]]할 수 있는가"),
   ("that fake news does not [[mislead]] you?","가짜뉴스가 너를 [[오도하지]] 않는다고?")],
  [("필자는 인터넷에 정보가 부족하다고 말한다.","'so much information(그토록 많은 정보)'이라 정보가 넘친다는 뜻이야 — 부족이 아니야."),
   ("겉의 물음처럼 단순히 정보를 묻는 문장이다.","겉으론 질문이지만 속뜻은 '방법이 있으니 따라오라'는 도입 수사의문문이야.")]),
 S(r7,2,
  [("명령문","동사원형 read로 시작하는 명령문"),("beyond","전치사 '~을 넘어서'")],
  [("provocative","자극적인, 도발적인"),("headline","표제, 헤드라인")],
  [("First, [[read beyond]]","첫째, [[~을 넘어서 읽어라]]"),
   ("the [[provocative headlines]].","그 [[자극적인 표제]]를.")],
  [("표제만 보고 판단하라는 조언이다.","'read beyond the headlines(표제를 넘어서 읽어라)'니 표제 너머 본문까지 읽으란 뜻이야.")]),
 S(r7,3,
  [("so ~ that 구문","'너무 ~해서 …하다'라는 정도와 결과"),("to부정사(목적)","to get more clicks '~하려고'")],
  [("stimulating","자극적인"),("accidentally","무심코, 우연히")],
  [("They can be","그것들(표제)은"),
   ("so [[stimulating]]","너무 [[자극적]]이어서"),
   ("to get [[more clicks]]","[[더 많은 클릭]]을 얻으려고"),
   ("that you may [[click on them accidentally]].","네가 [[무심코 그것들을 클릭할]] 수도 있다는 것이다.")],
  [("'They'는 클릭을 하는 사람들을 가리킨다.","'They'는 앞 문장의 provocative headlines(자극적 표제)를 가리켜 — 사람들이 아니야."),
   ("표제가 자극적인 것은 우연히 그렇게 된 것이다.","'to get more clicks(더 많은 클릭을 얻으려고)'로 일부러 자극적으로 만든 것 — 우연이 아니야.")]),
 S(r7,4,
  [("not just A but B","'A만 하지 말고 B하라' 병렬 대조"),("명령문","don't ~, but read ~ 명령문")],
  [("carefully","주의 깊게, 꼼꼼히"),("text","본문, 글")],
  [("So don't just [[read the headlines]],","그러니 [[표제만 읽지]] 말고,"),
   ("but [[read the text carefully]].","[[본문을 주의 깊게 읽어라]].")],
  [("표제는 아예 읽지 말라는 뜻이다.","'don't just read(~만 읽지 마라)'는 표제만 보고 끝내지 말고 본문도 읽으란 뜻 — 표제 금지가 아니야.")]),
 S(r7,5,
  [("명령문","Don't + 동사원형 부정 명령"),("at face value","숙어 '액면 그대로, 곧이곧대로'")],
  [("face value","액면가, 표면적 가치"),("news","뉴스, 소식")],
  [("Second, don't [[read the news]]","둘째, [[뉴스를 읽지]] 마라"),
   ("at [[face value]].","[[액면 그대로]] 받아들이며.")],
  [("뉴스를 겉으로 보이는 대로 믿으라는 뜻이다.","'don't read at face value(액면 그대로 받아들이지 마라)'니 곧이곧대로 믿지 말란 뜻이야.")]),
 S(r7,6,
  [("명령문","Exercise 동사원형으로 시작하는 명령문"),("to부정사(목적)","to judge '판단하기 위해'")],
  [("exercise","(능력을) 발휘하다"),("critical thinking","비판적 사고")],
  [("[[Exercise critical thinking skills]]","[[비판적 사고력을 발휘하라]]"),
   ("to [[judge the news]].","[[뉴스를 판단하려고]].")],
  [("비판적 사고는 전문가만 쓰는 특별한 기술이다.","누구나 뉴스를 판단하려고 발휘해야 할 능력으로 제시돼 — 전문가 전유물이 아니야.")]),
 S(r7,7,
  [("병렬(A, B, and C)","question, analyze, evaluate 세 동사 병렬"),("관계대명사 what","'~하는 것', 선행사를 포함")],
  [("analyze","분석하다"),("evaluate","평가하다")],
  [("You should [[question, analyze, and evaluate]]","너는 [[질문하고, 분석하고, 평가]]해야 한다"),
   ("[[what you read]].","[[네가 읽는 것을]].")],
  [("'what you read'는 특정한 한 기사 하나만 가리킨다.","'what you read(네가 읽는 것)'는 관계대명사 what으로 네가 읽는 모든 것을 가리켜 — 하나로 한정되지 않아.")]),
]

P7 = build("Ways to Spot and Avoid ①","식별법 · 1 (표제 넘어읽기·액면 부정)",r7,ov7,i7)

PARTS = [P7]
