# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, "/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad/batches/공통영어2_YBM_박준언_1과")
from _helpers import *

# =====================================================================
# P8 — 식별법 · 2 (편견 점검·출처 확인)
# =====================================================================
r8 = [
    "Third, examine your biases.",
    "Consider if your own beliefs could affect your judgment.",
    "Ask yourself if you are only reading articles that suit your opinion, and look for articles that oppose your opinion as well.",
    "Finally, check the credibility of the source.",
    "You should examine who wrote the news story and what the intent was behind writing the news story.",
    "You also need to check whether the news story is from a reliable media source and the evidence is valid.",
]

ov8 = Overview(
    theme_ko="가짜뉴스 식별법 ②: 편견 점검과 출처 신뢰성 확인",
    key_grammar=KeyGrammar(
        point="간접의문문 (의문사·whether/if가 이끄는 명사절)",
        source_sentence="You should examine who wrote the news story and what the intent was behind writing the news story.",
        explanation=[
            GN("쉽게 말하면", "동사 examine의 목적어로 '누가/무엇을 ~했는지'가 통째로 들어간 [[명사절]]이야."),
            GN("어순 주의", "간접의문문은 '의문사+주어+동사'의 [[평서문]] 어순 — who wrote, what the intent was."),
            GN("연결", "who wrote ~ and what ~ was: 명사절 두 개가 [[and]]로 대등하게 연결됐어."),
            GN("복원", "who wrote the news story = '누가 그 기사를 [[썼는가]]'라는 물음을 목적어로 넣은 것."),
        ],
        example_analysis="examine [who wrote ~] and [what the intent was ~] = 의문사 명사절 2개가 목적어.",
        drills=[
            GrammarDrill(kind="객관식", from_passage=True,
                question="지문 'who wrote the news story'의 문장 내 역할은?",
                options=["examine의 목적어가 되는 명사절", "the news story를 꾸미는 관계사절", "이유를 나타내는 부사절"],
                answer="examine의 목적어가 되는 명사절"),
            GrammarDrill(kind="객관식", from_passage=False,
                question="간접의문문 어순이 옳은 것은?",
                options=["I know who he is.", "I know who is he.", "I know who does he be."],
                answer="I know who he is."),
            GrammarDrill(kind="객관식", from_passage=False,
                question="빈칸: 'Tell me ____ the intent was.'(의도가 무엇이었는지)",
                options=["what", "that", "which"],
                answer="what"),
            GrammarDrill(kind="영작", from_passage=True,
                question="(지문) 당신은 누가 그 뉴스 기사를 썼고 그 기사를 쓴 의도가 무엇이었는지 살펴야 한다.",
                answer="You should examine who wrote the news story and what the intent was behind writing the news story."),
            GrammarDrill(kind="영작", from_passage=False,
                question="나는 그녀가 무엇을 원하는지 안다.",
                answer="I know what she wants."),
        ],
    ),
    topic="가짜뉴스 식별의 셋째·넷째 방법 — 자신의 편견을 점검하고 출처의 신뢰성을 확인하기.",
    stance="중립적",
    stance_reason="독자가 따라 할 수 있는 점검 방법을 객관적으로 나열·안내한다.",
    structure="시간·순서(나열)",
    structure_reason="Third → Finally로 방법을 순서대로 나열한다.",
    restatement_chains=[
        RestatementChain(label="출처·신뢰성 점검",
            expressions=["check the credibility of the source", "a reliable media source"],
            variation="'출처의 신뢰성 확인' → '믿을 만한 매체인지'로 구체화."),
        RestatementChain(label="편견 점검",
            expressions=["examine your biases", "your own beliefs could affect your judgment"],
            variation="'편견을 점검하라' → '신념이 판단에 영향 줄 수 있다'로 이유 제시."),
    ],
    flow_blocks=[
        FlowBlock(stage="전개", sentence_range="1~3",
            summary="셋째, 자신의 [[편견]]을 점검하고 반대 의견 기사도 함께 찾아 읽어라."),
        FlowBlock(stage="확장", sentence_range="4~6",
            summary="마지막으로 [[출처]]의 신뢰성 — 작성자·의도·매체·증거를 확인하라."),
    ],
)

i8 = [
    S(r8, 1,
        [("명령문", "동사원형 examine으로 시작하는 명령문 — '~을 점검하라'")],
        [("bias", "편견, 선입견"), ("examine", "조사하다, 점검하다")],
        [("Third, [[examine]]", "셋째, [[점검하라]]"),
         ("your [[biases]].", "당신의 [[편견]]을.")],
        [("언론사의 정치적 편향을 조사하라는 뜻이다.",
          "your biases는 '독자 자신의 편견'을 가리켜 — 남이 아니라 내 선입견을 점검하라는 조언이야.")]),
    S(r8, 2,
        [("if 명사절", "if = whether, '~인지 아닌지'를 이끄는 명사절(목적어)"),
         ("조동사 could", "could affect: '영향을 줄 수도 있다'는 가능성")],
        [("belief", "신념, 믿음"), ("affect", "영향을 미치다"), ("judgment", "판단")],
        [("[[Consider]]", "[[생각해 보라]]"),
         ("if your own [[beliefs]]", "당신 자신의 [[신념]]이"),
         ("could [[affect]] your judgment.", "당신의 판단에 [[영향을 줄]] 수 있는지를.")],
        [("if는 '만약 ~라면'이라는 조건을 뜻한다.",
          "여기 if는 whether와 같은 '~인지 아닌지'의 명사절이야 — '내 신념이 판단에 영향 줄 수 있는지 생각해 보라'는 뜻.")]),
    S(r8, 3,
        [("if 명사절", "Ask ... if ~: '~인지 (스스로에게) 물어라'"),
         ("관계대명사 that", "articles that suit / that oppose: 기사를 수식"),
         ("병렬", "Ask ... and look for ... 두 명령이 대등하게 연결")],
        [("suit", "~에 맞다, 어울리다"), ("oppose", "반대하다"), ("as well", "또한, ~도")],
        [("Ask [[yourself]]", "[[스스로]]에게 물어라"),
         ("if you are only reading [[articles]]", "오직 [[기사]]만 읽고 있는지"),
         ("that [[suit]] your opinion,", "당신 의견에 [[맞는]],"),
         ("and look for [[articles]]", "그리고 [[기사]]를 찾아라"),
         ("that [[oppose]] your opinion as well.", "당신 의견에 [[반대되는]] 기사도.")],
        [("that suit your opinion에서 that은 '당신의 의견'을 가리킨다.",
          "that은 관계대명사로 앞의 articles(기사)를 가리켜 — '내 의견에 맞는 기사'라는 뜻이야. (지칭)"),
         ("반대 의견 기사는 피하라는 뜻이다.",
          "'oppose your opinion ... as well'은 반대 의견 기사도 함께 찾아 읽으라는 말 — 확증편향을 막으라는 조언이야.")]),
    S(r8, 4,
        [("명령문", "check로 시작하는 명령문"),
         ("서수 부사", "Finally: 마지막 단계를 알리는 신호어")],
        [("credibility", "신뢰성, 신빙성"), ("source", "출처, 정보원")],
        [("Finally, [[check]]", "마지막으로, [[확인하라]]"),
         ("the [[credibility]] of the source.", "그 출처의 [[신뢰성]]을.")],
        [("자료의 양이 충분한지 확인하라는 뜻이다.",
          "credibility of the source는 '출처의 신뢰성' — 정보량이 아니라 그 출처를 믿을 수 있는지를 점검하라는 말이야.")]),
    S(r8, 5,
        [("간접의문문", "examine who wrote ... and what ... was: 의문사절이 목적어"),
         ("병렬", "who wrote ~ and what ~ was 두 명사절이 대등")],
        [("intent", "의도, 목적"), ("behind", "~ 뒤에, ~의 배경에")],
        [("You should [[examine]]", "당신은 [[살펴야]] 한다"),
         ("who [[wrote]] the news story", "누가 그 뉴스 기사를 [[썼는지]]"),
         ("and what the [[intent]] was", "그리고 [[의도]]가 무엇이었는지를"),
         ("behind [[writing]] the news story.", "그 뉴스 기사를 [[쓴]] 배경에 있는.")],
        [("기사를 쓴 사람 이름만 확인하면 된다는 뜻이다.",
          "누가·왜 썼는지 의도까지 살피라는 말에는 '기사에 숨은 목적이 있을 수 있다'는 속뜻이 담겨 있어 — 작성 의도 점검이 핵심. (함축)"),
         ("독자가 직접 기사를 써 보라는 뜻이다.",
          "writing the news story는 '그 기사를 쓴 일'을 가리켜 — 독자에게 집필을 시키는 게 아니라 누가 왜 썼는지 따지라는 말이야.")]),
    S(r8, 6,
        [("whether 명사절", "check whether ~: '~인지 아닌지 확인하다'"),
         ("병렬", "the news story is ... and the evidence is valid: 두 절이 대등")],
        [("reliable", "신뢰할 수 있는"), ("media source", "언론 출처, 매체"),
         ("evidence", "증거"), ("valid", "타당한, 유효한")],
        [("You also need to [[check]]", "당신은 또한 [[확인할]] 필요가 있다"),
         ("whether the news [[story]] is", "그 뉴스 [[기사]]가 ~인지"),
         ("from a [[reliable]] media source", "[[신뢰할 만한]] 언론 출처에서 나온 것인지"),
         ("and the [[evidence]] is valid.", "그리고 그 [[증거]]가 타당한지를.")],
        [("믿을 만한 언론이면 증거는 안 봐도 된다는 뜻이다.",
          "whether ... source and the evidence is valid는 '출처가 믿을 만한지'와 '증거가 타당한지'를 둘 다 확인하라는 말이야.")]),
]

P8 = build("Ways to Spot and Avoid ②", "식별법 · 2 (편견 점검·출처 확인)", r8, ov8, i8)

# =====================================================================
# P9 — 마무리 · 1 (디지털 시대 결어)
# =====================================================================
r9 = [
    "In the digital age, it might be impossible to avoid or eliminate all false information that spreads online.",
    "However, if you have the ability to view information critically and objectively, you will be able to reduce the damage that fake news can cause.",
    "Don't forget! Anyone can be the next person producing or spreading fake news!",
]

ov9 = Overview(
    theme_ko="디지털 시대의 결어: 비판적 시각으로 가짜뉴스 피해 줄이기",
    key_grammar=KeyGrammar(
        point="조건 부사절 if (가정·조건: If ~, 주어 will ~)",
        source_sentence="However, if you have the ability to view information critically and objectively, you will be able to reduce the damage that fake news can cause.",
        explanation=[
            GN("쉽게 말하면", "'If + [[현재]]형, 주어 will ~': 조건이 이뤄지면 일어날 일을 말하는 구문이야."),
            GN("시제 주의", "조건 부사절에서는 미래 일이라도 will을 안 쓰고 [[현재]]형으로 미래를 대신해."),
            GN("의미", "if you have the ability ~, you will be able to reduce ~ = '~할 능력이 있으면, [[줄일]] 수 있을 것이다'."),
            GN("주의", "여기 if는 '~인지'의 명사절이 아니라 '~라면'을 뜻하는 [[조건]] 부사절이야."),
        ],
        example_analysis="if you have the ability ~(조건절·현재형), you will be able to reduce ~(주절·will) 구조.",
        drills=[
            GrammarDrill(kind="객관식", from_passage=True,
                question="지문 'if you have the ability ~'의 성격은?",
                options=["가정·조건을 나타내는 부사절", "목적어가 되는 명사절", "양보를 나타내는 부사절"],
                answer="가정·조건을 나타내는 부사절"),
            GrammarDrill(kind="객관식", from_passage=False,
                question="조건 부사절의 시제가 옳은 것은?",
                options=["If it rains, we will stay home.", "If it will rain, we will stay home.", "If it rained, we will stay home."],
                answer="If it rains, we will stay home."),
            GrammarDrill(kind="객관식", from_passage=False,
                question="빈칸: 'If you ____ hard, you will pass.'",
                options=["study", "will study", "studied"],
                answer="study"),
            GrammarDrill(kind="영작", from_passage=False,
                question="네가 서두르면, 버스를 탈 수 있을 것이다.",
                answer="If you hurry, you will be able to catch the bus."),
            GrammarDrill(kind="영작", from_passage=True,
                question="(지문) 그러나 당신이 정보를 비판적이고 객관적으로 볼 능력이 있다면, 당신은 가짜뉴스가 일으킬 수 있는 피해를 줄일 수 있을 것이다.",
                answer="However, if you have the ability to view information critically and objectively, you will be able to reduce the damage that fake news can cause."),
        ],
    ),
    topic="온라인 거짓 정보를 다 없앨 순 없지만, 비판적·객관적 시각으로 그 피해를 줄일 수 있다는 마무리.",
    stance="부정적·비판적",
    stance_reason="가짜뉴스의 위험을 경고하고 누구나 가해자가 될 수 있다며 경계를 촉구한다.",
    structure="문제→해결(방안)",
    structure_reason="'다 없앨 순 없다'는 한계(문제) → '비판적 시각으로 피해를 줄이라'는 해결로 이어진다.",
    restatement_chains=[
        RestatementChain(label="거짓 정보의 확산과 피해",
            expressions=["all false information that spreads online", "the damage that fake news can cause"],
            variation="'온라인에 퍼지는 거짓 정보' → '가짜뉴스가 일으키는 피해'로 결과 강조."),
        RestatementChain(label="비판적·객관적 시각의 힘",
            expressions=["view information critically and objectively", "reduce the damage"],
            variation="'비판적·객관적으로 정보 보기' → '피해 줄이기'로 효과 연결."),
    ],
    flow_blocks=[
        FlowBlock(stage="문제", sentence_range="1",
            summary="디지털 시대엔 온라인 [[거짓 정보]]를 전부 없애기란 불가능할 수 있다."),
        FlowBlock(stage="해결", sentence_range="2",
            summary="그러나 [[비판적]]·객관적 시각이 있으면 가짜뉴스 피해를 줄일 수 있다."),
        FlowBlock(stage="결론", sentence_range="3",
            summary="누구나 가짜뉴스의 [[생산자]]·전파자가 될 수 있음을 잊지 마라."),
    ],
)

i9 = [
    S(r9, 1,
        [("가주어 it / 진주어 to", "it = 가주어, to avoid ~ 가 진주어 — 'it ~ to부정사' 구문"),
         ("관계대명사 that", "information that spreads online: 정보를 수식"),
         ("조동사 might", "might be impossible: '불가능할지도 모른다'는 추측")],
        [("eliminate", "없애다, 제거하다"), ("false information", "거짓 정보"), ("spread", "퍼지다")],
        [("In the [[digital]] age,", "[[디지털]] 시대에는,"),
         ("it might be [[impossible]]", "~하기가 [[불가능할]]지도 모른다"),
         ("to avoid or [[eliminate]] all false information", "모든 거짓 정보를 피하거나 [[없애는]] 것이"),
         ("that [[spreads]] online.", "온라인에 [[퍼지는]].")],
        [("it might be impossible의 it은 앞 문장의 무언가를 가리킨다.",
          "이 it은 가리키는 대상이 없는 '가주어'야 — 진짜 주어는 뒤의 to avoid or eliminate ~로, '~하기가 불가능할지도 모른다'는 뜻. (지칭)"),
         ("가짜뉴스를 완전히 없앨 수 있다는 뜻이다.",
          "might be impossible to avoid or eliminate all은 '전부 막거나 없애기는 불가능할 수 있다'며 한계를 인정하는 말이야. (함축)")]),
    S(r9, 2,
        [("조건문 (if ~, you will ~)", "if 현재형 조건절 + will 주절: '~하면 …할 것이다'"),
         ("관계대명사 that", "the damage that fake news can cause: 피해를 수식(목적격 that)"),
         ("병렬", "critically and objectively: 부사 대등 연결")],
        [("ability", "능력"), ("critically", "비판적으로"), ("objectively", "객관적으로"),
         ("reduce", "줄이다"), ("damage", "피해, 손해")],
        [("[[However]],", "[[그러나]],"),
         ("if you have the [[ability]]", "당신에게 [[능력]]이 있다면"),
         ("to view information [[critically]] and objectively,", "정보를 [[비판적]]이고 객관적으로 보는,"),
         ("you will be able to [[reduce]] the damage", "당신은 그 피해를 [[줄일]] 수 있을 것이다"),
         ("that fake news can [[cause]].", "가짜뉴스가 [[일으킬]] 수 있는.")],
        [("that fake news can cause에서 that은 가짜뉴스를 가리킨다.",
          "that은 목적격 관계대명사로 앞의 the damage(피해)를 가리켜 — '가짜뉴스가 일으킬 수 있는 피해'라는 뜻이야. (지칭)"),
         ("가짜뉴스 피해를 완전히 없앨 수 있다는 뜻이다.",
          "reduce the damage는 피해를 '줄인다'는 것 — 완전 제거가 아니라 비판적·객관적 시각으로 피해를 덜 수 있다는 조건부 주장이야.")]),
    S(r9, 3,
        [("부정 명령문", "Don't forget!: '~하지 마라'"),
         ("현재분사 수식", "person producing or spreading ~: person을 뒤에서 꾸미는 분사구"),
         ("병렬", "producing or spreading: 분사 대등 연결")],
        [("forget", "잊다"), ("produce", "만들어 내다, 생산하다"), ("spread", "퍼뜨리다")],
        [("Don't [[forget]]!", "[[잊지]] 마라!"),
         ("Anyone can be the next [[person]]", "누구나 다음 [[사람]]이 될 수 있다"),
         ("producing or [[spreading]] fake news!", "가짜뉴스를 만들거나 [[퍼뜨리는]]!")],
        [("가짜뉴스는 전문가만 만든다는 뜻이다.",
          "Anyone can be the next person ~은 '누구든 가짜뉴스의 생산자·전파자가 될 수 있다'는 경고야 — 독자 자신도 예외가 아니라는 속뜻. (함축)"),
         ("이미 가짜뉴스를 퍼뜨린 사람을 비난하는 문장이다.",
          "the next person producing or spreading은 '앞으로 그럴 수 있는 사람'을 뜻해 — 특정인을 비난하는 게 아니라 모두에게 경각심을 주는 마무리야.")]),
]

P9 = build("Ways to Spot and Avoid ③(결론)", "마무리 · 1 (디지털 시대 결어)", r9, ov9, i9)

PARTS = [P8, P9]
