# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad/batches/공통영어2_YBM_박준언_2과")
from _helpers import *

# =====================================================================
# P9 — Hunger Stones ① (기아석이란)
# =====================================================================
r9 = [
 "In the summer of 2022, during the worst drought in 500 years in Europe, a stone known as a “hunger stone” was found in a Czech town along the Elbe River.",
 "The stone had a sentence written on it that read: “If you see me, then cry.”",
 "The hunger stones, found in rivers across central Europe, typically remain underwater.",
 "However, when droughts occur and water levels retreat, these stones become visible.",
 "The stones are significant because they bear records of the past severe droughts.",
]

ov9 = Overview(
 theme_ko="기아석(hunger stone)이란 무엇인가",
 key_grammar=KeyGrammar(
  point="과거분사 삽입구 (found ~, 명사 뒤에서 수식)",
  source_sentence="The hunger stones, found in rivers across central Europe, typically remain underwater.",
  explanation=[
   GN("쉽게 말하면","명사 뒤 콤마로 붙은 '[[found]] ~'는 '관계대명사+be'가 생략된 과거분사 삽입구로, 앞 명사를 '~된'이라고 꾸며."),
   GN("복원","The hunger stones, found in rivers ~ = The hunger stones, [[which are found]] in rivers ~."),
   GN("수동 의미","과거분사라서 앞 명사가 '[[발견되는]]' 대상이야 — 능동(-ing)이 아니라 수동."),
   GN("삽입","콤마 두 개 사이에 끼어 [[주어]](The hunger stones)와 본동사(remain) 사이를 잠깐 설명해."),
  ],
  example_analysis="found in rivers across central Europe = 앞의 The hunger stones를 뒤에서 수식하는 과거분사 삽입구(= which are found ~).",
  drills=[
   GrammarDrill(kind="객관식", from_passage=True,
    question="지문 'The hunger stones, found in rivers across central Europe ~'에서 'found in rivers across central Europe'의 역할은?",
    options=["명사 The hunger stones를 뒤에서 꾸미는 과거분사구","문장의 본동사","목적어를 이끄는 관계대명사"],
    answer="명사 The hunger stones를 뒤에서 꾸미는 과거분사구"),
   GrammarDrill(kind="객관식", from_passage=False,
    question="밑줄 친 부분이 '명사를 수식하는 과거분사'인 것은?",
    options=["The book written by her is famous.","She is writing a letter.","He wants to write a book."],
    answer="The book written by her is famous."),
   GrammarDrill(kind="객관식", from_passage=False,
    question="빈칸: 'The car ____ in Korea is popular.'(한국에서 만들어진)",
    options=["made","making","makes"],
    answer="made"),
   GrammarDrill(kind="영작", from_passage=False,
    question="그 소녀가 쓴 편지는 감동적이었다.",
    answer="The letter written by the girl was moving."),
   GrammarDrill(kind="영작", from_passage=True,
    question="(지문) 중부 유럽 전역의 강에서 발견되는 그 기아석들은 평소에 물속에 잠겨 있다.",
    answer="The hunger stones, found in rivers across central Europe, typically remain underwater."),
  ]),
 topic="가뭄 때 강바닥에서 드러나는 '기아석'의 정체와 그 문구를 소개한다.",
 stance="부정적·비판적",
 stance_reason="돌에 새겨진 '내가 보이면 울어라'라는 문구로 가뭄이 몰고 올 고통을 경고하는 어조다.",
 structure="예시→일반화(결론)",
 structure_reason="2022년에 발견된 특정 돌(사례)에서 시작해 기아석 전체의 성질과 의미로 일반화한다.",
 restatement_chains=[
  RestatementChain(label="가뭄 때 드러나는 돌",
   expressions=["hunger stones","these stones become visible"],
   variation="'기아석'이 가뭄으로 수위가 낮아질 때 '보이게 된다'로 이어짐."),
 ],
 flow_blocks=[
  FlowBlock(stage="도입", sentence_range="1",
   summary="2022년 유럽 대가뭄 때 체코에서 발견된 [[기아석]]."),
  FlowBlock(stage="전개", sentence_range="2",
   summary="돌에 새겨진 문구 '내가 보이면, 그때 [[울어라]]'."),
  FlowBlock(stage="설명", sentence_range="3~4",
   summary="기아석은 평소 물속에 잠겨 있다가 [[가뭄]]으로 수위가 낮아지면 드러남."),
  FlowBlock(stage="결론", sentence_range="5",
   summary="과거의 극심한 [[가뭄]] 기록을 담고 있어 의미가 크다."),
 ])

i9 = [
 S(r9,1,
  [("과거분사구","known as a 'hunger stone'이 앞 stone을 수식"),("수동태","was found = 발견되었다")],
  [("drought","가뭄"),("along","~을 따라")],
  [("In the summer of [[2022]],","[[2022]]년 여름에,"),
   ("during the worst [[drought]] in 500 years in Europe,","유럽에서 500년 만의 최악의 [[가뭄]] 동안,"),
   ("a stone [[known]] as a “hunger stone”","‘기아석(hunger stone)’으로 [[알려진]] 한 돌이"),
   ("was [[found]] in a Czech town","체코의 한 마을에서 [[발견되었다]]"),
   ("along the [[Elbe River]].","[[엘베강]]을 따라.")],
  [("이 가뭄은 유럽 전역이 아니라 체코에서만 일어났다는 뜻이다.","'the worst drought in 500 years in Europe'는 유럽 전역의 500년 만의 최악의 가뭄을 가리켜 — 체코는 그 돌이 발견된 장소일 뿐이야."),
   ("이 돌은 사람들이 최근에 새로 세운 기념비다.","'was found(발견되었다)'로 가뭄에 강바닥에서 드러난 오래된 돌이지, 새로 세운 기념비가 아니야.")]),
 S(r9,2,
  [("과거분사","written on it = 그 위에 새겨진(수식)"),("관계사절","that read: 뒤가 문구 내용")],
  [("sentence","문장"),("read","(글이) ~라고 쓰여 있다")],
  [("The stone had a [[sentence]]","그 돌에는 한 [[문장]]이 있었는데"),
   ("[[written]] on it","그 위에 [[새겨진]]"),
   ("that [[read]]:","[[이렇게]] 적혀 있었다:"),
   ("[[“If you see me, then cry.”]]","[[“내가 보이면, 그때 울어라.”]]")],
  [("이 문구는 물이 넉넉하니 기뻐하라는 축하 인사다.","'If you see me, then cry(내가 보이면 울어라)'는 돌이 드러날 만큼 물이 마르면 가뭄의 고통이 온다는 경고야 — 축하가 아니야."),
   ("문구 속 'me'는 그 문장을 쓴 사람을 가리킨다.","'me'는 그 돌(hunger stone) 자신을 가리켜 — 돌이 보이면 울라는 의인화된 표현이야.")]),
 S(r9,3,
  [("과거분사 삽입구","found in rivers ~ 가 The hunger stones를 수식"),("부사","typically = 평소에는")],
  [("remain","(어떤 상태로) 남아 있다"),("underwater","물속에")],
  [("The hunger [[stones]],","그 [[기아석들]]은,"),
   ("[[found in rivers across central Europe]],","[[중부 유럽 전역의 강에서 발견되는]],"),
   ("typically remain [[underwater]].","평소에는 [[물속에]] 잠겨 있다.")],
  [("'The hunger stones'는 앞에서 발견된 그 돌 하나만 가리킨다.","'The hunger stones(그 기아석들)'는 중부 유럽 여러 강에 있는 이런 돌들 전체를 가리켜 — 한 개만이 아니야."),
   ("기아석은 항상 물 위에 드러나 있다.","'typically remain underwater(평소엔 물속에 잠겨 있다)'라서 보통은 안 보이고 가뭄 때만 드러나.")]),
 S(r9,4,
  [("시간 부사절","when droughts occur ~ = ~할 때"),("병렬","droughts occur and water levels retreat")],
  [("retreat","(물이) 물러나다·낮아지다"),("visible","눈에 보이는")],
  [("However, when [[droughts]] occur","하지만, [[가뭄]]이 발생하고"),
   ("and water levels [[retreat]],","수위가 [[낮아지면]],"),
   ("these stones become [[visible]].","이 돌들이 [[보이게]] 된다.")],
  [("'these stones'는 사람들이 물가에 쌓아 둔 돌무더기를 가리킨다.","'these stones(이 돌들)'는 앞서 말한 기아석(hunger stones)을 가리켜 — 새로 쌓은 돌무더기가 아니야."),
   ("이 돌들은 비가 많이 올 때 드러난다.","'when droughts occur and water levels retreat(가뭄이 나고 수위가 낮아지면)'일 때 드러나 — 비가 아니라 가뭄 때야.")]),
 S(r9,5,
  [("이유 부사절","because they bear ~ = ~하기 때문에"),("대명사","they = the stones")],
  [("significant","중요한"),("bear","(기록을) 지니다·담다")],
  [("The stones are [[significant]]","그 돌들이 [[중요한]] 것은"),
   ("because they bear [[records]]","그것들이 [[기록]]을 담고 있기 때문이다"),
   ("of the past [[severe]] droughts.","과거의 [[극심한]] 가뭄들의.")],
  [("'they'는 과거의 가뭄들을 가리킨다.","'they bear records(그것들이 기록을 담고 있다)'의 they는 그 돌들(the stones)을 가리켜 — 가뭄이 아니야."),
   ("이 돌들은 미래의 가뭄을 예측해 주기 때문에 중요하다.","'records of the past severe droughts(과거의 극심한 가뭄 기록)'를 담고 있어 중요한 거라, 핵심은 과거의 기록이야.")]),
]
P9 = build("Hunger Stones ①","본문 외 · 1 (기아석이란)", r9, ov9, i9)

# =====================================================================
# P10 — Hunger Stones ② (경고와 미래 예측)
# =====================================================================
r10 = [
 "Droughts cause reduced harvests, food shortages, and hunger, especially for the poor.",
 "The words on the hunger stones are believed to warn of these hardships and to urge people to be prepared.",
 "Considering the continuation of climate change, experts warn that the situation we face is not just a simple, occasional drought but a severe drought that could persist for decades.",
 "The United Nations has predicted that by 2050, 75 percent of the global population could suffer from the effects of drought unless significant action is taken to address climate change.",
]

ov10 = Overview(
 theme_ko="가뭄의 경고와 미래 예측",
 key_grammar=KeyGrammar(
  point="상관접속사 not just A but B (A가 아니라 B)",
  source_sentence="Considering the continuation of climate change, experts warn that the situation we face is not just a simple, occasional drought but a severe drought that could persist for decades.",
  explanation=[
   GN("쉽게 말하면","'not just A but B'는 'A가 아니라 (사실은) [[B]]이다'로, 뒤의 B에 초점을 두는 상관접속사야."),
   GN("짝","not just ~ 뒤에는 반드시 [[but]]이 와서 A와 B를 이어 줘."),
   GN("대등","A와 B는 문법적으로 [[대등한]] 형태를 써 — 여기선 둘 다 '~ drought'라는 명사구."),
   GN("초점","just(단지)를 부정하니 강조점이 A가 아니라 [[B]](severe drought)에 놓여."),
  ],
  example_analysis="not just a simple, occasional drought(A) but a severe drought(B) = 'A가 아니라 B'로 B(심각한 가뭄)를 강조.",
  drills=[
   GrammarDrill(kind="객관식", from_passage=True,
    question="지문 'the situation we face is not just a simple, occasional drought but a severe drought ~'에서 'not just A but B'의 뜻은?",
    options=["A가 아니라 (오히려) B이다","A이면서 동시에 B이다","A도 B도 아니다"],
    answer="A가 아니라 (오히려) B이다"),
   GrammarDrill(kind="객관식", from_passage=False,
    question="다음 중 'not just A but B(A가 아니라 B)' 구조인 문장은?",
    options=["He wants not just money but happiness.","He wants both money and happiness.","He wants either money or happiness."],
    answer="He wants not just money but happiness."),
   GrammarDrill(kind="객관식", from_passage=False,
    question="빈칸: 'The issue is not just local ____ global.'(지역이 아니라 세계적)",
    options=["but","and","nor"],
    answer="but"),
   GrammarDrill(kind="영작", from_passage=False,
    question="그것은 단순한 문제가 아니라 심각한 위기다.",
    answer="It is not just a simple problem but a serious crisis."),
   GrammarDrill(kind="영작", from_passage=True,
    question="(지문) 우리가 마주한 상황은 단순하고 이따금 오는 가뭄이 아니라 수십 년간 지속될 수 있는 심각한 가뭄이다.",
    answer="The situation we face is not just a simple, occasional drought but a severe drought that could persist for decades."),
  ]),
 topic="가뭄이 부르는 고난과, 기후 변화로 더 심해질 미래 가뭄에 대한 경고.",
 stance="부정적·비판적",
 stance_reason="수십 년 지속될 심각한 가뭄과 2050년 인구 75% 피해 예측을 들어 위기를 경고한다.",
 structure="주장→근거·예시",
 structure_reason="가뭄이 고난을 부른다는 주장을 기아석의 경고·전문가·UN 예측이라는 근거로 뒷받침한다.",
 restatement_chains=[
  RestatementChain(label="가뭄이 부르는 고난",
   expressions=["reduced harvests, food shortages, and hunger","these hardships"],
   variation="'수확 감소·식량 부족·기아'가 'these hardships(이런 고난)'로 다시 묶임."),
 ],
 flow_blocks=[
  FlowBlock(stage="근거", sentence_range="1",
   summary="가뭄은 수확 감소·식량 부족·[[기아]]를 부르고, 특히 가난한 이에게 가혹함."),
  FlowBlock(stage="전개", sentence_range="2",
   summary="기아석 글귀는 이런 고난을 [[경고]]하고 대비를 촉구하는 것으로 여겨짐."),
  FlowBlock(stage="심화", sentence_range="3",
   summary="전문가들은 수십 년 지속될 [[심각한]] 가뭄을 경고함."),
  FlowBlock(stage="결론", sentence_range="4",
   summary="UN은 2050년까지 인구 75%가 가뭄 피해를 볼 수 있다고 [[예측]]함."),
 ])

i10 = [
 S(r10,1,
  [("병렬 명사구","reduced harvests, food shortages, and hunger 나열"),("부사","especially = 특히")],
  [("harvest","수확(량)"),("shortage","부족")],
  [("Droughts cause [[reduced harvests]],","가뭄은 [[수확 감소]]를 일으키고,"),
   ("food [[shortages]], and hunger,","식량 [[부족]]과 기아를 부르는데,"),
   ("especially for the [[poor]].","특히 [[가난한]] 사람들에게.")],
  [("가뭄의 피해는 모든 사람에게 똑같이 닥친다.","'especially for the poor(특히 가난한 사람들에게)'라고 하여 가난한 사람들이 더 큰 타격을 받음을 강조해."),
   ("가뭄이 수확량을 늘린다는 뜻이다.","'reduced harvests(수확 감소)'라서 수확이 줄어드는 거야 — 늘어나는 게 아니야.")]),
 S(r10,2,
  [("수동태","are believed to ~ = ~한다고 여겨진다"),("병렬 부정사","to warn ~ and to urge ~")],
  [("warn of","~을 경고하다"),("urge","촉구하다")],
  [("The words on the hunger [[stones]]","기아석에 새겨진 그 [[글귀]]는"),
   ("are believed to [[warn of]] these hardships","이런 고난을 [[경고하는]] 것으로 여겨지며,"),
   ("and to [[urge]] people","사람들에게 [[촉구하는]] 것으로 여겨진다"),
   ("to be [[prepared]].","[[대비]]하라고.")],
  [("'these hardships'는 돌을 새길 때 겪는 어려움을 가리킨다.","'these hardships(이런 고난)'는 앞 문장의 가뭄으로 인한 수확 감소·식량 부족·기아를 가리켜."),
   ("돌의 글귀는 그저 옛날 낙서일 뿐 의미가 없다.","'to warn ~ and to urge people to be prepared(경고하고 대비를 촉구)'하려는 목적으로 여겨지니 단순 낙서가 아니야.")]),
 S(r10,3,
  [("분사구문","Considering ~ = ~을 고려하면"),("상관접속사","not just A but B = A가 아니라 B"),("관계사절","that could persist ~ 수식")],
  [("continuation","지속·계속"),("persist","지속되다")],
  [("Considering the continuation of [[climate change]],","[[기후 변화]]가 계속되는 것을 고려하면,"),
   ("experts [[warn]] that","전문가들은 [[경고한다]]"),
   ("the situation we [[face]]","우리가 [[마주한]] 상황은"),
   ("is [[not just a simple, occasional drought]]","[[단순하고 이따금 오는 가뭄이 아니라]]"),
   ("but a [[severe drought]]","[[심각한 가뭄]]이라고"),
   ("that could [[persist]] for decades.","수십 년간 [[지속]]될 수 있는.")],
  [("'the situation we face'는 과거 사람들이 겪은 상황을 가리킨다.","'the situation we face(우리가 마주한 상황)'는 지금 우리가 처한 현재의 가뭄 상황을 가리켜 — 과거가 아니야."),
   ("전문가들은 앞으로의 가뭄이 잠깐이면 끝날 거라고 본다.","'not just a simple, occasional drought but a severe drought that could persist for decades'라며 수십 년 지속될 심각한 가뭄을 경고해 — 잠깐이 아니야.")]),
 S(r10,4,
  [("조건 부사절","unless ~ = ~하지 않으면"),("수동태","action is taken = 조치가 취해지다"),("명사절","that ~ 이 predicted의 목적어")],
  [("population","인구"),("address","(문제를) 다루다·대응하다")],
  [("The United Nations has [[predicted]] that","국제연합(UN)은 [[예측했는데]],"),
   ("by 2050, 75 percent of the global [[population]]","2050년까지 세계 [[인구]]의 75퍼센트가"),
   ("could [[suffer]] from the effects of drought","가뭄의 영향으로 [[고통받을]] 수 있다고,"),
   ("unless [[significant action]] is taken","[[상당한 조치]]가 취해지지 않으면,"),
   ("to [[address]] climate change.","기후 변화에 [[대응하기]] 위한.")],
  [("행동을 취하든 안 취하든 인구의 75%가 고통받는다는 뜻이다.","'unless significant action is taken(상당한 조치가 취해지지 않으면)'이라는 조건이 붙어 — 대응하면 피할 수 있다는 뜻이야."),
   ("UN은 이미 인구의 75%가 가뭄으로 고통받고 있다고 했다.","'by 2050 ~ could suffer(2050년까지 ~ 고통받을 수 있다)'는 미래 예측이야 — 현재 벌어진 일이 아니야.")]),
]
P10 = build("Hunger Stones ②","본문 외 · 2 (경고와 미래 예측)", r10, ov10, i10)

PARTS = [P9, P10]
