# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad/batches/공통영어2_YBM_박준언_2과")
from _helpers import *

# =====================================================================
# P7 — Dry ⑦ 위기와 구원 (장면 · 7 반전과 삼촌의 등장)
# =====================================================================
r7 = [
    "For a moment I think he is joking, but then realize he is serious. “Excuse me?”",
    "He is still smiling, but his eyes scare me.",
    "As long as his hands are firmly locked on the handle of our cart, there is nothing to prove that it’s ours and not his.",
    "“Is there a problem here?” It is Uncle Basil. He has arrived just in time.",
    "“Not at all.” The man looks at the ice with a bitter face, then leaves.",
]

ov7 = Overview(
    theme_ko="미소 뒤에 숨은 위협과 때맞춘 삼촌의 등장",
    key_grammar=KeyGrammar(
        point="As long as (조건 접속사: ~하는 한)",
        source_sentence="As long as his hands are firmly locked on the handle of our cart, there is nothing to prove that it’s ours and not his.",
        explanation=[
            GN("쉽게 말하면", "'As long as ~'는 '~하는 [[한]]'이라는 [[조건]] 부사절 접속사(= if · only if)."),
            GN("의미", "조건이 유지되는 [[동안]]에만 주절이 성립 — 손이 손잡이를 잡고 있는 한 소유를 증명 못 함."),
            GN("구별", "'as long as'는 '~하는 한([[조건]])'과 '~하는 동안([[기간]])' 둘 다 되지만, 여기선 조건."),
            GN("주의", "조건 부사절이라 미래 일도 [[현재]]시제로 — are locked (will be 아님)."),
        ],
        example_analysis="As long as his hands are firmly locked ~ = 조건 부사절(~하는 한), 주절은 there is nothing to prove ~.",
        drills=[
            GrammarDrill(kind="객관식", from_passage=True,
                question="지문 'As long as his hands are firmly locked ~'의 뜻으로 알맞은 것은?",
                options=["그의 손이 손잡이에 단단히 잠겨 있는 한", "그의 손이 잠겨 있는 동안 내내", "그의 손이 잠겼기 때문에"],
                answer="그의 손이 손잡이에 단단히 잠겨 있는 한"),
            GrammarDrill(kind="객관식", from_passage=False,
                question="빈칸에 알맞은 것은? '____ you keep the receipt, you can get a refund.'(영수증을 갖고 있는 한)",
                options=["As long as", "As soon as", "As far as"],
                answer="As long as"),
            GrammarDrill(kind="객관식", from_passage=False,
                question="밑줄 친 'as long as'가 '조건(~하는 한)'으로 쓰인 것은?",
                options=["As long as you try, you will improve.", "I waited as long as two hours.", "The rope is as long as the room."],
                answer="As long as you try, you will improve."),
            GrammarDrill(kind="영작", from_passage=True,
                question="(지문) 그의 손이 우리 카트 손잡이에 단단히 잠겨 있는 한, 그것이 그의 것이 아니라 우리 것임을 증명할 것이 없다.",
                answer="As long as his hands are firmly locked on the handle of our cart, there is nothing to prove that it’s ours and not his."),
            GrammarDrill(kind="영작", from_passage=False,
                question="네가 조용히 있는 한, 우리는 안전하다.",
                answer="As long as you stay quiet, we are safe."),
        ],
    ),
    topic="정장 남자가 카트 손잡이를 잡고 얼음을 가로채려 하지만 바질 삼촌이 나타나 물러서는 장면.",
    stance="중립적",
    stance_reason="화자의 시점에서 위기와 구원의 장면을 있는 그대로 보여 준다.",
    structure="시간·순서(나열)",
    structure_reason="농담→위협→삼촌 등장→남자 퇴장의 시간 순서로 전개된다.",
    restatement_chains=[
        RestatementChain(label="미소 뒤의 위협",
            expressions=["his eyes scare me", "looks at the ice with a bitter face"],
            variation="'눈이 겁나게 한다'는 위협이 '씁쓸한 표정으로 떠남'으로 이어진다."),
        RestatementChain(label="때맞춘 구원",
            expressions=["Uncle Basil", "arrived just in time"],
            variation="'바질 삼촌'의 등장이 '때마침 도착'으로 강조된다."),
    ],
    flow_blocks=[
        FlowBlock(stage="전개", sentence_range="1~2", summary="농담인 줄 알았던 남자가 [[진심]]임을 알고, 미소 뒤 눈빛이 [[위협]]적이다."),
        FlowBlock(stage="위기", sentence_range="3", summary="손잡이를 잡은 한 카트가 우리 [[것]]임을 증명할 길이 없다."),
        FlowBlock(stage="전환", sentence_range="4", summary="바질 [[삼촌]]이 때마침 나타나 위기를 끊는다."),
        FlowBlock(stage="결말", sentence_range="5", summary="남자는 씁쓸한 [[표정]]으로 얼음을 보다 물러난다."),
    ],
)

i7 = [
    S(r7, 1,
        [("that 생략", "I think (that) he is joking — 접속사 that 생략"), ("but (역접)", "생각↔깨달음의 대비")],
        [("joking", "농담하는"), ("serious", "진심인·진지한")],
        [("For a [[moment]]", "잠깐 [[동안]]"),
         ("I think he is [[joking]],", "나는 그가 [[농담한다]]고 생각하지만,"),
         ("but then realize he is [[serious]].", "그러다 그가 [[진심]]임을 깨닫는다."),
         ("“[[Excuse]] me?”", "“[[뭐라고요]]?”")],
        [("화자는 남자가 진짜로 농담을 하고 있다고 끝까지 확신한다.",
          "처음엔 농담인 줄 알았지만 곧 'he is serious(그가 진심이다)'임을 깨닫는다 — 확신이 아니라 반전이다.")]),
    S(r7, 2,
        [("but (역접)", "미소 ↔ 겁나는 눈빛의 대조"), ("still (계속)", "여전히 웃고 있음")],
        [("scare", "겁먹게 하다·위협하다")],
        [("He is still [[smiling]],", "그는 여전히 [[웃고]] 있지만,"),
         ("but his eyes [[scare]] me.", "그의 눈은 나를 [[겁먹게]] 한다.")],
        [("그가 웃고 있으므로 화자에게 친절하고 우호적인 사람이다.",
          "웃고 있어도 'his eyes scare me(눈이 나를 겁먹게 한다)' — 미소는 위협을 감추는 것이라 실제로는 우호적이지 않다(함축).")]),
    S(r7, 3,
        [("As long as (조건)", "~하는 한 (조건 부사절)"), ("to prove (부정사)", "nothing을 꾸미는 형용사적 용법"), ("it’s = it is", "it은 the cart")],
        [("firmly", "단단히"), ("locked", "잠긴·꽉 쥔"), ("prove", "증명하다")],
        [("As long as his hands are firmly [[locked]]", "그의 손이 단단히 [[잠겨]] 있는 한"),
         ("on the [[handle]] of our cart,", "우리 카트 [[손잡이]]에,"),
         ("there is nothing to [[prove]]", "[[증명]]할 것이 아무것도 없다"),
         ("that it’s [[ours]] and not his.", "그것이 그의 것이 아니라 [[우리 것]]이라는 걸.")],
        [("여기서 it은 남자의 손(his hands)을 가리킨다.",
          "it은 our cart(우리 카트)를 가리킨다(지칭) — 손이 손잡이를 잡고 있어 카트가 우리 것임을 증명할 수 없다는 뜻."),
         ("남자는 그저 카트를 정리해 주려고 손잡이를 잡고 있을 뿐이다.",
          "'hands are firmly locked(손을 꽉 쥐고 있다)'는 얼음이 든 카트를 빼앗으려는 위협 — 도둑 같은 의도가 담겨 있다(함축).")]),
    S(r7, 4,
        [("has arrived (현재완료)", "막 도착한 결과"), ("It is ~ (지칭)", "It은 말을 건 사람의 정체")],
        [("just in time", "때마침·아슬아슬하게 제때")],
        [("“Is there a [[problem]] here?”", "“여기 무슨 [[문제]] 있나요?”"),
         ("It is [[Uncle Basil]].", "[[바질 삼촌]]이다."),
         ("He has [[arrived]] just in time.", "그가 때마침 [[도착]]했다.")],
        [("'It is Uncle Basil.'의 It은 앞에서 말한 문제(problem)를 가리킨다.",
          "It은 방금 말을 건 사람의 정체를 가리키는 지칭 — '그렇게 말한 사람은 바질 삼촌이다'라는 뜻."),
         ("삼촌은 상황이 다 끝난 뒤에 뒤늦게 나타난다.",
          "'arrived just in time(때마침 도착)' — 위기의 순간에 딱 맞춰 나타나 화자를 구해 준다는 함축이다.")]),
    S(r7, 5,
        [("looks ~ then leaves (동사 나열)", "본다 → 떠난다 순서"), ("with a ~ face (부대상황)", "~한 표정으로")],
        [("bitter", "씁쓸한·분한"), ("leaves", "떠나다")],
        [("“Not at all.”", "“전혀요.”"),
         ("The man [[looks]] at the ice", "그 남자는 얼음을 [[본다]]"),
         ("with a [[bitter]] face,", "[[씁쓸한]] 표정으로,"),
         ("then [[leaves]].", "그러고는 [[떠난다]].")],
        [("남자는 만족스러운 표정으로 얼음을 챙겨서 떠난다.",
          "'bitter face(씁쓸한 표정)'로 얼음을 바라보다 떠난다 — 얼음을 얻지 못해 분하게 물러서는 것이지 챙겨 가는 게 아니다(함축).")]),
]

P7 = build("Dry ⑦ 위기와 구원", "장면 · 7 (반전과 삼촌의 등장)", r7, ov7, i7)

# =====================================================================
# P8 — Dry ⑧ 작품 소개·경고 (작품 정리 · 1 소설 「Dry」와 현실 경고)
# =====================================================================
r8 = [
    "The above is a shortened version of the opening of the novel Dry (2018).",
    "It tells the story of a girl who has to make tough choices for her family during a disastrous California drought.",
    "Her unwanted adventure ends when the water supply resumes and life is back to normal.",
    "Provided that the factors contributing to water shortages worldwide are not addressed, including climate change, population growth, and using too much water for agriculture, it is possible that this story can become a reality.",
]

ov8 = Overview(
    theme_ko="소설 「Dry」 소개와 물 부족이 현실이 될 수 있다는 경고",
    key_grammar=KeyGrammar(
        point="Provided that (조건 접속사: ~라면)",
        source_sentence="Provided that the factors contributing to water shortages worldwide are not addressed, including climate change, population growth, and using too much water for agriculture, it is possible that this story can become a reality.",
        explanation=[
            GN("쉽게 말하면", "'Provided that ~'는 '[[만약]] ~라면'이라는 [[조건]] 접속사(= if)."),
            GN("의미", "여기선 'not addressed'와 합쳐 '~하지 [[않는다면]]'이라는 조건이 된다."),
            GN("바꿔쓰기", "Provided that ~ = [[If]] ~ / As long as ~ 로 바꿔 쓸 수 있다."),
            GN("주의", "조건절이라 미래 일도 [[현재]]시제 — are not addressed(will be 아님)."),
        ],
        example_analysis="Provided that the factors ~ are not addressed = 조건 부사절, 주절은 it is possible that this story can become a reality.",
        drills=[
            GrammarDrill(kind="객관식", from_passage=True,
                question="지문 'Provided that the factors ~ are not addressed'의 뜻으로 알맞은 것은?",
                options=["그 요인들이 해결되지 않는다면", "그 요인들이 해결되었으므로", "그 요인들이 해결될 때까지"],
                answer="그 요인들이 해결되지 않는다면"),
            GrammarDrill(kind="객관식", from_passage=False,
                question="빈칸에 알맞은 것은? '____ that you finish the work, you may leave.'(일을 끝낸다면)",
                options=["Provided", "Despite", "Unless"],
                answer="Provided"),
            GrammarDrill(kind="객관식", from_passage=False,
                question="'Provided that'와 바꿔 쓸 수 있는 접속사는?",
                options=["If", "Although", "Because"],
                answer="If"),
            GrammarDrill(kind="영작", from_passage=True,
                question="(지문) 그 요인들이 해결되지 않는다면, 이 이야기가 현실이 되는 것도 가능하다.",
                answer="Provided that the factors are not addressed, it is possible that this story can become a reality."),
            GrammarDrill(kind="영작", from_passage=False,
                question="네가 규칙을 따른다면, 너는 참가할 수 있다.",
                answer="Provided that you follow the rules, you can join."),
        ],
    ),
    topic="위 지문이 소설 「Dry」 도입부의 축약본임을 밝히고, 물 부족 요인을 방치하면 이야기가 현실이 될 수 있다고 경고한다.",
    stance="부정적·비판적",
    stance_reason="기후 변화 등 물 부족 요인을 방치하면 소설이 현실이 될 수 있다고 경고한다.",
    structure="예시→일반화(결론)",
    structure_reason="소설의 줄거리를 사례로 든 뒤, 현실이 될 수 있다는 일반화된 경고로 마무리한다.",
    restatement_chains=[
        RestatementChain(label="현실이 될 수 있는 경고",
            expressions=["the factors contributing to water shortages", "this story can become a reality"],
            variation="'물 부족을 부르는 요인'을 방치하면 '이야기가 현실이 된다'로 이어진다."),
        RestatementChain(label="가뭄의 규모",
            expressions=["a disastrous California drought", "water shortages worldwide"],
            variation="'캘리포니아의 재난 같은 가뭄'이 '전 세계 물 부족'으로 확대된다."),
    ],
    flow_blocks=[
        FlowBlock(stage="도입", sentence_range="1", summary="위 글이 소설 「Dry」 [[도입부]]의 축약본임을 밝힌다."),
        FlowBlock(stage="전개", sentence_range="2~3", summary="가뭄 속 소녀의 힘든 [[선택]], 물 공급이 [[재개]]되며 일상 회복."),
        FlowBlock(stage="결론", sentence_range="4", summary="물 부족 [[요인]]을 방치하면 이야기가 [[현실]]이 될 수 있다는 경고."),
    ],
)

i8 = [
    S(r8, 1,
        [("shortened (과거분사)", "version을 꾸미는 '축약된'"), ("of ~ of ~ (전치사 연결)", "축약본 ← 도입부 ← 소설")],
        [("shortened", "축약한"), ("version", "판·형태"), ("opening", "도입부·첫 부분")],
        [("The above is a shortened [[version]]", "위 글은 [[축약본]]이다"),
         ("of the [[opening]] of the novel Dry (2018).", "소설 「Dry」(2018)의 [[도입부]]의.")],
        [("위 글은 소설 「Dry」 전체를 그대로 옮긴 것이다.",
          "'shortened version(축약본)'이자 opening(도입부) — 전체가 아니라 첫 부분을 줄인 것이다.")]),
    S(r8, 2,
        [("who (주격 관계대명사)", "a girl을 꾸미는 절"), ("has to (의무)", "~해야 한다"), ("It (지칭)", "It은 the novel Dry")],
        [("tough", "힘든·어려운"), ("disastrous", "재난 같은·파괴적인"), ("drought", "가뭄")],
        [("It tells the story of a [[girl]]", "그것은 한 [[소녀]]의 이야기를 들려준다"),
         ("who has to make [[tough]] choices", "[[힘든]] 선택을 해야 하는"),
         ("for her [[family]]", "[[가족]]을 위해"),
         ("during a [[disastrous]] California drought.", "[[재난 같은]] 캘리포니아 가뭄 동안.")],
        [("문장 첫머리 It은 앞 문장에 나온 소녀(a girl)를 가리킨다.",
          "It은 the novel Dry(소설)를 가리키는 지칭 — '소설이 한 소녀의 이야기를 들려준다'는 뜻이다."),
         ("소녀는 가뭄 동안 손쉬운 결정만 내리면 된다.",
          "'tough choices(힘든 선택)'를 make 해야 한다 — 가족을 위해 어려운 결정을 내려야 하는 처지다.")]),
    S(r8, 3,
        [("when (시간 부사절)", "~할 때 모험이 끝남"), ("and (병렬)", "resumes ↔ is back to normal")],
        [("resumes", "재개되다·다시 시작되다"), ("normal", "정상·평상")],
        [("Her unwanted [[adventure]] ends", "그녀의 원치 않은 [[모험]]은 끝난다"),
         ("when the water supply [[resumes]]", "물 공급이 [[재개될]] 때"),
         ("and life is back to [[normal]].", "그리고 삶이 [[정상]]으로 돌아온다.")],
        [("그녀의 모험은 물 공급이 완전히 끊기면서 끝난다.",
          "'water supply resumes(물 공급이 재개되다)'로 끝난다 — 끊기는 게 아니라 다시 공급되어 일상이 회복된다는 뜻이다.")]),
    S(r8, 4,
        [("Provided that (조건)", "'~라면(안 하면)' 조건 접속사"), ("가주어 it", "it is possible that ~ 의 it"), ("including (예시)", "요인들의 예를 나열")],
        [("factors", "요인"), ("addressed", "해결된·다뤄진"), ("agriculture", "농업"), ("reality", "현실")],
        [("Provided that the [[factors]] contributing to water shortages worldwide", "전 세계 물 부족을 부르는 [[요인]]들이"),
         ("are not [[addressed]],", "[[해결되지]] 않는다면,"),
         ("including [[climate change]], population growth,", "[[기후 변화]], 인구 증가,"),
         ("and using too much water for [[agriculture]],", "그리고 [[농업]]에 물을 너무 많이 쓰는 것을 포함해,"),
         ("it is [[possible]]", "[[가능하다]]"),
         ("that this story can become a [[reality]].", "이 이야기가 [[현실]]이 될 수 있다는 것이.")],
        [("이 소설의 내용은 현실과 무관한 순전한 상상일 뿐이다.",
          "'Provided that ~ not addressed ~ this story can become a reality' — 기후 변화 등 요인을 방치하면 소설이 현실이 될 수 있다는 경고다(함축)."),
         ("여기서 this story는 앞으로 새로 쓸 다른 소설을 가리킨다.",
          "this story는 앞서 소개한 소설 「Dry」의 이야기를 가리키는 지칭 — 그 이야기가 현실이 될 수 있다는 뜻이다.")]),
]

P8 = build("Dry ⑧ 작품 소개·경고", "작품 정리 · 1 (소설 「Dry」와 현실 경고)", r8, ov8, i8)

PARTS = [P7, P8]
