# -*- coding: utf-8 -*-
"""
초등 4학년 수준 영어 회화 교재 콘텐츠 데이터 (OPIC 주제 기반).

각 단원(UNIT)은 동일한 '템플릿' 구조를 따릅니다.
  1) 워드뱅크(Word Bank)   - 핵심 단어 + 뜻 + 한글 발음
  2) 핵심 표현(Patterns)   - 질문/대답 문장 패턴
  3) 대화 예시(Dialogue)   - A/B 짧은 회화
  4) 나만의 대답(Template) - 빈칸을 채워 말하기

초등학생에게 어려운 OPIC 주제(직장/출장/은행/호텔예약 등)는 제외했습니다.
콘텐츠만 수정하면 build_textbook.py 가 그대로 PDF 로 만들어 줍니다.
"""

TITLE = "초등 영어 회화 교재"
SUBTITLE = "OPIC 주제로 배우는 말하기 · 초등 4학년 눈높이"
FOOTER = "초등 영어 회화 교재 · 템플릿 + 워드뱅크"

# 템플릿 사용법 설명 (교재 앞부분)
HOW_TO_USE = [
    ("1. 워드뱅크 익히기", "먼저 단원의 핵심 단어를 소리 내어 읽어 봐요. 한글 발음을 참고하면 쉬워요."),
    ("2. 핵심 표현 따라 하기", "질문과 대답 문장을 그대로 3번씩 말해 봐요. 회화의 뼈대가 되는 문장이에요."),
    ("3. 대화 예시 읽기", "친구와 A, B 역할을 나누어 대화를 읽어 봐요. 역할을 바꿔서 한 번 더!"),
    ("4. 나만의 대답 만들기", "빈칸에 워드뱅크 단어를 넣어 '나만의 문장'을 완성하고 말해 봐요."),
]

UNITS = [
    {
        "emoji": "👪",
        "title_ko": "나와 가족",
        "title_en": "Me & My Family",
        "words": [
            ("family", "가족", "패밀리"),
            ("mom", "엄마", "맘"),
            ("dad", "아빠", "대드"),
            ("sister", "언니 / 여동생", "시스터"),
            ("brother", "형 / 남동생", "브라더"),
            ("grandmother", "할머니", "그랜드마더"),
            ("grandfather", "할아버지", "그랜드파더"),
            ("name", "이름", "네임"),
            ("age", "나이", "에이지"),
            ("years old", "~살", "이어스 올드"),
        ],
        "patterns": [
            ("What is your name?", "네 이름이 뭐야?", "My name is Jimin.", "내 이름은 지민이야."),
            ("How old are you?", "몇 살이야?", "I am ten years old.", "나는 열 살이야."),
            ("How many people are in your family?", "가족이 몇 명이야?", "There are four people in my family.", "우리 가족은 네 명이야."),
            ("Who is in your family?", "가족이 누구누구야?", "My mom, my dad, and me.", "엄마, 아빠, 그리고 나야."),
        ],
        "dialogue": [
            ("A", "Hi! What's your name?", "안녕! 네 이름이 뭐야?"),
            ("B", "My name is Jimin. What's your name?", "내 이름은 지민이야. 너는?"),
            ("A", "I'm Sora. How old are you?", "나는 소라야. 몇 살이야?"),
            ("B", "I'm ten years old. How about you?", "나는 열 살이야. 너는?"),
            ("A", "I'm eleven. How many people are in your family?", "나는 열한 살이야. 가족은 몇 명이야?"),
            ("B", "There are four people. My mom, my dad, my brother, and me.", "네 명이야. 엄마, 아빠, 남동생, 그리고 나."),
        ],
        "template": [
            "My name is ____________.",
            "I am ________ years old.",
            "There are ______ people in my family.",
            "I love my ____________.",
        ],
    },
    {
        "emoji": "🏠",
        "title_ko": "우리 집",
        "title_en": "My House",
        "words": [
            ("house", "집", "하우스"),
            ("room", "방", "룸"),
            ("my room", "내 방", "마이 룸"),
            ("kitchen", "부엌", "키친"),
            ("living room", "거실", "리빙 룸"),
            ("bathroom", "화장실", "배쓰룸"),
            ("bed", "침대", "베드"),
            ("desk", "책상", "데스크"),
            ("window", "창문", "윈도우"),
            ("door", "문", "도어"),
        ],
        "patterns": [
            ("Where do you live?", "어디에 살아?", "I live in Seoul.", "나는 서울에 살아."),
            ("What is your favorite room?", "제일 좋아하는 방은 어디야?", "My favorite room is my room.", "내가 제일 좋아하는 방은 내 방이야."),
            ("What is in your room?", "네 방에는 뭐가 있어?", "There is a bed and a desk.", "침대랑 책상이 있어."),
            ("Is your house big?", "너희 집은 커?", "Yes, it is. / No, it is small.", "응, 커. / 아니, 작아."),
        ],
        "dialogue": [
            ("A", "Where do you live?", "어디에 살아?"),
            ("B", "I live in Seoul. I live in an apartment.", "나는 서울에 살아. 아파트에 살아."),
            ("A", "What is your favorite room?", "제일 좋아하는 방은 어디야?"),
            ("B", "My favorite room is my room. I have a big desk.", "내 방이야. 큰 책상이 있어."),
            ("A", "What is in your room?", "네 방에는 뭐가 있어?"),
            ("B", "There is a bed, a desk, and many books.", "침대, 책상, 그리고 책이 많이 있어."),
        ],
        "template": [
            "I live in ____________.",
            "My house has a ____________ and a ____________.",
            "My favorite room is my ____________.",
            "There is a ____________ in my room.",
        ],
    },
    {
        "emoji": "🏫",
        "title_ko": "학교 생활",
        "title_en": "My School",
        "words": [
            ("school", "학교", "스쿨"),
            ("teacher", "선생님", "티처"),
            ("friend", "친구", "프렌드"),
            ("classroom", "교실", "클래스룸"),
            ("subject", "과목", "서브젝트"),
            ("math", "수학", "매쓰"),
            ("English", "영어", "잉글리시"),
            ("science", "과학", "사이언스"),
            ("homework", "숙제", "홈워크"),
            ("lunch", "점심", "런치"),
        ],
        "patterns": [
            ("What grade are you in?", "몇 학년이야?", "I am in fourth grade.", "나는 4학년이야."),
            ("What is your favorite subject?", "제일 좋아하는 과목은?", "My favorite subject is science.", "내가 제일 좋아하는 과목은 과학이야."),
            ("Who is your best friend?", "제일 친한 친구는 누구야?", "My best friend is Minho.", "제일 친한 친구는 민호야."),
            ("What do you do at school?", "학교에서 뭐 해?", "I study and play with my friends.", "공부하고 친구들이랑 놀아."),
        ],
        "dialogue": [
            ("A", "What grade are you in?", "몇 학년이야?"),
            ("B", "I am in fourth grade.", "나는 4학년이야."),
            ("A", "What is your favorite subject?", "제일 좋아하는 과목은?"),
            ("B", "My favorite subject is science. It is fun!", "과학이야. 재미있어!"),
            ("A", "Do you have a best friend?", "제일 친한 친구 있어?"),
            ("B", "Yes. My best friend is Minho. We play every day.", "응. 민호야. 우리는 매일 놀아."),
        ],
        "template": [
            "I am in ________ grade.",
            "My favorite subject is ____________.",
            "My teacher is ____________.",
            "At school, I like to ____________.",
        ],
    },
    {
        "emoji": "🎨",
        "title_ko": "취미",
        "title_en": "My Hobbies",
        "words": [
            ("hobby", "취미", "하비"),
            ("draw", "그림 그리다", "드로우"),
            ("read", "읽다", "리드"),
            ("play games", "게임하다", "플레이 게임즈"),
            ("ride a bike", "자전거 타다", "라이드 어 바이크"),
            ("sing", "노래하다", "싱"),
            ("dance", "춤추다", "댄스"),
            ("free time", "여가 시간", "프리 타임"),
            ("fun", "재미있는", "펀"),
            ("every day", "매일", "에브리 데이"),
        ],
        "patterns": [
            ("What is your hobby?", "취미가 뭐야?", "My hobby is drawing.", "내 취미는 그림 그리기야."),
            ("What do you do in your free time?", "여가 시간에 뭐 해?", "I like to read books.", "나는 책 읽는 걸 좋아해."),
            ("Do you like drawing?", "그림 그리는 거 좋아해?", "Yes, I do. / No, I don't.", "응, 좋아해. / 아니, 안 좋아해."),
            ("How often do you draw?", "얼마나 자주 그려?", "Every day. / On weekends.", "매일. / 주말에."),
        ],
        "dialogue": [
            ("A", "What is your hobby?", "취미가 뭐야?"),
            ("B", "My hobby is drawing. I like to draw animals.", "내 취미는 그림 그리기야. 동물 그리는 걸 좋아해."),
            ("A", "Cool! What do you do in your free time?", "멋지다! 여가 시간엔 뭐 해?"),
            ("B", "I read books and ride my bike.", "책 읽고 자전거 타."),
            ("A", "How often do you ride your bike?", "자전거는 얼마나 자주 타?"),
            ("B", "I ride my bike every weekend.", "주말마다 타."),
        ],
        "template": [
            "My hobby is ____________.",
            "In my free time, I like to ____________.",
            "I do it ____________ (every day / on weekends).",
            "It is so fun!",
        ],
    },
    {
        "emoji": "⚽",
        "title_ko": "운동",
        "title_en": "Sports & Exercise",
        "words": [
            ("soccer", "축구", "사커"),
            ("basketball", "농구", "배스킷볼"),
            ("swimming", "수영", "스위밍"),
            ("running", "달리기", "러닝"),
            ("jump rope", "줄넘기", "점프 로프"),
            ("badminton", "배드민턴", "배드민턴"),
            ("ball", "공", "볼"),
            ("team", "팀", "팀"),
            ("play", "(운동을) 하다", "플레이"),
            ("good at", "~을 잘하는", "굿 앳"),
        ],
        "patterns": [
            ("What sport do you like?", "무슨 운동 좋아해?", "I like soccer.", "나는 축구를 좋아해."),
            ("Can you swim?", "수영할 수 있어?", "Yes, I can. / No, I can't.", "응, 할 수 있어. / 아니, 못해."),
            ("Where do you play?", "어디서 해?", "I play at the park.", "나는 공원에서 해."),
            ("Who do you play with?", "누구랑 해?", "I play with my friends.", "친구들이랑 해."),
        ],
        "dialogue": [
            ("A", "What sport do you like?", "무슨 운동 좋아해?"),
            ("B", "I like soccer. I play every Saturday.", "축구 좋아해. 토요일마다 해."),
            ("A", "Can you swim?", "수영할 수 있어?"),
            ("B", "Yes, I can. I swim at the pool.", "응. 수영장에서 수영해."),
            ("A", "Who do you play soccer with?", "축구는 누구랑 해?"),
            ("B", "I play with my friends at the park.", "공원에서 친구들이랑 해."),
        ],
        "template": [
            "I like ____________.",
            "I play it at the ____________.",
            "I play with my ____________.",
            "I am good at ____________.",
        ],
    },
    {
        "emoji": "🍚",
        "title_ko": "음식",
        "title_en": "Food & Meals",
        "words": [
            ("food", "음식", "푸드"),
            ("rice", "밥", "라이스"),
            ("pizza", "피자", "핏자"),
            ("chicken", "치킨", "치킨"),
            ("fruit", "과일", "프룻"),
            ("apple", "사과", "애플"),
            ("milk", "우유", "밀크"),
            ("breakfast", "아침밥", "브렉퍼스트"),
            ("dinner", "저녁밥", "디너"),
            ("delicious", "맛있는", "딜리셔스"),
        ],
        "patterns": [
            ("What is your favorite food?", "제일 좋아하는 음식은?", "My favorite food is pizza.", "내가 제일 좋아하는 음식은 피자야."),
            ("What do you eat for breakfast?", "아침에 뭐 먹어?", "I eat rice and eggs.", "밥이랑 계란을 먹어."),
            ("Do you like fruit?", "과일 좋아해?", "Yes, I love apples.", "응, 사과를 정말 좋아해."),
            ("Is it delicious?", "맛있어?", "Yes, it is very delicious!", "응, 정말 맛있어!"),
        ],
        "dialogue": [
            ("A", "What is your favorite food?", "제일 좋아하는 음식은?"),
            ("B", "My favorite food is pizza. It is delicious!", "피자야. 정말 맛있어!"),
            ("A", "What do you eat for breakfast?", "아침엔 뭐 먹어?"),
            ("B", "I eat rice and eggs. I drink milk, too.", "밥이랑 계란 먹어. 우유도 마셔."),
            ("A", "Do you like fruit?", "과일 좋아해?"),
            ("B", "Yes, I love apples and bananas.", "응, 사과랑 바나나 좋아해."),
        ],
        "template": [
            "My favorite food is ____________.",
            "For breakfast, I eat ____________.",
            "I like ____________, but I don't like ____________.",
            "It is delicious!",
        ],
    },
    {
        "emoji": "🐶",
        "title_ko": "반려동물",
        "title_en": "Pets",
        "words": [
            ("pet", "반려동물", "펫"),
            ("dog", "강아지", "도그"),
            ("cat", "고양이", "캣"),
            ("rabbit", "토끼", "래빗"),
            ("fish", "물고기", "피시"),
            ("bird", "새", "버드"),
            ("cute", "귀여운", "큐트"),
            ("feed", "먹이를 주다", "피드"),
            ("walk", "산책시키다", "워크"),
            ("name", "이름", "네임"),
        ],
        "patterns": [
            ("Do you have a pet?", "반려동물 있어?", "Yes, I have a dog. / No, I don't.", "응, 강아지가 있어. / 아니, 없어."),
            ("What is its name?", "이름이 뭐야?", "Its name is Coco.", "이름은 코코야."),
            ("What does it look like?", "어떻게 생겼어?", "It is small and cute.", "작고 귀여워."),
            ("What do you do with your pet?", "반려동물이랑 뭐 해?", "I feed it and walk it.", "먹이 주고 산책시켜."),
        ],
        "dialogue": [
            ("A", "Do you have a pet?", "반려동물 있어?"),
            ("B", "Yes, I have a dog. Its name is Coco.", "응, 강아지 있어. 이름은 코코야."),
            ("A", "What does Coco look like?", "코코는 어떻게 생겼어?"),
            ("B", "Coco is small and brown. It is very cute.", "코코는 작고 갈색이야. 정말 귀여워."),
            ("A", "What do you do with Coco?", "코코랑 뭐 해?"),
            ("B", "I feed Coco and walk it every day.", "매일 먹이 주고 산책시켜."),
        ],
        "template": [
            "I have a ____________.",
            "Its name is ____________.",
            "It is ____________ and ____________.",
            "I like to ____________ with my pet.",
        ],
    },
    {
        "emoji": "🌈",
        "title_ko": "날씨와 계절",
        "title_en": "Weather & Seasons",
        "words": [
            ("weather", "날씨", "웨더"),
            ("sunny", "맑은", "써니"),
            ("rainy", "비 오는", "레이니"),
            ("snowy", "눈 오는", "스노위"),
            ("hot", "더운", "핫"),
            ("cold", "추운", "콜드"),
            ("spring", "봄", "스프링"),
            ("summer", "여름", "써머"),
            ("fall", "가을", "폴"),
            ("winter", "겨울", "윈터"),
        ],
        "patterns": [
            ("How is the weather today?", "오늘 날씨 어때?", "It is sunny and warm.", "맑고 따뜻해."),
            ("What is your favorite season?", "제일 좋아하는 계절은?", "My favorite season is summer.", "내가 제일 좋아하는 계절은 여름이야."),
            ("What do you do in summer?", "여름에 뭐 해?", "I go swimming.", "수영하러 가."),
            ("Do you like winter?", "겨울 좋아해?", "Yes, I like the snow.", "응, 눈이 좋아."),
        ],
        "dialogue": [
            ("A", "How is the weather today?", "오늘 날씨 어때?"),
            ("B", "It is sunny and warm.", "맑고 따뜻해."),
            ("A", "What is your favorite season?", "제일 좋아하는 계절은?"),
            ("B", "My favorite season is summer. I like to go swimming.", "여름이야. 수영하러 가는 걸 좋아해."),
            ("A", "I like winter. I can make a snowman!", "나는 겨울이 좋아. 눈사람을 만들 수 있거든!"),
            ("B", "That sounds fun!", "재미있겠다!"),
        ],
        "template": [
            "Today it is ____________.",
            "My favorite season is ____________.",
            "In ____________, I like to ____________.",
            "I don't like ____________ weather.",
        ],
    },
    {
        "emoji": "🎬",
        "title_ko": "영화와 음악",
        "title_en": "Movies & Music",
        "words": [
            ("movie", "영화", "무비"),
            ("music", "음악", "뮤직"),
            ("song", "노래", "송"),
            ("sing", "노래하다", "싱"),
            ("listen", "듣다", "리슨"),
            ("watch", "보다", "워치"),
            ("funny", "웃긴", "퍼니"),
            ("exciting", "신나는", "익사이팅"),
            ("singer", "가수", "싱어"),
            ("K-pop", "케이팝", "케이팝"),
        ],
        "patterns": [
            ("Do you like movies?", "영화 좋아해?", "Yes, I love movies.", "응, 영화 정말 좋아해."),
            ("What is your favorite movie?", "제일 좋아하는 영화는?", "My favorite movie is Frozen.", "내가 제일 좋아하는 영화는 겨울왕국이야."),
            ("What music do you like?", "무슨 음악 좋아해?", "I like K-pop.", "나는 케이팝을 좋아해."),
            ("Who is your favorite singer?", "제일 좋아하는 가수는?", "My favorite singer is IU.", "내가 제일 좋아하는 가수는 아이유야."),
        ],
        "dialogue": [
            ("A", "Do you like movies?", "영화 좋아해?"),
            ("B", "Yes! My favorite movie is Frozen. It is exciting.", "응! 제일 좋아하는 영화는 겨울왕국이야. 신나."),
            ("A", "What music do you like?", "무슨 음악 좋아해?"),
            ("B", "I like K-pop. I listen to music every day.", "케이팝 좋아해. 매일 음악 들어."),
            ("A", "Who is your favorite singer?", "제일 좋아하는 가수는?"),
            ("B", "I like IU. Her songs are great.", "아이유 좋아해. 노래가 정말 좋아."),
        ],
        "template": [
            "My favorite movie is ____________.",
            "It is ____________ (funny / exciting).",
            "I like ____________ music.",
            "My favorite singer is ____________.",
        ],
    },
    {
        "emoji": "✈️",
        "title_ko": "여행과 방학",
        "title_en": "Travel & Vacation",
        "words": [
            ("travel", "여행하다", "트래블"),
            ("trip", "여행", "트립"),
            ("vacation", "방학 / 휴가", "베케이션"),
            ("beach", "해변", "비치"),
            ("mountain", "산", "마운틴"),
            ("sea", "바다", "씨"),
            ("plane", "비행기", "플레인"),
            ("train", "기차", "트레인"),
            ("visit", "방문하다", "비짓"),
            ("fun", "재미있는", "펀"),
        ],
        "patterns": [
            ("Where do you want to go?", "어디에 가고 싶어?", "I want to go to the beach.", "나는 해변에 가고 싶어."),
            ("What do you do on vacation?", "방학 때 뭐 해?", "I visit my grandmother.", "할머니를 뵈러 가."),
            ("How do you go there?", "거기 어떻게 가?", "I go by train.", "기차를 타고 가."),
            ("Was it fun?", "재미있었어?", "Yes, it was so fun!", "응, 정말 재미있었어!"),
        ],
        "dialogue": [
            ("A", "What do you do on vacation?", "방학 때 뭐 해?"),
            ("B", "I visit my grandmother. She lives in Busan.", "할머니를 뵈러 가. 부산에 사셔."),
            ("A", "How do you go there?", "거기 어떻게 가?"),
            ("B", "I go by train. It is fast.", "기차 타고 가. 빨라."),
            ("A", "Where do you want to go next?", "다음엔 어디 가고 싶어?"),
            ("B", "I want to go to the beach. I love the sea!", "해변에 가고 싶어. 바다 정말 좋아!"),
        ],
        "template": [
            "On vacation, I ____________.",
            "I want to go to ____________.",
            "I go there by ____________ (car / plane / train).",
            "It is so fun!",
        ],
    },
]
