# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad/batches/공통영어2_능률_민병천_2과")
from _helpers import *

# =====================================================================
# P1 — 1 · 과학 수사와 Lee 소개
# =====================================================================
r1 = [
 "Criminals never leave a crime scene without leaving behind traces of their presence.",
 "The traces might be tiny, like hairs, or more obvious, such as soil from their shoes.",
 "So detectives carefully collect all the possible evidence.",
 "Scientists then analyze everything and find some clues.",
 "The clues are used to find the person who committed the crime.",
 "This process is called forensic science.",
 "It has evolved thanks to the contributions of many researchers.",
 "One of the most important people in the development of modern forensic science was Frances Glessner Lee.",
]

ov1 = Overview(
 theme_ko="흔적에서 범인까지 — 과학 수사의 원리와 Lee의 등장",
 key_grammar=KeyGrammar(
  point="이중부정 never ~ without -ing (…없이는 결코 …않는다)",
  source_sentence="Criminals never leave a crime scene without leaving behind traces of their presence.",
  explanation=[
   GN("쉽게 말하면", "never와 without이 겹친 [[이중부정]]은 '…없이는 결코 …않는다' = '반드시 …한다'는 [[강한 긍정]]."),
   GN("구조", "never leave ~ without [[leaving]] : without 뒤에는 [[동명사]](-ing)가 온다."),
   GN("뜻풀이", "'흔적을 남기지 않고는 결코 떠나지 않는다' = '떠날 때 [[반드시]] 흔적을 남긴다'."),
   GN("주의", "겉으로는 부정문 두 개지만 속뜻은 [[긍정]] 강조라는 점에 유의."),
  ],
  example_analysis="never leave ... without leaving = 이중부정 → '반드시 흔적을 남긴다'는 강한 긍정.",
  drills=[
   GrammarDrill(kind="객관식", from_passage=True,
    question="지문에서 'never leave a crime scene without leaving'이 뜻하는 바로 알맞은 것은?",
    options=["떠날 때 반드시 흔적을 남긴다는 강한 긍정", "흔적을 남기지 않아도 된다는 허용", "떠날지 말지 정하지 못했다는 미정"],
    answer="떠날 때 반드시 흔적을 남긴다는 강한 긍정"),
   GrammarDrill(kind="객관식", from_passage=False,
    question="이중부정(never ~ without -ing)이 바르게 쓰인 문장은?",
    options=["He never passes by without saying hello.", "He never says hello to anyone.", "He always says hello without a smile."],
    answer="He never passes by without saying hello."),
   GrammarDrill(kind="객관식", from_passage=False,
    question="빈칸: 'She never leaves home ____ locking the door.' (문을 잠그지 않고는 결코 나가지 않는다)",
    options=["without", "with", "by"],
    answer="without"),
   GrammarDrill(kind="영작", from_passage=True,
    question="(지문) 범죄자는 자신이 있었다는 흔적을 남기지 않고는 결코 범죄 현장을 떠나지 않는다.",
    answer="Criminals never leave a crime scene without leaving behind traces of their presence."),
   GrammarDrill(kind="영작", from_passage=False,
    question="그는 사전을 확인하지 않고는 결코 글을 쓰지 않는다.",
    answer="He never writes without checking the dictionary."),
  ]),
 topic="범죄 현장의 흔적을 수집·분석해 범인을 찾는 과학 수사의 원리와 그 핵심 인물 Lee 소개.",
 stance="중립적",
 stance_reason="과학 수사의 절차와 정의를 객관적으로 설명하는 도입부다.",
 structure="예시→일반화(결론)",
 structure_reason="흔적 수집·분석·단서라는 구체적 절차를 열거한 뒤 그것을 '과학 수사'로 일반화하고 핵심 인물로 마무리한다.",
 restatement_chains=[
  RestatementChain(label="과학 수사",
   expressions=["forensic science", "the development of modern forensic science"],
   variation="'과학 수사'라는 정의가 '현대 과학 수사의 발전'으로 확장된다."),
 ],
 flow_blocks=[
  FlowBlock(stage="도입", sentence_range="1~2", summary="범죄자는 반드시 [[흔적]]을 남기며, 작은 것부터 뚜렷한 것까지 다양하다."),
  FlowBlock(stage="전개", sentence_range="3~5", summary="형사가 [[증거]]를 수집→과학자가 분석→단서로 범인을 찾는다."),
  FlowBlock(stage="일반화", sentence_range="6~7", summary="이 과정을 [[과학 수사]]라 부르며 여러 연구자의 기여로 발전해 왔다."),
  FlowBlock(stage="인물 도입", sentence_range="8", summary="발전의 핵심 인물 중 한 명이 [[Frances Glessner Lee]]다."),
 ])

i1 = [
 S(r1, 1,
  [("이중부정 never ~ without -ing", "never와 without이 겹쳐 '반드시 …한다'는 강한 긍정"),
   ("전치사 without + 동명사", "without 뒤에는 leaving 같은 -ing형")],
  [("criminal", "범죄자"), ("trace", "흔적"), ("presence", "있었음, 존재")],
  [("Criminals never leave a [[crime scene]]", "범죄자는 결코 [[범죄 현장]]을 떠나지 않는다"),
   ("without [[leaving behind traces]] of their presence.", "자신이 있었다는 [[흔적을 남기지]] 않고는.")],
  [("범죄자는 흔적을 남기지 않고 현장을 빠져나갈 수 있다는 뜻이다.", "never ~ without는 이중부정으로 '반드시 흔적을 남긴다'는 강조 — 흔적 없이 떠날 수 있다는 말이 아니다.")]),
 S(r1, 2,
  [("비교급 more obvious", "'더 뚜렷한'을 나타내는 비교급"),
   ("like / such as", "예시를 드는 전치사구")],
  [("tiny", "아주 작은"), ("obvious", "뚜렷한, 분명한"), ("soil", "흙")],
  [("The traces might be [[tiny]], like hairs,", "그 흔적은 [[아주 작을]] 수도 있는데, 머리카락처럼,"),
   ("or [[more obvious]], such as soil from their shoes.", "혹은 [[더 뚜렷할]] 수도 있는데, 신발에 묻은 흙처럼.")],
  [("여기서 The traces는 형사가 일부러 놓아둔 표시를 가리킨다.", "(지칭) The traces는 1번 문장에서 범죄자가 남긴 흔적 — 머리카락이나 흙 같은 것을 가리킨다.")]),
 S(r1, 3,
  [("결과 접속사 So", "'그래서'로 앞 내용의 결과를 이음")],
  [("detective", "형사, 탐정"), ("collect", "수집하다"), ("evidence", "증거")],
  [("So detectives carefully [[collect]]", "그래서 형사들은 신중하게 [[수집한다]]"),
   ("all the possible [[evidence]].", "가능한 모든 [[증거]]를.")],
  [("형사들은 눈에 잘 띄는 증거만 골라서 수집한다.", "'all the possible evidence(가능한 모든 증거)'를 신중히 모은다 — 일부만 고르는 것이 아니다.")]),
 S(r1, 4,
  [("순서 부사 then", "'그런 다음'으로 다음 단계를 이음"),
   ("병렬 동사", "analyze와 find가 and로 나열")],
  [("analyze", "분석하다"), ("clue", "단서")],
  [("Scientists then [[analyze]] everything", "그런 다음 과학자들이 모든 것을 [[분석한다]]"),
   ("and find some [[clues]].", "그리고 몇 가지 [[단서]]를 찾아낸다.")],
  [("이 문장은 과학자가 증거를 수집하는 단계를 설명한다.", "수집은 형사(detectives)의 몫이고, 과학자(Scientists)는 그것을 분석해 단서를 찾는 역할이다.")]),
 S(r1, 5,
  [("수동태 are used", "'사용되다'는 be동사+과거분사"),
   ("주격 관계대명사 who", "the person을 꾸미는 who절")],
  [("commit", "(범죄를) 저지르다"), ("crime", "범죄")],
  [("The clues are [[used]]", "그 단서들은 [[사용된다]]"),
   ("to find the [[person]]", "[[그 사람]]을 찾는 데"),
   ("who committed the [[crime]].", "[[범죄]]를 저지른.")],
  [("단서는 범죄를 저지른 사람을 처벌하는 데 쓰인다.", "'to find the person'은 범인을 '찾는' 데 쓰인다는 뜻 — 처벌이 아니라 신원 확인 목적이다.")]),
 S(r1, 6,
  [("수동태 is called", "'…라고 불리다'"),
   ("지시 This process", "앞서 말한 절차 전체를 가리킴")],
  [("process", "과정, 절차"), ("forensic science", "과학 수사")],
  [("This process is [[called]]", "이 과정은 [[불린다]]"),
   ("[[forensic science]].", "[[과학 수사]]라고.")],
  [("This process는 범죄를 저지르는 과정을 가리킨다.", "(지칭) This process는 앞에서 말한 증거 수집·분석·단서로 범인 찾기의 전 과정, 즉 과학 수사를 가리킨다.")]),
 S(r1, 7,
  [("현재완료 has evolved", "지금까지 발전해 온 결과"),
   ("지시 It", "앞의 forensic science를 가리킴")],
  [("evolve", "발전하다, 진화하다"), ("contribution", "기여"), ("researcher", "연구자")],
  [("It has [[evolved]]", "그것은 [[발전해 왔다]]"),
   ("thanks to the [[contributions]]", "[[기여]] 덕분에"),
   ("of many [[researchers]].", "많은 [[연구자들]]의.")],
  [("여기서 It은 특정 연구자 한 사람을 가리킨다.", "(지칭) It은 forensic science(과학 수사)를 가리키며, 여러 연구자의 기여로 발전해 왔다는 뜻이다.")]),
 S(r1, 8,
  [("최상급 the most important", "'가장 중요한'"),
   ("One of the 최상급 + 복수명사", "'가장 …한 것들 중 하나'")],
  [("development", "발전"), ("modern", "현대의")],
  [("One of the most [[important]] people", "가장 [[중요한]] 인물 중 한 명은"),
   ("in the [[development]] of modern forensic science", "현대 과학 수사의 [[발전]]에서"),
   ("was [[Frances Glessner Lee]].", "바로 [[Frances Glessner Lee]]였다.")],
  [("Lee가 현대 과학 수사를 혼자서 처음 만들어 냈다는 뜻이다.", "(함축) 'One of the most important people'은 '가장 중요한 인물 중 한 명'이라는 뜻 — 단독 창시자가 아니라 핵심 기여자 중 하나다.")]),
]

P1 = build("Lee ① 과학수사 도입", "1 · 과학 수사와 Lee 소개", r1, ov1, i1)

# =====================================================================
# P2 — 2 · 좌절된 꿈과 뒤늦은 시작
# =====================================================================
r2 = [
 "Frances Glessner Lee was born into a rich family in Chicago in 1878.",
 "She became interested in medicine at a young age.",
 "Her dream was to attend Harvard Medical School, but, at that time, the school did not accept women.",
 "She had no choice but to get married.",
 "It was not until she was in her fifties that Lee was able to start a career in medicine.",
]

ov2 = Overview(
 theme_ko="꺾인 의학의 꿈, 그리고 오십 대의 뒤늦은 출발",
 key_grammar=KeyGrammar(
  point="It was not until ~ that ... 강조구문 (…에야 비로소)",
  source_sentence="It was not until she was in her fifties that Lee was able to start a career in medicine.",
  explanation=[
   GN("쉽게 말하면", "It was not until A that B = 'A가 되어서야 [[비로소]] B했다' = 그만큼 [[늦게]]야 B했다."),
   GN("구조", "It was ~ that로 [[not until she was in her fifties]] 부분을 앞으로 빼 [[강조]]한다."),
   GN("복원", "원래 문장은 'Lee was not able to start ... [[until]] she was in her fifties.'"),
   GN("함축", "'오십 대가 되어서야'는 그 전에는 시작하지 [[못했다]]는 늦은 출발을 강조한다."),
  ],
  example_analysis="It was not until [she was in her fifties] that Lee ... = until절을 강조로 앞세운 강조구문.",
  drills=[
   GrammarDrill(kind="객관식", from_passage=True,
    question="지문 'It was not until she was in her fifties that Lee ~'의 뜻으로 알맞은 것은?",
    options=["오십 대가 되어서야 비로소 시작했다", "오십 대가 되기 전에 이미 시작했다", "오십 대 내내 계속하기만 했다"],
    answer="오십 대가 되어서야 비로소 시작했다"),
   GrammarDrill(kind="객관식", from_passage=False,
    question="'It was not until ~ that ~' 강조구문이 바르게 쓰인 문장은?",
    options=["It was not until midnight that he arrived.", "He arrived until midnight last night.", "He did not arrive at midnight at all."],
    answer="It was not until midnight that he arrived."),
   GrammarDrill(kind="객관식", from_passage=False,
    question="빈칸: 'It was not ____ she left that I felt relieved.' (그녀가 떠나고 나서야 비로소 안심했다)",
    options=["until", "because", "although"],
    answer="until"),
   GrammarDrill(kind="영작", from_passage=True,
    question="(지문) 그녀가 오십 대가 되어서야 비로소 Lee는 의학 분야의 경력을 시작할 수 있었다.",
    answer="It was not until she was in her fifties that Lee was able to start a career in medicine."),
   GrammarDrill(kind="영작", from_passage=False,
    question="밤이 되어서야 비로소 그는 집으로 돌아왔다.",
    answer="It was not until night that he came back home."),
  ]),
 topic="부유한 가정에서 태어나 의학을 꿈꿨으나 여성이라는 이유로 좌절하고, 오십 대에야 경력을 시작한 Lee의 생애 초반.",
 stance="중립적",
 stance_reason="Lee의 출생·좌절·뒤늦은 출발을 시간 순으로 담담하게 서술한다.",
 structure="시간·순서(나열)",
 structure_reason="1878년 출생 → 어린 시절 관심 → 하버드 좌절·결혼 → 오십 대의 시작으로 생애가 시간 순으로 전개된다.",
 restatement_chains=[
  RestatementChain(label="좌절된 의학의 꿈",
   expressions=["to attend Harvard Medical School", "start a career in medicine"],
   variation="'하버드 의대 진학'의 꿈이 오랜 좌절 끝에 '의학 경력 시작'으로 뒤늦게 이어진다."),
 ],
 flow_blocks=[
  FlowBlock(stage="도입", sentence_range="1~2", summary="1878년 시카고 [[부유한 가정]]에서 태어나 어릴 때 의학에 관심을 갖는다."),
  FlowBlock(stage="좌절", sentence_range="3~4", summary="하버드 의대를 꿈꿨으나 [[여성]]을 받지 않아 결혼할 수밖에 없었다."),
  FlowBlock(stage="뒤늦은 시작", sentence_range="5", summary="[[오십 대]]가 되어서야 비로소 의학 경력을 시작할 수 있었다."),
 ])

i2 = [
 S(r2, 1,
  [("수동태 was born", "'태어나다'는 be born"),
   ("전치사 into", "'…한 환경 속으로' 태어남")],
  [("be born into", "…한 가정에 태어나다"), ("rich", "부유한")],
  [("Frances Glessner Lee was [[born]]", "Frances Glessner Lee는 [[태어났다]]"),
   ("into a [[rich family]] in Chicago", "시카고의 [[부유한 가정]]에서"),
   ("in 1878.", "1878년에.")],
  [("Lee는 가난한 집안에서 태어나 스스로 부를 일궜다.", "'born into a rich family'는 부유한 가정에서 태어났다는 뜻 — 가난하게 시작한 것이 아니다.")]),
 S(r2, 2,
  [("감정 형용사 interested", "'관심 있는'을 나타내는 형용사"),
   ("become + 형용사", "'…하게 되다'라는 상태 변화")],
  [("become interested in", "…에 관심을 갖게 되다"), ("medicine", "의학")],
  [("She became interested in [[medicine]]", "그녀는 [[의학]]에 관심을 갖게 되었다"),
   ("at a young [[age]].", "[[어린 나이]]에.")],
  [("여기서 She는 앞 문장과 다른 인물, 즉 그녀의 어머니를 가리킨다.", "(지칭) She는 앞 문장의 Frances Glessner Lee를 가리킨다 — 어린 나이에 의학에 관심을 가진 인물이다.")]),
 S(r2, 3,
  [("to부정사 보어", "was to attend = '다니는 것'이라는 주격보어"),
   ("역접 접속사 but", "꿈과 현실을 대비")],
  [("attend", "다니다, 참석하다"), ("accept", "받아들이다")],
  [("Her dream was to [[attend]] Harvard Medical School,", "그녀의 꿈은 하버드 의대에 [[다니는]] 것이었다,"),
   ("but, at that [[time]],", "그러나, 그 [[당시]]에는,"),
   ("the school did not [[accept]] women.", "그 학교는 [[여성을 받아들이지]] 않았다.")],
  [("하버드 의대는 예나 지금이나 여성을 전혀 받지 않는다는 뜻이다.", "(함축) 'at that time(그 당시에는)'은 지금은 다르다는 속뜻을 담은 표현으로, 당시에만 여성을 받지 않았음을 나타낸다."),
   ("여기서 the school은 그녀가 다니던 다른 학교를 가리킨다.", "(지칭) the school은 앞에 나온 Harvard Medical School을 가리킨다.")]),
 S(r2, 4,
  [("have no choice but to", "'…할 수밖에 없다'는 숙어"),
   ("인과 관계", "여성 불허의 결과로 결혼")],
  [("have no choice but to", "…할 수밖에 없다"), ("get married", "결혼하다")],
  [("She had no [[choice]]", "그녀는 [[선택]]의 여지가 없었다"),
   ("but to get [[married]].", "[[결혼하는]] 것 외에는.")],
  [("그녀는 의학을 포기하고 스스로 원해서 결혼을 선택했다.", "(함축·인과) 하버드가 여성을 받지 않아 'had no choice but to get married' — 자발적 선택이 아니라 결혼할 수밖에 없었다는 뜻이다.")]),
 S(r2, 5,
  [("It was not until ~ that 강조구문", "'…에야 비로소 …했다'"),
   ("be able to", "'…할 수 있다'는 가능 표현")],
  [("not until", "…에야 비로소"), ("career", "경력, 이력"), ("fifties", "오십 대")],
  [("It was not until she was in her [[fifties]]", "그녀가 [[오십 대]]가 되어서야 비로소"),
   ("that Lee was able to [[start]]", "Lee는 [[시작할]] 수 있었다"),
   ("a [[career]] in medicine.", "의학 분야의 [[경력]]을.")],
  [("Lee는 젊을 때 곧바로 의학 경력을 시작했다.", "(함축) 'It was not until she was in her fifties'는 오십 대가 되어서야 비로소 시작했다는 뜻으로, 아주 늦게 출발했음을 강조한다.")]),
]

P2 = build("Lee ② 좌절과 시작", "2 · 좌절된 꿈과 뒤늦은 시작", r2, ov2, i2)

PARTS = [P1, P2]
