# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad/batches/공통영어2_능률_민병천_2과")
from _helpers import *

r7 = [
    "In 1945, she held a week-long seminar and gave her first lecture using her miniature crime scenes.",
    "While reading case files, the detectives studied the details of the miniature scenes.",
    "They looked for clues in order to determine if the scene in the miniature resulted from an accident or a violent crime.",
    "The detectives learned to notice tiny details and to observe a scene without destroying any evidence.",
    "By developing their observation skills, they were able to improve their ability to solve crime cases.",
    "Lee's training process was successful.",
    "By 1949, the annual seminar was being attended by detectives not only from the US but also from Canada.",
    "Special agents and military staff also attended the seminar.",
    "Lee died in 1962, after a career of more than thirty years.",
    "Although she had struggled to enter the field, her contributions to forensic science were significant.",
    "It is no wonder that she was called the “mother of forensic science.”",
]

ov7 = Overview(
    theme_ko="세미나의 성공과 '과학 수사의 어머니'라는 유산",
    key_grammar=KeyGrammar(
        point="상관접속사 not only A but also B (A뿐 아니라 B도)",
        source_sentence="By 1949, the annual seminar was being attended by detectives not only from the US but also from Canada.",
        explanation=[
            GN("쉽게 말하면", "'not only A but also B'는 'A뿐만 아니라 B도'라는 뜻의 [[상관접속사]] 짝이야."),
            GN("짝 맞추기", "A와 B는 문법적으로 [[대등한]] 형태여야 해 — 여기선 'from the US'와 'from Canada'."),
            GN("also 생략", "격식체에선 but 뒤의 [[also]]를 생략하거나 'but ~ as well'로 바꿔 쓰기도 해."),
            GN("도치 주의", "문두에 'Not only'가 오면 뒤가 [[도치]]되지만, 여기선 문중이라 도치는 없어."),
        ],
        example_analysis="'not only from the US but also from Canada' = 미국뿐 아니라 캐나다도, 두 출처를 대등하게 연결.",
        drills=[
            GrammarDrill(kind="객관식", from_passage=True,
                question="지문에서 미국과 캐나다(두 출처)를 대등하게 연결한 상관접속사 짝은?",
                options=["not only ~ but also ~", "either ~ or ~", "neither ~ nor ~"],
                answer="not only ~ but also ~"),
            GrammarDrill(kind="객관식", from_passage=False,
                question="빈칸에 알맞은 것: 'She speaks ____ English but also French.'",
                options=["not only", "not", "only"],
                answer="not only"),
            GrammarDrill(kind="객관식", from_passage=False,
                question="'not only A but also B'와 의미가 가장 가까운 것은?",
                options=["B as well as A", "A instead of B", "A rather than B"],
                answer="B as well as A"),
            GrammarDrill(kind="영작", from_passage=True,
                question="(지문) 1949년에 이르러, 그 연례 세미나는 미국뿐 아니라 캐나다에서 온 형사들에게도 참석되고 있었다.",
                answer="By 1949, the annual seminar was being attended by detectives not only from the US but also from Canada."),
            GrammarDrill(kind="영작", from_passage=False,
                question="그는 영어뿐 아니라 중국어도 말한다.",
                answer="He speaks not only English but also Chinese."),
        ],
    ),
    topic="1945년 미니어처 세미나로 형사들의 관찰력을 훈련하고, 그 성공과 함께 '과학 수사의 어머니'로 남은 Lee의 유산.",
    stance="긍정적",
    stance_reason="세미나의 성공과 사후 유산을 높이 평가하며 그녀의 기여를 긍정적으로 조명한다.",
    structure="시간·순서(나열)",
    structure_reason="1945년 세미나 → 1949년 확산 → 1962년 사망·유산으로 시간순 전개.",
    restatement_chains=[
        RestatementChain(label="관찰력 훈련",
            expressions=["studied the details of the miniature scenes",
                         "learned to notice tiny details",
                         "developing their observation skills"],
            variation="'세부 관찰' → '작은 것 알아채기' → '관찰 기술 개발'로 훈련 내용이 이어진다."),
        RestatementChain(label="성공과 유산",
            expressions=["Lee's training process was successful",
                         "her contributions to forensic science were significant"],
            variation="'훈련의 성공'이 '법의학에 대한 상당한 기여'라는 평가로 확장된다."),
    ],
    flow_blocks=[
        FlowBlock(stage="전개", sentence_range="1~5",
            summary="1945년 [[세미나]]에서 미니어처로 형사들의 관찰력을 훈련해 사건 해결 능력을 키웠다."),
        FlowBlock(stage="성과", sentence_range="6~8",
            summary="훈련은 [[성공]]적이었고 미국·캐나다 형사와 특수 요원·군 관계자까지 참석했다."),
        FlowBlock(stage="결론", sentence_range="9~11",
            summary="1962년 사망 후에도 '[[과학 수사의 어머니]]'라는 칭호로 남은 그녀의 유산."),
    ],
)

i7 = [
    S(r7, 1,
        [("병렬", "held ~ and gave ~ 두 과거동사 병렬"), ("분사구", "using ~ = '~을 사용하여'(수단)")],
        [("week-long", "일주일간의"), ("miniature", "미니어처의, 축소 모형의")],
        [("In 1945, she [[held]] a week-long seminar", "1945년에, 그녀는 일주일간의 세미나를 [[열었다]]"),
         ("and [[gave]] her first lecture", "그리고 그녀의 첫 [[강의를 했다]]"),
         ("using her [[miniature]] crime scenes.", "그녀의 [[미니어처]] 범죄 현장을 사용하여.")],
        [("그녀는 실제 범죄 현장을 세미나에 가져와 강의했다.",
          "'using her miniature crime scenes'는 실제 현장이 아니라 그녀가 만든 미니어처 모형을 사용했다는 뜻이야.")]),
    S(r7, 2,
        [("분사구문", "While reading ~ = 접속사 남긴 분사구문(~하면서)")],
        [("case files", "사건 파일"), ("details", "세부 사항")],
        [("While [[reading]] case files,", "사건 파일을 [[읽으면서]],"),
         ("the detectives [[studied]] the details", "형사들은 세부 사항을 [[연구했다]]"),
         ("of the [[miniature]] scenes.", "[[미니어처]] 현장의.")],
        [("형사들은 파일만 읽고 미니어처는 살펴보지 않았다.",
          "파일을 '읽으면서(while reading)' 동시에 미니어처 현장의 세부까지 연구했다는 뜻 — 미니어처를 무시한 게 아니야.")]),
    S(r7, 3,
        [("부정사 목적", "in order to determine = '판단하기 위해'"), ("if 명사절", "determine if ~ = '~인지 아닌지 판단'")],
        [("clues", "단서"), ("determine", "판단하다, 알아내다"), ("violent crime", "폭력 범죄")],
        [("They looked for [[clues]]", "그들은 [[단서]]를 찾았다"),
         ("in order to [[determine]]", "[[판단하기]] 위해"),
         ("if the scene in the [[miniature]]", "[[미니어처]] 속 현장이"),
         ("resulted from an [[accident]] or a violent crime.", "[[사고]]로 인한 것인지 폭력 범죄로 인한 것인지.")],
        [("여기서 They는 미니어처 속 범죄자들을 가리킨다.",
          "They는 앞 문장의 the detectives(형사들)를 가리켜 — 단서를 찾는 주체는 형사들이야. (지칭)"),
         ("형사들은 모든 현장을 폭력 범죄로 미리 단정했다.",
          "'determine if ~ an accident or a violent crime'은 사고인지 폭력 범죄인지 '판단'한다는 뜻 — 미리 정한 게 아니야.")]),
    S(r7, 4,
        [("병렬 부정사", "learned to notice ~ and to observe ~ 병렬"), ("전치사+분사", "without destroying = '훼손하지 않고'")],
        [("notice", "알아차리다"), ("evidence", "증거")],
        [("The detectives [[learned]] to notice tiny details", "형사들은 작은 세부 사항을 알아차리는 법을 [[배웠다]]"),
         ("and to [[observe]] a scene", "그리고 현장을 [[관찰하는]] 법도"),
         ("without [[destroying]] any evidence.", "어떤 증거도 [[훼손하지]] 않고.")],
        [("형사들은 증거를 없애 가며 현장을 관찰하는 법을 배웠다.",
          "'without destroying any evidence'는 증거를 훼손하지 '않고' 관찰한다는 뜻 — 없애는 게 아니라 보존하는 거야.")]),
    S(r7, 5,
        [("동명사 수단", "By developing ~ = '~을 개발함으로써'"), ("be able to", "were able to = '~할 수 있었다'")],
        [("observation", "관찰"), ("solve", "해결하다")],
        [("By [[developing]] their observation skills,", "그들의 관찰 기술을 [[개발함]]으로써,"),
         ("they were able to [[improve]] their ability", "그들은 능력을 [[향상시킬]] 수 있었다"),
         ("to [[solve]] crime cases.", "범죄 사건을 [[해결하는]].")],
        [("관찰력은 늘었지만 사건 해결 능력은 나아지지 않았다.",
          "'were able to improve their ability to solve crime cases'는 사건 해결 능력이 실제로 향상됐다는 뜻이야.")]),
    S(r7, 6,
        [("2형식", "training process was successful — 주어+be+보어")],
        [("training process", "훈련 과정"), ("successful", "성공적인")],
        [("Lee's [[training process]]", "Lee의 [[훈련 과정]]은"),
         ("was [[successful]].", "[[성공적이었다]].")],
        [("이 문장은 그녀의 훈련 방식이 실패했음을 요약한다.",
          "'was successful'은 성공적이었다는 뜻으로, 앞의 훈련 성과를 긍정적으로 결론짓는 문장이야.")]),
    S(r7, 7,
        [("상관접속사 not only A but also B", "'A뿐 아니라 B도' — from the US와 from Canada를 대등 연결"),
         ("과거진행 수동태", "was being attended = '참석되고 있었다'")],
        [("annual", "연례의, 매년의"), ("attend", "참석하다")],
        [("By 1949, the [[annual]] seminar", "1949년에 이르러, [[연례]] 세미나는"),
         ("was being [[attended]] by detectives", "형사들에게 [[참석되고]] 있었다"),
         ("not only from the [[US]]", "[[미국]]에서뿐 아니라"),
         ("but also from [[Canada]].", "[[캐나다]]에서 온 형사들에게도.")],
        [("1949년에는 미국 형사들만 세미나에 참석했다.",
          "'not only from the US but also from Canada'는 미국뿐 아니라 캐나다 형사들도 참석했다는 뜻이야.")]),
    S(r7, 8,
        [("복수 주어 병렬", "Special agents and military staff — 두 주어 병렬"), ("also", "'또한' 추가 참석자")],
        [("special agents", "특수 요원"), ("military staff", "군 관계자")],
        [("Special agents and [[military]] staff", "특수 요원과 [[군]] 관계자들도"),
         ("also [[attended]] the seminar.", "세미나에 또한 [[참석했다]].")],
        [("특수 요원과 군 관계자는 세미나에 참석하지 않았다.",
          "'also attended the seminar'는 그들'도' 세미나에 참석했다는 뜻으로, 참석 범위가 더 넓어졌음을 보여줘.")]),
    S(r7, 9,
        [("전치사 after", "after a career of ~ = '~의 경력 후에'"), ("more than", "'~이 넘는'(초과)")],
        [("career", "경력"), ("more than", "~이 넘는")],
        [("Lee [[died]] in 1962,", "Lee는 1962년에 [[사망했다]],"),
         ("after a [[career]]", "[[경력]] 후에"),
         ("of more than [[thirty years]].", "[[30년]]이 넘는.")],
        [("Lee는 경력을 시작한 지 얼마 되지 않아 사망했다.",
          "'after a career of more than thirty years'는 30년이 넘는 경력을 쌓은 뒤에 사망했다는 뜻이야.")]),
    S(r7, 10,
        [("양보 접속사 Although", "'비록 ~이지만'"), ("과거완료", "had struggled — 진입 이전의 앞선 시점")],
        [("struggle", "고군분투하다"), ("contributions", "기여"), ("significant", "상당한, 중요한")],
        [("Although she had [[struggled]]", "비록 그녀가 [[고군분투했지만]]"),
         ("to enter the [[field]],", "그 [[분야]]에 들어가기 위해,"),
         ("her [[contributions]] to forensic science", "법의학에 대한 그녀의 [[기여]]는"),
         ("were [[significant]].", "[[상당했다]].")],
        [("그녀는 별 어려움 없이 법의학 분야에 들어갔다.",
          "'Although she had struggled to enter the field'는 그 분야에 들어가려고 고군분투했다는 뜻 — 쉽게 진입한 게 아니야.")]),
    S(r7, 11,
        [("It is no wonder that", "'~은 당연하다'(놀랄 일이 아니다)"), ("수동태", "was called = '~라고 불렸다'")],
        [("no wonder", "당연하다, 놀랄 일이 아니다"), ("forensic science", "법의학, 과학 수사")],
        [("It is no [[wonder]] that", "~라는 것은 [[당연하다]]"),
         ("she was [[called]]", "그녀가 [[불린]] 것은"),
         ("the “[[mother of forensic science]].”", "‘[[과학 수사의 어머니]]’라고.")],
        [("'It is no wonder'는 그녀가 그 칭호를 받은 것이 뜻밖이라는 반어적 표현이다.",
          "'no wonder'는 '당연하다·놀랄 일이 아니다'라는 뜻으로 반어가 아니야 — 큰 기여를 했으니 그 칭호가 당연하다는 함축이야. (함축)"),
         ("'mother of forensic science'는 그녀의 실제 가족 관계를 가리킨다.",
          "이 칭호는 그녀가 법의학 분야에 남긴 업적·유산을 기리는 별칭이야 — 실제 혈연을 뜻하지 않아.")]),
]

P7 = build("Lee ⑦ 성공과 유산", "7 · 세미나의 성공과 유산", r7, ov7, i7)

PARTS = [P7]
