# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad/batches/공통영어2_능률_민병천_2과")
from _helpers import *

r5 = [
    "She thought laws had to be changed so that medical examiners had independent power.",
    "Public support was needed to change laws, so she used the World's Fair held from 1939 to 1940 to educate the public about the modern medical examiner system.",
    "She also visited the governor with the chairman of the Department of Legal Medicine at Harvard.",
    "They talked about the importance of legal medicine.",
    "Thanks to Lee's efforts, the Legal Medicine department at Harvard began to train future medical examiners in 1940.",
]

ov5 = Overview(
    theme_ko="법 개정을 향한 대중 교육과 하버드 법의학과의 출범",
    key_grammar=KeyGrammar(
        point="so that ~ (목적: …하도록)",
        source_sentence="She thought laws had to be changed so that medical examiners had independent power.",
        explanation=[
            GN("쉽게 말하면", "'so that + 주어 + 동사'는 '~하도록/~하기 위해'라는 [[목적]]을 나타내는 부사절이야."),
            GN("주의", "'so that'(목적)과 'so ~ that'(너무 …해서 ~하다, [[정도·결과]])은 형태가 비슷하지만 뜻이 달라."),
            GN("신호", "so that 뒤에는 흔히 could·would·can 같은 [[조동사]]가 와서 '할 수 있도록'의 뜻을 더해."),
            GN("복원", "here: laws had to be changed so that examiners [[had]] independent power = 조사관이 독립 권한을 갖도록 법을 바꿔야 했다."),
        ],
        example="so that medical examiners had independent power",
        example_analysis="주절(laws had to be changed) 뒤의 'so that ~'는 법 개정의 '목적'을 밝히는 부사절.",
        drills=[
            GrammarDrill(kind="객관식", from_passage=True,
                question="지문 'so that medical examiners had independent power'에서 'so that'의 역할은?",
                options=["목적을 나타내는 부사절 (…하도록)", "이유를 나타내는 부사절 (…때문에)", "정도·결과를 나타내는 so ~ that"],
                answer="목적을 나타내는 부사절 (…하도록)"),
            GrammarDrill(kind="객관식", from_passage=False,
                question="밑줄 친 부분이 '목적(~하도록)'의 so that로 쓰인 것은?",
                options=["She spoke slowly so that everyone could understand.", "It was raining, so we stayed at home.", "He is so tall that he can touch the ceiling."],
                answer="She spoke slowly so that everyone could understand."),
            GrammarDrill(kind="객관식", from_passage=False,
                question="빈칸에 알맞은 것은? 'Laws had to be changed ____ examiners had independent power.'(조사관이 독립 권한을 갖도록)",
                options=["so that", "because", "although"],
                answer="so that"),
            GrammarDrill(kind="영작", from_passage=True,
                question="(지문) 그녀는 의료 조사관이 독립적인 권한을 갖도록 법이 바뀌어야 한다고 생각했다.",
                answer="She thought laws had to be changed so that medical examiners had independent power."),
            GrammarDrill(kind="영작", from_passage=False,
                question="그는 시험에 합격할 수 있도록 열심히 공부했다.",
                answer="He studied hard so that he could pass the exam."),
        ],
    ),
    topic="법 개정을 위해 대중을 교육하고, 하버드에 법의학 교육 과정을 세운 Lee의 제도 개혁 노력.",
    stance="긍정적",
    stance_reason="Lee의 노력이 법 제도와 하버드 학과 출범으로 이어졌다고 공로를 인정하며 조명한다.",
    structure="시간·순서(나열)",
    structure_reason="법 개정 필요성 인식 → 박람회 대중 교육 → 주지사·학과장 면담 → 1940년 하버드 학과 출범의 시간 순.",
    restatement_chains=[
        RestatementChain(label="법 개정을 위한 대중 교육",
            expressions=["Public support was needed to change laws", "to educate the public about the modern medical examiner system"],
            variation="'법을 바꾸려면 대중 지지 필요' → '박람회로 대중을 교육'으로 목적이 구체화."),
        RestatementChain(label="하버드 법의학의 제도화",
            expressions=["the importance of legal medicine", "the Legal Medicine department at Harvard began to train future medical examiners"],
            variation="'법의학의 중요성'을 알리는 데서 → 실제 '조사관 양성 학과 출범'으로 결실."),
    ],
    flow_blocks=[
        FlowBlock(stage="전개", sentence_range="1~2",
            summary="조사관이 독립 권한을 갖도록 법을 바꿔야 했고, 이를 위해 [[대중]]의 지지가 필요해 박람회로 대중을 교육했다."),
        FlowBlock(stage="전개", sentence_range="3~4",
            summary="하버드 법의학과 [[학과장]]과 함께 주지사를 찾아가 법의학의 중요성을 논의했다."),
        FlowBlock(stage="결론", sentence_range="5",
            summary="Lee의 노력 덕분에 [[1940]]년 하버드 법의학과가 미래 조사관 양성을 시작했다."),
    ],
)

i5 = [
    S(r5, 1,
        [("so that ~ (목적)", "'so that + 주어 + 동사'는 '~하도록'이라는 목적을 나타냄"),
         ("had to be p.p.", "'have to' + 수동태 — '~되어야만 했다'")],
        [("law", "법"), ("medical examiner", "검시관·의료 조사관"), ("independent", "독립적인")],
        [("She [[thought]]", "그녀는 [[생각했다]]"),
         ("laws had to be [[changed]]", "법이 [[바뀌어야]] 한다고"),
         ("so that medical examiners had [[independent]] power.", "그래서 의료 조사관이 [[독립적인]] 권한을 갖도록.")],
        [("(함축) 'so that ~ had independent power'는 조사관의 권한을 없애자는 뜻이다.",
          "함축은 반대야 — 조사관이 '독립적인 권한을 갖도록(목적)' 법을 바꿔야 한다는 것으로, 권한을 강화하려는 의도다."),
         ("법이 이미 바뀌어서 조사관이 권한을 얻었다는 문장이다.",
          "실제로는 'had to be changed(바뀌어야만 했다)'로, 아직 바뀌지 않은 '앞으로 개정해야 할 필요'를 말한다.")]),
    S(r5, 2,
        [("so (그래서)", "결과·귀결을 잇는 등위접속사 'so'"),
         ("과거분사 후치수식", "held from 1939 to 1940 이 the World's Fair 를 뒤에서 꾸밈")],
        [("public support", "대중의 지지"), ("World's Fair", "세계 박람회"), ("educate", "교육하다"), ("system", "제도")],
        [("Public [[support]] was needed", "대중의 [[지지]]가 필요했다"),
         ("to change [[laws]],", "[[법]]을 바꾸려면,"),
         ("so she [[used]] the World's Fair", "그래서 그녀는 세계 박람회를 [[이용했다]]"),
         ("[[held]] from 1939 to 1940", "1939년부터 1940년까지 [[열린]]"),
         ("to educate the [[public]]", "[[대중]]을 교육하기 위해"),
         ("about the modern medical examiner [[system]].", "현대의 의료 조사관 [[제도]]에 대해.")],
        [("그녀는 자신의 미니어처를 팔려고 세계 박람회를 이용했다.",
          "목적이 달라 — 법 개정에 필요한 대중의 지지를 얻으려고 '현대 의료 조사관 제도를 대중에게 알리려(교육)' 박람회를 이용했다."),
         ("세계 박람회는 법이 바뀐 뒤 이를 축하하려고 열렸다.",
          "인과가 반대야 — 법을 바꾸려면 대중 지지가 '먼저' 필요했고, 그 지지를 얻기 위한 교육 수단으로 박람회를 썼다.")]),
    S(r5, 3,
        [("also (또한)", "앞선 대중 교육에 더해 추가 행동을 나열"),
         ("with + 명사구", "동행자를 나타내는 전치사구 (학과장과 함께)")],
        [("governor", "주지사"), ("chairman", "학과장·의장"), ("Department of Legal Medicine", "법의학과")],
        [("She also [[visited]] the governor", "그녀는 또한 주지사를 [[방문했다]]"),
         ("with the [[chairman]]", "[[학과장]]과 함께"),
         ("of the Department of [[Legal Medicine]] at Harvard.", "하버드 [[법의학]]과의.")],
        [("그녀는 하버드 총장을 설득하러 혼자 찾아갔다.",
          "대상·동행이 달라 — 그녀는 하버드 법의학과 '학과장과 함께' '주지사(governor)'를 방문했다."),
         ("'She'는 하버드 법의학과 학과장을 가리킨다.",
          "지칭이 틀렸어 — 'She'는 이 전기의 주인공 Lee이고, 학과장(the chairman)은 그녀가 동행한 별개의 인물이다.")]),
    S(r5, 4,
        [("They (지시대명사)", "앞 문장의 두 인물(Lee와 학과장)을 되받는 주어")],
        [("importance", "중요성"), ("legal medicine", "법의학")],
        [("They [[talked]]", "그들은 [[이야기를 나눴다]]"),
         ("about the [[importance]] of legal medicine.", "법의학의 [[중요성]]에 대해.")],
        [("(지칭) 'They'는 박람회를 찾은 일반 대중과 기자들을 가리킨다.",
          "지칭이 틀렸어 — 'They'는 앞 문장에서 함께 주지사를 찾아간 'Lee와 학과장(the chairman)' 두 사람을 가리킨다."),
         ("그들은 법의학이 불필요하다고 주지사를 설득했다.",
          "내용이 반대야 — 그들은 법의학의 '중요성(importance)'을, 즉 왜 필요한지를 이야기했다.")]),
    S(r5, 5,
        [("Thanks to ~ (덕분에)", "긍정적 원인을 밝히는 전치사구"),
         ("begin to + 동사원형", "'~하기 시작하다'")],
        [("efforts", "노력"), ("train", "훈련하다·양성하다"), ("future medical examiners", "미래의 의료 조사관")],
        [("Thanks to Lee's [[efforts]],", "Lee의 [[노력]] 덕분에,"),
         ("the Legal Medicine [[department]] at Harvard", "하버드의 [[법의학과]]는"),
         ("began to [[train]] future medical examiners", "미래의 의료 조사관을 [[양성하기]] 시작했다"),
         ("in 1940.", "1940년에.")],
        [("(함축) 하버드가 스스로 판단해 학과를 열었을 뿐 Lee와는 무관하다.",
          "함축이 반대야 — 'Thanks to Lee's efforts(Lee의 노력 덕분에)'가 명시되어, 학과 출범이 그녀의 노력이 낳은 결실임을 강조한다."),
         ("하버드 법의학과는 이미 오래전부터 조사관을 양성해 왔다.",
          "시점이 틀렸어 — 이 문장은 '1940년에' 비로소 미래 조사관 '양성을 시작했다(began to train)'고 말한다.")]),
]

P5 = build("Lee ⑤ 제도 개혁", "5 · 법 개정·대중 교육·학과 출범", r5, ov5, i5)

PARTS = [P5]
