# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad/batches/공통영어2_능률_민병천_2과")
from _helpers import *

r6 = [
 "However, detectives were not careful with potential evidence.",
 "By touching and stepping on things, they often destroyed clues without realizing it.",
 "Due to this fact, analyzing the clues later was impossible.",
 "Lee thought detectives also had to learn how to observe crime scenes from a medical point of view.",
 "In order to educate detectives effectively, Lee came up with a creative tool.",
 "Her idea came from her hobby: creating miniatures.",
 "She started creating miniatures of crime scenes that were highly detailed and accurate.",
 "Based on real criminal cases, they included details like blood stains.",
 "Lee did not miss even the smallest detail, such as a small lamp or a label on a jar.",
 "She wanted to train detectives to notice tiny clues.",
 "She created around twenty miniature scenes during the 1940s and 1950s.",
]

ov6 = Overview(
 theme_ko="미니어처라는 창의적 도구 — 정밀한 범죄현장 재현",
 key_grammar=KeyGrammar(
  point="분사구문 Based on ~ (…에 기반하여)",
  source_sentence="Based on real criminal cases, they included details like blood stains.",
  explanation=[
   GN("쉽게 말하면","콤마로 붙은 'Based on ~'은 'Being based on'에서 Being이 [[생략]]된 [[분사구문]]으로 '~에 기반하여'라는 뜻."),
   GN("복원","Based on real cases ~ = [[As they were based on]] real cases ~."),
   GN("의미상 주어","분사의 주인은 주절 주어 [[they]](미니어처들)와 같아 — 사건에 '기반한' 것은 미니어처야."),
   GN("해석","'~에 [[기반하여]]/근거하여'로 옮긴다 — 수동(과거분사) 의미가 핵심."),
  ],
  example_analysis="Based on real criminal cases = Being이 생략된 수동 분사구문, 주절 주어 they를 수식.",
  drills=[
   GrammarDrill(kind="객관식",from_passage=True,
    question="지문 'Based on real criminal cases,'의 문법 기능은?",
    options=["과거분사로 시작하는 분사구문(Being 생략)","목적을 나타내는 부정사구","시간의 관계부사절"],
    answer="과거분사로 시작하는 분사구문(Being 생략)"),
   GrammarDrill(kind="객관식",from_passage=False,
    question="밑줄 친 부분이 '분사구문'으로 쓰인 것은?",
    options=["Based on the data, we changed the plan.","The plan based on the data was wrong.","We based the plan on the data."],
    answer="Based on the data, we changed the plan."),
   GrammarDrill(kind="객관식",from_passage=False,
    question="'____ on true events, the film moved us.'(실화에 기반하여)에 알맞은 것은?",
    options=["Based","Basing","To base"],
    answer="Based"),
   GrammarDrill(kind="영작",from_passage=False,
    question="실제 사례에 기반하여, 그들은 보고서를 작성했다.",
    answer="Based on real cases, they wrote the report."),
   GrammarDrill(kind="영작",from_passage=True,
    question="(지문) 실제 범죄 사건에 기반하여, 그것들은 핏자국 같은 세부를 담았다.",
    answer="Based on real criminal cases, they included details like blood stains."),
  ]),
 topic="형사들의 단서 훼손 문제를 풀기 위해 Lee가 정밀한 범죄현장 미니어처를 고안·제작함.",
 stance="긍정적",
 stance_reason="증거 훼손 문제를 창의적 도구로 해결한 Lee의 착상과 정밀함을 조명한다.",
 structure="문제→해결(방안)",
 structure_reason="형사들의 단서 훼손·분석 불가라는 문제 → 미니어처라는 해결책 제시로 이어진다.",
 restatement_chains=[
  RestatementChain(label="단서: 훼손에서 포착으로",
   expressions=["destroyed clues","notice tiny clues"],
   variation="형사가 단서를 훼손하던 문제 → 미니어처로 작은 단서를 알아채도록 훈련."),
  RestatementChain(label="창의적 도구의 정체",
   expressions=["creative tool","creating miniatures"],
   variation="'창의적 도구'가 무엇인지 → 취미인 '미니어처 제작'으로 구체화."),
 ],
 flow_blocks=[
  FlowBlock(stage="문제",sentence_range="1~3",
   summary="형사들이 단서를 [[훼손]]해 나중의 분석이 [[불가능]]해졌다."),
  FlowBlock(stage="착안",sentence_range="4~6",
   summary="Lee가 [[의학적 관점]]의 관찰 훈련을 위해 취미인 [[미니어처]]에서 도구를 착안했다."),
  FlowBlock(stage="제작",sentence_range="7~9",
   summary="실제 사건에 기반한 [[정밀]]한 범죄현장 미니어처를 만들며 [[사소한]] 세부도 놓치지 않았다."),
  FlowBlock(stage="목적·규모",sentence_range="10~11",
   summary="형사가 [[작은 단서]]를 알아채도록 훈련하려 1940~50년대에 약 [[스무]] 점을 제작했다."),
 ],
)

i6 = [
 S(r6,1,
  [("부정 not","'~하지 않았다' 부주의를 지적"),("with (대상)","'~에 대해' 다룬 대상")],
  [("careful","조심하는"),("potential","잠재적인"),("evidence","증거")],
  [("However, detectives were not [[careful]]","하지만, 형사들은 [[조심하지]] 않았다"),
   ("with [[potential evidence]].","[[잠재적 증거]]를.")],
  [("형사들이 증거를 신중하게 잘 다뤘다는 뜻이다.","'were not careful(조심하지 않았다)'이므로 정반대 — 형사들이 잠재적 증거에 부주의했다는 문제 제기야.")]),
 S(r6,2,
  [("By -ing","'~함으로써' 수단"),("without -ing","'~하지 않은 채' 부대상황")],
  [("step on","~을 밟다"),("destroy","파괴하다"),("clue","단서")],
  [("By [[touching and stepping]] on things,","물건을 [[만지고 밟음]]으로써,"),
   ("they often destroyed [[clues]]","그들은 종종 [[단서]]를 파괴했다"),
   ("without [[realizing]] it.","그것을 [[깨닫지]] 못한 채.")],
  [("문장 끝의 'it'은 형사들이 만진 '물건'을 가리킨다.","여기 'it'은 자신들이 단서를 훼손했다는 '사실'을 가리켜 — 훼손하고도 그걸 알아채지 못했다는 뜻이야."),
   ("형사들이 일부러 단서를 없앴다는 뜻이다.","'without realizing it(깨닫지 못한 채)'이므로 고의가 아니라 무심코 훼손했다는 의미야.")]),
 S(r6,3,
  [("Due to","'~ 때문에' 원인"),("동명사 주어","'analyzing ~'이 단수 주어")],
  [("analyze","분석하다"),("impossible","불가능한")],
  [("Due to this [[fact]],","이 [[사실]] 때문에,"),
   ("[[analyzing the clues]] later","나중에 [[단서를 분석하는]] 것은"),
   ("was [[impossible]].","[[불가능했다]].")],
  [("'this fact'는 형사들이 유능하다는 사실을 가리킨다.","'this fact'는 앞 문장의 '형사들이 무심코 단서를 훼손했다'는 사실을 가리켜 — 그래서 나중 분석이 불가능해진 인과야.")]),
 S(r6,4,
  [("의문사+to부정사","'어떻게 관찰할지 = 관찰하는 법'"),("also had to","'~도 해야 했다' 당위")],
  [("observe","관찰하다"),("crime scene","범죄 현장"),("medical","의학의")],
  [("Lee thought detectives also had to [[learn]]","Lee는 형사들도 [[배워야]] 한다고 생각했다"),
   ("how to [[observe crime scenes]]","[[범죄 현장을 관찰하는]] 법을"),
   ("from a [[medical point of view]].","[[의학적 관점]]에서.")],
  [("Lee는 형사들이 의학은 배울 필요가 없다고 보았다.","정반대야 — 형사도 '의학적 관점(medical point of view)'에서 현장을 관찰하는 법을 배워야 한다고 생각했어.")]),
 S(r6,5,
  [("In order to","'~하기 위해' 목적"),("come up with","'~을 생각해내다'")],
  [("educate","교육하다"),("effectively","효과적으로"),("creative","창의적인")],
  [("In order to [[educate detectives effectively]],","[[형사들을 효과적으로 교육하기]] 위해,"),
   ("Lee came up with a [[creative tool]].","Lee는 [[창의적인 도구]]를 생각해냈다.")],
  [("이 도구는 일반 대중을 교육하려고 만든 것이다.","'educate detectives(형사들을 교육)'라고 했어 — 교육 대상은 대중이 아니라 형사야.")]),
 S(r6,6,
  [("콜론(동격)","'취미' = '미니어처 만들기' 설명"),("from (출처)","'~에서 나오다' 기원")],
  [("hobby","취미"),("miniature","미니어처, 소형 모형")],
  [("Her idea came from her [[hobby]]:","그녀의 아이디어는 [[취미]]에서 나왔다:"),
   ("[[creating miniatures]].","[[미니어처를 만드는]] 것.")],
  [("'Her idea'는 형사를 처벌하려는 계획을 가리킨다.","'Her idea'는 앞의 '창의적 도구(creative tool)'를 가리켜 — 그 착상이 취미인 미니어처 제작에서 왔다는 뜻이야.")]),
 S(r6,7,
  [("관계대명사 that","'~한 (현장)' 앞의 crime scenes 수식"),("start -ing","'~하기 시작하다'")],
  [("detailed","정밀한, 세밀한"),("accurate","정확한")],
  [("She started [[creating miniatures]]","그녀는 [[미니어처를 만들기]] 시작했다"),
   ("of [[crime scenes]]","[[범죄 현장]]의"),
   ("that were highly [[detailed and accurate]].","매우 [[정밀하고 정확한]].")],
  [("Lee가 만든 모형은 대충 만든 조잡한 것이었다.","'highly detailed and accurate(매우 정밀하고 정확한)'라고 했어 — 대충이 아니라 극도로 세밀하게 재현했다는 뜻이야.")]),
 S(r6,8,
  [("분사구문 Based on","'~에 기반하여' = Being based on 축약"),("like (예시)","'~같은' 예시 제시")],
  [("criminal case","범죄 사건"),("include","포함하다"),("blood stain","핏자국")],
  [("Based on [[real criminal cases]],","[[실제 범죄 사건]]에 기반하여,"),
   ("they included [[details]]","그것들은 [[세부]]를 담았다"),
   ("like [[blood stains]].","[[핏자국]] 같은.")],
  [("문장 앞의 'they'는 형사들을 가리킨다.","'they'는 앞 문장의 미니어처들(miniatures of crime scenes)을 가리켜 — 그 모형들이 실제 사건에 기반해 핏자국까지 담았다는 뜻이야."),
   ("미니어처는 상상으로 지어낸 장면을 담았다.","'Based on real criminal cases(실제 범죄 사건에 기반하여)'라고 했어 — 지어낸 게 아니라 실제 사건을 재현한 거야.")]),
 S(r6,9,
  [("최상급","'가장 작은' the smallest"),("such as","'~같은' 구체적 예시")],
  [("miss","놓치다"),("label","라벨, 표"),("jar","병, 단지")],
  [("Lee did not miss even [[the smallest detail]],","Lee는 [[가장 작은 세부]]조차 놓치지 않았다,"),
   ("such as a [[small lamp]]","[[작은 램프]] 같은"),
   ("or a [[label on a jar]].","병에 붙은 [[라벨]].")],
  [("Lee는 큰 물건만 신경 쓰고 사소한 것은 무시했다.","정반대의 속뜻이야 — '작은 램프나 병 라벨(smallest detail)'까지 놓치지 않았다는, 극도의 세밀함을 강조하는 표현이야.")]),
 S(r6,10,
  [("to부정사(목적)","'~하도록/~하기 위해' 훈련 목적"),("train A to V","'A가 ~하도록 훈련하다'")],
  [("train","훈련시키다"),("notice","알아채다"),("tiny","아주 작은")],
  [("She wanted to [[train detectives]]","그녀는 [[형사들을 훈련]]시키고 싶었다"),
   ("to [[notice tiny clues]].","[[작은 단서를 알아채]]도록.")],
  [("미니어처는 예술 작품으로 전시하려고 만든 것이다.","목적은 전시가 아니라 형사 훈련 — 'train detectives to notice tiny clues(작은 단서를 알아채도록 형사 훈련)'가 진짜 의도야.")]),
 S(r6,11,
  [("during","'~ 동안/에 걸쳐' 기간"),("around (수)","'약 ~' 대략의 수")],
  [("create","만들다"),("scene","장면, 현장")],
  [("She created around [[twenty miniature scenes]]","그녀는 약 [[스무 개의 미니어처 장면]]을 만들었다"),
   ("[[during]] the 1940s and 1950s.","1940년대와 1950년대 [[동안]].")],
  [("Lee는 단 몇 개의 미니어처만 만들었다.","'around twenty(약 스무 개)'를 1940~50년대에 걸쳐 제작했어 — 몇 개가 아니라 약 20점의 상당한 규모야.")]),
]

P6 = build("Lee ⑥ 미니어처","6 · 미니어처라는 창의적 도구",r6,ov6,i6)
PARTS = [P6]
