# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad")
from _helpers_oladd import *

# =====================================================================
# P1 — Unit10-2
# =====================================================================
r1 = [
 "Although the wish to be alone is often strong, its intensity varies from person to person.",
 "An equally impelling impulse, though, is to seek the company of others and to spend extended periods of time sharing activities.",
 "In these periods we exchange information and feelings in both conversational and non-verbal forms (facial expressions, eye contact, gestures, touching, and so on).",
 "We need other people to provide us with love, support, approval, bodily contact, reassurance, physical help and a myriad of other practical, physical and emotional needs.",
 "In a very basic sense we need others to confirm that we are there, that we exist and that we have an identity that is unique and separate from anyone else.",
 "Thus, we generally cannot exist for too long without seeking companionship.",
]

ov1 = Overview(
 theme_ko="자신의 존재·정체성 확인을 위해 타인과의 교제·유대를 갈망하는 인간의 본성",
 key_grammar=KeyGrammar(
  point="need + 목적어 + to부정사 (5형식: …가 ~하도록 필요로 하다)",
  source_sentence="We need other people to provide us with love, support, approval, bodily contact, reassurance, physical help and a myriad of other practical, physical and emotional needs.",
  explanation=[
   GN("쉽게 말하면","'need+목적어+to-V'는 '(목적어)가 ~하도록 [[필요로]] 한다'는 5형식 구조."),
   GN("구조","We need other people [[to provide]] ~ = 사람들이 제공해 주도록 필요로 한다."),
   GN("주의","to부정사의 의미상 주어는 [[목적어]](other people)이고, 제공하는 주체는 '다른 사람들'."),
   GN("확장","같은 틀: we need others [[to confirm]] that ~ (남들이 확인해 주도록 필요로 한다)."),
  ],
  example_analysis="need other people to provide = need+O(목적어)+to부정사(5형식) — people이 provide의 의미상 주어.",
  drills=[
   GrammarDrill(kind="객관식",from_passage=True,
    question="지문 'We need other people to provide us ~'에서 to provide의 의미상 주어는?",
    options=["other people","we","love and support"],answer="other people"),
   GrammarDrill(kind="객관식",from_passage=False,
    question="빈칸: I need you ____ me the truth. (네가 진실을 말해 주기를 필요로 한다)",
    options=["to tell","tell","telling","told"],answer="to tell"),
   GrammarDrill(kind="객관식",from_passage=False,
    question="다음 중 'need+목적어+to부정사' 구조로 어법이 옳은 것은?",
    options=["We need others to confirm our identity.","We need confirm our identity.","We need others confirming our identity."],
    answer="We need others to confirm our identity."),
   GrammarDrill(kind="영작",from_passage=True,
    question="(지문) 우리는 우리에게 사랑과 지지를 제공해 줄 다른 사람들을 필요로 한다.",
    answer="We need other people to provide us with love and support."),
   GrammarDrill(kind="영작",from_passage=False,
    question="나는 그가 나를 도와주도록 필요로 한다.",
    answer="I need him to help me."),
  ]),
 topic="인간이 혼자 있고 싶어 하면서도 존재·정체성 확인을 위해 타인과의 교제를 필요로 한다는 본성.",
 stance="중립적",
 stance_reason="타인을 필요로 하는 인간의 본성을 객관적으로 설명·주장하는 논설.",
 structure="주장→근거·예시",
 structure_reason="교제 충동을 제시하고(1~3) 그 필요의 근거(4~5)를 든 뒤 결론(6)으로 마무리.",
 restatement_chains=[RestatementChain(
   label="타인과의 교제 갈망",
   expressions=["seek the company of others","seeking companionship"],
   variation="'남과 함께하려는 충동'이 마지막에 '교제 추구'로 다시 진술됨.")],
 flow_blocks=[
  FlowBlock(stage="도입",sentence_range="1~2",summary="혼자 있고 싶은 소망과 [[대등한]] 교제 충동이 공존한다."),
  FlowBlock(stage="전개",sentence_range="3",summary="교제하는 시간에 언어·비언어로 정보와 [[감정]]을 교환한다."),
  FlowBlock(stage="근거",sentence_range="4~5",summary="타인은 실질적 [[필요]]와 존재·정체성 확인을 제공한다."),
  FlowBlock(stage="결론",sentence_range="6",summary="교제를 추구하지 않고는 오래 [[살아갈]] 수 없다."),
 ])

i1 = [
 S(r1,1,
  [("양보 although","'~이지만'으로 대조 도입"),("its 지칭","its = the wish의")],
  [("intensity","강도"),("vary","다르다")],
  [("Although the [[wish]] to be alone","혼자 있고 싶은 [[소망]]은"),
   ("is often [[strong]],","종종 [[강하지만]],"),
   ("its [[intensity]] varies","그 [[강도]]는 다르다"),
   ("from [[person]] to person.","[[사람]]마다.")],
  [("its intensity는 외로움 자체의 강도를 뜻한다.","여기서 its가 가리키는 것은 the wish to be alone(혼자 있고 싶은 소망)이며, 외로움이 아니라 그 소망의 강도가 사람마다 다르다는 뜻이야.")]),
 S(r1,2,
  [("병렬 to부정사","to seek ~ and to spend ~ 대등 연결"),("though 삽입","'하지만'의 역접 부사")],
  [("impelling","뿌리칠 수 없는"),("impulse","충동")],
  [("An equally impelling [[impulse]], though,","하지만 똑같이 뿌리칠 수 없는 [[충동]]은"),
   ("is to [[seek]] the company of others","다른 사람과 함께 있는 것을 [[추구하고]]"),
   ("and to spend [[extended]] periods of time","[[긴]] 시간을 보내는 것이다"),
   ("[[sharing]] activities.","활동을 [[공유하면서]].")],
  [("혼자 있으려는 욕구가 어울리려는 욕구보다 훨씬 강하다는 뜻이다.","equally impelling(똑같이 강한)이라 했으므로 두 충동의 세기가 대등하다는 뜻이지, 고독 욕구가 더 세다는 게 아니야.")]),
 S(r1,3,
  [("these 지칭","these periods = 교제하는 시간"),("both A and B","대화·비언어 두 형태 모두")],
  [("exchange","교환하다"),("non-verbal","비언어적인")],
  [("In these [[periods]]","이 [[시간]] 동안"),
   ("we [[exchange]] information and feelings","우리는 정보와 감정을 [[교환한다]]"),
   ("in both [[conversational]] and non-verbal forms","[[대화]]의 형태와 비언어적 형태 둘 다로"),
   ("(facial expressions, eye contact, gestures, [[touching]], and so on).","(표정, 눈 맞춤, 몸짓, [[접촉]] 등).")],
  [("these periods는 혼자 잠자거나 쉬는 시간을 가리킨다.","these periods는 앞 문장의 '남과 함께 활동을 공유하며 보내는 긴 시간'을 가리키며, 그 교제 시간에 정보·감정을 나눈다는 뜻이야.")]),
 S(r1,4,
  [("need+O+to부정사","사람들이 제공해 주도록 필요로 함(5형식)"),("myriad of","무수히 많은")],
  [("approval","인정"),("reassurance","안심"),("myriad","무수히 많음")],
  [("We [[need]] other people","우리는 다른 사람들을 [[필요로 한다]]"),
   ("to [[provide]] us with love, support, approval,","우리에게 사랑, 지지, 인정을 [[제공해 줄]]"),
   ("bodily contact, [[reassurance]], physical help","신체적 접촉, [[안심]], 신체적 도움"),
   ("and a myriad of other practical, physical and emotional [[needs]].","그리고 무수히 많은 다른 실질적, 신체적, 정서적 [[필요사항]]들을.")],
  [("다른 사람들이 우리에게 필요한 것들을 스스로 요구한다는 뜻이다.","need other people to provide는 '~가 …해 주도록 필요로 한다'는 5형식으로, 남들이 우리에게 사랑·지지 등을 제공해 주기를 우리가 필요로 한다는 뜻이야.")]),
 S(r1,5,
  [("need+O+to부정사","others가 confirm해 주도록 필요로 함"),("that절 나열","that ~, that ~ and that ~ 병렬")],
  [("confirm","확인하다"),("identity","정체성"),("separate","구별되는")],
  [("In a very [[basic]] sense","아주 [[기본]]적인 의미에서"),
   ("we need others to [[confirm]]","우리는 [[확인하기]] 위해 다른 사람들을 필요로 한다"),
   ("that we are there, that we exist and that we have an [[identity]]","우리가 거기에 있고, 존재하며, [[정체성]]을 가지고 있다는 것을"),
   ("that is unique and [[separate]] from anyone else.","고유하면서 다른 누구와도 [[구별되는]].")],
  [("우리는 남들과 똑같은 정체성을 갖기 위해 타인을 필요로 한다는 뜻이다.","unique and separate from anyone else(고유하고 남과 구별되는)라 했으므로, 남과 같아지려는 게 아니라 '나만의 구별되는 정체성'을 확인받기 위해 타인이 필요하다는 뜻이야.")]),
 S(r1,6,
  [("cannot ~ without","'~하지 않고는 …할 수 없다'(이중부정)"),("Thus 결론","앞 내용의 귀결")],
  [("companionship","교제, 벗함")],
  [("Thus, we generally cannot [[exist]]","따라서 우리는 일반적으로 [[살아갈]] 수 없다"),
   ("for too [[long]]","그렇게 [[오랫동안]]"),
   ("without seeking [[companionship]].","[[교제]]를 추구하지 않고는.")],
  [("우리는 교제 없이도 얼마든지 오래 살 수 있다는 뜻이다.","cannot exist ~ without seeking companionship은 '교제를 추구하지 않고서는 오래 살 수 없다'는 이중부정으로, 결국 교제가 반드시 필요하다는 속뜻이야.")]),
]
P1 = build("자신의 존재·정체성 확인을 위해 타인과의 교제·유대를 갈망하는 인간의 본성","Unit10-2",r1,ov1,i1)

# =====================================================================
# P2 — Unit14-1
# =====================================================================
r2 = [
 "Personal branding is not something that you have to do behind the scenes.",
 "For many it does not always feel comfortable to deliberately plan how we are going to promote ourselves and our accomplishments to others.",
 "Personal branding, however, is essential to achieving success.",
 "The key takeaway from this concept is awareness and anticipation.",
 "If you are not aware of the opportunities to brand yourself, you may not be directed to leave a favorable impression.",
 "If you cannot anticipate the opportunities that will present themselves to favorably demonstrate your brand through capability, you may not be prepared when they occur.",
 "So as you begin to think about what you want to be known for, begin to be more aware of what you want people to say about you when you are not in the room as an effective way to guide your personal brand.",
]

ov2 = Overview(
 theme_ko="성공을 위해 자리에 없을 때 회자될 평판을 관리하는 퍼스널 브랜딩의 중요성",
 key_grammar=KeyGrammar(
  point="가주어 it - 진주어 to부정사 (It ~ to-V: …하는 것이 …하다)",
  source_sentence="For many it does not always feel comfortable to deliberately plan how we are going to promote ourselves and our accomplishments to others.",
  explanation=[
   GN("쉽게 말하면","'It ~ to-V'에서 It은 [[가주어]], 진짜 주어는 뒤의 to부정사구."),
   GN("해석","it does not feel comfortable [[to plan]] ~ = '~을 계획하는 것이' 편치 않다."),
   GN("주의","가주어 it은 '그것'이라 [[해석하지]] 않고 비워 둔다."),
   GN("진주어","진주어 = to deliberately plan how we are going to [[promote]] ~."),
  ],
  example_analysis="it = 가주어, to deliberately plan how ~ = 진주어(to부정사구).",
  drills=[
   GrammarDrill(kind="객관식",from_passage=True,
    question="지문 'it does not always feel comfortable to deliberately plan ~'의 가주어/진주어는?",
    options=["it(가주어) / to deliberately plan ~(진주어)","it(진주어) / to plan(가주어)","many(가주어) / comfortable(진주어)"],
    answer="it(가주어) / to deliberately plan ~(진주어)"),
   GrammarDrill(kind="객관식",from_passage=False,
    question="빈칸: ____ is important to plan ahead. (미리 계획하는 것이 중요하다)",
    options=["It","That","This","There"],answer="It"),
   GrammarDrill(kind="객관식",from_passage=False,
    question="다음 중 '가주어 it - 진주어 to부정사' 문장으로 옳은 것은?",
    options=["It is hard to promote yourself.","It that you promote yourself is hard.","To it is hard promote yourself."],
    answer="It is hard to promote yourself."),
   GrammarDrill(kind="영작",from_passage=False,
    question="자기 자신을 홍보하는 것은 항상 편안하지는 않다.",
    answer="It is not always comfortable to promote yourself."),
   GrammarDrill(kind="영작",from_passage=True,
    question="(지문) 하지만 퍼스널 브랜딩은 성공을 이루는 데 필수적이다.",
    answer="Personal branding, however, is essential to achieving success."),
  ]),
 topic="자기 홍보가 부담스럽더라도 성공에 필수인 퍼스널 브랜딩과, 부재 시 평판을 의식한 관리의 필요성.",
 stance="긍정적",
 stance_reason="퍼스널 브랜딩이 성공에 필수적이라며 그 중요성을 적극 옹호한다.",
 structure="통념→반박(반전)",
 structure_reason="자기 홍보가 편치 않다는 거리낌(1~2)을 however로 뒤집어 필수임을 주장하고(3~4) 실천을 조언(5~7).",
 restatement_chains=[RestatementChain(
   label="자기 홍보로서의 브랜딩",
   expressions=["promote ourselves and our accomplishments","brand yourself"],
   variation="'자신과 업적을 홍보하기'가 뒤에서 '자신을 브랜딩하기'로 다시 진술됨.")],
 flow_blocks=[
  FlowBlock(stage="도입",sentence_range="1~2",summary="브랜딩은 [[남몰래]] 할 일이 아니나 자기 홍보 계획이 늘 편치는 않다."),
  FlowBlock(stage="반박",sentence_range="3~4",summary="그러나 브랜딩은 성공에 [[필수]]이며 핵심은 인식과 예상이다."),
  FlowBlock(stage="조건",sentence_range="5~6",summary="기회를 인식·[[예상]]하지 못하면 좋은 인상과 준비를 놓친다."),
  FlowBlock(stage="결론",sentence_range="7",summary="부재 시 남들이 할 말, 즉 [[평판]]을 의식해 브랜드를 이끌라."),
 ])

i2 = [
 S(r2,1,
  [("명사절 that","something that ~ 목적격 관계사"),("not something","'~하는 것이 아니다'")],
  [("behind the scenes","남몰래, 무대 뒤에서")],
  [("Personal branding is not [[something]]","퍼스널 브랜딩은 [[무언가]]가 아니다"),
   ("that you have to do [[behind the scenes]].","여러분이 [[남몰래]] 해야 하는 것이.")],
  [("퍼스널 브랜딩은 남들 모르게 은밀히 준비해야 하는 일이라는 뜻이다.","is not something you have to do behind the scenes는 '남몰래 할 일이 아니다'라는 뜻으로, 오히려 드러내 놓고 하는 것임을 함축해.")]),
 S(r2,2,
  [("가주어 it-진주어 to부정사","it=가주어, to plan ~=진주어"),("부분부정","not always = '항상 ~인 것은 아니다'")],
  [("deliberately","의도적으로"),("promote","홍보하다"),("accomplishment","업적")],
  [("For many it does not always feel [[comfortable]]","많은 사람에게 항상 [[편안하게]] 느껴지는 것은 아니다"),
   ("to [[deliberately]] plan","[[의도적으로]] 계획하는 것이"),
   ("how we are going to promote ourselves and our [[accomplishments]]","우리 자신과 우리의 [[업적]]을 어떻게 홍보할지"),
   ("to [[others]].","[[다른 사람들]]에게.")],
  [("많은 사람은 자기 홍보 계획 세우기를 언제나 편안하게 느낀다는 뜻이다.","it does not always feel comfortable은 '항상 편안하게 느껴지는 것은 아니다'라는 부분부정으로, 자기 홍보 계획이 늘 편치는 않다는 뜻이야.")]),
 S(r2,3,
  [("however 역접","앞의 거리낌을 반전"),("be essential to -ing","'~하는 데 필수적이다'")],
  [("essential","필수적인"),("achieve","이루다")],
  [("Personal [[branding]], however,","하지만 퍼스널 [[브랜딩]]은"),
   ("is [[essential]] to achieving success.","성공을 이루는 데 [[필수적이다]].")],
  [("however는 앞 내용을 예로 덧붙이는 연결어다.","however(하지만)는 앞의 '편치 않다'는 흐름을 뒤집어, 그럼에도 브랜딩이 성공에 필수라는 반전을 이끄는 역접 연결어야.")]),
 S(r2,4,
  [("this 지칭","this concept = 퍼스널 브랜딩"),("A and B","awareness와 anticipation 병렬")],
  [("takeaway","핵심, 요점"),("anticipation","예상")],
  [("The key [[takeaway]] from this concept","이 개념의 주요한 [[핵심]]은"),
   ("is [[awareness]] and anticipation.","[[인식]]과 예상이다.")],
  [("this concept는 앞서 말한 '남몰래 하는 일'을 가리킨다.","this concept가 가리키는 것은 앞에서 다룬 '퍼스널 브랜딩'이며, 그 핵심이 인식과 예상이라는 뜻이야.")]),
 S(r2,5,
  [("조건 if","'~하지 못하면'의 가정·조건"),("may not","'~하지 못할 수도 있다'")],
  [("opportunity","기회"),("favorable","호의적인"),("impression","인상")],
  [("If you are not aware of the [[opportunities]]","만약 [[기회]]를 인식하지 못한다면"),
   ("to [[brand]] yourself,","자신을 [[눈에 띄게 할]]"),
   ("you may not be directed to leave a [[favorable]] impression.","여러분은 [[호의적인]] 인상을 남기게 되지 못할 수도 있다.")],
  [("기회를 인식하지 못해도 좋은 인상을 남기는 데는 문제가 없다는 뜻이다.","If you are not aware ~, you may not ~ leave a favorable impression은 '기회를 못 알아채면 좋은 인상을 못 남길 수 있다'는 조건-결과로, 인식 부족이 인상 실패로 이어진다는 뜻이야.")]),
 S(r2,6,
  [("they 지칭","they = the opportunities"),("관계사 that","opportunities that ~ 수식")],
  [("anticipate","예상하다"),("demonstrate","보여 주다"),("capability","역량")],
  [("If you cannot [[anticipate]] the opportunities","[[기회]]를 예상할 수 없다면"),
   ("that will [[present]] themselves","자신을 [[나타낼]]"),
   ("to favorably [[demonstrate]] your brand through capability,","역량을 통해 여러분의 브랜드를 호의적으로 [[보여 주기]] 위해"),
   ("you may not be [[prepared]] when they occur.","여러분은 기회가 생길 때 [[준비]]가 되어 있지 않을지도 모른다.")],
  [("they occur의 they는 여러분의 경쟁자들을 가리킨다.","they가 가리키는 것은 the opportunities(기회들)이며, 기회가 생길 때 준비되어 있지 않을 수 있다는 뜻이야.")]),
 S(r2,7,
  [("what 관계대명사","what you want ~ '~하는 것'"),("명령문 조언","begin to ~ 실천 지시")],
  [("known for","~으로 알려진"),("guide","이끌다")],
  [("So as you begin to [[think]] about","그래서 여러분이 [[생각하기]] 시작할 때"),
   ("what you want to be [[known]] for,","자신이 무엇으로 [[알려지고]] 싶은지,"),
   ("begin to be more [[aware]] of","더 많이 [[인식하기]] 시작하라"),
   ("what you want people to [[say]] about you","사람들이 여러분에 대해 무엇을 [[말하기]]를 원하는지"),
   ("when you are not in the [[room]]","여러분이 [[방]]에 없을 때"),
   ("as an [[effective]] way to guide your personal brand.","여러분의 퍼스널 브랜드를 이끌 [[효과적인]] 방법으로서.")],
  [("자리에 없을 때 남들이 하는 말은 신경 쓸 필요 없다는 뜻이다.","사람들이 방에 없을 때 여러분에 대해 무엇을 말하길 원하는지 인식하라는 것으로, 부재 시의 평판을 미리 관리하라는 핵심 조언이야.")]),
]
P2 = build("성공을 위해 자리에 없을 때 회자될 평판을 관리하는 퍼스널 브랜딩의 중요성","Unit14-1",r2,ov2,i2)

PARTS = [P1, P2]
