# -*- coding: utf-8 -*-
import sys; sys.path.insert(0,"/tmp/claude-0/-home-user-english-data-making/3e2ff8b7-89bb-5341-95ca-4062ce95757b/scratchpad")
from _helpers_oladd import *

# ============================================================================
# P3 — Unit14-2 : Clyde Tombaugh의 명왕성 발견 (대조의 접속사 while)
# ============================================================================
r3 = [
"The ability to detect visual movement played an interesting role in the history of astronomy.",
"In 1930, Clyde Tombaugh was searching the skies for a possible undiscovered planet beyond Neptune.",
"He photographed each region of the sky twice, several days apart.",
"Stars essentially remain unmoving in photos, while a planet moves from one photo to the next.",
"However, how would he find a small dot that moved among all the countless unmoving dots in the sky?",
"He put each pair of photos on a machine that would flip back and forth between one photo and the other.",
"When he came to one pair of photos, he immediately noticed one dot moving as the machine flipped back and forth.",
"He identified that dot as Pluto, which astronomers now list as a dwarf planet.",
]

ov3 = Overview(
 theme_ko="사진 간 시각적 움직임 포착 기술로 이룬 Clyde Tombaugh의 명왕성 발견",
 key_grammar=KeyGrammar(
  point="대조의 접속사 while (~인 반면에)",
  source_sentence="Stars essentially remain unmoving in photos, while a planet moves from one photo to the next.",
  explanation=[
   GN("쉽게 말하면","두 절을 잇는 while은 '~하는 [[반면에]]'로 앞뒤 내용을 [[대조]]한다."),
   GN("구별","시간의 while('~하는 [[동안]]')과 달리 여기서는 [[대조]]의 뜻으로 쓰였다."),
   GN("자리","while절은 주로 문장 [[뒤]]에 붙어 앞 절과 반대되는 사실을 덧붙인다."),
   GN("해석","항성은 안 움직이는 [[반면]], 행성은 사진마다 위치가 바뀐다."),
  ],
  example_analysis="앞 절(항성은 불변) ↔ while절(행성은 이동)의 대조 구조.",
  drills=[
   GrammarDrill(kind="객관식",from_passage=True,
    question="지문에서 접속사 while이 나타내는 의미로 알맞은 것은?",
    options=["대조(~인 반면에)","시간(~하는 동안)","조건(~라면)"],
    answer="대조(~인 반면에)"),
   GrammarDrill(kind="객관식",from_passage=False,
    question="밑줄 친 while이 '대조(~인 반면에)'의 뜻으로 쓰인 문장은?",
    options=["He is rich, while his brother is poor.","While I was sleeping, the phone rang.","Wait here while I park the car."],
    answer="He is rich, while his brother is poor."),
   GrammarDrill(kind="객관식",from_passage=False,
    question="'The city is noisy, ____ the country is quiet.' 빈칸에 알맞은 것은?",
    options=["while","during","unless"],
    answer="while"),
   GrammarDrill(kind="영작",from_passage=True,
    question="(지문) 항성은 본질적으로 사진에서 움직이지 않는 반면, 행성은 한 사진에서 다음 사진으로 이동한다.",
    answer="Stars essentially remain unmoving in photos, while a planet moves from one photo to the next."),
   GrammarDrill(kind="영작",from_passage=False,
    question="그는 부유한 반면, 그의 형은 가난하다.",
    answer="He is rich, while his brother is poor."),
  ]),
 topic="움직임을 감지하는 능력을 이용해 명왕성을 발견한 Clyde Tombaugh의 일화.",
 stance="중립적",
 stance_reason="발견 과정을 시간 순으로 서술하는 설명적 일화문.",
 structure="시간·순서(나열)",
 structure_reason="촬영→대조 원리→문제 제기→기계 활용→발견의 시간 순서로 전개.",
 restatement_chains=[
  RestatementChain(label="움직임 감지",
   expressions=["detect visual movement","noticed one dot moving"],
   variation="'움직임을 감지하는 능력'이 실제로 '움직이는 한 점을 알아채는' 장면으로 실현됨."),
 ],
 flow_blocks=[
  FlowBlock(stage="도입",sentence_range="1",summary="시각적 [[움직임]] 감지 능력이 천문학사에서 흥미로운 역할을 함."),
  FlowBlock(stage="전개",sentence_range="2~3",summary="Tombaugh가 미발견 행성을 찾으려 각 영역을 며칠 간격 두 번 [[촬영]]."),
  FlowBlock(stage="대조",sentence_range="4",summary="항성은 불변이지만 행성은 사진마다 [[이동]]한다는 원리."),
  FlowBlock(stage="전환",sentence_range="5",summary="수많은 점 속에서 움직인 점을 어떻게 [[찾을지]] 문제 제기."),
  FlowBlock(stage="사례",sentence_range="6~7",summary="두 사진을 번갈아 [[뒤집는]] 기계로 움직인 점을 포착."),
  FlowBlock(stage="결론",sentence_range="8",summary="그 점을 [[명왕성]]으로 확인, 지금은 왜소 행성으로 분류."),
 ])

i3 = [
 S(r3,1,
  [("부정사 형용사적 용법","the ability to detect: '감지하는 능력'로 명사를 수식")],
  [("detect","감지하다"),("astronomy","천문학")],
  [("The ability to detect [[visual]] movement","[[시각적]] 움직임을 감지하는 능력은"),
   ("played an [[interesting]] role","[[흥미로운]] 역할을 했다"),
   ("in the history of [[astronomy]].","[[천문학]]의 역사에서")],
  [("시각적 움직임 감지 능력은 천문학에서 아무런 역할도 하지 못했다는 내용이다.","played an interesting role이라 했으니, 그 능력이 흥미로운 역할을 했다는 뜻 — 논지가 반대야.")]),
 S(r3,2,
  [("과거진행","was searching: 그 시점에 진행 중이던 탐색")],
  [("undiscovered","미발견의"),("Neptune","해왕성")],
  [("In 1930, Clyde Tombaugh was [[searching]] the skies","1930년에, Clyde Tombaugh는 하늘을 [[탐색하고]] 있었다"),
   ("for a possible [[undiscovered]] planet","있을지도 모르는 [[미발견]] 행성을 찾기 위해"),
   ("beyond [[Neptune]].","[[해왕성]] 너머에")],
  [("Tombaugh는 이미 발견된 행성의 위치를 재확인하려고 하늘을 봤다.","a possible undiscovered planet이니, 아직 발견 안 된 행성을 찾고 있었던 거야.")]),
 S(r3,3,
  [("부사구","several days apart: '며칠 간격으로'")],
  [("region","영역"),("apart","간격을 두고")],
  [("He [[photographed]] each region of the sky","그는 하늘의 각 영역을 [[촬영했다]]"),
   ("[[twice]], several days apart.","며칠 간격으로 [[두 번씩]]")],
  [("그는 하늘의 각 영역을 단 한 번만 촬영했다.","twice, several days apart이니, 며칠 간격을 두고 두 번씩 찍어 변화를 비교하려 한 거야.")]),
 S(r3,4,
  [("대조의 접속사 while (~인 반면에)","앞 절(항성 불변)과 while절(행성 이동)을 대조"),
   ("현재시제","일반적 사실을 나타내는 현재")],
  [("essentially","본질적으로"),("unmoving","움직이지 않는")],
  [("Stars essentially remain [[unmoving]] in photos,","항성은 본질적으로 사진에서 [[움직이지 않는]] 상태로 남아 있는"),
   ("while a planet [[moves]]","반면, 행성은 [[이동한다]]"),
   ("from one photo to the [[next]].","한 사진에서 [[다음]] 사진으로 가면서")],
  [("항성과 행성 모두 사진에서 똑같이 자리를 옮긴다는 뜻이다.","while이 대조를 나타내 — 항성은 안 움직이는 반면 행성만 사진마다 위치가 바뀐다는 거야.")]),
 S(r3,5,
  [("관계대명사 that","a small dot that moved: 앞의 명사를 수식하는 주격 관계사"),
   ("수사의문문","'어떻게 찾을까'로 문제를 던지는 형식")],
  [("countless","셀 수 없이 많은"),("dot","점")],
  [("However, how would he [[find]] a small dot","하지만 그가 하나의 작은 점을 어떻게 [[찾을]] 것인가"),
   ("that moved among all the [[countless]] unmoving dots","움직이지 않는 [[수많은]] 점들 사이에서 움직인"),
   ("in the sky?","하늘에서")],
  [("그는 이미 그 작은 점을 손쉽게 찾아낸 상태였다.","how would he find ~는 함축적으로 '찾기가 매우 어렵다'는 문제 제기야 — 아직 못 찾았어.")]),
 S(r3,6,
  [("관계대명사 that","a machine that would flip ~: 기계를 수식하는 주격 관계사")],
  [("pair","쌍"),("flip","뒤집다")],
  [("He put each [[pair]] of photos on a machine","그는 각 [[쌍]]의 사진을 기계에 놓았다"),
   ("that would [[flip]] back and forth","앞뒤로 [[뒤집어주는]]"),
   ("between one photo and the [[other]].","한 사진과 [[다른]] 사진 사이를")],
  [("그 기계는 두 사진을 하나로 합쳐 겹쳐 보여 주는 장치였다.","flip back and forth between one photo and the other이니, 함축적으로 두 사진을 번갈아 뒤집어 움직인 점을 드러내는 장치야.")]),
 S(r3,7,
  [("지각동사+O+-ing","noticed one dot moving: 점이 움직이는 것을 알아챔"),
   ("접속사 as","'~할 때'의 뜻")],
  [("immediately","즉시"),("notice","알아채다")],
  [("When he came to one [[pair]] of photos,","한 [[쌍]]의 사진에 다다랐을 때,"),
   ("he immediately [[noticed]] one dot moving","그는 점 하나가 움직이는 것을 즉시 [[알아챘다]]"),
   ("as the machine [[flipped]] back and forth.","기계가 앞뒤로 [[뒤집을]] 때")],
  [("기계를 뒤집자 모든 점이 다 함께 움직였다.","he noticed one dot moving이니, 오직 한 점만 움직였고 그래서 그것이 행성임을 알아챈 거야.")]),
 S(r3,8,
  [("계속적 용법 관계대명사 (, which)","앞 내용(Pluto)을 부연 설명")],
  [("identify","확인하다"),("dwarf planet","왜소 행성")],
  [("He [[identified]] that dot as Pluto,","그는 그 점을 명왕성으로 [[확인했는데]],"),
   ("which astronomers now [[list]]","천문학자들은 현재 그것을 [[목록에 포함한다]]"),
   ("as a [[dwarf]] planet.","[[왜소]] 행성으로")],
  [("관계사 which가 가리키는 것은 astronomers(천문학자들)이다.","which는 앞의 that dot, 곧 Pluto(명왕성)를 가리켜 — 천문학자들이 그것을 왜소 행성으로 분류한다는 뜻."),
   ("that dot은 Tombaugh가 찾던 해왕성을 가리킨다.","that dot은 그가 새로 발견해 명왕성(Pluto)으로 확인한 점을 가리켜 — 해왕성은 이미 알려진 별개의 행성이야.")]),
]

P3 = build("사진 간 시각적 움직임 포착 기술로 이룬 Clyde Tombaugh의 명왕성 발견","Unit14-2",r3,ov3,i3)


# ============================================================================
# P4 — Unit14-3 : 근시안적 목재 남용 비판 (가정법 otherwise)
# ============================================================================
r4 = [
"People are cutting down forests much faster than the rate at which forests can regrow.",
"We need to dramatically reduce our use of wood, not just because the supply is decreasing, and not just because entire species of flora and fauna that live in forests are vanishing, but because the forest performs an important function.",
"Forests control global warming by absorbing carbon from the atmosphere and reducing greenhouse gases.",
"They also provide oxygen for us to breathe.",
"There are too many trivial and shortsighted uses of wood.",
"When a hurricane advances on a city, people board up their windows with plywood.",
"After the storm has passed, they discard the plywood.",
"It's ironic to think that for purposes such as these, forests are cut down that otherwise would aid in controlling such storms.",
]

ov4 = Overview(
 theme_ko="기후 조절이라는 숲의 기능을 망각한 채 이뤄지는 근시안적 목재 남용 비판",
 key_grammar=KeyGrammar(
  point="가정법 otherwise (otherwise + 조동사 과거: 그렇지 않다면 ~할 텐데)",
  source_sentence="It's ironic to think that for purposes such as these, forests are cut down that otherwise would aid in controlling such storms.",
  explanation=[
   GN("쉽게 말하면","otherwise는 '[[그렇지 않다면]]'이라는 [[가정]]을 한 단어에 담는다."),
   GN("복원","otherwise would aid = [[if they were not cut down]], they would aid ~."),
   GN("짝","otherwise 뒤엔 would/could 같은 [[조동사 과거]]가 와서 가정법을 이룬다."),
   GN("해석","베지 않았다면 그 숲이 폭풍 통제에 [[도움]]이 되었을 것이다."),
  ],
  example_analysis="forests are cut down that otherwise would aid ~ = 베어지지 않았다면(가정) 도움이 됐을 것이라는 가정법.",
  drills=[
   GrammarDrill(kind="객관식",from_passage=True,
    question="지문에서 otherwise가 뜻하는 것으로 알맞은 것은?",
    options=["그렇지 않다면(숲을 베지 않았다면)","게다가","반드시"],
    answer="그렇지 않다면(숲을 베지 않았다면)"),
   GrammarDrill(kind="객관식",from_passage=False,
    question="'I was busy; ____ I would have called you.' 빈칸에 알맞은 것은?",
    options=["otherwise","therefore","moreover"],
    answer="otherwise"),
   GrammarDrill(kind="객관식",from_passage=False,
    question="밑줄 친 otherwise가 '그렇지 않다면'의 가정 의미로 쓰인 문장은?",
    options=["Hurry up; otherwise you will miss the bus.","She thinks otherwise.","Do it this way, not otherwise."],
    answer="Hurry up; otherwise you will miss the bus."),
   GrammarDrill(kind="영작",from_passage=False,
    question="서둘러라, 그렇지 않으면 너는 버스를 놓칠 것이다.",
    answer="Hurry up, otherwise you will miss the bus."),
   GrammarDrill(kind="영작",from_passage=True,
    question="(지문) 이러한 목적을 위해 숲이 베어지는데, 그렇지 않다면 그 숲이 그러한 폭풍을 통제하는 데 도움이 되었을 것이라 생각하면 아이러니이다.",
    answer="It's ironic to think that for purposes such as these, forests are cut down that otherwise would aid in controlling such storms."),
  ]),
 topic="숲의 기후 조절 기능을 무시한 근시안적 목재 남용에 대한 비판.",
 stance="부정적·비판적",
 stance_reason="목재의 사소하고 근시안적인 남용을 반어적으로 비판함.",
 structure="주장→근거·예시",
 structure_reason="목재 사용을 줄여야 한다는 주장 뒤에 숲의 기능(근거)과 합판 사례를 제시.",
 restatement_chains=[
  RestatementChain(label="숲의 중요한 기능",
   expressions=["the forest performs an important function","control global warming"],
   variation="'숲이 중요한 기능을 한다'가 '지구온난화를 억제한다'로 구체화됨."),
 ],
 flow_blocks=[
  FlowBlock(stage="도입",sentence_range="1",summary="숲이 [[재성장]]하는 속도보다 훨씬 빠르게 벌목이 진행됨."),
  FlowBlock(stage="주장",sentence_range="2",summary="목재 사용을 줄여야 하는 핵심 이유는 숲의 [[기능]] 때문."),
  FlowBlock(stage="근거",sentence_range="3~4",summary="숲은 탄소를 [[흡수]]해 온난화를 억제하고 산소를 공급함."),
  FlowBlock(stage="전환",sentence_range="5",summary="목재의 사소하고 [[근시안적]]인 쓰임새가 너무 많음."),
  FlowBlock(stage="사례",sentence_range="6~7",summary="허리케인 때 합판으로 창을 막고 폭풍 뒤엔 [[버림]]."),
  FlowBlock(stage="결론",sentence_range="8",summary="폭풍 대비로 숲을 베는 것은 [[반어적]] — 숲이 폭풍을 억제하는데."),
 ])

i4 = [
 S(r4,1,
  [("비교급 faster than","'~보다 더 빠르게' 벌목 속도와 재성장 속도를 비교"),
   ("전치사+관계대명사","the rate at which ~: '~하는 속도'")],
  [("regrow","다시 자라다"),("rate","속도")],
  [("People are [[cutting down]] forests","사람들은 숲을 [[베어내고]] 있다"),
   ("much [[faster]] than the rate","속도보다 훨씬 더 [[빠르게]]"),
   ("at which forests can [[regrow]].","숲이 [[재성장할]] 수 있는")],
  [("숲은 베이는 속도보다 더 빠르게 다시 자라나고 있다.","much faster than the rate at which forests can regrow이니, 재성장 속도보다 벌목이 훨씬 빠르다는 정반대 뜻이야.")]),
 S(r4,2,
  [("상관접속사 not (just) A but B","'~때문만이 아니라 ~때문이다'로 진짜 이유를 강조"),
   ("주격 관계대명사 that","species ... that live in forests")],
  [("dramatically","급격하게"),("vanish","사라지다"),("function","기능")],
  [("We need to dramatically [[reduce]] our use of wood,","우리는 목재 사용을 급격하게 [[줄여야]] 하는데,"),
   ("not just because the supply is [[decreasing]],","이는 공급이 [[감소하고]] 있기 때문만이 아니라,"),
   ("and not just because entire species of [[flora and fauna]]","그리고 [[동식물군]] 전체 종이"),
   ("that live in forests are [[vanishing]],","숲에 서식하는 것들이 [[사라지고]] 있기 때문만이 아니라,"),
   ("but because the forest performs an [[important]] function.","숲이 [[중요한]] 기능을 수행하기 때문이다.")],
  [("목재 사용을 줄여야 하는 유일한 이유는 목재 공급이 줄기 때문이다.","not just because ~ but because the forest performs an important function이니, 공급 감소만이 아니라 숲의 기능이 진짜 이유야.")]),
 S(r4,3,
  [("by -ing","'~함으로써'라는 수단"),
   ("동명사 병렬","absorbing ~ and reducing ~")],
  [("absorb","흡수하다"),("greenhouse gas","온실 가스")],
  [("Forests control global [[warming]]","숲은 [[지구온난화]]를 억제한다"),
   ("by [[absorbing]] carbon from the atmosphere","대기로부터 탄소를 [[흡수하고]]"),
   ("and [[reducing]] greenhouse gases.","온실 가스를 [[줄여]]")],
  [("숲은 대기에 탄소를 내뿜어 지구온난화를 더 심화시킨다.","absorbing carbon과 reducing greenhouse gases이니, 탄소를 흡수하고 온실가스를 줄여 온난화를 억제한다는 뜻이야.")]),
 S(r4,4,
  [("for + 목적격 + to부정사","for us to breathe: 부정사의 의미상 주어 us")],
  [("provide","공급하다"),("oxygen","산소")],
  [("They also [[provide]] oxygen","그것은 또한 산소를 [[공급한다]]"),
   ("for us to [[breathe]].","우리가 [[숨 쉴]] 수 있는")],
  [("여기서 They는 온실 가스(greenhouse gases)를 가리킨다.","They는 앞 문장의 숲(forests)을 가리켜 — 숲이 우리가 숨 쉴 산소를 공급한다는 뜻이야.")]),
 S(r4,5,
  [("There are 구문","'~가 있다/많다'")],
  [("trivial","사소한"),("shortsighted","근시안적인")],
  [("There are too [[many]]","너무 [[많다]]"),
   ("[[trivial]] and shortsighted uses of wood.","목재의 [[사소하고]] 근시안적인 쓰임새가")],
  [("필자는 목재의 다양한 쓰임새를 긍정적으로 평가하고 있다.","trivial and shortsighted uses이라 했으니, 사소하고 근시안적인 남용이 많다고 비판하는 거야.")]),
 S(r4,6,
  [("접속사 When","'~할 때'의 시간 부사절")],
  [("advance","다가오다"),("board up","(판자로) 막다"),("plywood","합판")],
  [("When a hurricane [[advances]] on a city,","허리케인이 도시로 [[다가오면]],"),
   ("people [[board up]] their windows with plywood.","사람들은 합판으로 창문을 [[막는다]].")],
  [("허리케인이 다가오면 사람들은 창문을 활짝 열어 둔다.","board up their windows with plywood이니, 합판으로 창문을 막아 대비한다는 뜻이야.")]),
 S(r4,7,
  [("현재완료 has passed","폭풍이 지나간 완료 시점"),
   ("접속사 After","'~한 후에'")],
  [("discard","버리다"),("storm","폭풍")],
  [("After the storm has [[passed]],","폭풍이 [[지난]] 후에,"),
   ("they [[discard]] the plywood.","그들은 합판을 [[버린다]].")],
  [("여기서 they는 폭풍(the storm)을 가리킨다.","they는 앞의 사람들(people)을 가리켜 — 폭풍이 지난 뒤 사람들이 합판을 버린다는 뜻이야.")]),
 S(r4,8,
  [("가정법 otherwise (그렇지 않다면 ~할 텐데)","otherwise would aid: 베지 않았다면 도움이 됐을 것"),
   ("가주어 It","It's ironic to think ~"),
   ("주격 관계대명사 that","forests ... that otherwise would aid")],
  [("ironic","반어적인"),("aid","돕다")],
  [("It's [[ironic]] to think that","생각하면 [[아이러니]]이다"),
   ("for [[purposes]] such as these,","이러한 [[목적]]을 위해,"),
   ("forests are [[cut down]]","숲이 [[베어지는데]],"),
   ("that otherwise would [[aid]] in controlling such storms.","그렇지 않다면 그러한 폭풍을 통제하는 데 [[도움이 되었을]]")],
  [("숲을 베어 폭풍을 막는 것은 매우 효율적이고 합리적인 방법이다.","It's ironic ~ otherwise would aid in controlling such storms이니, 숲 자체가 폭풍을 억제하는데 그 숲을 베어 대비하는 게 반어적이라는 함축이야."),
   ("otherwise는 '게다가'라는 뜻으로, 숲이 폭풍을 더 키운다는 말이다.","otherwise는 가정법으로 '숲을 베지 않았다면'의 뜻 — 숲이 그대로였다면 폭풍 통제에 도움이 됐을 것이라는 함축이야.")]),
]

P4 = build("기후 조절이라는 숲의 기능을 망각한 채 이뤄지는 근시안적 목재 남용 비판","Unit14-3",r4,ov4,i4)

PARTS = [P3, P4]
